### ISSUE TITLE
Camera  some time get wrong position 

### ISSUE THREAD

**Issue by warzoku** [Microsoft/MixedRealityToolkit-Unity#1646] opened 2018-01-18 09:05 UTC
In Mixed reality portal camera always get right rotation and distance from floor but in app when scene is begining Camera don't get right distance from floor. 
(Microsoft Mixed Reality Headset)

**Comment by odens** [comment] 2018-01-26 08:55
The same here, also recently faced this issue.
As I notice it take 5-20 seconds to fix vertical offset, sometime app start with camera on the floor, then I move head side-to-side it get my normal elevation.
Seems Headset lost tracking, not sure.
Also in seating/standing experience the position in somewhere in 1 meter above the floor but at the same time Cliff House track elevation well.

**Comment by designnomad** [comment] 2018-01-31 23:18
Same here. It's not due to tracking loss, because in Cliffhouse, floor is in the right position. 
This is the most frustrating problem. When this occurs, I close and reopen Unity, or exit the app and launch it again, but success is so random.

**Comment by odens** [comment] 2018-02-01 08:40
I note it recently happen when I see that headset lost tracking (not bounds displayed).
And @designnomad right, switching back to Cliffhouse works well.
To fix this issue do one of the point below:
1. Move head side-to-side, sometime in 10-15 seconds problem disappear.
2. Restart Mixed Reality Portal.

**Comment by warzoku** [comment] 2018-02-02 12:45
Thanks for answers. Maybe anyone know is It
1) hardware problem?
2) SDK problem
3) My wrong code

**Comment by odens** [comment] 2018-02-04 00:49
Think the problem somewhere in the MRTK.
The best solution in case there is no boundary or elevation data to get some default average value of 1.6-1.8 meters.

**Comment by warzoku** [comment] 2018-02-04 11:56
I don't know where in code camera is getting its position. But as far i know it is impossible to set position to camera.transform it can be possible only for camera parent. 
Most offten this problem appear if headset  place on table(for example) in begining of scene. But sometimes  problem can be too even if headset on head.

**Comment by keveleigh** [comment] 2018-02-04 18:38
Which version of Unity are you using? This sounds like a Unity issue, since the camera's position (other than moving the camera parent for teleporting) and the alignment of the coordinate space are both handled by the platform/Unity, not by the Toolkit.

**Comment by odens** [comment] 2018-02-04 20:17
Unity 2017.3.0f3

Also have some issue with the camera height.
Image you have a floor and a 1m height box, your camera at 1.8m.
You teleport from the floor to the box (camera height 2.8) then back to the floor and sometime camera height stay at 2m or 2.5m.
I.e. after teleport on some different height the camera elevation does not return at origin value.

**Comment by warzoku** [comment] 2018-02-05 07:36
keveleigh,
Unity 2017.3.0f3 and in Unity 2017.2.0p1-MRTP4  this problem was. I mean if I set camera position in LateUpdate  camera position doesn't change.
But problem in another. Camera some times after scene starts still placing on floor and doesn't jump to right position from floor. And sometimes together with this problem also controllers  not spawned

**Comment by odens** [comment] 2018-02-05 23:48
Unity 2017.3.1 released today but I did not found any information about this issue
https://unity3d.com/unity/whats-new/unity-2017.3.1

**Comment by odens** [comment] 2018-02-07 00:03
Just tested and camera positioning issue exists on Unity 2017.3.1

**Comment by keveleigh** [comment] 2018-02-07 00:07
@warzoku 
> I mean if I set camera position in LateUpdate camera position doesn't change.

That's right. Unity overrides any change to the camera based on the user's head movement. That's why we use the camera parent object to move the camera around.

All of the camera issues sound like Unity bugs, where they aren't properly moving the coordinate space.

**Comment by odens** [comment] 2018-02-13 09:03
Sent bug report to Unity
Case 1001658

**Comment by odens** [comment] 2018-03-01 18:17
Got response from Unity team.
They have been able to reproduce this issue and have sent it to developers for resolution.

**Comment by HBJKZLH** [comment] 2018-03-02 03:08
Untiy [Universal Windows Platform] Platform does not support.

The Socket code is written and the Thread code is written and the FileStream code is written, you know what?



I used the network communication section to find that this part of the code could not be transferred to the [Universal Windows Platform].

After I tested Unity 2017.2.0f3 (64-bit) version,Unity 2017.3.1f1 (64-bit) version,Unity 2017.2.1f1 (64-bit) version.



They don't support it.



Do you have any feedback on untiy?









When I wrote socket and IO and Thread related code in the program, untiy packaging times was wrong,
The socket.Connect function is not supported.
The socket.Receive function is not supported, and the 
socket.Send function is not supported.
The filestream.close function is not supported,
New Thread(recv) is not supported,
Does not support Thread. IsBackground,
Does not support Thread. To Start,




But if I just write in the code.

The Socket client = null;

Thread the Thread = null;

FileStream filedata = null;



This way, the Universal Windows Platform is passed.

I think it should be the flaw in the Platform library of untiy [Universal Windows Platform].


Please help me to feedback this question,








------------------ 原始邮件 ------------------
发件人: "odens"<notifications@github.com>;
发送时间: 2018年3月2日(星期五) 凌晨2:17
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [Microsoft/MixedRealityToolkit-Unity] Camera some time get wrongposition (#1646)




Got response from Unity team.
 They have been able to reproduce this issue and have sent it to developers for resolution.

**Closed** 2018-05-25 04:30 UTC
Labels: Immersive HMD, Unity Bug

**Comment by Le0nLyn** [comment] 2019-10-24 20:47
This issue is still reproducible with **Unity 2019.2.6f1**.
