### ISSUE TITLE
MixedRealityInputSimulationProfile serialization problem

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6054] opened 2019-09-24 12:31 UTC
## Describe the bug

The DefaultMixedRealityInputSimulationProfile is part of the the simulation data provider in the MRKT input profile. But at the same time it's AMSDEF is Editor and UWP only, causing a deserialization problem on all other platforms.
Since it's the only service (I think) that's only being used in Editor and the fact that it also compiles for UWP makes me believe that either this could very well be just compiled for all platforms and we're done with it, or the profile needs to be extracted out, which I tried and stopped after the 3rd file.

## To reproduce

1. Build MRKT with SimulationProfile for e.g. Standalone.

## Expected behavior

no serialization problem

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- Standalone

**Comment by keveleigh** [comment] 2019-11-07 19:18
Closing as duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3971, I believe

**Closed by keveleigh** 2019-11-07 19:18 UTC
Labels: Bug
