### ISSUE TITLE
Setting ManipulationHandler script to “RotateScale” mode doesn't prevent Move operation from happening

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#4395] opened 2019-05-16 01:59 UTC
## Describe the bug
Setting the script to “RotateScale” mode doesn't prevent Move operation from happening
. If that is intended behavior, what is the purpose of constraining these manipulation Modes?

## To reproduce

1. Create a simple cube in the unity scene
2, Add the ManipulationHandler script to the gameobject.
Configure the script in the following manner:
![image](https://user-images.githubusercontent.com/17660747/57820918-728f0300-7743-11e9-9174-21ae509ed472.png)
3. Build and deploy to device. 
4. the user is able to move the gameobject

## Expected behavior

The object should not move since the developer has configured the options to only RotateScale for the manipulation.

## Your Setup (please complete the following information)

- Unity Version  2018.3.10f1
- MRTK Version 2.0

## Target Platform (please complete the following information)
Hololens
Hololens2

**Comment by wiwei** [comment] 2019-05-16 16:58
@julenka, can you comment on the intent here?

**Comment by julenka** [comment] 2019-05-16 17:31
This is actually by design, it's a duplicate of #2021. You can get the desired behavior (rotate only, no movement) by setting Manipulation Type to "Two Handed Only" and then setting "Two Handed Manipulation Type" to "Rotate Scale".

**Comment by julenka** [comment] 2019-05-16 17:31
This is good feedback though that the configuration is not obvious. Can somebody propose a better design?

**Closed by julenka** 2019-05-16 17:31 UTC
Labels: 0 - Backlog, Bug, Interactions, MRW Cares
