### ISSUE TITLE
Feature Tool hangs at "Discover Features"

### ISSUE THREAD

**Issue by iBacon** [microsoft/MixedRealityToolkit-Unity#11291] opened 2022-12-13 06:05 UTC
## Describe the bug

MRTK Feature Tool hangs at "Discover Features"

## To reproduce

1. Have an existing Unity project, set up as normal for Hololens 2 target
2. Open MRTK Feature Tool
3. Point MRTK at project folder
4. Click "Discover Features"
5. Tool lists no features.

Note that the tool has functioned normally within the past 3 weeks.

## Expected behavior

Tool should display a list of features to import to project.
Tool should also show a "Last updated" date other than 1/1/0001

## Screenshots

![image](https://user-images.githubusercontent.com/63789241/207236111-6b59bcab-96f8-4693-ae7a-c8533e3f0371.png)

## Your setup (please complete the following information)

- Unity Version 2021.3.12f1
- Mixed Reality Feature Tool 1.0.2209.0
- Win10 21H2 (1904.2251)
- .NET SDK 6.0.402

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Log shows 
```
...
[13/12/2022 6:44:28 pm] Reading version information for com.microsoft.windows.mixedreality.dotnetwinrt
[13/12/2022 6:44:28 pm] Reading additional information for com.microsoft.windows.mixedreality.dotnetwinrt
[13/12/2022 6:44:28 pm] Completed reading Primary feed. (00:00:29.1125754) - 0 issues encountered.
[13/12/2022 6:44:28 pm] Feature catalog saved.
[13/12/2022 6:44:28 pm] Merging feed: Primary
[13/12/2022 6:44:28 pm] Failed to update the catalog... refreshing.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.MixedReality.FeatureTool.Controls.FeaturePackageListEntryControlViewModel..ctor(FeaturePackageListEntry parent, AdoPackageInfo package, AdoPackageVersionInfo version, Boolean showAvailablePackages)
   at Microsoft.MixedReality.FeatureTool.Controls.FeatureCategoryListEntryControlViewModel.AddPackages(List`1 packages)
   at Microsoft.MixedReality.FeatureTool.Pages.DiscoveryPageViewModel.UpdatePackageCollection(List`1 feeds)
[13/12/2022 6:44:28 pm] Refreshing the Primary catalog.
[13/12/2022 6:44:28 pm] Reading Primary feed
[13/12/2022 6:44:29 pm] Reading version information for com.microsoft.adaptivecards.net
[13/12/2022 6:44:29 pm] Reading additional information for com.microsoft.adaptivecards.net
[13/12/2022 6:44:29 pm] Reading version information for com.microsoft.altspacevr_uploader
...
```

Same error is shown in log when using the "Restore Features" option, although some successful downloads are also noted:
```
...
[13/12/2022 6:47:23 pm] Downloading com.microsoft.mixedreality.toolkit.standardassets 2.8.2 - attempt: 0
[13/12/2022 6:47:26 pm] Downloaded com.microsoft.mixedreality.toolkit.foundation 11551936 bytes (00:00:39.8324164)
[13/12/2022 6:47:26 pm] Download complete (00:00:39.8333609).
[13/12/2022 6:47:26 pm] Downloading com.microsoft.mixedreality.worldlockingtools 1.5.9 - attempt: 0
[13/12/2022 6:47:26 pm] Copying com.microsoft.mixedreality.openxr-1.4.1.tgz into the project.
[13/12/2022 6:47:26 pm] Copying com.microsoft.mixedreality.toolkit.foundation-2.8.0.tgz into the project.
[13/12/2022 6:47:27 pm] Copying com.microsoft.mixedreality.toolkit.standardassets-2.8.0.tgz into the project.
[13/12/2022 6:47:28 pm] Restore complete. (0 issues).
[13/12/2022 6:47:28 pm] Reading version information for com.microsoft.mrtk.tts.windows
[13/12/2022 6:47:28 pm] Reading additional information for com.microsoft.mrtk.tts.windows
[13/12/2022 6:47:29 pm] Reading version information for com.microsoft.mrtk.uxcomponents
[13/12/2022 6:47:29 pm] Reading additional information for com.microsoft.mrtk.uxcomponents
[13/12/2022 6:47:29 pm] Reading version information for com.microsoft.mrtk.uxcomponents.noncanvas
[13/12/2022 6:47:30 pm] Reading additional information for com.microsoft.mrtk.uxcomponents.noncanvas
[13/12/2022 6:47:30 pm] Reading version information for com.microsoft.mrtk.uxcore
[13/12/2022 6:47:30 pm] Reading additional information for com.microsoft.mrtk.uxcore
[13/12/2022 6:47:31 pm] Reading version information for com.microsoft.mrtk.windowsspeech
[13/12/2022 6:47:31 pm] Downloaded com.microsoft.azure.spatial-anchors-sdk.core 84498 bytes (00:00:27.7579996)
[13/12/2022 6:47:31 pm] Reading additional information for com.microsoft.mrtk.windowsspeech
[13/12/2022 6:47:31 pm] Reading version information for com.microsoft.spatialaudio.spatializer.unity
[13/12/2022 6:47:32 pm] Reading additional information for com.microsoft.spatialaudio.spatializer.unity
[13/12/2022 6:47:32 pm] Reading version information for com.microsoft.windows.mixedreality.dotnetwinrt
[13/12/2022 6:47:32 pm] Reading additional information for com.microsoft.windows.mixedreality.dotnetwinrt
[13/12/2022 6:47:33 pm] Completed reading Primary feed. (00:00:57.2380911) - 0 issues encountered.
[13/12/2022 6:47:33 pm] Downloaded com.microsoft.mixedreality.toolkit.extensions 1129390 bytes (00:00:29.4294543)
[13/12/2022 6:47:33 pm] Feature catalog saved.
[13/12/2022 6:47:33 pm] Merging feed: Primary
[13/12/2022 6:47:33 pm] Failed to update the catalog... refreshing.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.MixedReality.FeatureTool.Controls.FeaturePackageListEntryControlViewModel..ctor(FeaturePackageListEntry parent, AdoPackageInfo package, AdoPackageVersionInfo version, Boolean showAvailablePackages)
   at Microsoft.MixedReality.FeatureTool.Controls.FeatureCategoryListEntryControlViewModel.AddPackages(List`1 packages)
   at Microsoft.MixedReality.FeatureTool.Pages.DiscoveryPageViewModel.UpdatePackageCollection(List`1 feeds)
[13/12/2022 6:47:33 pm] Refreshing the Primary catalog.
[13/12/2022 6:47:33 pm] Reading Primary feed
[13/12/2022 6:47:33 pm] Reading version information for com.microsoft.adaptivecards.net
...
```

**Comment by Zee2** [comment] 2022-12-13 06:52
@davidkline-ms @keveleigh , getting more reports of this bug #11274. Same issue with the 0001 date.

(Closing this as dupe of #11274. @iBacon, thank you so much for adding your report here, this well help us a lot!)

**Comment by iBacon** [comment] 2022-12-13 07:07
Welcome. Good luck squashing it

**Comment by davidkline-ms** [comment] 2022-12-13 21:36
@iBacon, thank you for the log. have there been any changes to your environment since the tool last worked for you?

**Comment by davidkline-ms** [comment] 2022-12-13 21:38
@iBacon, also can you try deleting the settings file in the app's data folder (typically c:\users\<yourusername>\AppData\Local\MixedRealityFeatureTool) to see if that fixes things? It is possible that something may have gottent corrupted.

Thanks!

**Comment by Zee2** [comment] 2022-12-13 22:36
@davidkline-ms I closed this as a dupe of #11274

**Closed by Zee2** 2022-12-13 22:36 UTC
Labels: Bug

**Comment by MaxWang-MS** [comment] 2022-12-14 01:37
Thanks to the logs we have root caused the issue, which users will hit when the "Show preview releases" option is disabled. The bug will be fixed in the next release of Mixed Reality Feature Tool.

In the meantime, here's a workaround: Click on the settings button (gear icon) when the feature tool starts, go to the Feature tab and ensure the Show preview releases checkbox is checked. Then press OK and use the feature tool as you normally would.

**Comment by iBacon** [comment] 2022-12-23 23:32
Sorry, I should have reported back. Deleting the AppData cache folder like @davidkline-ms suggests worked for me.

Thanks for your efforts, team
