### ISSUE TITLE
MixedReality Standard Shader transparency distortion 

### ISSUE THREAD

**Issue by anandmulay3** [microsoft/MixedRealityToolkit-Unity#8408] opened 2020-08-28 10:38 UTC
## Describe the bug

I'm using MixedReality Standard shader for 3d models in my project, and it's awesome best shader I've ever seen, but I notice one thing, if I set the the rendering mode to transparent and culling mode off. it gives some kind of artifacts/distortion and its only visible on certain angle.

## To reproduce

set Materal shader to MixedReality Standard shader , set rendering mode to transparent and culling mode off
you can even notice the artifact in the matreal preview widget
## Expected behavior
I'm expecting a normal transparency which we can adjust using alpha
## Screenshots

![image](https://user-images.githubusercontent.com/17264989/91551787-633bc500-e948-11ea-8ab6-921517e30022.png)

## Your setup (please complete the following information)

- Unity Version [2018.4.14f1]
- MRTK Version [ v2.4]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
NA

**Comment by anandmulay3** [comment] 2020-09-08 07:09
Any thoughts? I really want to see my models in a transparent mode like it shown in the example scene.

**Comment by polar-kev** [comment] 2021-09-15 18:01
@anandmulay3, sorry for the delay. @elbuhofantasma can you try to reproduce this one?

**Comment by WikkidEdd** [comment] 2021-09-23 10:41
This isn't an MRTK Shader issue. This is just an artifact of how most real-time renderers work. 

When rendering transparency, to get correct rendering the triangles need to be rendered back to front. That is to say the triangles furthest from the camera should be rendered first followed by the next closest away and so on. Within a single object, most real-time renders won't sort individual triangles of a mesh to ensure the draw order is correct. This means that they are drawn in an arbitrary order and the artifacts you see in the screenshots are simply that the far away triangles are being rendered over the closer triangles.

You can reproduce this exact sample behaviour using the Unity standard shader. The only way to get around it is to implement [order independent transparency](https://en.wikipedia.org/wiki/Order-independent_transparency). This is probably too expensive for the likes of the Hololens, but if you use Azure Remote Rendering, that supports OIT out of the box.

**Comment by polar-kev** [comment] 2021-11-05 16:53
Thanks @WikkidEdd. Closing this since it's not an MRTK issue.

**Closed by polar-kev** 2021-11-05 16:53 UTC
Labels: Bug, External
