### ISSUE TITLE
vNext Task - Create Input Modifier component

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2622] opened 2018-08-21 13:19 UTC
## Overview
It has been noted, that some developers would like a quick and easy way to transform a single action configured against an input, into multiple actions depending on the current value of the input.

This should be an addon component so as not to break the current input implementation as it is a generic feature.

For discussion is whether we should have one generic component to all axis types or one per axis type

E.G. 
* Up / Down / Left / Right on a D-Pad
* Specific Angles on a thumbstick
* N / NW / W / SW / S / SE / E / NE  on a touchpad
* Range on a trigger

## Requires
* A new component to be able to configure actions based on values (_Core or SDK?)
* Code documentation
* Supporting user documentation

## Acceptance Criteria
- [ ] I can configure different actions for Dpad directions
- [ ] I can configure different actions for Thumbstick directions
- [ ] I can configure different actions for Touchpad directions
- [ ] I can configure different actions for trigger pressure
- [ ] I can configure different actions for controller rotation
- [ ] I can configure different actions for controller position

**Comment by StephenHodgson** [comment] 2018-08-21 13:29
This wouldn't be a component. It would be part of the interaction mapping UI

**Comment by StephenHodgson** [comment] 2018-08-21 13:34
Duplicate of https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2610

**Comment by StephenHodgson** [comment] 2018-08-21 13:36
Although I do see the appeal to having a configurable input threshold amounts and different options based on values of the inkut being received, but that would be for each component to figure out and implement (look at teleport pointer)

**Closed** 2018-08-21 14:27 UTC
Labels: MRTK vNEXT, Proposal
