### ISSUE TITLE
Runtime Bounding Box is Incorrectly Sized In Tests

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5386] opened 2019-07-19 18:59 UTC
## Describe the bug

A handful of the tests in the BoundingBoxRuntimeExample scene do not produce a correctly sized bounding box.

## To reproduce

1. Open the BoundingBoxRuntimeExample scene.
2. Hit play.
3. Press 1 to move to the second test.
4. Notice the bounding box is incorrectly sized and placed.

## Expected behavior

The bounding box matches the visuals.

## Screenshots

![image](https://user-images.githubusercontent.com/13305729/61558578-51d17b00-aa1c-11e9-8e72-96ac909ca12b.png)

## Your Setup (please complete the following information)

- mrtk_development

**Comment by Alexees** [comment] 2019-07-20 10:33
That's actually what the test does. If you check out the Hierarachy you'll notice that another collider appeared that the boundingbox perfectly fits.

![image](https://user-images.githubusercontent.com/32508825/61577644-8c094e00-aaea-11e9-9635-3fb1cef9c32d.png)

**Comment by julenka** [comment] 2019-07-21 07:28
Thank you Alex! And thank you very much for posting the updates, sorry for the late replies here (have been trying to get a couple other fixes in for GA release). Will look at this soon. Closing as by design, see Alex's comments above.

**Closed by julenka** 2019-07-21 07:28 UTC
Labels: Bug

**Comment by Cameron-Micka** [comment] 2019-07-22 17:12
Excellent, thank you @Alexees!
