### ISSUE TITLE
Input on Unity UI not working ONLY when ran with WMR

### ISSUE THREAD

**Issue by Wolfoso** [microsoft/MixedRealityToolkit-Unity#4305] opened 2019-05-13 10:05 UTC
## Describe the bug

While trying to build the same application for both HoloLens and WMR, I noticed that if I ran that App through the Mixed Reality Portal, UI input did not work. Everything worked in Editor and HoloLens.
To be clear, the raycast _did_ stop on the Canvas, but the button did not highlight on hovering and click did nothing.
Also, simulating the controllers in the WMR Portal while running the Unity Editor _worked_.

## To reproduce

Create a new Unity Project
Add only the MRTK2 with Examples
Build a project with the scene _HandInteractionUnityUIExample.unity_

## Expected behavior

When hovering or clicking a Unity UI button, the button should react accordingly.

## Video

Here's a video showing the button not reacting to the simulated controller (it takes a while for me to get on and off the button, sorry about that, simulated controls are terrible):

https://imgur.com/h5qLfv8

You can see the controller's ray _does_ collide with the Canvas, but nothing happens with the buttons.

## Setup

- Unity 2018.3.12f1
- MRTK v2.0.0-RC1

## Target Platform

- WMR immersive

**Comment by wiwei** [comment] 2019-05-14 23:17
I would ask if this repros on the latest release (i.e. RC1 refresh) but I think our latest actually has an issue where it doesn't work when deployed for reals (like you have here). 

I think that we can try to validate this after fixing that bug (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4287)

**Comment by Wolfoso** [comment] 2019-05-24 13:35
Updating to latest release seems to have fixed the issue.

**Comment by bielkinv** [comment] 2019-05-31 21:19
Exactly the same bug is reproduced for me on the latest release on the HandInteractionUnityUIExample scene. Works ok in Unity Editor with WMR headset and HL1. 

Unity: 2018.3.14f1, 2019.1.0f2
Mixed Reality Toolkit 2.0.0-RC1-Refresh
OS version: 10.0.17763 Build 17763
Mixed Reality Portal Version: 2000.19011.1132.0 (I tried to re-install it too).

**Comment by Wolfoso** [comment] 2019-07-30 16:54
Reopening as the problem is not completely solved.
This issue is still present though not all the time. Using the latest version of the MRTK2 (RC2.1) most of the time input does not work on UI elements. Restarting the computer multiple times solves the issue (restarting until it works)

**Comment by maluoi** [comment] 2020-02-18 23:28
Just gonna confirm, this looks like it's still happening.

**Comment by Troy-Ferrell** [comment] 2020-03-02 18:54
Closing as dupe of #4821

**Comment by keveleigh** [comment] 2020-04-21 17:11
Closing as dupe of #4821

**Closed by keveleigh** 2020-04-21 17:11 UTC
Labels: 0 - Backlog, Bug, DDE Partner, Input System, UnityUI, Urgency-Soon

**Comment by albinhw** [comment] 2020-07-12 21:33
This problem is still occurring. I have tested with MRTK 2.4. This is so random and hard to figure out the cause. The unity canvas based UI arbitrarily stops working. Does anyone figured out why it is happening?
