### ISSUE TITLE
HoloLens native keyboard issue

### ISSUE THREAD

**Issue by tletie** [microsoft/MixedRealityToolkit-Unity#10247] opened 2021-10-06 15:15 UTC
## Describe the bug

OS keyboard won't show up inside immersive app when place focus on text field while other app like edge is opened.

## To reproduce

When using the MRTK example hub app => go to "Hand Interaction Examples" => Keyboard Interaction => Keyboard => the os System keyboard is show up.
Now if user use the home gesture to bring up something like Edge and leave it open. Go back and do the the above steps inside MRTK example hub app => Keyboard won't show up.

The above will happen if we try on any other immersive app that have input text field that need keyboard. As long as we launch edge or other non immersive app and leave it opens, the keyboard won't show up when get back to immersive app.

## Expected behavior

It would be nice that we still can get the keyboard show inside immersive app text input field while other app like edge, file explorer, photo is opened

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.4.32f1]
- MRTK Version [e.g. v2.3.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by polar-kev** [comment] 2021-10-06 17:50
Hey @tletie this sounds like a platform bug. Can you share what version of the Hololens OS you're running?

**Comment by MaxWang-MS** [comment] 2021-11-20 01:19
Closing this issue as duplicate of #10289 (which also contains a video for the issue).

**Closed by MaxWang-MS** 2021-11-20 01:19 UTC
Labels: OS Bug, Bug
