### ISSUE TITLE
Standard Shader error on Android

### ISSUE THREAD

**Issue by grabbinits** [microsoft/MixedRealityToolkit-Unity#10532] opened 2022-04-07 13:37 UTC
## Describe the bug

I have a project running with the MRTK and for some reason, whenever I try to build for Android, I receive this error message:
`Shader error in 'Mixed Reality Toolkit/Standard': Non system-generated input signature parameter () cannot appear after a system generated value. at line 775 (on gles3)`

## To reproduce

1. Create a project ([MRTK Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/oculus-quest-mrtk?view=mrtkunity-2021-05))
2. Build Android 

## Screenshots
![image](https://user-images.githubusercontent.com/53926367/162211611-a6d2313e-6ddb-407a-af0a-5309242bf7a1.png)

## Your setup (please complete the following information)

- Unity Version [2021.2.14f1c1]
- MRTK Version [2.7.3.0]

## Target platform (please complete the following information)

- Oculus Quest2

**Comment by adiazcan** [comment] 2022-04-12 15:22
Same error here, I cannot use any material using this shader. 

![image](https://user-images.githubusercontent.com/6652046/162996943-813e2d5f-7d5e-457e-94bf-6d3b69a7b147.png)

**Comment by adiazcan** [comment] 2022-04-12 17:30
I solved my problem with the upgrade process to URP

![image](https://user-images.githubusercontent.com/6652046/163020079-cbfc9868-f044-4ace-a18e-4fb4ad90bbeb.png)

**Comment by keveleigh** [comment] 2022-04-25 19:20
Closing as duplicate of #10449

**Closed by keveleigh** 2022-04-25 19:20 UTC
Labels: Bug

**Comment by fatboxSoftware** [comment] 2022-05-04 00:37
> I solved my problem with the upgrade process to URP
> 
> ![image](https://user-images.githubusercontent.com/6652046/163020079-cbfc9868-f044-4ace-a18e-4fb4ad90bbeb.png)

Thank you for this!

**Comment by interactive3d** [comment] 2022-07-29 14:03
> I am actually having this issue, and the upgrade option is currently greyed out..... could something else be causing this issue?
> 
> ![image](https://user-images.githubusercontent.com/17780361/167667746-3387d5a9-eaf1-4b8a-a0cf-f38647b0b2ae.png)

Did you manage to find the solution?

**Comment by ahmed-shariff** [comment] 2022-10-06 06:55
@interactive3d You'll have to follow the instructions in https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/InstallURPIntoAProject.html to install and setup URP for this menu item to be enabled

**Comment by JCMazza** [comment] 2022-10-10 15:56
I tried by adding URP but it still doesn't work. This issue seem to have started when upgrading unity to 2021. It works fine on 2019 LTS.

**Comment by k3rn3l-paN1c** [comment] 2022-12-17 02:42
This still does not work is there an actual real fix for this!

**Comment by JCMazza** [comment] 2022-12-19 18:22
> This still does not work is there an actual real fix for this!

Here is the fix tht works for me in ehs hader code change:

fixed facing : VFACE" to "bool facing : SV_IsFrontFace" at line 775
* facing to "* (facing ? 1.0 : -1.0)" at lines 956 & 959

**Comment by ChevronXRKeef** [comment] 2023-06-16 01:12
> > This still does not work is there an actual real fix for this!
> 
> Here is the fix tht works for me in ehs hader code change:
> 
> fixed facing : VFACE" to "bool facing : SV_IsFrontFace" at line 775
> 
> * facing to "* (facing ? 1.0 : -1.0)" at lines 956 & 959

You legend! This saved me hours of troubleshooting.

**Comment by MiCkSoftware** [comment] 2024-05-04 12:19
possible fix :             fixed4 frag(v2f i, fixed facing : VFACE) : SV_Target
      //      fixed4 frag(v2f i, bool facing : SV_IsFrontFace : SV_Target
