### ISSUE TITLE
Utilities.Editor assembly should reference the core, not the other way around.

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7152] opened 2020-01-24 22:46 UTC
While working on XR SDK setup, I noticed that the core assembly as a reference to the editor utilities assembly. This means that it is not possible for the editor utils to reference any MRTK types that may be desirable to share between runtime and editor code.

This fix would involve rethinking some parts of the MixedRealityToolkit service locator class to separate editor functionality from the runtime.

When the necessary changes to invert this relationship are made, careful testing must be performed to ensure no functionality breaks and the product maintains or improves the current stability level.

**Comment by Troy-Ferrell** [comment] 2020-01-28 03:02
Related #7152

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/06d162ba21eb50e615085e4638eea4731c108ee4/Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs

Line 105 after PR goes in

**Comment by Troy-Ferrell** [comment] 2020-01-29 00:34
Related #7175 

Can't use the `BaseSpatialObserver.DefaultSpatialAwarenessLayer` in MRTK configurator or other editor utility locations because of this bug

**Comment by keveleigh** [comment] 2020-02-05 16:56
Duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3952

**Closed by keveleigh** 2020-02-05 16:56 UTC
Labels: Bug, Services
