### ISSUE TITLE
Hand Controller Velocity is always <0, 0, 0> on Hololens 2

### ISSUE THREAD

**Issue by sktistakis** [microsoft/MixedRealityToolkit-Unity#10477] opened 2022-02-20 16:10 UTC
## Describe the bug

Using the IMixedRealityController obtained by the OnSourceDetected event (IMixedRealitySourceStateHandler), the hand controllers velocity is always <0, 0, 0> on the Hololens 2. It works in Unity Editor Play Mode, though.

## To reproduce

Create a MonoBehaviour class that implements the IMixedRealitySourceStateHandler interface.
On the Update() function, try to access the Controllers Velocity property in case the Controller was previously set via the OnSourceDetected() event handler. When moving the hands around (regardless of left or right hand) the velocity will always be a Vector3 of zeros. In the Unity Editor Mode though the velocity is displayed correctly.

## Expected behavior

I expect the velocity of the hand controller to display the hand velocities and not 0 for the x,y,z components.

## Your setup (please complete the following information)

- Unity Version 2020.3.20
- MRTK Version v2.7.2.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by davidkline-ms** [comment] 2022-03-02 18:44
@sktistakis, Is this the OpenXR runtime or the Windows XR plugin?

Also, can you share an example of the code you are using and/or a video capture.

Thanks!

**Comment by MarkoXR** [comment] 2022-04-13 15:49
I have encountered the same issue, could this be the cause of another issue: #7178 ? 
This is my code:
var hand = HandJointUtils.FindHand(Handedness.Right);
if (hand == null) return;
Debug.Log(hand.Velocity.magnitude);
It behaves as expected in editor but on hololens it is always 0.
I have to check which versions I'm using

**Comment by MarkoXR** [comment] 2022-04-14 12:02
It seems to me that the OpenXR Hand Controllers velocity isn't being updated

**Comment by RogPodge** [comment] 2022-04-14 16:18
Will be addressed by [#10538](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10538)

**Closed** 2022-04-21 19:26 UTC
Labels: Bug
