### ISSUE TITLE
Building UWP in all versions of Unity not working for Visual Studio 2017 15.3

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#860] opened 2017-08-15 11:29 UTC
**Be advised, do not update visual studio to 15.3!**
See https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/833

>There is a compatibility issue between Unity and upcoming Visual Studio 2017 update 3 when targeting UWP, using .NET scripting backend (IL2CPP scripting backend is not affected) and building generated Visual Studio project.

[Read full details here.](https://forum.unity3d.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/)

Here is the status of patches with the fix:
- 5.5 version with the fix: 5.5.4p5 (not released yet)
- 5.6 version with the fix: 5.6.3p3 (not released yet)
- 2017.1 version with fix: [2017.1.0p5](https://unity3d.com/unity/qa/patch-releases/2017.1.0p5)
- 2017.2 version with fix: [2017.2.0b7](http://beta.unity3d.com/download/4bc201a72e4a/UnityDownloadAssistant-2017.2.0b7.exe)

[Potential Work Around.](https://forum.unity3d.com/threads/unable-to-build-even-an-empty-project.488278/)

**Comment by jessemcculloch** [comment] 2017-08-15 12:55
This is a duplicate of #833

**Comment by StephenHodgson** [comment] 2017-08-15 14:27
Not exactly, more of a report that there was an issue, where this issue details the cause and soon resolution.

I was under the impression that it only affects 2017.2, but it instead affects all current versions of the editor.

**Comment by jessemcculloch** [comment] 2017-08-15 14:39
Gotcha.  Interesting that it's the exact same error message.

**Comment by hencohen3** [comment] 2017-08-16 11:03
I have vs 2017 15.3 and i download the 2017.2.0b7 Released you suggest  now i have build problems with 
using UnityEngine.VR.WSA;   The type or namespace name `WSA' does not exist in the namespace `UnityEngine.VR'. Are you missing an assembly reference?

**Comment by ThmsMsqrt** [comment] 2017-08-16 12:40
@hencohen3 try to change UnityEngine.VR.WSA to UnityEngine.XR.WSA

**Comment by hencohen3** [comment] 2017-08-16 13:31
@ThmsMsqrt  i change to UnityEngine.XR.WSA  but now im getting a lot of errors(i attached image) . the build is successful but when i try to run for exmple the "cursor" scene in the hololens the build and deployment is successful but i cant see any thing in th
![capture555](https://user-images.githubusercontent.com/19545791/29365623-529bb474-82a0-11e7-9984-8b4488be55cf.PNG)
e hololens. 
Any idea?

**Comment by StephenHodgson** [comment] 2017-08-16 15:48
Only use the 2017.2 Dev branch with the 2017.2 editor.

**Comment by hencohen3** [comment] 2017-08-16 15:54
@StephenHodgson  what do you mean? to download vs 2017.2 and to stay with the unity 2017.2.0b7 ?

**Comment by StephenHodgson** [comment] 2017-08-16 16:03
I'm saying we've already done the work to get the 2017.2 Dev branch working in the 2017.2 editor and to test that, instead of upgrading the 2017.1 branch.

**Comment by Zod-** [comment] 2017-08-21 06:45
They've pushed back the versions for when this will be fixed as the the new patch is for the security update. e.g. `5.6.3p1` was just released but the fixed version was pushed back to `5.6.3p3`

5.5 version with the fix: 5.5.4p5 (not released yet)
5.6 version with the fix: 5.6.3p3 (not released yet)
2017.1 version with fix: 2017.1.0p5 (not released yet)

**Comment by genereddick** [comment] 2017-08-22 01:43
I can't seem to find any working combination of Visual Studio, Unity and HoloLens Toolkit. -- things were fine prior to updating VS  

I've tried VS 2017.3 and 2017.3.1 with Unity 2017.1.n and 2017.2.0b7 and 2017.2.0b8 and HL 2017.1 master & 2017.2 with no luck but maybe I'm missing something.  

Is there one set of those that definitely works, or is rolling back VS to 2017.2 the best bet?

**Comment by StephenHodgson** [comment] 2017-08-22 23:35
A nice little [discussion on the unity forum](https://forum.unity3d.com/threads/unable-to-build-even-an-empty-project.488278/).

An interesting workaround.

**Comment by joekellyms** [comment] 2017-08-22 23:54
Just tried this workaround today, and it worked for me:
https://forum.unity3d.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/#post-3191224
I also didn't have re-do the fix after building again. It must keep that file if you build to the same location.

**Comment by StephenHodgson** [comment] 2017-08-25 16:00
Finally a fix! [2017.1.0p5 released](https://unity3d.com/unity/qa/patch-releases/2017.1.0p5)

**Closed** 2017-08-25 18:59 UTC
Labels: Unity Bug

**Comment by StephenHodgson** [comment] 2017-09-01 17:03
[Unity patch 5.6.3p3 Released](https://unity3d.com/unity/qa/patch-releases/5.6.3p2)
