### ISSUE TITLE
Service Facades no longer update when enabling / disabling services

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#5991] opened 2019-09-18 17:36 UTC
## Describe the bug

When enabling / disabling services outside of play mode facades no longer update to reflect changes.

## To reproduce

1) Add an MRTK instance to the scene.
2) Check 'Use Service Inspectors.'
2) Enable or disable a service.
3) Observe that facades do not change.

## Expected behavior

Facades should always be up-to-date.

- Unity Version 2018.4.3f1
- MRTK development branch

**Comment by keveleigh** [comment] 2019-09-18 19:04
Due to #5977? @wiwei

**Comment by Railboy** [comment] 2019-09-18 19:11
I _believe_ it's a result of #5746. Facade updates were very aggressive before that change. Not 100% sure though.

**Comment by keveleigh** [comment] 2020-03-25 16:33
Actually, I think I'll leave this closed as a dupe of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7587, which has a bit more info

**Closed by keveleigh** 2020-03-25 16:33 UTC
Labels: Bug, Profile and Inspectors
