### ISSUE TITLE
MRTKFeatureTool doesn't work first time on new project

### ISSUE THREAD

**Issue by julesra** [microsoft/MixedRealityToolkit-Unity#9232] opened 2021-02-04 20:37 UTC
## Describe the bug

The MRTK Feature Tool doesn't seem to work on a fresh unity project on first run. After it validates & applies changes & displays success message, the Unity project remains unchanged and Unity doesn't seem to notice any updates. To make it work I have to run the MRTK Feature Tool again on the same project with the same settings.

## To reproduce

- Follow the instructions here to create a new Unity project: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02
- After the step of running the MRTK Feature Tool to install the MRTK Framework into the project, switch back to the Unity project and observe that nothing happens. Even if refreshing the project using CTRL+R.
- Rerun the tool on the same project and observe that it works properly on the 2nd run.
- (During this whole time, the project has remained open in Unity; I don't know what happens if Unity is restarted)

## Expected behavior

- I expect that as soon as I switch from MRTK Feature Tool back to the Unity project, Unity would start importing the projects.
- If there is a problem, I would want the tool to tell me.

## Your setup (please complete the following information)

- Unity Version 2019.4.19f1
- MRTK Version to be installed through the tool: 2.5.1 (I also tried with 2.5.3) 
- MRTK Feature Tool version 1.0.2102.0 Beta

## Target platform (please complete the following information)

UWP

**Comment by MaxWang-MS** [comment] 2021-02-09 01:02
@davidkline-ms Please take a look at this issue - seems to be the same as what people reported on the slack channel.

**Comment by davidkline-ms** [comment] 2021-02-11 18:32
@julesra. Thank you for the report. I will investigate this for the next tool update.

**Comment by davidkline-ms** [comment] 2021-02-11 23:55
I have tried to reproduce this on the upcoming version and have not been successful. i tried on Unity 2018.4, 2019.4 and 2020.2.

**Comment by davidkline-ms** [comment] 2021-02-11 23:55
es

**Comment by davidkline-ms** [comment] 2021-03-10 19:12
I believe this is now fixed, if that is not the case, please download version 1.0.2103.1-Beta (or later) from https://aka.ms/mrfeaturetool and attach the log file when reopening this issue.

**Closed by davidkline-ms** 2021-03-10 19:12 UTC
Labels: External
