### ISSUE TITLE
Disabling "Use Service Inspectors" in MRTK Editor menu throw InvalidOperationException

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6762] opened 2019-12-02 09:54 UTC
## Describe the bug

Disabling the mentioned option after enabling it throws a bunch of errors like this one:

```
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.DestroyFacades () (at Assets/MixedRealityToolkit/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:189)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.UpdateServiceFacades () (at Assets/MixedRealityToolkit/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:129)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.OnSceneGUI (UnityEditor.SceneView sceneView) (at Assets/MixedRealityToolkit/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:44)
UnityEditor.SceneView.CallOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:2849)
UnityEditor.SceneView.HandleSelectionAndOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:2126)
UnityEditor.SceneView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:1987)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:342)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:336)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:310)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean customBorder, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:361)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:320)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:244)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

## To reproduce

1. Go to any scene, create an MRKT with default profile and toggle it's Editor menu "Use Service Inspectors" checkbox on and off

## Expected behavior

No errors

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/69949579-15e21280-14f2-11ea-8ee2-a9a60a9945da.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK mrtk_development

## Target Platform (please complete the following information)

- Android Editor

**Comment by Troy-Ferrell** [comment] 2019-12-04 23:11
Dupe of #6794

**Closed by Troy-Ferrell** 2019-12-04 23:11 UTC
Labels: Bug
