### ISSUE TITLE
Heavy flickering 

### ISSUE THREAD

**Issue by PowZone** [microsoft/MixedRealityToolkit-Unity#10308] opened 2021-11-10 15:05 UTC
I just created a new project, used MixedRealityFeatureTool to install all packages, applied recommented settings to project and scene for Hololens2 and added a sphere to an empty scene.

With Hololens 2 I can move around the sphere, but the entire scene flicker badly. Like the rendering jumps between eyes.

Versions:
- Unity 2020.3.21f1 
- MRTK 2.7.2 
- OpenXR 1.2.8

Platform:
- HoloLens 2

**Comment by keveleigh** [comment] 2021-11-10 18:56
This is a known issue with Unity versions 2020.3.21f1 and newer. We're tracking it at https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10288, and Unity is tracking it at https://issuetracker.unity3d.com/issues/severe-flickering-in-unity-2020-dot-3-21f1-with-openxr-on-hl2?_ga=2.265488847.1383477956.1636396113-862490274.1597860099.

I'll close this as a duplicate of #10288, and we'll be sure to keep that issue updated!

**Closed by keveleigh** 2021-11-10 18:56 UTC
Labels: Bug
