### ISSUE TITLE
stereoscopic rendering is off

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1282] opened 2017-11-01 15:14 UTC
For some reason, the stereoscoping rendering is broken in our project. Sometimes, when starting from the editor, the gaze points part away from each other the further I look down or up and the closer it is. Maybe someone can give me a hint on how to debug or fix this?

**Comment by StephenHodgson** [comment] 2017-11-01 15:21
Duplicate of #1236

**Closed by StephenHodgson** 2017-11-01 15:21 UTC
Labels: Duplicate, Unity Bug
