### ISSUE TITLE
"View Asset" in MRTK profile inspector does nothing

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6766] opened 2019-12-02 17:19 UTC
## Overview

Clicking view asset for any profile item in MRTK profile inspector does not do anything.

## Expected Behavior

Inspector should switch to that profile only or highlight/select the item in asset view. etc

## Actual Behavior

![view-asset](https://user-images.githubusercontent.com/25975362/69980300-cc3efb00-14e4-11ea-898e-e1c8440b7cf4.gif)

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version

2018.4.13

## Mixed Reality Toolkit Release Version

2.2.0_Stabilization

**Comment by Troy-Ferrell** [comment] 2019-12-02 17:26
Looks like view asset is using EditorGUIUtility.PingObject which I believe targets the scene hierarchy. not asset database

**Comment by davidkline-ms** [comment] 2019-12-02 17:29
thanks @Troy-Ferrell. i will take a look

**Comment by davidkline-ms** [comment] 2019-12-02 17:56
I tried with unlocked profiles and do not see the reported behavior. Will investigate with profiles locked.

**Comment by Railboy** [comment] 2019-12-02 18:11
>Looks like view asset is using EditorGUIUtility.PingObject which I believe targets the scene hierarchy. not asset database.

@Troy-Ferrell This pings asset in the project view as well, but only if the project window is open. If the project view is not open it has no effect.

I'm not able to repo the behavior I see in your gif. When I click the button the profile is highlighted in the project view both for locked and unlocked profiles.

**Comment by Troy-Ferrell** [comment] 2019-12-02 18:21
Hmmm I'll try with a different version of Unity. I was on 2018.4.13

**Comment by davidkline-ms** [comment] 2019-12-02 18:26
I'm on 2018.4.13 also

**Comment by Troy-Ferrell** [comment] 2019-12-02 20:10
> I'm on 2018.4.13 also

Damn, I'll try restarting or something. I have the project window open so it should highlight. I thought `PingObject` would work for assets not in the scene as I swear I have seen before. 

Unity's docs *suggest* otherwise though
https://docs.unity3d.com/ScriptReference/EditorGUIUtility.PingObject.html
"Ping an object in the Scene like clicking it in an inspector."

**Comment by davidkline-ms** [comment] 2019-12-02 22:47
removing release blocker until we can find a consistent repro (preferably on multiple computers)

**Comment by davidkline-ms** [comment] 2019-12-03 21:39
Closing as not able to reproduce. If this occurs again, please reactivate and we will continue to investigate.

**Closed by davidkline-ms** 2019-12-03 21:39 UTC
Labels: Bug, Profile and Inspectors
