### ISSUE TITLE
Example Hub: duplicated menu

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6799] opened 2019-12-05 09:07 UTC
## Describe the bug

when launching any subscene from the example hub, the menu is duplicated (this can be ssen by moving the menu by hand)
one of the menu has the 'home' menu icon, the otehr has not.
the menu is not duplicated in the hub itself

## To reproduce

1. launch mrtk example hub
2. select any cube representing an example
3. move the menu
4. observe the menu is duplicated

## Expected behavior

only one menu should be displayed

## Screenshots

![20191205_005727_HoloLens](https://user-images.githubusercontent.com/49415246/70220263-9a2cd380-1746-11ea-8b36-565d04e29701.jpg)

## Your Setup (please complete the following information)

- Unity Version [2018.4.13f1]
- MRTK Version [v2.2]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by keveleigh** [comment] 2019-12-05 17:55
Duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6735

**Closed by keveleigh** 2019-12-05 17:55 UTC
Labels: Bug
