### ISSUE TITLE
System keyboard : backspace and preview don't work

### ISSUE THREAD

**Issue by Eleart** [microsoft/MixedRealityToolkit-Unity#8916] opened 2020-11-06 10:38 UTC
## Describe the bug

When I use TouchScreenKeyboard on my app the backspace doesn't work. The left and right arrows neither. Finally I don't see the input field

## To reproduce

Use the following script : 
```
public TouchScreenKeyboard keyboard;

...

public void OpenSystemKeyboard()
{
    keyboard = TouchScreenKeyboard.Open("", TouchScreenKeyboardType.Default, false, false, false, false);
}

private void Update()
{
    if (keyboard != null)
    {
        keyboardText = keyboard.text;
        // Do stuff with keyboardText
    }
}
```

## Expected behavior

At least to be able to backspace and navigate on the input. Not necesarely  to have a preview (I can use an input field to do that)

## Your setup

- Unity Version 2019.4.13.f1
- MRTK Version 2.4

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment] 2020-11-06 18:15
The delete key is a Unity bug. We've been tracking this with them, but it doesn't look like a fix has shipped yet.

**Comment by MaxWang-MS** [comment] 2021-01-27 22:38
The backspace key issue has been fixed in the current mrtk_development branch. The missing preview is not a bug and if you do need one we have an implementation in MRTK (the `MixedRealityKeyboardPreview` prefab). Please see the left hand side of the `HandInteractionExamples` scene as an example.

**Closed by MaxWang-MS** 2021-01-27 22:38 UTC
Labels: External
