### ISSUE TITLE
Render from PV Camera: Additional holographic camera no offset like main camera during MRC

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#9169] opened 2021-01-26 04:41 UTC
## Describe the bug
During mixed reality capture, an additional holographic camera will not be offset in the same way as the main camera if the main camera is under an MRTK Playspace which has been teleported. The additional camera appears to still be treated as though the main camera is relative to the world origin. 

This bug was identified in the comments of #8066 as a separate an external Unity bug. This issue has been created for visibility and tracking.

## To reproduce

100% repro on this, using Unity 2019.4.2f1. It appears the MRC is ignoring the MRTKPlayspace transform and only using the camera's local transform.

Repro steps:
1) Open HandInteractionSamples scene.
2) Set "Render from PV Camera" checkbox (will need to clone some profiles to do this).
3) Set the MixedRealityPlayspace position to (1, 0, 0).
3.a) Note that something intermittently sets the camera's transform to counteract the playspace offset. Make sure camera transform is still identity.
4) Observe in game view that camera is displaced to the right, as expected.
5) Build, deploy, and run.
6) Observe in HL2 that camera is displaced to the right, as expected.
7) Open MRC in Windows Device Portal
8) Start Live Preview
9) Observe that camera is still centered, unlike what user sees in HL2 (or Unity game view).

Note that if "Render from PV Camera" is not enabled, then there is no disparity, the MRC and the user view are both displaced to the right as expected.

_Originally posted by @fast-slow-still in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8066#issuecomment-728937028_

## Target platform (please complete the following information)

- HoloLens 2

**Comment by polar-kev** [comment] 2021-01-26 20:10
This appears to be fixed in Unity 2020 but is still present across the board in 2018 and 2019.

**Comment by polar-kev** [comment] 2021-01-27 21:02
Closing as a duplicate of #8707

**Comment by fast-slow-still** [comment] 2021-01-28 11:09
Hi @polar-kev , this isn't really a duplicate of #8707, as that bug is specifically limited to when using XRSDK, and this bug is specifically for when using Unity's Legacy VR/XR pipeline.

Thanks!

**Comment by polar-kev** [comment] 2021-01-28 17:24
My mistake @fast-slow-still, thanks for catching that.

**Comment by keveleigh** [comment] 2021-09-08 20:17
This should be fixed in 2018.4.34 and 2019.4.24 or later. Please reopen if you're still hitting this on these versions or later!

**Closed by keveleigh** 2021-09-08 20:17 UTC
Labels: External
