### ISSUE TITLE
[ManipulationHandler][DefaultControllerPointer] Nullref occurs at times when interacting with a ManipulationHandler via a DefaultControllerPointer

### ISSUE THREAD

**Issue by Kjakubzak** [microsoft/MixedRealityToolkit-Unity#6011] opened 2019-09-20 00:20 UTC
## Describe the bug

When interacting (via DefaultControllerPointer) with an object using the ManipulationHandler, it sometimes causes the following errors to hit:

```
`NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerDragged(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_12(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)

NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Component_Get_Custom_PropTransform(Object self)
   at UnityEngine.Component.get_transform()
   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Rotation()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.PointerData.get_GrabPoint()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.HandleOneHandMoveUpdated()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.InvokeStateUpdateFunctions(State oldState, State newState)
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.UpdateStateMachine()
   at Microsoft.MixedReality.Toolkit.UI.ManipulationHandler.OnPointerUp(MixedRealityPointerEventData eventData)
   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.<>c.<.cctor>b__195_14(IMixedRealityPointerHandler handler, BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute[T](GameObject target, BaseEventData eventData, EventFunction1 functor) 
(Filename: <Unknown> Line: 0)`

```
## To reproduce

This sometimes results in the app losing all user input capabilities; but more often it causes a significant amount of performance degradation. 

There's no consistent repro step in our application; it seems to be related to turning pointers on and off based on what utilities we are activating/deactivating, and then triggering far field interactions with our manipulation handler. 

## Expected behavior

When switching between active pointers (using a pointer mediator), it's 

## Your Setup (please complete the following information)

- Unity Version 2018.4.8f1
- MRTK Version 2.1.0-20190918.5

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by Alexees** [comment] 2019-09-20 07:22
This is no MRKT bug, the NullRef is thrown by Unity when accessing the Transform component. Are you doing anything funny with your GameObjects, cloning them, performing custom serialization, anything that could break a GameObject on a lower level?

**Comment by Kjakubzak** [comment] 2019-09-21 16:14
It's a Unity Nullref that's being triggered when the ManipulationHandler is trying to access the transform component of a BaseControllerPointer. The ManipulationHandler is a MRTK construct, and the BaseControllerPointer is a MRTK construct (since we're using the DefaultBaseControllerPointer for far field, and not a custom one).

We don't own the lifecycle management of pointers gameobjects in our app; MRTK's system is doing so. Unless we're somehow throwing a wrench into MRTK's pointer lifetime management; I believe this is likely a MRTK bug.

**Comment by MenelvagorMilsom** [comment] 2019-10-03 15:11
> it seems to be related to turning pointers on and off based on what utilities we are activating/deactivating

@Kjakubzak I wanted to see if I could repro this today, but I couldn't get the errors that you showed. Could you let me know if what you're doing is similar to what's being done in the DisablePointersExample scene. If so, can you see if you can reproduce this bug in this scene?

If you're not doing something similar to this scene, could you give me some more specifics for what utilities you are activating/deactivating

**Comment by Kjakubzak** [comment] 2019-10-07 14:45
Hi, sorry for the late response. I really should take a look at Github more often.

This has become a much higher-pri bug for me and my team since we want to branch soon, so I will take a look at that scene and try to repro this in that scene. 

We've actually started to use the PointerUtilities rather than directly enabling and disabling pointers. It's led to this happening leiss often, but it still occurs. Will get back to you today with either a repro or no repro. If all else fails,  I can always bring my device upstairs (granted you're in C).

**Comment by MenelvagorMilsom** [comment] 2019-10-07 14:52
> Hi, sorry for the late response. I really should take a look at Github more often.

No worries!

> This has become a much higher-pri bug for me and my team since we want to branch soon, so I will take a look at that scene and try to repro this in that scene.
>
> We've actually started to use the PointerUtilities rather than directly enabling and disabling pointers. It's led to this happening leiss often, but it still occurs. Will get back to you today with either a repro or no repro. If all else fails, I can always bring my device upstairs (granted you're in C).

I'm actually based in Dublin, but give me an update here and I'll do my best to investigate right away.

**Comment by Kjakubzak** [comment] 2019-10-08 16:47
Hi,

Following up on this! We weren't able to repro this in the min scene, however we did repro it locally and were able to isolate the code path. Hopefully this will give more context as to what's happening (and what might need to be changed).

So following the drag event (ManipulationHandler.cs: 548), the event that's passed in is thrown out and the UpdateStateMachine function is called. The reason I bring this up is because it seems like at one point in the drag lifecycle (whether it's near or far field); there's a potential for the pointer that's doing the dragging to change. The pointer seems to blink out of existence and back in (the PointerID is completely different, but the pointer type and associated hand that is passed into the drag event is the same). 

The UpdateStateMachine then refers to the pointerIdToPointerMap variable; which now contains a stale reference to the old pointer (different source ID, same pointer type as what triggered this). That stale reference isn't null, but the transform it referred to is now null. 

HandleOneHandMoveUpdated then is called, and in the case of the FaceUser/FaceAwayFromUser/RotateAboutGrabPoint rotation types, refers to the stored stale pointer and attempts to use the rotation value in it (which is now null, since the pointer reference itself is stale). 

There are two things here:
1. Making sure the ManipulationHandler has a more robust pointer consistency/mapping system that can handle these blips
2. The fact that there are blips occuring in the pointer system; which by all rights shouldn't be happening.

**Comment by MenelvagorMilsom** [comment] 2019-10-09 15:46
Hey again @Kjakubzak, I've been looking again today. I still have no success reproducing this issue. I've been sifting through the input system code looking for possible causes, but haven't found anything yet. 

Some additional info and questions:
- > Making sure the ManipulationHandler has a more robust pointer consistency/mapping system that can handle these blips

  `ManipulationHandler` should be able to handle this; usually when we get a new pointer, we expect an `OnPointerUp` event for the old pointer and an `OnPointerDown` event for the new pointer. This would update the map. I assume that this isn't happening for your case? Can you ensure that these functions are not called immediately prior to the NullReferenceException.
- > The fact that there are blips occuring in the pointer system; which by all rights shouldn't be happening.

  I 100% agree. If the source of the issue is in the pointer/input system, we should fix it there as this is definitely unexpected behaviour that `ManipulationHandler` shouldn't have to deal with.
- > The reason I bring this up is because it seems like at one point in the drag lifecycle (whether it's near or far field); there's a potential for the pointer that's doing the dragging to change. The pointer seems to blink out of existence and back in (the PointerID is completely different, but the pointer type and associated hand that is passed into the drag event is the same).

  This appears to suggest that this happens of it's own accord. How does this relate to enabling and disabling of pointers using `PointerUtils`? Do you think you could share a video so I can get more context around what it is you're trying to do?
- Does this only repro on device (i.e. can you repro with simulated hands in editor)? So far I've only been attempting to repro on device, but it's useful information all the same.

Let me know if you have any additional updates for this. Cheers.

**Comment by Kjakubzak** [comment] 2019-10-09 17:05
>   `ManipulationHandler` should be able to handle this; usually when we get a new pointer, we expect an `OnPointerUp` event for the old pointer and an `OnPointerDown` event for the new pointer. This would update the map. I assume that this isn't happening for your case? Can you ensure that these functions are not called immediately prior to the NullReferenceException.

The OnPointerUp event isn't triggering due to the pointer dying (even if it's a part of the pointer lifecycle for OnDestroy, it doesn't seem to be getting received by this) from what I've seen. Let me check if the OnPointerDown event is getting triggered.
  
>   I 100% agree. If the source of the issue is in the pointer/input system, we should fix it there as this is definitely unexpected behaviour that `ManipulationHandler` shouldn't have to deal with.

Sure, I agree with this. We've created a local version of it in the interim that handles the dead pointers and does collection on them (which mitigates the problem); but that's since we're close to creating a release branch and can't wait for a proper fix. 

>   This appears to suggest that this happens of it's own accord. How does this relate to enabling and disabling of pointers using `PointerUtils`? Do you think you could share a video so I can get more context around what it is you're trying to do?

We have two scenarios it's reproing in. One is where we're grabbing and not turning off any pointers (and actually setting our grab pointer to AlwaysOn), and then we go from two-handed manipulation to one-handed and vice-versa. It seems to be when users are doing a lot of grab/poke operations on the object, and eventually it gets to a point where the blip occurs and the user can't interact further through grabbing. 

The other we are forcing the gaze pointer on for a gaze/voice-driven interaction model, and one of the things that happens is that we're also allowing for them to first attach it using gaze or hand beams. If done through gaze, we also allow them to override that usage with hand beams and the OnPointerUp event isn't getting hit (resulting in this dragging error).

> * Does this only repro on device (i.e. can you repro with simulated hands in editor)? So far I've only been attempting to repro on device, but it's useful information all the same

We can doing the second scenario above. The first scenario has only been repro'd on device after 10+ minutes of app usage.

**Comment by davidkline-ms** [comment] 2019-11-21 22:10
This has not been able to have been reproduced. After speaking with relevant individuals, closing.

If you see this in the future, please re-open and flag @davidkline-ms and @wiwei.

**Closed by davidkline-ms** 2019-11-21 22:10 UTC
Labels: Bug, Consider for Next Iteration, MRW Cares, Urgency-Now
