### ISSUE TITLE
Distribute test utility functions

### ISSUE THREAD

**Issue by FreakTheMighty** [microsoft/MixedRealityToolkit-Unity#6997] opened 2020-01-07 18:47 UTC
## Describe the problem

As a consumer of MRTK I would like to be able to easily write integration tests that utilize MRTK systems. For example, simply triggering a button click requires the scene is setup and configured propertly. Internal tests have utility functions [here](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.Tests/TestUtilities.cs) and [here](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs). Unfortunately, those functions are difficult to access as they are not distributed as packages and come with the internal test suite which depends on nearly every other part of the code base.

## Describe the solution you'd like
I would like all test utility functions to be packaged with the tools.

## Describe alternatives you've considered
I've looked into better ways to mock inputs. For example, if `Interactable` implemented an `IClickable` interface, then I could have provided dumbed down version for testing. I wasn't able to come up with an easy way to mock this particular dependency though.

**Comment by wiwei** [comment] 2020-01-07 21:55
This is actually something that we're looking at right now with some of our NuGet packages - i.e. the test infrastructure that we have (around showing hands, moving things, etc) is pretty handy for writing tests and preventing regressions and has been a big part of what allows us to prevent random things from breaking.

Definite +1 here for making this possible.

@FreakTheMighty specifically are you looking for maybe a .unitypackage containing the test infra that we have?

**Comment by FreakTheMighty** [comment] 2020-01-07 23:54
A unitypackage would be fine. I'm sure somewhere there's discussion about moving to UPM, but I'll take it however the rest of the framework is distributed.

**Comment by davidkline-ms** [comment] 2020-01-08 00:40
We are considering adding the testing utilities to the Tools package (unitypackage, nuget initially). Would that work?

**Comment by FreakTheMighty** [comment] 2020-01-08 01:11
I'm not terribly familiar with what else is in the tools package, but seems like a fine place to me. The developer experience I'm looking for is the relatively easy installation of these utility functions.

**Comment by wiwei** [comment] 2020-01-08 03:16
@davidkline-ms chat with @CDiaz-MS on what's she's working on, it's not adding to the Tools package (which itself has a ton of things that you may not actually be interested in if you're just writing tests)

**Comment by wiwei** [comment] 2020-01-17 00:26
Alrighty, this should be out in the next release:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7032/files

**Comment by wiwei** [comment] 2020-01-17 00:28
Note that we made the decision to have it be a separate package (separate from tools) so make it possible to create pipelines/setups that don't pull in the editor-specific tooling (i.e. optimizer, dependency window, etc). Ideally you should be able to create a minimal pipeline/infra setup using just the foundation + test utilities package instead of pulling in other stuff you don't need.

I think we're open though to other organizations of stuff. I *think* I'm going to close this out because we've done the legwork here to make this possible, it's just now waiting for it to hit the upcoming release train.

**Closed by wiwei** 2020-01-17 00:28 UTC
Labels: Feature Request, MRW Cares
