### ISSUE TITLE
Voice Commands in Editor do not work after focus transferred to headset

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4302] opened 2019-05-11 22:21 UTC
(Ported to GitHub, reference 19337743)

From Alex:

1. Add some voice commands to an MRTK Scene
2. Press play in the editor
3. Say some commands, observe that they run
4. Put focus into headset
5. Say Commands
6. Observe that they do not work
7. Remove focus from headset
8. Say Commands
9.  Observe that they do not work

Expected: Commands should run in all of 3, 6, and 9
Actual: Commands only run in step 3.

I suspect this is an input routing issue that may not be easily resolved; but perhaps if we have communication/documentation on where to put focus back to?

**Comment by chbecker-ms** [comment] 2019-05-11 22:21
Comment from David:

Best of my knowledge is that the platform (Windows) is responsible for mic / speaker switching when using headsets.

There may also be an issue with Unity's play mode.

Should continue to investigate. Perhaps asking for help from the audio team.

**Comment by wiwei** [comment] 2019-07-15 22:46
This is a dupe of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4320

**Closed by wiwei** 2019-07-15 22:46 UTC
Labels: 0 - Backlog, Bug, Speech
