### ISSUE TITLE
"Select" voice command does not fire the appropriate events when using OpenXR on HoloLens 2

### ISSUE THREAD

**Issue by cj-lopez** [microsoft/MixedRealityToolkit-Unity#10154] opened 2021-08-12 16:33 UTC
## Describe the bug
When you Gaze and say "Select" on a HoloLens 2, the MRTK input system should fire the appropriate events for the "select" action. This no longer works like it did for the Legacy XR. Other keywords work just fine.

## To reproduce

The easiest way to see the problem is with the EyeTrackingDemo example
1. Install the OpenXR Plugin
2. Import the EyeTracking demo
3. Deploy to the HoloLens 2
4. In the TargetSelection scene, say "select" while looking at a gem, the speech confirmation tooltip appears, but the gem does not explode.  Saying "explode" does explode the gem. 
5. Gaze at a different scene in the Scene Menu and say "select".  It's no longer possible to change scenes with the "select command".

## Expected behavior

Saying "Select" should fire the appropriate events to cause a "select" action.  

## Screenshots

Unfortunately, the "select" tooltip isn't captured when I try to take a screenshot.
![Select](https://user-images.githubusercontent.com/37610557/129233695-4e9039b3-5818-4def-8bd7-a458e11e11a1.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.15f2
- MRTK Version 2.7.2
- MR OpenXR Plugin 1.0.2
- OpenXR Plugin 1.2.8
- XR Plugin Management 4.0.7

## Target platform (please complete the following information)

- HoloLens 2

**Comment by elbuhofantasma** [comment] 2021-08-13 22:57
Hello @cj-lopez Thanks for reporting this speech issue! I was able to reproduce this across Unity versions, MRTK versions, and across XR pipelines. @cre8ivepark will investigate this in the near future and we will give you an update when the investigation is complete.

**Comment by cj-lopez** [comment] 2021-08-13 23:12
Is this also related - [https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8582](url)?

**Comment by elbuhofantasma** [comment] 2021-08-14 22:22
@cj-lopez I do not believe that issue #8582 is related to this issue. The "Select" voice command in this issue seems to be occurring due the MRTK not being detected by the EyeTrackingTarget.cs script as seen in this picture below in the Eye Tracking Targeting example scene. This issue occurs in the OpenXR and XR SDK pipelines and across Unity versions. I have not tried to reproduce this issue on Unity 2018 LTS yet.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/65038391/129461422-966e2eed-a375-4acb-a7e4-700bc4bf7454.png)

**Comment by Spoon2311** [comment] 2021-08-24 14:04
Any updates on this issue?

**Comment by Spoon2311** [comment] 2021-09-20 07:06
Any updates on this issue?

**Comment by cre8ivepark** [comment] 2021-10-06 18:31
Verified that this is not only for the Eye Tracking example scenes. I don't see a gaze cursor even if when 'Select' is recognized. It does not trigger any target objects (e.g. buttons)

**Comment by DavidShapiraRimon** [comment] 2022-01-27 13:27
Is there any update on this issue?

**Comment by Spoon2311** [comment] 2022-02-24 09:38
Hey guys
Are there any updates available to this issue?

**Comment by abhimanyusinghal** [comment] 2022-03-24 08:20
Folks Is there any update? This is causing serious issues..

**Comment by Spoon2311** [comment] 2022-04-07 19:30
Hey @keveleigh For myself the most important part is, that the eye tracking will work again when deploying the application to hololens.

If remoting won't support it it is totally fine for me.

**Comment by MaxWang-MS** [comment] 2022-06-30 20:53
The fix for this issue has been released in MRTK 2.8.1. Please let me know if you are still running into the issue!

**Closed by MaxWang-MS** 2022-06-30 20:53 UTC
Labels: Bug, Urgency-Soon

**Comment by bnelligan** [comment] 2023-03-21 21:43
Note: the fix in [PR 10661](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10661) does not work for MRTK 2.8.2. After much debugging, I found a fix for our project with the following changes:

- Add the EyeGazeInteractionProfile to the OpenXR Interaction Profiles setting.
- Update line 134 of `OpenXRDeviceManager.cs` as follows:
`Service?.RaiseSpeechCommandRecognized(controller.InputSource, RecognitionConfidenceLevel.High, TimeSpan.MinValue, DateTime.Now, new SpeechCommands("Select", KeyCode.Alpha1, new MixedRealityInputAction(1,  "Select", AxisType.Digital)));`

**Comment by quater782** [comment] 2023-12-20 01:00
> The fix in [PR 10661](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10661) does not work for MRTK 2.8.2. After much debugging, I found a fix for our project with the following changes:
> 
> * Add the EyeGazeInteractionProfile to the OpenXR Interaction Profiles setting. (Source: [Joost van Schaik](https://localjoost.github.io/Getting-Eye-Tracking-to-work-with-OpenXR-on-HoloLens-2/))
> * Update line 134 of `OpenXRDeviceManager.cs` as follows:
>   `Service?.RaiseSpeechCommandRecognized(controller.InputSource, RecognitionConfidenceLevel.High, TimeSpan.MinValue, DateTime.Now, new SpeechCommands("Select", KeyCode.Alpha1, new MixedRealityInputAction(1,  "Select", AxisType.Digital)));`

This works perfectly for me, thanks a lot for the help.
