### ISSUE TITLE
How to fix floor height offset issues for the VR headsets?

### ISSUE THREAD

**Issue by sabingeo** [Microsoft/MixedRealityToolkit-Unity#1368] opened 2017-11-15 13:04 UTC
## Overview
Floor height postion is not never matches with the real ground Floor( hope it is supposed to work in this way). So the charactor with normal height will always rendered beyond  your eye level while you are standing.
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by StephenHodgson** [comment] 2017-11-15 15:06
Duplicate of #1324

Also, in the future be sure to fill out the whole form.

**Closed by StephenHodgson** 2017-11-15 15:06 UTC
