### ISSUE TITLE
Unable to open built projects from MRTK RC1

### ISSUE THREAD

**Issue by Avalin** [Microsoft/MixedRealityToolkit-Unity#3917] opened 2019-04-10 11:33 UTC
## Overview
Downloading a fresh MRTK RC1 project cannot run on HoloLens, and results in errors in the Unity Editor. Built is, however, still "Successful"

## Expected Behavior
Built projects should be runnable on HoloLens.

## Actual Behavior
Nothing appears on HoloLens. Not even Unity splash screen. However the app is clearly open, as you can "exit" the app once it's open.

**Unity errors:**
Quite lengthy, and I couldn't make the markup work as intended so you get this pastebin: https://pastebin.com/dubghPDG

And these are the other follow up issues. As you can see the built is claimed successful despite these errors:
![issues](https://user-images.githubusercontent.com/15669154/55875284-085bcf00-5b95-11e9-9f7c-795552b85746.png)

## Steps to reproduce
We removed OpenVR through the package manager, as we only need the HoloLens working part (and it was kinda frustrating with the constant opening of SteamVR whenever we tried to run the project) aside from that, we kept it pretty vanilla.

- Just download MRTK RC1
- Make a scene with a cube
- Built it for HoloLens x86
- Built the project on the HoloLens from visual studio, Release x86
- When it says "Ready" nothing shows up. Not even Unity Splash screen.

## Unity Editor Version
2018.3.8f1

## Mixed Reality Toolkit Release Version
MRTK V2, RC1

Sidenote:
Another thing we discovered in the RC1 is that In order to change scene and have the camera be persistent, we had to add this line to the focusprovider script CreateUIRaycastCamera: `uiRaycastCamera.transform.SetParent(GameObject.FindWithTag("MainCamera").transform);`
This was not necessary in the beta release, as it was already done for us. Is there a reason for this?

**Comment by julenka** [comment] 2019-04-10 16:37
Hi Avalin, thanks for filing the bug! MRTK RC1 needs a newer Windows SDK to build a UWP. You need [Windows SDK 18362+](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK). 

We are working on updating MRTK to not require the new Windows SDK so you can still build for the old HoloLens.

**Comment by julenka** [comment] 2019-04-10 16:37
Duplicate of #3801

**Closed** 2019-04-10 16:38 UTC

**Comment by Avalin** [comment] 2019-04-11 12:01
Hi Julenka,
Thank you for your reply! I should have probably noted that we _did_ install the Windows 10 Insider Preview OS along with the Windows SDK 18362. We also ran Windows Update alongside this and installed everything it suggested, and finally we also made it through the trouble of installing the Developer Mode packages in this version of Windows which seemingly required some tweaking to work. Despite all the effort, issues remains the same so I'm afraid there's more to it, (or we missed a step, maybe)? 

We attempted to build it on an emulator today (Version 10.0.17763.134, as there does not seem to be a version 10.0.18362 available yet), however on this we get an error that says "The emulator is unable to verify that the virtual machine is running", an error that seemingly either has to do with Hyper-V not being activated (it is) or Developer Mode not activated (it also is), but maybe it have to do with deprecation then?

And that's noted, I will post on stackoverflow next time :)

**Comment by hanfengsunshine** [comment] 2019-04-23 08:27
Hi Avalin, I encounter the problem building HoloLens 1 with MRTK ,with Windows SDK 18363, nothing appearing on my HoloLens screen, but when I try audio demos, there actually women sounds(it works), I wonder could we have a talk about the settings of the problems?  fhanab@connect.ust.hk

**Comment by Walker8711** [comment] 2019-04-23 18:35
I'm having the same problems, the microphone permissions pop up and that is it.

**Comment by Walker8711** [comment] 2019-04-23 20:23
@hanfengsunshine The issue is caused by leaving WSA Holographic Remoting Suported checked when you build.  After spending hours of testing in Unity and side loading to test, We were able to figure this out.

**Comment by hanfengsunshine** [comment] 2019-04-25 12:53
> @hanfengsunshine The issue is caused by leaving WSA Holographic Remoting Suported checked when you build. After spending hours of testing in Unity and side loading to test, We were able to figure this out.

Do you mean I need to tick this WSA Holographic Remoting Supported, like in the attached pic?

![Capture](https://user-images.githubusercontent.com/14012055/56737051-2718b300-679c-11e9-90c3-55522500817f.PNG)

Thank you!
