### ISSUE TITLE
Bug: Keyboard not deleting final character

### ISSUE THREAD

**Issue by bkfichter** [Microsoft/MixedRealityToolkit-Unity#1169] opened 2017-10-16 15:24 UTC
Using the Keyboard prefab to type into an inputfield-
When using backspace to remove characters, the final character is not deleting from the input field.
If you highlight the character and type any other character, it still does not delete or replace.

**Comment by StephenHodgson** [comment] 2017-10-16 16:30
Duplicate of #917

**Closed by StephenHodgson** 2017-10-16 16:30 UTC
Labels: Duplicate

**Comment by davidkline-ms** [comment] 2018-05-25 03:32
This was released in the 2017.4.0.0 release candidate
