### ISSUE TITLE
Headset tracking lost when the app is resumed

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#1395] opened 2017-11-19 19:09 UTC
## Overview
In MotionControllerTest scene, the app runs fine on the first run. However, **when it is resumed from cliff house**, headset tracking lost and the scene/controller moves with your body. This might happen in any scenes that uses MixedRealityCamera. 
**This only happens in deployed app. Unity's game mode is fine.**

## Expected Behavior
Tracking should work.

## Actual Behavior
Tracking is not working when the app is resumed. Entire scene moves with your head/body.
The symptom shows up only when it is resumed.

## Steps to reproduce
Build and deploy MotionControllerTest scene with Visual Studio. 

## Unity Editor Version
Unity 2017.2.0p1-MRTP4 (64-bit)

## Mixed Reality Toolkit Release Version
Latest master clone.

**Comment by keveleigh** [comment] 2017-11-19 19:15
MRTP4 has had issues with tracking lost recovery. Duplicate of #1383, possible duplicate of #1353.

**Comment by cre8ivepark** [comment] 2017-11-19 19:18
@keveleigh Thank you Kurtis! Glad I am not the only one struggling with this issue! :)

**Closed** 2017-11-19 19:24 UTC
Labels: Duplicate
