### ISSUE TITLE
Fingertip cursor alignment

### ISSUE THREAD

**Issue by mpkoz** [microsoft/MixedRealityToolkit-Unity#6478] opened 2019-11-05 23:53 UTC
## Describe the bug

Fingertip cursor position in MRTK stays at a static position on the tip of the finger when approaching touchable UI. This is in opposition to shell behavior, in which the fingertip cursor translates to the pad of the finger. Below is a screen capture of MRTK behavior. 

## Screenshots

![FingertipCursorPre_Trim](https://user-images.githubusercontent.com/16657884/68255984-a9075580-ffe3-11e9-9e41-26a444d8a941.gif)

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- MRTK Version 2.0

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment] 2019-11-06 02:15
Duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6406?

**Comment by cre8ivepark** [comment] 2019-11-11 04:18
Fixed with #6479

**Closed by cre8ivepark** 2019-11-11 04:18 UTC
Labels: Bug
