### ISSUE TITLE
MRTK should have different hand mesh/marker settings based on transparent or opaque displays

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4347] opened 2019-05-14 20:51 UTC
In VR you always want hand visualizations, even if you only use it in the editor, but in AR there's a good chance you don't want the hand visualizations. You should be able to determine which to use based on display type.

**Comment by wiwei** [comment] 2019-05-14 20:51
Ported to Github, reference 20585593

**Comment by keveleigh** [comment] 2019-05-14 21:19
This feels like a dupe of #4213

**Comment by wiwei** [comment] 2019-05-15 00:58
Yep, definitely overlaps

**Closed** 2019-05-17 21:53 UTC
Labels: 0 - Backlog, Controller Visualization, Duplicate, Feature Request
