### ISSUE TITLE
Sample Demo compiler errors, 2.7.3

### ISSUE THREAD

**Issue by ttkrpink** [microsoft/MixedRealityToolkit-Unity#11202] opened 2022-11-14 14:17 UTC
Unity 2020.3.40
MRTK 2.7.3
Examples Demos - UX: Dialog Example

![image](https://user-images.githubusercontent.com/2522889/201682627-bd8b8a78-8c8b-4165-b141-64673e3522d2.png)

**Comment by MaxWang-MS** [comment] 2022-11-16 03:47
Hi @ttkrpink, I am having difficulties reproducing this error. Could you try to upgrade to our latest MRTK2 version (2.8.2) and see if that resolves the problem? Make sure the samples are updated as well. If that still doesn't resolve the issue, could you try again with a new Unity project and just import the MRTK packages as I noticed some third party packages in the screenshot.

**Comment by MaxWang-MS** [comment] 2022-11-16 04:04
Update: I am now able to reproduce the issue, which is a duplicate of #10372. Will follow up there soon.

**Closed by MaxWang-MS** 2022-11-16 04:04 UTC
Labels: Bug, Oculus, MRTK2
