### ISSUE TITLE
System Keyboard - Have to hit a letter multiple times to write it

### ISSUE THREAD

**Issue by BertrandOustriere** [microsoft/MixedRealityToolkit-Unity#6921] opened 2019-12-17 08:48 UTC
## Describe the bug

Using the MRTK 2.1, system keyboard's backspace was not working. 
Switching to MRTK 2.2, backspace is working, but we have now to hit 2 times a letter to be able to write it. Non-character keys like backspace or arrows to move the carret are working at first hit though.

This is only reproducible on Unity 2019, the keyboard works perfectly on 2018.

## To reproduce

Build & deploy the HandInteractionExamples scene from the MRTK 2.2. 
Air tap on the 'Keyboard' button on the left.
Use the opened keyboard to write text. 

## Expected behavior

Hit a key once should write its value.

## Your setup (please complete the following information)

- Unity Version 2019.2.6f1 (tested on 2019.2.15f1 as well)
- MRTK Version 2.2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Cameron-Micka** [comment] 2020-02-25 19:28
Just tried to reproduce this issue. In MRTK v2.3 and Unity 2018 everything worked fine. In MRTK v2.3 and Unity 2019 only the delete key does not work (other keys appear to operate fine, including the arrow keys). This would hint that this logic isn't occurring in 2019: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/f38399007d30bcee7d3e7ceb27c058074650a311/Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/MixedRealityKeyboard.cs#L233

**Comment by marcinwalus** [comment] 2020-04-06 15:14
Hello,
I have the same issue. I downloaded MixedRealityToolkit-Unity (releases/2.3.0). I build project with "Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity" scene only using Unity 2018.4.14 and keyboard works ok.
When I build same project using Unity 2019.3.7 backspace key doesn't work ([short video](https://www.icloud.com/iclouddrive/03GB6f_Nkjxy44XkmG8mCPlow#20200406%5F170517%5FHoloLens%5FTrim)) and there is no way to delete text.
Should I file a bug in Unity?

**Comment by Cameron-Micka** [comment] 2020-04-06 16:47
Thank you for reporting your findings @marcinwalus, Unity is aware of the issue and looking into a fix.

**Comment by marcinwalus** [comment] 2020-04-07 08:25
@Cameron-Micka I checked also just released Unity 2019.3.8 and problem still exists.

**Comment by martdob** [comment] 2020-07-08 11:45
Is this issue closed? The backspace is still not working on Unity 2019.4.

**Comment by Cameron-Micka** [comment] 2020-07-08 15:49
@marcinwalus & @martdob, I just got word from Unity that that a fix is in and getting backported to 2020.1 and 2019 LTS.

**Comment by martdob** [comment] 2020-07-09 16:25
I am using 2019 LTS and the bug is still there. I also tried 2020.1 and there the MRTK 2.4 samples aren't working. The app stops working after start.

**Comment by Cameron-Micka** [comment] 2020-07-09 16:34
Adding @wiwei & @keveleigh who might be able to speak to 2020 support.

**Comment by keveleigh** [comment] 2020-07-09 16:38
>I also tried 2020.1b and the MRTK 2.4 samples aren't working togehter with this verson. The app stops working after start.

That could be due to legacy XR being removed in Unity 2020. We have support for their new XR pipeline, if you follow the steps at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html.

Note: I haven't fully tested out 2020, but I'm not aware of any major changes that'd break our existing support.

**Comment by Cameron-Micka** [comment] 2020-07-09 18:43
Just received some new info, the keyboard fixes will first appear in 2020.2 alpha and be back ported to 2020.1 and 2019 LTS at a later date (TBD).

**Comment by marcinwalus** [comment] 2020-09-15 14:57
I can confirm that it works now in Unity 2019.4.10 LTS.

**Closed** 2020-09-15 15:38 UTC
Labels: Bug, Keyboard, Unity 2019
