### ISSUE TITLE
MRTK Build Tool triggers indefinite "Importing" dialog in Unity 2020

### ISSUE THREAD

**Issue by srinjoym** [microsoft/MixedRealityToolkit-Unity#9723] opened 2021-04-29 18:48 UTC
## Describe the bug
The MRTK Build Window triggers Unity 2020 to start an indefinite "Importing" message. I've reproduced on an empty Unity 2020 project with just MRTK 2.6.1:

![image](https://user-images.githubusercontent.com/7866060/116595419-26114380-a8d8-11eb-8a9b-76ade250cc85.png)

## To reproduce

1. Create a new Unity 2020 LTS Project
2. Add MRTK Foundation and Tools
3. Click "Build All" on the build window to start a build
4. After the build finishes, Unity 2020 starts showing an indefinite "Importing" message.

## Expected behavior
This doesn't happen on Unity 2019 LTS - might be an issue with where the Build Assets are placed in Unity 2020?

## Your setup (please complete the following information)

- Unity Version 2020.3.3
- MRTK Version v2.6.1

## Target platform (please complete the following information)
- HoloLens 2

**Comment by davidkline-ms** [comment] 2021-05-14 23:44
While investigating this, @CDiaz-MS and I came upon the following line in the MRTK EditorAssemblyReloadManager

```
EditorApplication.delayCall += () => AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
```

We tried removing this line and also removing the Refresh() parameter and we still encounter the loop.

**Comment by davidkline-ms** [comment] 2021-05-14 23:45
Testing was done on Unity 2020.3.8f1. This does not occur on previous versions (ex: 2019.4)

**Comment by davidkline-ms** [comment] 2021-05-15 00:16
The more we look at this, the mo.re if seems like a behavior change in Unity 2020

**Comment by davidkline-ms** [comment] 2021-05-19 18:04
Disabled the two likely causes of the importing trigger to no avail. From what I am seeing, I cannot identify where MRTK is doing something that is the root cause,

**Comment by davidkline-ms** [comment] 2021-05-19 18:06
Here are the changes that were attempted:

EditorAssemblyReloadManager.cs
```
#if !UNITY_2020_3_OR_NEWER
                    EditorApplication.delayCall += () => AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
#endif
```

ProjectPreferences.cs
```
#if !UNITY_2020_3_OR_NEWER
                        AssetDatabase.Refresh();
#endif
```

**Comment by davidkline-ms** [comment] 2021-05-21 22:02
Contacted Unity. They are able to repro this issue (and potentially in a similar scenario). Moving this to the 2.x future milestone.

**Comment by keveleigh** [comment] 2021-07-01 20:35
Unity provided an update with why it's newly failing (they hardened some state logic requiring a `ClearProgressBar` call), so I opened #10046 to fix! I double checked the rest of our progress bar calls, and this was the only one missing a corresponding clear.

**Closed** 2021-07-01 21:28 UTC
Labels: Build / Tools, External, Unity 2020
