### ISSUE TITLE
Cannot interact with Unity UI examples (HandInteractionExamples scene)

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9270] opened 2021-02-09 21:00 UTC
## Describe the bug
Cannot interact with Unity UI examples (HandInteractionExamples scene)
Not responding to any input types - default gaze cursor, near hand, far hand-ray.
(Symptom in the editor. Not tested with device)

## To reproduce
- Checkout prerelease/2.6.0_stabilization branch
- Open HandInteractionExample scene
- Play
- Try to interact with Unity UI examples on the right side of the scene

## Environment
- Unity Version 2018.4.28f1
- MRTK Version 2.6.0 Stabilization

## Screenshots

<img width="680" alt="2021-02-09 12_56_36-Window" src="https://user-images.githubusercontent.com/13754172/107427937-c96f6b00-6ad6-11eb-8c36-acf6cc5ec324.png">

**Comment by davidkline-ms** [comment] 2021-02-10 03:37
@MaxWang-MS, can you work with @cre8ivepark to investigate?

**Comment by MaxWang-MS** [comment] 2021-02-10 20:19
Hi @cre8ivepark I was not able to repro with Unity 2018.4.29f1. Could you double check and share more info if you are still encountering the issue?

**Comment by cre8ivepark** [comment] 2021-02-10 21:28
@MaxWang-MS Let me try with fresh clone.

**Comment by cre8ivepark** [comment] 2021-02-10 23:10
Just tested with a fresh clone but shows the issue.

https://user-images.githubusercontent.com/13754172/107584867-16743f80-6bb2-11eb-9cc4-bb7d4add4031.mp4

**Comment by davidkline-ms** [comment] 2021-02-11 18:24
@cre8ivepark / @MaxWang-MS, Is this behavior in editor (input simulation), on device or both?

**Comment by cre8ivepark** [comment] 2021-02-11 18:50
@davidkline-ms This happens in editor only. It works well in the device.

**Comment by davidkline-ms** [comment] 2021-02-11 22:36
Thanks @cre8ivepark. As with @MaxWang-MS, i am having difficulty reproducing this behavior in 2018.4. Are there any steps that are performed prior to seeing this issue that may be a cause?

My repro:
* clone the stabilization branch
* load into Unity 2018.4 (my version is 31f1)
* open the HandInteractionExamples scene
* enter play mode
* disable the on screen profiler (makes it easier to access the ui components)
* try to interact with far and near interactions

result: am able to successfully interact with the UI panel

**Comment by davidkline-ms** [comment] 2021-02-12 17:57
Spoke with @cre8ivepark yesterday and we shared our screens to share the repros. For both, we are able to interact on device, the issue appears to be specific to @cre8ivepark's system.

Still investigating.

**Comment by davidkline-ms** [comment] 2021-02-12 19:25
Follow up with @cre8ivepark, he is able to successfully interact with Unity UI in playmode while using Unity 2018.4.31f1. This may be specific to his previous version of Unity. 

Removing from the 2.6.0 milestone. Leaving open while the investigation is completed.

**Comment by polar-kev** [comment] 2021-03-24 19:23
Hey @cre8ivepark, we'll be closing this issue since we are not able to repro. Please feel free to share a repro project and reopen if this issue is still affecting you.

**Closed by polar-kev** 2021-03-24 19:23 UTC
Labels: Bug, UnityUI
