### ISSUE TITLE
Users should be able to apply offsets to cameras within the mixed reality playspace

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedRealityToolkit-Unity#6786] opened 2019-12-03 21:49 UTC
## Describe the problem

Different folks have voiced an interest in being able to apply offsets to their main camera while keeping it in the mixed reality playspace. See [here](https://stackoverflow.com/questions/59106315/how-to-adjust-character-height-when-playing-seated-in-closed-vr-with-mrtk).

## Describe the solution you'd like

We should have some mechanism/best practice for enabling camera offsets. It seems like it may be worth having the ability to specify some sort of game object as a parent of the main camera that then has the playspace as a parent so that folks can apply an arbitrary offset. Right now it seems like this may not be possible because the camera is reparented to the playspace at runtime.

**Comment by keveleigh** [comment] 2020-12-01 17:21
Closing as duplicate of #7913, which has a little more discussion.

**Closed by keveleigh** 2020-12-01 17:21 UTC
Labels: Feature Request
