### ISSUE TITLE
Proposal: have a "service discovery" component for MRTK vNext

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#2700] opened 2018-09-04 13:14 UTC
# Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?
Mixed Reality Toolkit

# Describe the solution you'd like
An oft problem that is found in most solutions, is trying to discover what does what and in which areas of the solution where a feature is in use.  What is using a particular interface? (e.g. Pointing, grabbing, etc)

If would be fabulous if there was a discovery "tool" to be select a feature of the MRTK and discover where in a scene that feature is being implemented.  Which GameObjects have a script attached for Grabbing / highlighting / etc.  Which GameObjects are using specific SDK components, etc.

# Describe alternatives you've considered
Manually searching through a scene to find which gameobjects can be interacted with is a REAL pain :D

# Additional context
On many projects I've supported or worked with.  Trying to diagnose any specific issue for why something is not happening (or happening when you don't want it to) is usually very painful.  Aim is to see if there is a way to help these scenarios by interrogating the scene rather than using manual discovery.

**Comment by Troy-Ferrell** [comment] 2019-07-28 21:48
You can search the Unity scene for all of the ManipulationHandler or any other given component via "t:ManipulationHandler" or "t:script"

For the larger issue of debugging input and what's on what visually, closing this as a dupe of #4212

**Closed by Troy-Ferrell** 2019-07-28 21:48 UTC
Labels: Feature Request
