### ISSUE TITLE
Newtonsoft.Serialization exeption with IL2CPP Backend

### ISSUE THREAD

**Issue by jganser** [Microsoft/MixedRealityToolkit-Unity#2269] opened 2018-06-07 15:09 UTC
## Overview

Due to an reflection exception for AOT the serialization crashes applications

Current Workaround: Use Newtonsoft.dll for AOT from the unity package: https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347
for IL2CPP build

Possible Solution: Add the Newtonsoft.dll for AOT from the unity package: https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347
to the included json resources

## Expected Behavior

JsonString gets generated

## Actual Behavior

Exception flies due to reflection exception

## Steps to reproduce

JsonConvert.Serialize(object obj) with IL2CPP build

## Unity Editor Version

2018.1

## Mixed Reality Toolkit Release Version

05d004f3f6c384fa856172aab00d351168fa478a

**Comment by StephenHodgson** [comment] 2018-06-07 15:14
Yeah I'm not a fan of the fact we even depend on that newtonsoft dll.

**Comment by StephenHodgson** [comment] 2018-06-07 15:15
Part of the issue is that the glTF library is the one that has it embedded, and they explicitly made a choice to use the newtonsoft dll instead of the natice unity json utility.

**Comment by keveleigh** [comment] 2018-06-15 00:30
I don't see any [instances of `JsonConvert.Serialize(object obj)`](https://github.com/Microsoft/MixedRealityToolkit-Unity/search?q=JsonConvert.Serialize&unscoped_q=JsonConvert.Serialize). Is this reproducible in the Toolkit, or a side effect of distributing a specific DLL with the Toolkit?

**Comment by jganser** [comment] 2018-06-15 07:05
JsonConvert.Serialize(object obj) is not used by the HoloToolkit, but part of the Newtonsoft.dll. As StephenHodgson already mentioned, the HoloToolkit depends on the Newtonsoft.dll for the glTF library.

Since their already is a Json conversion implementation available as soon as one uses the HoloToolkit, one might use that for it's own application as well. Meaning to Convert some object wo a Json format with the mentioned method.

But when using it AND building for IL2CPP, their is a reflection problem because IL2CPP is an ahead of time compilation.

Hope that answers your question keveleigh.

**Comment by XPav** [comment] 2018-07-06 21:21
MRTK depending on glTF depending on Json.Net for the sake of 5 lines of code inside MotionControllerVisualizer.cs, for WMR platforms only, is... suboptimal? 

I was using Json.net for my own purposes, and didn't care whether it was the one in MRTK or the "normal" one, but neither of those are workable when using IL2CPP.   So I use the Unity package referenced above, all is well, but then MRTK complains.

So I deleted all the glTF folders and removed out the 6 lines that were actually using them, because I'm using a Hololens anyway, and now everything is happy.

**Comment by keveleigh** [comment] 2018-07-06 21:24
>So I use the Unity package referenced above, all is well, but then MRTK complains.

What are you referring to here?

**Comment by XPav** [comment] 2018-07-06 21:50
https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

It works on the Hololens.

**Comment by wiwei** [comment] 2019-04-11 20:14
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:14 UTC
Labels: External
