### ISSUE TITLE
Spatial awareness demo scene doesn't do anything in editor view

### ISSUE THREAD

**Issue by SoundGuy** [microsoft/MixedRealityToolkit-Unity#6471] opened 2019-11-05 14:35 UTC
## Describe the bug

I'm running the Spatial Awareness demo scene from the examples  and nothing happens

## To reproduce

Open a new empty project
import nuget
installed MRTK foundatoin, extentions, tools, and examples.
Opened the spatial awareness scene
in the holographic emulator i connected to my hololens.
i hit play

nothing happens.

## Expected behavior
I expected to see a wireframe mesh of my environemtn as the plague suggest i do. 

## Your Setup (please complete the following information)

- Unity Version 2019.2.11f
- MRTK Version 2.1.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by Troy-Ferrell** [comment] 2019-11-05 17:52
@SoundGuy, you will only see a wireframe mesh if you are on a device with sensors capturing data.

There is another MeshObserver class that will render a mesh object file as a spatial mesh. 

Updating this bug to revamp the example scene. If in editor, show a game object. If on device, use the actual spatial mesh. 

Even with this change, spatial mesh will not show up in emulator by default

**Comment by Troy-Ferrell** [comment] 2019-11-05 18:21
Actually going to close this as dupe of #6262

**Closed by Troy-Ferrell** 2019-11-05 18:21 UTC
Labels: Bug, Example/Test Scene, Spatial Mapping / Awareness
