### ISSUE TITLE
XR Remoting does not work [XR SDK, 2019.x]

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#8044] opened 2020-06-11 19:15 UTC
## Describe the bug

XR Remoting silently fails when using XR SDK in 2019.x.

No errors are thrown. The device XR remoting window also says that the device has successfully connected.

## To reproduce

- Follow the XR SDK setup instructions: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html
- Set up all packages as stated in the instructions, with the versions listed below
- Connect your device with XR Remoting
- Hit Play
- Observe that no remoting occurs. Head tracking does not occur, the headset display is blank. The editor acts as if there is no remoting active at all.

## Expected behavior

The head pose is shown in the editor, and the view is correctly rendered to the display. Hand tracking + eye tracking should also work.

## Screenshots

![image](https://user-images.githubusercontent.com/5544935/84428943-d2b8d880-abd3-11ea-9ad2-9ba2b7c1a9cf.png)

## Your setup (please complete the following information)

Package setup:

- _XR Plugin Management_ - Version 3.2.10
- _Windows XR Plugin_ - Version 2.1.6 preview 3
- _XR Legacy Input Helpers-_ - Version 2.1.4

The MixedRealityToolkit component is using the `DefaultXRSDKConfigurationProfile`.

Unity version: 

- Tested on 2019.3 and 2019.4, both fail to work.
- MRTK 2.4.

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

The XR remoting setup works great in 2018.x with the legacy XR stack.

**Comment by keveleigh** [comment] 2020-06-11 19:19
Marking as External, as this is almost definitely a Unity-side bug. I'll dig in.

**Comment by frosadev** [comment] 2020-06-23 14:53
Any news on this?

**Comment by dudziakl** [comment] 2020-07-08 09:57
Same problem here🙁 
Tested with Holographic Remoting Player 2.2.1.0 app and two project:
Unity 2019.4.2f1, XR Plugin Management 3.2.13, Windows XR Plugin 2.2.0
Unity 2019.4.0f1, XR Plugin Management 3.2.10, Windows XR Plugin 2.1.5

**Comment by theolizard** [comment] 2020-07-20 04:31
Same issue here.
However, if I uninstall the "Windows XR Plugin" and "XR Plugin Management" packages and I switch to the deprecated built-in XR API, it works as expected.

**Comment by keveleigh** [comment] 2020-07-21 18:34
Update: it looks like the editor takes the XR settings from the Windows Standalone build. Please ensure Windows Mixed Reality and Initialize XR on Startup are checked under the standalone settings:

![image](https://user-images.githubusercontent.com/3580640/88092832-f7df2600-cb45-11ea-905a-bd2f125817a7.png)

It's being investigated as a doc / workflow issue on the Unity side, but this should resolve it.

**Comment by omanuke** [comment] 2020-10-29 13:31
I'm not sure this is the same issue or not, but I can't use XR Remoting.
I set Windows Mixed Reality in Plug-in Providers checked for 'Standalone' platform, but XR Plugin Remoting panel still indicates alert.

Unity Ver: 2019.4.12f1
Windows XR Plugin: 2.3.0
XR Plugin Management: 3.2.16
MRTK: 2.5.0


![image](https://user-images.githubusercontent.com/1901757/97579471-70069300-1a35-11eb-97a0-888141803562.png)

**Comment by keveleigh** [comment] 2020-10-29 20:15
>I set Windows Mixed Reality in Plug-in Providers checked for 'Standalone' platform, but XR Plugin Remoting panel still indicates alert.

I believe that info block is always visible, even if you have the settings set up correctly. Are you unable to connect?

**Comment by omanuke** [comment] 2020-10-30 03:14
I didn't try, but panel of Remoting is showing alert like above and there is no combobox to select device(Hololens1 and 2 are the candidates). Still, can I connect?

**Comment by omanuke** [comment] 2020-10-30 06:13
I tried. But it seems not to work. Instead of that, Mixed reality portal waked up.

**Comment by Naphier** [comment] 2020-12-22 14:41
From one of my engineers on Slack:

(Working on HoloLens 2 with unity 2019.4.16, latest Remoting App on HL2, MapsSDK SampleProject that includes MRTK etc. Also tried on a blank project with XR SDK and WMR plugin).

So does "Remote to Device" work for play mode in the Unity Editor? I've been working with older projects for a while and the "legacy" holographic remoting works flawlessly. This new one doesn't ever seem to work for me. I've never been able to get the XR SDK Windows Mixed Reality Remote to Device to work.
After I hit "Connect" it says Remoting connect returned: True and no other errors/messages. The connection status is "Connected" but disconnects after I end each play session.
I often get this error: [XRInputSubsystem] A device disconnection with the id <some number here> has been reported but no device with that id was connected.  In play mode.
I was able to actually see my unity scene on the HL once after I changed the bitrate setting but it's inconsistent (this only occurs in my blank project). Still no tracking here either.

Any help would be greatly appreciated.

---------
Any help on this? We'd like to adopt the new ecosystem, but we can't dev without remoting. Thanks

**Comment by keveleigh** [comment] 2020-12-23 20:30
>After I hit "Connect" it says Remoting connect returned: True and no other errors/messages. The connection status is "Connected" but disconnects after I end each play session.

That sounds like the currently expected behavior. Can you confirm the Windows Standalone XR Plug-in Management settings are enabled for WMR?

**Comment by Verex** [comment] 2020-12-23 21:58
> That sounds like the currently expected behavior.

The disconnection after play has ended is not the issue I'm facing. Though, thank you for clarifying that it's not a bug.

> Can you confirm the Windows Standalone XR Plug-in Management settings are enabled for WMR?

Yes it is.

The primary issue I'm having is that once connected and in play mode I don't see anything. Head rotation / position is not tracked. The game window shows a black screen. I also often see an error message like this being spammed with different IDs: 
```
[XRInputSubsystem] A device disconnection with the id has been reported but no device with that id was connected.
```
This happens 98% of the time.

The other 2% of the time (after messing with bitrate, audio, and video) I'm able to see the scene rendered on the HL and in the game window. No head tracking so I had to rotate the camera in the editor. 

I appreciate the support!

**Comment by radacadabra** [comment] 2021-01-27 03:27
I'm also having trouble with Remote to Device. Unity's Windows Mixed Reality windows fails to connect with the message:

Connection Failure Reason: None

I'm using MRTK 2.4.0, Unity 2019.4 and HoloLens 1. According to this thread:

https://forum.unity.com/threads/hololens-1-windows-xr-plugin-remoting-not-working.827970/

due to Microsoft not providing certain APIs and libraries, remoting on XR SDK is limited to HoloLens 2.

Could you please confirm this?

**Comment by keveleigh** [comment] 2021-05-28 19:08
> Could you please confirm this?

I can. Windows XR Plugin only supports remoting to HoloLens 2.

**Comment by keveleigh** [comment] 2021-06-11 17:02
I'm going to close this one out. The most common resolution has been to double check your Standalone XR Plugin Management settings. Unity has also defaulted to connecting automatically when you hit play, so if that doesn't work, reverting to a manual connection might help as well.

**Closed by keveleigh** 2021-06-11 17:02 UTC
Labels: Bug, Editor, External, Holographic Remoting, XR SDK
