### ISSUE TITLE
Shader errors are generated when building for iOS

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9851] opened 2021-05-21 17:14 UTC
## Describe the bug

When the user attempt to build on a mac for iOS, Unity generates several shader errors in the console during the build process. This issue will sometimes cause the build to fail. on the first attempt. This issue also happens in Unity 2019 and Unity 2020 with OpenXR and XR SDK.

## To reproduce

1. Setup your project for iOS
2. build any example scene
3. See error

## Screenshots

![Image 5-21-21 at 9 54 AM](https://user-images.githubusercontent.com/65038391/119173322-fa3b3680-ba1b-11eb-8c48-d35285f81d07.jpg)
![Image 5-21-21 at 9 56 AM](https://user-images.githubusercontent.com/65038391/119173342-fdcebd80-ba1b-11eb-803b-cc756572828e.jpg)
![Image 5-21-21 at 9 56 AM (1)](https://user-images.githubusercontent.com/65038391/119173346-feffea80-ba1b-11eb-9b2b-fd3f56e3fcc4.jpg)
![Image 5-21-21 at 9 57 AM](https://user-images.githubusercontent.com/65038391/119173349-00311780-ba1c-11eb-9d48-1c342c099584.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.7f1 and 2019.4.25f1
- MRTK Version 2.7
- XR SDK
- OpenXR

## Target platform (please complete the following information)

- iOS
- 
## Additional context

This issue only appears on the first build attempt.

**Comment by Cameron-Micka** [comment] 2021-05-24 20:13
This seems like it could be a dupe of this issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6359

It's hard to see what the shader compilation issue is based on the output. But, my guess is the Metal shader compiler is warning us about fixed or half type conversions. We could "fix" this by changing all types to full floating point precision, or do a sanity check of all conversions (which could take awhile).

**Closed** 2021-06-30 16:39 UTC
Labels: Bug, Shaders / Materials, Unity 2019, Unity 2020, iOS
