### ISSUE TITLE
Exit-and-reenter app makes app horribly slow (also when tracking is lost)

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1237] opened 2017-10-25 19:03 UTC
Start app, look around, press start button, reactivate app. App becomes extremely slow. This also seems to happen when tracking is lost (cover the camera for a few secs). Possibly related

**Comment by keveleigh** [comment] 2017-10-31 06:59
Likely a Unity issue. I know there were some suspend/resume fixes in MRTP3. Have you filed a Unity bug?

**Comment by LocalJoost** [comment] 2017-10-31 07:05
Uhm, no. It’s such a glaring issue I assumed it to be a MRTK issue.

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10 on my Surface Pro 4

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by keveleigh** [comment] 2017-10-31 07:09
Did you debug or were otherwise able to narrow it down to any specific Toolkit component? Did you validate that this doesn't repro in an app without the Toolkit? We're working with preview versions of Unity here, and bugs are being actively fixed as they're reported.

**Comment by LocalJoost** [comment] 2017-10-31 07:54
It was just running the app from the start menu. And no to all the other questions.


Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by StephenHodgson** [comment] 2017-11-14 16:40
Someone opened a [bug report for this](https://fogbugz.unity3d.com/default.asp?967505_0mtquuhmjkq9aqmp)

**Comment by ivan2007** [comment] 2017-11-28 07:54
I am having the same problem with my app.
I will try without unity and mrtk.

**Comment by keveleigh** [comment] 2017-12-01 01:12
Was this possibly related to #1383 and #1353 (and thus fixed in MRTP5)?

**Comment by ivan2007** [comment] 2017-12-01 07:43
I made a test with the app created by the vs template but it crashes immediately.
I reported this to Microsoft.
Can I use MRTP5 with the latest MRTK release?

**Comment by LocalJoost** [comment] 2017-12-01 09:58
I am not really sure I understand your work flow. I create an app in Unity, (MRTP5, yes) then bring in the MRTK. Then I generate the Visual Studio app. That app runs fine. What do you mean by ‘Visual Studio template’ ?

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10 on my Surface Pro 4

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by ivan2007** [comment] 2017-12-01 10:45
![nuovo file](https://user-images.githubusercontent.com/17752475/33479303-e1abf74c-d68c-11e7-815c-a4f338339cf0.png)
Hi,
I mean the holographic app that vs can generate without unity and mrtk.
Normally I use it when I have problems to see if without unity it is the same.

Ivan

**Comment by ivan2007** [comment] 2017-12-01 10:50
I used it in the past but now it crashes.
Is it the same for you?
Thanks
Ivan

**Comment by LocalJoost** [comment] 2017-12-01 11:39
I never used the VS template. I always start with Unity

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by ivan2007** [comment] 2017-12-02 15:03
I made a test with MRTP5 and the latest release of MRTK.
Now  the app runs ok also after the first start
Ivan

**Comment by ivan2007** [comment] 2017-12-19 22:29
Has anyone made a test with 2017.3.0f3 ?
With Unity 2017.2.1f1 the problem is still present again.
Thanks
Ivan

**Comment by ivan2007** [comment] 2017-12-28 19:10
With Unity 2017.3.0f3 this issue is not present.

**Closed** 2018-05-17 16:41 UTC
Labels: Immersive HMD, OS Bug, Unity Bug
