### ISSUE TITLE
Flexible Mechanism for Recording Audio without Dictation, like MicStream

### ISSUE THREAD

**Issue by mtaulty** [microsoft/MixedRealityToolkit-Unity#4135] opened 2019-05-01 08:16 UTC
## Describe the problem
In the V1 toolkit, there was a MicStream class which was handy for recording audio with quite a few control options.

In V2 RC1, MicStream is gone. The IMixedRealityDictationSystem interface does have capabilities to record audio but it could be more flexible and not tied to dictation.

## Describe the solution you'd like
It would be good to see some of the recording functionality (like MicStream) brought back and separated from dictation as sometimes you want to record without necessarily running dictation and MicStream allowed for this.

## Describe alternatives you've considered
In porting applications from V1 to V2 we can work around this with custom code but there doesn't seem to be a direct replacement for MicStream.

## Additional context

N/A

**Comment by Troy-Ferrell** [comment] 2020-02-27 00:19
Closing this item as a dupe of #2505

**Closed by Troy-Ferrell** 2020-02-27 00:19 UTC
Labels: 0 - Backlog, Feature Request
