### ISSUE TITLE
Disable Mixed Reality Portal Minimizes Other Windows

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#881] opened 2017-08-21 15:35 UTC
Hi, I'm using the Acer Immersive Headset to do some demos and I want the application to be in full screen on the monitor without the Mixed Reality Portal window.  As a work around I've published two versions of the app, one for MR and one for desktop with the hopes that the desktop version would stay in full screen.  However when I have the desktop version in full screen with the MR portal minimized, when I pick up the HMD the desktop version is immediately minimized and the portal pops up.  Is there anyway to prevent this?  The black box nature of the MR Portal along with its limited settings could use some work.

**Comment by jessemcculloch** [comment] 2017-08-22 13:03
There is a sensor in the headset meant to detect when you put it on, so that it launches the portal automatically.  This is intended behavior and is not a function of the HoloToolkit.  I would suggest moving this discussion to the forums if you are looking for solutions to try and find a workable solution for what you are trying to accomplish.

There is a specific category for the immersive headsets there, and we would be happy to help.  The link is [https://forums.hololens.com/categories/questions-and-answers-immersive](https://forums.hololens.com/categories/questions-and-answers-immersive)

**Comment by DDReaper** [comment] 2017-10-01 20:32
As this isn't an issue for the toolkit, can this now be closed @StephenHodgson / @jessemcculloch ?

**Closed** 2017-10-02 02:16 UTC
Labels: Dev-2017.2-Branch, Question

**Comment by JuanJSAR** [comment] 2019-04-11 18:39
If you do not use the sensor in the application you can simply cover it with a black ribbon
