### ISSUE TITLE
Second keyboard showing up for gaze

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1639] opened 2018-01-16 09:06 UTC
## Overview
When running the KeyboardTest scene, everything works fine in the editor. Clicking on a KeyboardInputField shows the keyboard, pressing close, closes it. As soon as the scene is built and run from Visual Studio as debug, or deployed and run (both from MR Headset), the behaviour is different. Gazing at the KeyboardInputField shows a completely different keyboard. The keyboard stays open as long as the user gazes at the field. He can operate it with motion controllers from the corner of the eye. If he stops gazing, the keyboard disappears unless the motion controller is pointing at it (this is completely weird behaviour btw.).
When the user clicks at the input field, the keyboard from the scene shows up. This means there is one gaze keyboard and one on-click-keyboard.

## Expected Behavior
Either the scene keyboard shows up on click or the auto created one (whereever that comes from). Furthermore, the keyboard shouldn't show up on gaze because it's not intuitive to stare at it until the motion controller is pointing at the keyboard to let it stay. The keyboard also shows up without any motion controller focus, so event when it shows up due to gazing, it can't be operated, so why is it there?

## Actual Behavior
One gaze, one click keyboard. Weird behaviour in when the mysterious keyboard shows up, disappears again...

## Steps to reproduce
use the KeyboardTest from the toolkit in editor and from Visual Studio

## Unity Editor Version
2017.3.0f3

## Mixed Reality Toolkit Release Version
not sure

**Comment by StephenHodgson** [comment] 2018-01-16 17:01
Duplicate of #1370

**Closed by StephenHodgson** 2018-01-16 17:01 UTC
