### ISSUE TITLE
InputManager's FocusManager and Unity InputFields

### ISSUE THREAD

**Issue by joherb** [Microsoft/MixedRealityToolkit-Unity#1510] opened 2017-12-12 21:58 UTC
## Overview
In my scene I have a canvas containing an InputField, HoloLensCamera, DefaultCursor and InputManager.

## Expected Behavior
When I click or tap the InputField it should get focussed and activated.

## Actual Behavior
The InputField gets activated and immediately deactivated.

## Steps to reproduce
Create a scene. Add a canvas containing an InputField, HoloLensCamera, DefaultCursor and InputManager. Try to activate the InputField.

## Unity Editor Version
Unity 2017.1.2f1 (64-bit)

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-v1.2017.2.0

**Comment by Skquark** [comment] 2017-12-16 01:02
I'm having the same issue I've been trying hard to find a workaround or fix for.  I'm using the TextMesh Pro Input Field, which uses Unity's InputField in it's core, and you described exactly what it's doing.  It highlights the text, briefly moves the caret, then unhighlights the input.. This is one of my last major bugs that's keeping my app from being fully functional since I rely a lot on the Input Fields for edits.  
Months ago before I got my headset, I hacked a workaround by converting taps into emulated mouse operations to move cursor to point of click and sending a mouse down, and it worked in the emulator, but doesn't in the MR Portal, where it actually moved the mouse on my desktop and clicks in regular Windows.  Was very complicated and tricky, and was sad when I had to undo that code.  My alternative workaround was to calculate the point on the InputField that's being pressed, figure out which character it's on, then manually move the input caret to that char position, but haven't been able to convert the point that way.  Slightly frustrating, lots of hours spent, hope there's a fix soon.
Also, is there any way to use the physical keyboard to type into the 3D Keyboard or input fields?  Regular typing does nothing and seems like there should be a way to get that standard functionality..

**Comment by joherb** [comment] 2017-12-18 09:21
My current workaround is to disable FocusManager when using InputFields and enable it after submit (InputManager.Instance.GetComponent<FocusManager>().enabled). Ok for me because I am using a bluetooth keyboard for activation and submiting.

**Comment by andnovar** [comment] 2017-12-20 20:05
This can be seen in the KeyboardTest scene when tapping on an InputField. It works very well on the editor but not when deployed. Has anyone have any advance on this I can continue ? I don't want to buy a Bluetooth keyboard

**Comment by StephenHodgson** [comment] 2017-12-20 20:35
The problem is that we're clearing the pointer data when we call `InputManager.RaiseSourceUp` and that clears the `EventSystem.current.currentSelectedGameObject` in the `StandaloneInputModule`.  We need to somehow recognize when we've got an input field selected and prevent our selection from changing.

**Comment by StephenHodgson** [comment] 2017-12-20 20:38
The best workaround for this atm is to set the override focused object in the InputManager when you select the input field.

**Comment by andnovar** [comment] 2017-12-20 21:06
You mean to set the override focused object to the InputField gameobject when you input down on the input field ?

**Comment by StephenHodgson** [comment] 2017-12-21 00:23
That is correct

**Comment by joherb** [comment] 2017-12-21 09:52
This is not working for me. Added a script implementing IInputClickHandler with
`public void OnInputClicked(InputClickedEventData eventData)
    {
        InputManager.Instance.OverrideFocusedObject = gameObject;
    }` 
to the InputField's GameObject.

**Comment by andnovar** [comment] 2017-12-21 19:49
It did not work for me either. So I found another workaround for the keyboard input. I extended the KeyboardInputField class from IInputHandler and implemented OnInputDown with the same code from OnPointerClick. This spawns the keyboard. Then for each key I added an InteractiveButton component and implemented the OnDownEvent firing the corresponding function. This may not be a good solution but helps in the meanwhile.

**Comment by Skquark** [comment] 2018-01-03 10:31
It doesn't help to disable the FocusManager because then we lose the motion controller.  Tried the OverrideFocusedObject method and didn't work for me either.  It sounds painful to add the InteractiveButton to each one of the keys, gotta be a better way to send the OnInputDown to the keyboard.  I could spend time looking for a hack, but it's probably best to fix it right..
I want to note that I'm focusing on the MotionController input more than the gaze and finger tap which still might work, I don't know.  I notice that the camera gaze point is what's highlighting onOver for both the keyboard and the input field, not the current input source.  So when I press the trigger on the InputField, the carat quickly moves to the gaze hitpoint then to the beginning.
Same thing applies to the keyboard's text input slider bar, but at least the carat moves there.  It's moving the cursor to my gaze instead of the current controller.  Understandable bug, I know it was made for the Hololens and many pains come from trying to get it working on multiple inputs.  Sucks that the bluetooth hand controllers arn't compatible with the Hololens, I expected that to be an automatic.
Anyone else make any progress?

**Comment by wiwei** [comment] 2019-04-11 20:26
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:26 UTC
Labels: Release Bug
