### ISSUE TITLE
Mapping of Xbox Controller

### ISSUE THREAD

**Issue by humpalum** [Microsoft/MixedRealityToolkit-Unity#1551] opened 2017-12-19 18:28 UTC
## Overview
Controller is not correctly mapped. Some Buttons dont work at all.

## Expected Behavior
Working Buttons.

## Actual Behavior
Dpad is controlling the "RightTrigger"
Trigger not reacting at all.
Same with right stick.

See this youtube video. It shows a Xbox Controller example Scene with the Xbox input not working correctly.
https://youtu.be/jLdp97GnPYk

## Steps to reproduce
With this Repo.
Boot up the example scene. (MixedRealityToolkit-Unity/Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity)
Had to apply the project settings in order to get the controller work at all.
Then just build and deploy it to the Hololens.

## Unity Editor Version
2017.2.1f1 - However, it didn't worked with earlier aswell.

## Mixed Reality Toolkit Release Version
Current release.

**Comment by StephenHodgson** [comment] 2017-12-19 18:30
Did you update your input mappings via MR Toolkit menu -> Configure -> Project Settings?

**Comment by humpalum** [comment] 2017-12-19 18:42
Jup, done that. 
Further we testet it, so that every Axis ist Kappes to something and made a simple debugoutput to check If there is any response at all. 
The 10th Axis was driven by the dpad.
The Trigger and the right stick did not change any value of the axis at all.

**Comment by johnyu89** [comment] 2018-01-15 21:10
Have the same issue with this current release of the mixed reality toolkit

Dpad is controlling RightTrigger
Left and Right Trigger no response but Shared trigger is working.
Right stick has no response.

Checked project settings input manager and everything is mapped correctly. 
One thing to note is when the controller is plugged in via USB on the computer and tested on the unity editor, it is working properly. Once project is loaded onto the hololens then some of the mapping is incorrect.

**Comment by humpalum** [comment] 2018-01-15 22:09
https://www.assetstore.unity3d.com/en/#!/content/70068

The example of that one works quite solid. So i guess its not an driver issue?

**Comment by StephenHodgson** [comment] 2018-01-15 23:49
That link was bad. 

In either case, the resource you've linked could be using a method that's outside of what Unity uses to map and provide input.  Chances are they're either using the Windows UWP APIs or XInput.

Also, be sure to check that the HID capabilities have been enabled for your application in the Project Settings.  That also affects how input is handed.

**Comment by StephenHodgson** [comment] 2018-01-18 01:02
https://developer.microsoft.com/en-us/windows/mixed-reality/hololens_known_issues#xbox_wireless_controller

**Comment by keveleigh** [comment] 2018-02-08 00:58
Additionally, make sure your controller firmware is up to date:

https://support.xbox.com/en-US/xbox-on-windows/accessories/how-to-update-xbox-one-controller-windows-10

I've seen various issues go away after updating everything.

**Comment by StephenHodgson** [comment] 2018-02-08 16:54
duplicate of #1490

**Closed by StephenHodgson** 2018-02-08 16:54 UTC
