### ISSUE TITLE
Manipulation handler moves object slower in vertical axis

### ISSUE THREAD

**Issue by marjackarpinski** [microsoft/MixedRealityToolkit-Unity#6151] opened 2019-10-01 08:33 UTC
## Overview
When using manipulation handler on an empty object, the user can move it freely in the scene. However moving object in vertical axis seems to be slower than moving it in horizontal axis. This problem occurs only when I build the app on Hololens, in Unity editor it works well.

## Expected Behavior
Object should move with the same speed in all directions when using manipulation handler.

## Actual Behavior
Object moves slower when moved vertically then horizontally

## Steps to reproduce
Add Manipulation handler to an object with collider. Build on Hololens.

## Unity Editor Version
2019.2.6f1

## Mixed Reality Toolkit Release Version
2.0.0

**Comment by julenka** [comment] 2019-10-02 20:40
Duplicate of #5896

**Closed by julenka** 2019-10-02 20:40 UTC
