### ISSUE TITLE
Hololens Unet client places anchor at headset position

### ISSUE THREAD

**Issue by benjamincoven** [Microsoft/MixedRealityToolkit-Unity#2303] opened 2018-06-14 13:19 UTC
## Overview

After a hololens starts to host and place corectly an anchor somewhere in the room. When a second hololens connects to the first one with Unet, it succesfully gets the server anchor (with the good id) but the anchor is placed at the headset position when the app connected. Note that all shared holograms and player controllers are well placed relatively to this anchor so all the scene is incorect of only one translation. Debug panel show nothing special except anchor set to true.

## Expected Behavior

The client should place the anchor at the same real position than the server.

## Actual Behavior

The client place the anchor at its headset position one second after connected to the server

## Steps to reproduce

Here a summary of what contains ma scene:
SpatialGameObject <SpatialMappingObserver, SpatialMappingManager>
UIContainer (prefab with UNET UI from MRTK)
NetworkGameObject <NetworkManager,NetworkDiscoveryWithAnchors,GenericNetworkTransmitter,WordlAnchorManager>
SharedCollectionGameObject <SharedCollection,SceneContentAdjuster>
UNetAnchorManager <NetworkIdentity,UNetAnchorManager>

## Unity Editor Version

2018.1.2f1

## Mixed Reality Toolkit Release Version

2017.4.0.0

Thank you very much for your help

**Comment by zachyale** [comment] 2018-06-14 18:21
Acknowledged- nothing else to add, but I am also encountering the same issue. 

Encountered using Mixed Reality Toolkit ver. 2017.4.0.0, and Unity ver.  2017.4.5f1.

**Comment by StephenHodgson** [comment] 2018-06-15 15:43
Duplicate of #2276?

**Comment by benjamincoven** [comment] 2018-06-15 15:51
Not sure, I don't have the error "This script is not intended to be run from the Unity Editor".

**Comment by hansbickhofe** [comment] 2018-06-15 21:55
After we changed some of the Compilerdirectives we got rid of the error "This script is not intended to be run from the Unity Editor". But we noticed the Debug Message that tells "Downloading from ...." seems to have missing Strings (two Spaces). So we think that the Client Lens try'd to download the Anchor, but doesnt know where to get it.

**Comment by benjamincoven** [comment] 2018-06-19 09:00
Is SpatialUnderstanding necessary for shared anchors? It is disabled in our project because it is not necessary. We keep SpatialMapping active and the Observer working.

No thought about the issue? Our application will be presented next week at an international exhibition with hundreds of potential Hololens customer from heavy industry.

Thank you very much.

**Comment by keveleigh** [comment] 2018-06-20 00:44
I believe I've root caused this issue and have opened #2319 with a fix. Please take a look and let me know if it fixes your issue! I was able to repro it before this fix and now the test scene works for me.

**Comment by benjamincoven** [comment] 2018-06-20 12:42
Thank you very much, we have tested the branch SharingInvestigation successfully with our app, however it breaks Vuforia, we will investigate tomorow.

**Comment by Redge-Ballard** [comment] 2018-06-20 21:53
@keveleigh this is a dumb question but how would I go about checking out your branch? Or do I need to wait until the PR is merged in?

**Comment by benjamincoven** [comment] 2018-06-21 07:55
@Redge-Ballard  Clone the following repository: https://github.com/keveleigh/HoloToolkit-Unity

Then checkout on branch SharingInvestigation.

You can use assets in folders Sharing and SharingWithUnet in HoloToolkit and Holotoolkit-Exemples

**Closed** 2018-08-01 22:39 UTC
Labels: Bug, Fixed in Stabilization, Sharing / Networking
