### ISSUE TITLE
Hand input broken in stabilization branch

### ISSUE THREAD

**Issue by sostel** [microsoft/MixedRealityToolkit-Unity#5557] opened 2019-08-08 22:37 UTC
## Describe the bug
Hand tracking is not working. Hand rays are not shown. I can't poke or grab holograms. I can't use air-tap.

## To reproduce
1. I've synced to latest in the prerelease/2.0.0_stabilization branch.
2. I've moved the HandInteractionExamples.unity to the first place in the BuildSettings to build and test that scene. 
3. Build and deploy to the device.
4. No hand input is registered. I do see an little opaque gaze cursor that is following my eye gaze. 

I did not change the MRTK config profile. When checking it's set to 'DefaultHoloLens2ConfigurationProfile'. 

## Expected behavior
1. The gaze cursor should not follow my eye gaze. If that's desired, let's replace the visuals as the distinct opaque circle is not recommended.
2. Holograms should be interactable using hand input (near and far). 

## Video
![image](https://user-images.githubusercontent.com/32180789/62742268-c3d12a80-b9f2-11e9-8046-4a033f438a0c.png)

## Your Setup (please complete the following information)
- Unity  2018.4.0f1
- MRTK Version: prerelease/2.0.0_stabilization

## Target Platform (please complete the following information)
- HoloLens 2

**Comment by wiwei** [comment] 2019-08-08 23:32
Also interesting, holographic remoting also not working in that branch

**Comment by keveleigh** [comment] 2019-08-09 00:08
@davidkline-ms and I believe we've figured this out. He'll have a PR incoming.

**Comment by davidkline-ms** [comment] 2019-08-09 00:09
This looks to have been a regression introduced by the recent data provider changes.  The root causes were:

* Enable in the new base class was calling Reset on the data providers instead of Enable
* The Input and Spatial AwarenessSystems were either
    * Not calling base.Enable / base.Disable
    * Calling them at the wrong time.

PR coming soon

**Comment by davidkline-ms** [comment] 2019-08-09 02:30
fixed in stabilization. merging fix into dev shortly

**Closed by davidkline-ms** 2019-08-09 02:30 UTC
Labels: 4 - In Review, Bug, GA Blocker, Services
