### ISSUE TITLE
PressableButton - cannot access StatefullInteractable MRTK Events Publicly through Unity Event System

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#11024] opened 2022-09-16 00:39 UTC
## Describe the problem

Blocked due to the inability to use Unity Event Fields in Inspector to set the Toggle or Is Interactable state of a PressableButton using 

## Describe the solution you'd like

PressableButton states such as Toggle or Is Interactable should be addressable through the Unity Event System and appear in the method list. For example, adding an event to OnClicked that sets a PressableButton to Toggled or Is Interactable.

## Describe alternatives you've considered

There is no alternative "no code" option here to build structures like mutually exclusive toggle groups by using the Unity Event system and Inspector driven reactions to button interactions.

**Comment by Zee2** [comment] 2022-09-16 17:43
Closing as a duplicate of #11006. This will be fixed very soon!

**Comment by Zee2** [comment] 2022-09-16 17:43
Also @holomatt `IsInteractable` == `.enabled`. You can enable/disable the button from UnityEvents just fine.

**Closed by Zee2** 2022-09-16 17:43 UTC
Labels: Feature Request
