### ISSUE TITLE
No Hand Interaction with Holographic Remoting on HoloLens 2

### ISSUE THREAD

**Issue by mbpictures** [microsoft/MixedRealityToolkit-Unity#9682] opened 2021-04-18 15:19 UTC
## Describe the bug

No kind of hand interaction (except AirTap) is working with Holographic Remoting on HoloLens 2. It seems like hands aren't recognized at all.

## To reproduce

1. Create a new Unity project
2. Switch Build Platform to UWP
3. Import TextMeshPro Essentials
4. Import MRTK Foundations and examples
5. Open scene which contains buttons (e.g. NearHandMenu example)
6. Open Holographic Remoting Player on Hololens 2
7. Open Windows Mixed Reality and enter the IP address of HoloLens 2
8. Press play
9. Bring hands in the viewport of HoloLens cameras

## Expected behavior

Visible hand representation and working interaction with Buttons etc.

## Your setup (please complete the following information)

- Unity Version 2020.3.3f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I already tried to install the DotNetAdapters manually (like described [here](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/Tools/HolographicRemoting.html#manual-dotnetadapter-installation), featured in this issue #8132) with no success. I'm also getting the following error in the unity console:
```
Unable to register IMixedRealityInputDeviceManager data provider (Windows Mixed Reality Device Manager) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal<Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputDeviceManager> (bool,System.Type,string,Microsoft.MixedReality.Toolkit.Utilities.SupportedPlatforms,object[]) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/BaseDataProviderAccessCoreSystem.cs:206)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider<Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputDeviceManager> (System.Type,string,Microsoft.MixedReality.Toolkit.Utilities.SupportedPlatforms,object[]) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/BaseDataProviderAccessCoreSystem.cs:159)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Services/InputSystem/MixedRealityInputSystem.cs:299)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Services/InputSystem/MixedRealityInputSystem.cs:241)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit/<>c:<InitializeAllServices>b__68_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:1030)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder (System.Action`1<Microsoft.MixedReality.Toolkit.IMixedRealityService>) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:1030)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:557)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:673)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance (Microsoft.MixedReality.Toolkit.MixedRealityToolkit,bool) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:825)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:get_Instance () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:648)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit/EditorEventListener/<>c:<.cctor>b__1_1 () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@dfa9edcffcdb-1618331409768/Core/Services/MixedRealityToolkit.cs:1560)
UnityEditor.EditorApplication:Internal_CallHierarchyHasChanged ()
```
I also tried a standalone, build application which doesn't work either.

**Comment by WikkidEdd** [comment] 2021-04-19 08:03
Holographic Remoting with hand tracking also requires a certain (laptop/PC) Windows OS version. 

I don't think there is any mention of it in the documentation, so I'm not exactly sure what version included this feature. I know that my desktop auto-updates got stuck on version 1809 and hand tracking wasn't working, while my laptop was on 1903 and hand tracking was working. I then upgraded my desktop OS manually and hand tracking started working. I've spoken to a couple of people in the community who also were able to resolve it by upgrading. So make sure you're on at least 1903.

**Comment by mbpictures** [comment] 2021-04-19 08:53
Thank you for your reply, here is my current windows version:
![image](https://user-images.githubusercontent.com/2772553/115207498-f3a75f80-a0fb-11eb-8e0e-8faba045524e.png)

The other fact is, that it didn't work with a build & deployed directly on the HoloLens 2 either. Which Profile of the MRTK do you use?

**Comment by WikkidEdd** [comment] 2021-04-19 09:03
Ah, sorry. I missed that little comment at the end that the built version didn't work either. Next time start with that information as it probably has nothing to do with Holographic Remoting :)

For Unity 2020 which is now XR SDK only, you should be using the DefaultXRSDKConfirmationProfile

**Comment by mbpictures** [comment] 2021-04-19 09:27
Thanks for that! Using this Profile, I can see the spatial awareness meshes but hand tracking doesn't work...

**Comment by mbpictures** [comment] 2021-04-19 09:43
Oh, I got an update! I just created a blank project (using the same setup) but downgraded the MRTK version to 2.5.0 and it is working!
Is there a bug in the current version?

**Comment by mbpictures** [comment] 2021-04-22 12:51
I guess, that I finally confirm this issue is related to the MRTK version. I tested the same scene with the same configuration the first time with MRTK version 2.5.4 with working hand tracking and the second time with MRTK version 2.6.0 without working hand tracking. It seems 2.6.0 introduced a bug there, can someone confirm this?

**Comment by ewolf29** [comment] 2021-05-02 19:45
I'm using Unity 2020.3.6f1 together with MRTK Version 2.6.1 and I can confirm the issue. There seems to be a bug with the initialization of the hand tracking I assume. Interestingly, out of my approximately 50 attempts to test the hand tracking, in two cases it worked indeed but I could not figure out why and could also not replicate it. It seems just random.

**Comment by mbpictures** [comment] 2021-05-02 22:09
@ewolf29 Glad to hear it's not on my end. I also got it to run once (with 2.6.1), but no idea why it worked.

**Comment by keveleigh** [comment] 2021-05-06 21:43
> It seems 2.6.0 introduced a bug there, can someone confirm this?

There was a bug for OpenXR in 2.6.0 (and fixed in 2.6.1), but I'm not aware of any blocking Windows XR Plugin issues in 2.6.x.

Which version of Windows XR Plugin are you using? Are you using the "auto connect" feature or manual connection? I believe the latest Windows XR Plugin offers the ability to choose one or the other. Can you try manual if you're not already using it?

**Comment by mbpictures** [comment] 2021-05-08 19:42
I'm using Windows XR Plugin 4.4.2. The issue appears in the packaged (built version) of the application, so I guess it's not related to holographic remoting. The only available emulation mode is "remote to device" as seen here:
![image](https://user-images.githubusercontent.com/2772553/117551426-2d59ef00-b046-11eb-9622-40e25a99d50c.png)

**Comment by keveleigh** [comment] 2021-05-17 16:25
I think this is a combination of a couple things.

1. Unity recently changed the behavior of remoting to auto-connect on startup instead of manually connecting before startup. This appears to have led to a slight delay in XR initializing after the app starts up due to needing to run through the connection hooks
    1. Unity re-added the manual connection option in the most recent releases (or the next release), but i believe auto-connect is still the default
1. We added (in 2.6) data provider filtering for XR SDK based on the active loader. We only check the active loader at initialization time, which means if XR hasn't initialized when MRTK initializes, there's no active loader and the data providers are never enabled

We'll likely need to enable some sort of delayed initialization in MRTK if we see the loader is null or XR is otherwise uninitialized

**Comment by ewolf29** [comment] 2021-05-19 09:58
> I'm using Windows XR Plugin 4.4.2. The issue appears in the packaged (built version) of the application, so I guess it's not related to holographic remoting. The only available emulation mode is "remote to device" as seen here:
> ![image](https://user-images.githubusercontent.com/2772553/117551426-2d59ef00-b046-11eb-9622-40e25a99d50c.png)

Just to confirm, MRTK 2.5.4 is working with the new remoting auto-connect system. This issue is exclusively related to MRTK 2.6.

**Comment by keveleigh** [comment] 2021-05-19 16:48
> Just to confirm, MRTK 2.5.4 is working with the new remoting auto-connect system. This issue is exclusively related to MRTK 2.6.

That makes sense! That's when the data provider filtering was added. I have some ideas and should have a PR open this week.

**Comment by mbpictures** [comment] 2021-05-25 10:51
Thanks for fixing this! Is there an ETA for 2.7?

**Comment by keveleigh** [comment] 2021-05-25 17:48
> Is there an ETA for 2.7?

Current ETA is the 27th!

**Comment by keveleigh** [comment] 2021-05-25 22:41
Fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9868

**Closed by keveleigh** 2021-05-25 22:41 UTC
Labels: Bug, Holographic Remoting, Release Blocker, XR SDK
