### ISSUE TITLE
KeyboardInputField is triggering both the Holotoolkit Keyboard and Mixed Reality system keyboard.

### ISSUE THREAD

**Issue by 265lutab** [Microsoft/MixedRealityToolkit-Unity#1707] opened 2018-02-09 02:20 UTC
## Overview
When selecting a KeyboardInputField it is displaying both the keyboard.prefab and the Mixed Reality system keyboard
## Expected Behavior
Only the keyboard.prefab from MixedRealityToolkit to be shown
## Actual Behavior
The MixedRealityToolkit keyboard is shown, then the MR system keyboard pops up, it then closes for a fraction of a second and pops up again. When pointing at the system keyboard the controllers and the pointer from the system are displayed on top of the controllers in my game as well. This does not happen in the unity editor, but only in builds. I'm using VRTK for the pointer input. A few days ago the build I created did not have this problem. Not sure if there was an update to the WMR or if something is set up differently in my unity project.
## Steps to reproduce
_(Links to sample github project preferred)_
1. Place the keyboard.prefab into the scene 
2. Setup a KeyboardInputField
3. Make a build
4. Select KeyboardInputField
## Unity Editor Version
Unity 2017.2.0.1p2-MRTP5
## Mixed Reality Toolkit Release Version
MixedRealityToolkit 2017.2.1f1

**Comment by Alexees** [comment] 2018-02-09 07:06
That's a duplicate of #1370 (can't edit this though)

**Closed** 2018-02-09 08:15 UTC
