### ISSUE TITLE
OnPointerClicked's IMixedRealityPointerHandler is called even after a long drag

### ISSUE THREAD

**Issue by romsahel** [microsoft/MixedRealityToolkit-Unity#5235] opened 2019-07-09 08:08 UTC
## Describe the bug
When implementing interface `IMixedRealityPointerHandler`, `OnPointerUp` and `OnPointerClicked` are always called together: this means that even after a long gesture (drag, manipulation, long tap), the `OnPointerClicked` method is called.

## To reproduce

1. Add a script implementing `IMixedRealityPointerHandler` that logs calls to `OnPointerClicked`
2. Run the scene and do a long gesture
3. `OnPointerClicked` is always called.

## Expected behavior

We would expect `OnPointerClicked` to be called only when the gesture is short (the delay between `OnPointerDown` and `OnPointerUp` should be small) and stationary (it's a click and not a swipe).   
Despite the name difference, as of now, `OnPointerUp` and `OnPointerClicked` are identical in their use.

## Screenshots

![2019-07-09_10-05-32](https://user-images.githubusercontent.com/3393362/60870446-2c30be80-a231-11e9-8f73-8e0d55f7d660.gif)

## Your Setup
- Unity Version [e.g. 2018.4.2f1]
- MRTK Version [e.g. v2.1]

## Target Platform

- HoloLens
- HoloLens 2

**Comment by wiwei** [comment] 2019-07-09 21:43
@lukastoenneMS @keveleigh

**Comment by lukastoenneMS** [comment] 2019-07-10 08:41
No strong opinion on this, it's not really my area and seems more like a design decision. Possibly a breaking change if OnPointerClicked is not raised any longer for long clicks.

**Comment by keveleigh** [comment] 2019-07-10 17:26
It's somewhat related to #5051, where we used to use the GestureRecognizer Tap as a click in HTK. The tap gesture is more strongly defined and does have a time component to it.

**Comment by naostranMS** [comment] 2019-07-11 22:49
I think this is the same as this issue: #4998
As I noted there, UnityTouchController already works this way.

**Comment by wiwei** [comment] 2019-07-24 22:23
Closing this as a dupe of #4998

**Closed by wiwei** 2019-07-24 22:23 UTC
Labels: Bug
