### ISSUE TITLE
Focusable events not being raised with rididbody objects.

### ISSUE THREAD

**Issue by ARUNVSHIV** [Microsoft/MixedRealityToolkit-Unity#1450] opened 2017-11-28 10:11 UTC
## Overview
When rigidbody is attached to parent or child gameobject , cursor gaze is not detected where I used  `OnFocusEnter()` , `OnFocusExit()`, eventhough `IsKinematic` selected or not.

## Expected Behavior
Gaze should work with rigidbody attached to model.

## Actual Behavior
Gaze not working with rigidbody attached to model. parent or child

## Steps to reproduce
1. Added cursor and input manager.
2. UI attached mesh collider or  box collider . 
3. with collider gaze working fine and able to use methods like OnFocusEnter() or Exit().
4. When rigidbody attached to the same model gaze not working.  
5. If rigidbody removed , gaze will work again.

## Unity Editor Version
2017.2f1 

## Mixed Reality Toolkit Release Version
2017.2.0

**Comment by StephenHodgson** [comment] 2017-11-28 16:49
Repro steps?

**Comment by ARUNVSHIV** [comment] 2017-11-29 07:15
1.Added cursor and input manager.
2.imported model with mesh collider or  box collider.
3.with collider gaze working fine and able to use methods like OnFocusEnter or Exit.
4.When rigidbody attached to the same model gaze not working.  
5.If rigidbody removed means gaze will work again.

*rigidbody used to move the gameobject and check collision.

**Comment by StephenHodgson** [comment] 2017-11-29 16:52
Duplicate of #1331.  I'll close the other one because it didn't have good repro steps.

**Comment by wiwei** [comment] 2019-04-11 20:26
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:26 UTC
Labels: Release Bug
