### ISSUE TITLE
ArgumentException: Input Button Fire1 is not setup

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1340] opened 2017-11-11 06:52 UTC
## Overview
Created a new project. Used default MRTK settings (target windows uwp, enable XR, *not* targeting occluded devices, etc.). On Run in the Unity Editor it loads but rhrows and error below. 

## Expected Behavior
Starts without error

## Actual Behavior
ArgumentException: Input Button Fire1 is not setup.
 To change the input settings use: Edit -> Project Settings -> Input
HoloToolkit.Unity.InputModule.GamepadInput.HandleGamepadAPressed () (at Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs:92)
HoloToolkit.Unity.InputModule.GamepadInput.Update () (at Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs:86)

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
Unity 2017.2.0p1-MRTP4 (64bit)

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-v1.2017.2.0

**Comment by keveleigh** [comment] 2017-11-11 07:18
Ahh interesting, did you use the input manager downloader? A potential side effect to the current way of downloading the latest input manager asset from the repo is that any changes may not be compatible with previously released packages. #1126 can help keep this in line. I'm not sure the best way to resolve this, since that script contains 1 default Unity axis and 2 custom ones. Keeping those in the asset forever wouldn't be great.

**Comment by StephenHodgson** [comment] 2017-11-11 15:15
This has been fixed in the latest master branch.

Duplicate of #1229.

**Closed by StephenHodgson** 2017-11-11 15:15 UTC
