### ISSUE TITLE
Broken Link in Documentation Button on Hand Tracking Settings

### ISSUE THREAD

**Issue by septianrazi** [microsoft/MixedRealityToolkit-Unity#7114] opened 2020-01-22 00:38 UTC
## Describe the issue
The Documentation Button on Hand Tracking Section of the Mixed Reality Toolkit (Script) goes to the following link that leads to a 404:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSystem/HandTracking.html

Mixed Reality Toolkit (Script) -> Input -> Hand Tracking

<img width="361" alt="brokenLink" src="https://user-images.githubusercontent.com/28195428/72855014-38322880-3d0a-11ea-9e8f-51250ee57db4.PNG">

## Feature area
Broken Link to the Input System Documentation Page

## Existing doc link
Probably should be redirected to this link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/HandTracking.html

**Comment by Troy-Ferrell** [comment] 2020-01-22 00:47
Dupe of #6857

**Closed by Troy-Ferrell** 2020-01-22 00:47 UTC
Labels: Documentation
