### ISSUE TITLE
TapToPlace Inspector throws errors

### ISSUE THREAD

**Issue by justinpando** [microsoft/MixedRealityToolkit-Unity#9672] opened 2021-04-15 23:09 UTC
## Describe the bug

This error occurs when I try to expand Advanced Properties - it also doesn't show the Magnetic Surfaces field which prevents following along with [Creating dynamic content using Solvers](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)

> NullReferenceException: Object reference not set to an instance of an object
> UnityEditor.EditorGUILayout.IsChildrenIncluded (UnityEditor.SerializedProperty prop) (at <5984c823338e4ca69b7a0ca01115425e>:0)
> UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUILayoutOption[] options) (at <5984c823338e4ca69b7a0ca01115425e>:0)
> Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers.TapToPlaceInspector.RenderAdvancedProperties () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@417f47aed5c2-1617916890577/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs:118)
> Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers.TapToPlaceInspector.RenderCustomInspector () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@417f47aed5c2-1617916890577/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs:99)
> Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers.TapToPlaceInspector.OnInspectorGUI () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@417f47aed5c2-1617916890577/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs:72)
> UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <5984c823338e4ca69b7a0ca01115425e>:0)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

## To reproduce

Follow the above tutorial and put a TapToPlace component on an object, then expand Advanced Properties.

## Expected behavior

I expect to see all advanced properties including Magnetic Surfaces.

## Screenshots
![image](https://user-images.githubusercontent.com/3631080/114948960-e9881700-9e04-11eb-8fe7-b8c5110c83c4.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.24f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

In the above screenshot there's also an unrelated error thrown by the NearInteractionGrabbable because the Cube prefab object in the tutorial [Initializing your project and deploying your first application](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=winxr) doesn't have any colliders on the base object.

**Comment by keveleigh** [comment] 2021-04-16 00:06
This is a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9645, which was fixed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9646 and shipped today in our preview.3 release of 2.7.0.

**Closed by keveleigh** 2021-04-16 00:06 UTC
Labels: Bug
