### ISSUE TITLE
Windows freeze after run emulator

### ISSUE THREAD

**Issue by xbandi** [Microsoft/MixedRealityToolkit-Unity#3198] opened 2018-11-29 16:20 UTC
Hi, 
mount and half ago I asked a same question on official microsoft holographic forums but everyone has successfully ignore me. I know, that this question out of scope MixedRealityToolkit but maybe you know about this issue.

I launched the basic application on the hololens emulator (only white cube in front of the camera), it was running normally, I tried to move with arrows, but then Windows freeze. I was waiting a few minutes, however I had to restart PC.

PC performance are good enough for emulator.

Motherboards: 	Gigabyte GA-B450M DS3H
CPU: 			AMD Ryzen 5 1600 Six-Core 
GUP: 			GeForce GTX 1050 2GB
RAM: 			8 GB
Windows 10 Education 64 bit   version: 1809

Did you meet with same issue ?

**Comment by chrisfromwork** [comment] 2018-12-03 20:34
Can we get more information on your application? Is it one of the visual studio template holographic apps? Was the application built in unity using the MRTK?

It may be that the keyboard keys you are using don't necessarily equate to the expected emulator behavior ( https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator ). It looks like to move around in a scene you may need to use w,s,a,d compared to arrow keys:

"...
Walk forward, back, left, and right - Use the W,A,S, and D keys on your keyboard, or the left stick on an Xbox controller.
..."

**Comment by IkeTheDestroyer** [comment] 2019-02-11 22:49
I also am having problems with this.  Every second time(at least it seems) I deploy to the emulator, my entire cpu freezes at which point I have to manually restart the computer.  This happens whether or not I use the keyboard or any input at all.   Even if I do nothing, it will freeze.  The first time I deploy it runs fine. This happens with the sample holographic app, and with unity apps. It also happens with both emulator 10.0.17763.134 and 10.0.17134.80. Maybe connected to AMD CPUs?

My specs:
CPU: AMD Threadripper 1950x 16-core
GPU: AMD Vega64
Ram: 64GB
Windows 10 Pro 1809

**Comment by IkeTheDestroyer** [comment] 2019-02-15 21:06
My suspicions about AMD processors being the problem seem to be confirmed.  It looks like Ryzen based processors have a bug running x86 (32 bit) virtual machines. This causes the machine to crash and freeze.  This has been fixed in AGESA 1.1.0.0(bios).  Make sure that your bios is the most recent version.  Even after updating my bios I still would freeze.  It seems that the fix only works when limiting the number of virtual CPUs to 1.  By default the Hololens emulator is set to 4.  You can change this in Hyper-V, in the virtual machine settings. After changing the Hololens VM to use a single core, no more freezes. Hope this helps.

Relevant details in the comments of this article: https://community.amd.com/thread/220392

**Comment by IkeTheDestroyer** [comment] 2019-02-15 21:35
My suspicions about AMD processors being the problem seem to be confirmed.  It looks like Ryzen based processors have a bug running x86 (32 bit) virtual machines. This causes the machine to crash and freeze.  This has been fixed in AGESA 1.1.0.0(bios).  Make sure that your bios is the most recent version.  Even after updating my bios I still would freeze.  It seems that the fix only works when limiting the number of virtual CPUs to 1.  By default the Hololens emulator is set to 4.  

I tried changing the settings in Hyper-V to use only 1 CPU, but when running the emulator from VS it seems to switch it back to 4, thereby causing a crash.  When I launch the emulator from Hyper-V with only 1 CPU -> no crash. Only problem is when I launch from Hyper-V, I can't use the mouse as input and there is no internet.  Now I am trying to figure out a way to stop VS from changing the settings, or to launch with only 1 CPU.

Relevant details in the comments of this article: https://community.amd.com/thread/220392

**Comment by IkeTheDestroyer** [comment] 2019-02-16 16:11
The configuration file is in C:\Program Files (x86)\Windows Kits\10\Microsoft XDE\10.0.17763.0\SKUs\HDE. (For the latest Emulator, 10.0.17763.0).  The configuration file is xdesku.xml.  In the file, change from ProcessorCount="4" to ProcessorCount="1". This prevents freezing but of course makes the emulator run slower. 

In conclusion, make sure your bios are at least AGESA 1.1.0.0 or higher, and only run the emulator on one virtual CPU.

**Comment by wiwei** [comment] 2019-04-19 21:02
Thanks @IkeTheDestroyer for sharing out your solution. I'm getting to this party somewhat delayed, but yeah, anytime you have a full system freeze it's probably something going on at the driver->below. I'm closing this issue out now.

**Closed by wiwei** 2019-04-19 21:02 UTC
