### ISSUE TITLE
XAML: Holotoolkit triggers own and system keyboard

### ISSUE THREAD

**Issue by IrisSReflekt** [Microsoft/MixedRealityToolkit-Unity#1940] opened 2018-04-11 12:33 UTC
## Overview
I use the Holotoolkit keyboard and gaze at its input field (the one directly on the keyboard) 

## Expected Behavior
nothing should happen except for maybe focus change 

## Actual Behavior
As soon as I gaze at the input field, I am thrown out of my app and into the 2d keyboard app. if i enter my text there and submit, the text is submitted into the input field of the holotoolkit keyboard and i have to click enter on that one once more to finally submit the text. If i gaze again on the input field the external keyboard opens again. This can make the user be stuck in a loop if he keeps looking there to check his input

## Steps to reproduce
build with xaml
open holotoolkit keyboard
gaze at the input field

## Unity Editor Version
2017.2.0f3 - building for XAML with 10.0.16299.0 sdk

## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by StephenHodgson** [comment] 2018-04-11 13:38
Duplicate of #1370

**Comment by StephenHodgson** [comment] 2018-04-11 13:40
Well not exactly a duplicate. Essentially we need to remove the keyboard prefab from the project for those that are using RS4 in the HoloLens

**Comment by IrisSReflekt** [comment] 2018-04-11 15:15
I dont think we are using rs4, i just checked os and firmware version numbers:
os: 10.0.14393.2007
firmware: 0005.05.P.1606.291.233.R

Also, if you would remove the keyboard prefab, that would mean we have to use the integrated 2d one? because we actually want to only use the one from holotoolkit to prevent breaking the 3d immersion

**Comment by cybergoulion** [comment] 2018-04-17 10:52
It's not specificallyon topic but I also exported my project in XAML because I needed to open a registered filetype file in the desktop version using OnFileActivated(FileActivatedEventArgs args). I didn't try this on the hololens version yet, but I cannot see another way of doing it. Is there a right/recommended way to do this in a D3D project?

**Closed** 2018-05-30 23:34 UTC
Labels: Fixed in Stabilization, Investigate, UX Controls
