### ISSUE TITLE
Bug in BuildDeployWindow

### ISSUE THREAD

**Issue by NiklasGit** [Microsoft/MixedRealityToolkit-Unity#1687] opened 2018-02-02 14:18 UTC
## Overview
When checking for the current Windows 10 SDK version in HoloToolkit.Unity.BuildDeployWindow in lines 309-329 the correct and isntalled version is not found if there is only one folder in C:\Program Files (x86)\Windows Kits\10\Lib
## Expected Behavior
If there exists a folder with the name "10.0.16299.0" in C:\Program Files (x86)\Windows Kits\10\Lib nothing bad shoul happen.
## Actual Behavior
If ONLY the one folder with the name "10.0.16299.0" exists unity throws the error detailed in line 328.
## Reason of Error
The variable "currentSDKVersionIndex" is initialized with 0. Then the already mentioned folder is searched. But there is only the one folder in C:\Program Files (x86)\Windows Kits\10\Lib then both conditions in lines 313-323 result in the variable staying 0 (because length (1) - 1 = 0 as well as the index being 0). When the index is checked in line 326 an error is falsly detected.
##Steps to Fix
Initiate the variable "currentSDKVersionIndex" with -1 and change the check in line 326 to checking against -1. Neither the index of the folder (if found) nor the number of subfolders - 1 (if any exist) can be negative.
## Unity Editor Version
2017.3.0f3
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by StephenHodgson** [comment] 2018-02-02 18:16
I fixed this in #1549, but it probably should be cherry picked and submitted on it's own.

**Comment by StephenHodgson** [comment] 2018-02-04 22:51
Actually, after reviewing this, it seems to already be fixed in the dev branch.

**Comment by StephenHodgson** [comment] 2018-02-04 22:54
duplicate of #1584

**Closed by StephenHodgson** 2018-02-04 22:54 UTC
Labels: Bug, Fixed in Dev Branch
