### ISSUE TITLE
3D Objects following along with the viewers hololens

### ISSUE THREAD

**Issue by holosuji** [Microsoft/MixedRealityToolkit-Unity#2353] opened 2018-06-28 02:17 UTC
## Overview
At times the 3D objects which are meant to be stationary in the real space follows the viewing user without their consent. I researched over this unintentional occurrence of the 3D objects following the users but found nothing helpful. Please do let me know if there is a way to resolve this error.

## Expected Behavior
The stationary 3D objects should remain stationary where they are meant to be.

## Actual Behavior
The stationary 3D objects ceases to remain stationary and follows the user's HMD (Head).

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
**Unity 2017.2.1p1**

## Mixed Reality Toolkit Release Version
**MRTK-Unity-2017.2.1.1**

**Comment by keveleigh** [comment] 2018-06-28 14:29
Are you receiving a lost tracking message?

I don't think there's enough information here to determine what the issue is or if this is Toolkit-related.

**Comment by ThomasAstrakhan** [comment] 2018-06-28 14:32
you should try to record a video of what is happening in your Unity Editor while using Holographic Remote

**Comment by holosuji** [comment] 2018-06-29 03:18
hi @keveleigh sorry for the lack of information, It happens only with the HoloLens and since MRTK being the crux of the entire HoloLens's deployment, I suspect it is something that has to do with the MRTK and also I got the same problem when running an example scene called **Sharing Test** on my HoloLens and I ended up experiencing the same _"objects being tagging along_" problem with the default sphere we were provided with the project.

**Comment by holosuji** [comment] 2018-06-29 03:19
Hi @ThomasAstrakhan, Sure I am trying to recreate the error and get that on a video. Thanks

**Comment by holosuji** [comment] 2018-06-29 05:10
This is the video of it happening https://streamable.com/o5ism Sorry if it is not very clear

**Comment by holosuji** [comment] 2018-06-29 05:36
And @keveleigh it shows that **"Trying to map your surrounding"** popup when it happens.

**Comment by StephenHodgson** [comment] 2018-06-29 06:28
@holosuji make sure your device sensors are not covered. It's def an issue with the hardware loosing it's tracking of the world.

**Comment by holosuji** [comment] 2018-07-02 01:42
Hi @StephenHodgson @ThomasAstrakhan @keveleigh  The device sensors are not covered and they're absolutely Intact. After an hour of research I presume this is what I am doing wrong with the project.

1) I presume the _**SharingTest**_ Example scene in the MRTK does not use the Spatial Mapping feature
2)I also presume that it places the objects based on the headset's orientation and not the spatial map (since the project does not use it)
3)Since when I shake my HMD or disorient it by any means it causes the headset to loose its orientation and fails to understand the 3D object's position in the space and it's own.
4)Thus after failing to get the orientation, it stops the update loop (I'm not very sure where exactly but this is what I've heard) and causes the 3D object to follow along because the HMD does not know where it stands and the HMD has nothing else to rely on thus the 3D object is being snapped to the user's body due to the lack of understanding.
5)And this is what causes the 3D Objects to follow along with the user.

I am sorry if I have got this whole thing wrong, It is just from my understanding from going through various other forums. Kindly acknowledge if my understanding about this matter is right. It will help others debug their problem for the better and also please do let me know if it is wrong.

**Comment by wiwei** [comment] 2019-04-11 20:14
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:14 UTC
