### ISSUE TITLE
Videos was shot using Mixed Reality Capture (MRC) have a gray overlay.

### ISSUE THREAD

**Issue by Futo23** [microsoft/MixedRealityToolkit-Unity#10207] opened 2021-09-09 14:20 UTC
## Describe the bug

Videos was shot using Mixed Reality Capture (MRC) have a gray overlay.

## To reproduce

1. Click on [ Mixed Reality ] > [ Project ] > [ Apply recommended scene settings for HoloLens 2] .
2. Move to Display Settings at Camera Profile in Mixed Reality Toolkit.
3. Check the value that Transparent > Background Color > α = 0 (transparent).
4. Deploy to HoloLens 2
5. Start App
6. Capture video using MRC from Home Menu.

## Expected behavior

Remove a gray overlay from capture video using MRC ( Mixed Reality Capture ) .

## Screenshots

<img src="https://user-images.githubusercontent.com/16267066/132701740-a71b27bf-ae7a-4d08-9d29-a029b5e7b6be.png" width="600">

## Your setup (please complete the following information)

- Unity Version 2020.3.8f1
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I understand that HoloLens 2 use the settings ( Display Settings > Transparent > Background Color ).
In spite of I set Background Color α value to 0, didn't remove gray overlay.
Then I changed the alpha value of opaque's Background color to 0,  could remove gray overlay.
Is this the correct behavior？

The figure below - ( Display Settings > Opaque > Background Color > α = 0 )

<img src="https://user-images.githubusercontent.com/16267066/132702134-3a16d4b2-cbb5-4918-b1ff-3faddef0e47a.png" width="600">

**Comment by keveleigh** [comment] 2021-09-10 19:28
Is this using OpenXR, Windows XR Plugin, or legacy built-in XR?

**Comment by Futo23** [comment] 2021-09-14 13:51
@keveleigh Thank you for your reply. I'm using OpenXR.

**Comment by horatiu665** [comment] 2021-11-23 13:16
Hi. I have this issue as well, however my issue does not exist when I use MRTK packages 2.7.2 without URP, but exists as soon as I use URP. I am able to set which color should be in the background, but the alpha value does not matter and it always draws a dark (or colored) overlay in the background, instead of the expected transparent.

I have tried everything, but I am out of ideas.

I'm using Unity 2020.3.20f1 (any later update breaks the shared depth buffer rendering unfortunately - it just flickers like crazy and it's a known, ignored issue)
I think I'm using Windows XR plugin, but I'm not 100% how to check. Here is how it looks in my proj window
![image](https://user-images.githubusercontent.com/5824753/143030490-9ee07241-f9a3-41d8-a65c-8f2f1adbd55d.png)

I am using the base project from the AOA (azure object anchors) sample which uses MRTK: https://github.com/Azure/azure-object-anchors.

Can anyone help?

**Comment by FelixWeichselgartner** [comment] 2021-12-08 13:21
I'm experiencing the same issue since a few hours. If I take screenshots without my developed app open I have no gray overlay. If I open my app I get the gray overlay over all my screenshots. When I open live preview in the device portal and I move my head fast, the gray overlay does not always align with the video, so at the borders I can see the normal image (without overlay). When the head is static again, the overlay is completely over the video again.

I not aware that I changed anything relevant here. Maybe this is caused through a HL2-Update?

**Comment by FelixWeichselgartner** [comment] 2021-12-08 16:04
I did some more debugging and found this:

I tried with different projects that worked fine so far:

New Unity 2020 Projekt (Unity 2020.3.16f1, OpenXR Plugin 1.2.8, MRTK 2.7.2, ARM32 Release Build with Visual Studio 2019):
This message comes up a lot in the Visual Studio log:
analog\input\mirage\publicapi\holographiccamerarenderingparameters.cpp(552)\Windows.Mirage.dll!6F7BB68B: (caller: 6C69A847) ReturnHr(54) tid(758) 80070057 The parameter is incorrect.
This also came up in my developed version from the comments above.

Periodic Table Example from Microsoft (https://github.com/microsoft/MRDL_Unity_PeriodicTable) (Unity 2019.4.18f1, Windows XR Plugin for Unity XR SDK 2.5.2, MRTK Version unsure, ARM64 Release Build with Visual Studio 2019):
works as expected

As @keveleigh specifically asked about the XR-SDK versions, I wrote the all versions I used above. It might be that OpenXR is the problem here. However, it worked until today for me. So far I'm still unsure what changed...

**Comment by FelixWeichselgartner** [comment] 2021-12-09 08:37
So I found out that in the "Web Windows device portal > Views > Mixed Reality Capture > Tick Off Render from Camera" solves the problem for me.

**Comment by keveleigh** [comment] 2021-12-09 19:01
@FelixWeichselgartner Thank you for that great write-up!! Some super helpful information in there for us to dig into. 

> It might be that OpenXR is the problem here. However, it worked until today for me. So far I'm still unsure what changed...

One quick question: which version of the MR OpenXR Plugin are you using?

**Comment by FelixWeichselgartner** [comment] 2021-12-10 08:24
@keveleigh I have to admit that I am not 100% sure what the difference between OpenXR-Plugin and MR OpenXR-Plugin is. Above I wrote the OpenXR-Plugin version, that I saw in the unity package manager and the section "Unity Technologies". In the section "Custom" I also see "Mixed Reality OpenXR Plugin" -> that is version 1.0.2. I hope that was the version you meant :). Let me know if you need more info.

**Comment by astaikos316** [comment] 2021-12-24 22:32
I am having the same issue.  I am running Unity 2020.3.16f1 with MR OpenXR Plugin 1.0.2 and Unity OpenXR Plugin 1.2.8.  I have tried the other suggestions of setting alpha to 0 but they have not worked.

**Comment by FelixWeichselgartner** [comment] 2021-12-24 23:22
@astaikos316 does disabling rendering from camera (see above) get rid of the gray overlay for you?

**Comment by astaikos316** [comment] 2021-12-24 23:23
No it does not.

**Comment by astaikos316** [comment] 2021-12-28 19:14
Just updated MR OpenXR plugin to 1.2.1 and the problem is not there anymore.

**Comment by thomaswester** [comment] 2022-01-19 20:11
I am still seeing the gray overlay. 

Unity 2020.3.26f
MRTK 2.7.3
Universal Render Pipeline 10.8.1
MR OpenXR 1.2.1
Unity OpenXR 1.3.1

Changing "Render from camera" does not have any impact
I can also replicate on 2020.3.18

Note I don't see the gray overlay when working with Holographic Remoting Play Mode in the Editor.

**Comment by thomaswester** [comment] 2022-01-19 20:39
I was able to fix this disabling HDR in the UniversalRenderPipelineAsset. It's under the Quality header and it's default is true/on.

Unity 2020.3.26f
MRTK 2.7.3
Universal Render Pipeline 10.8.1
MR OpenXR 1.2.1
Unity OpenXR 1.3.1

**Comment by astaikos316** [comment] 2022-01-19 22:30
I am not using URP for my project. I do occasionally see it come back if I
deactivate and reactivate the webcam source I have in my project. Then if I
do that again it goes away

**Comment by lmaxsmith** [comment] 2022-02-04 23:42
By updating all my stuff to the same as @thomaswester I was able to fix mine. Not sure which one did the trick, but MR OpenXR was the most out of date (was 1.0.1).

**Comment by nosy-b** [comment] 2022-02-28 14:29
I got the gray overlay when recording any WebXR demo. (I tried as suggested unticking Mixed reality capture/Render from Camera, no effect), I tried changing alpha value in my code without any effect. Actually same gray background when recording official demos too (https://immersive-web.github.io/webxr-samples/immersive-ar-session.html)
My test config: Hololens 2, Edge browser (all updated)

Thanks if anyone has an idea :)

Example capture here (in AR mode or even just with edge browser normal mode I see transparent but when recording it gets a gray background like this)
![image](https://user-images.githubusercontent.com/158514/155999948-2f6c048d-6596-449e-a55b-ca0c77919ece.png)

**Comment by keveleigh** [comment] 2022-05-12 01:37
Going to close this down due to the influx of success comments. Thanks for all the updates!

**Closed by keveleigh** 2022-05-12 01:37 UTC
Labels: Bug, External
