### ISSUE TITLE
Compressible button visuals tuning

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4562] opened 2019-05-24 21:19 UTC
## Overview
- Scale the button visuals transform along Z as press depth changes.
    - Requires a ‘visuals depth’ or similar parameter to map press-depth to scale.
- Also ensure that the front plane of visuals is the point at which depressing begins.

Need to follow up with Joshua Neff for more explanation.

**Comment by ADP-JoNeff** [comment] 2019-06-25 22:10
Closing dupe of this issue, #4978

**Comment by cre8ivepark** [comment] 2019-07-05 22:11
Completed with #5168

**Closed by cre8ivepark** 2019-07-05 22:11 UTC
Labels: 0 - Backlog, Bug, Shell Parity, UX Controls - Buttons
