### ISSUE TITLE
Box Projection for Reflection Probes (Shaders)

### ISSUE THREAD

**Issue by Ayfel** [microsoft/MixedRealityToolkit-Unity#9150] opened 2021-01-19 21:19 UTC
## Describe the problem

Box projection doesn't seem to work on the MRTK standard shaders, which causes really bad reflective surfaces for head mounted displays (especially in rooms)

## Describe the solution you'd like

Enable box projection for reflection probes to work with the MRTK standard shader

## Describe alternatives you've considered

Writing some custom shader

## Additional context
NA

**Comment by polar-kev** [comment] 2021-01-20 18:52
@Cameron-Micka, what's your take on this?

**Comment by Cameron-Micka** [comment] 2021-01-21 23:22
Thank you for reporting this @Ayfel. Yes, the MRTK/Standard shader does not account for box projection (or reflection probe blending). We should call this out in the docs.

To properly support box projection we need to introduce a call to the `BoxProjectedCubemapDirection` method within UnityStandardUtils. There is a great example of the changes need on this page: https://catlikecoding.com/unity/tutorials/rendering/part-8/

**Comment by Ayfel** [comment] 2021-01-22 00:45
Thanks @Cameron-Micka I tweaked the shader so the worldReflection parameter reads as follows:

`float3 worldReflection = BoxProjectedCubemapDirection(reflect(incident, worldNormal), i.worldPosition, unity_SpecCube0_ProbePosition, unity_SpecCube0_BoxMin, unity_SpecCube0_BoxMax);`

I didn't add blending as I didn't need it (yet), so this does the trick so far

**Comment by Zee2** [comment] 2022-08-25 02:22
Closing as duplicate of MRGT issue https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/54.

**Closed by Zee2** 2022-08-25 02:22 UTC
Labels: Shaders / Materials, Feature Request
