### ISSUE TITLE
Unity 2020.3.21f, 2020.3.22f1, and 2020.3.23f1 causes flashing/strobing effect on HoloLens 2 (Epilepsy Warning)

### ISSUE THREAD

**Issue by anthony-simetri** [microsoft/MixedRealityToolkit-Unity#10288] opened 2021-11-01 15:56 UTC
## Overview
Scene Understanding example not rendering as intended.

## Expected behavior
Creates meshes for different parts of the scene

## Actual behavior
Creates meshes for different parts of the scene but frame rate is choppy and flashy.

## Steps to reproduce
Pasted development branch into new project
Installed Scene Understanding SDK with Mixed Reality install tool
Built and uploaded to HoloLens 2

## Unity editor version
Unity 2020.3.21f

## Mixed Reality Toolkit release version
Tested with 2.7.2 and Development branch

Video attached. Epilepsy warning?
https://user-images.githubusercontent.com/73355311/139700708-413aa398-57a4-4b4f-b8bd-6077cac839b4.mp4

**Comment by anthony-simetri** [comment] 2021-11-01 15:57
UnityPlayer log attached

[UnityPlayer(14).log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/7454503/UnityPlayer.14.log)

**Comment by anthony-simetri** [comment] 2021-11-01 15:59
Uses Plugin managers rather than OpenXR

**Comment by polar-kev** [comment] 2021-11-02 18:43
Hey @anthony-simetri, thanks for reporting this. That flashing looks awful and I'm sorry to hear you experienced it. We did some digging and found that this issue is a Unity bug that was introduced in Unity 2020.3.21f. We've seen it across multiple example scenes, not just the scene understanding example. Unity is aware and working on a fix that is expected to be part of the 2020.3.22f release. 

In the meantime I recommend staying away from 2020.3.21f and using an earlier release of 2020.3 LTS.

**Comment by polar-kev** [comment] 2021-11-02 18:45
I am going to change the title of this issue to accurately reflect that it affects Unity 2020.3.21f across the board.

**Comment by anthony-simetri** [comment] 2021-11-02 18:55
Ah. Thank you for looking into this.

**Comment by elbuhofantasma** [comment] 2021-11-02 20:08
I have looked into this issue as well and found that not every way (example: ARM Release) to build MRTK HoloLens 2 apps are effected by this issue. Below you can find the results of my investigation and the effected architectures. 

**Architectures WITH the flashing issue**
Unity 2020.3.21f1 
_ARM64 Release_
_ARM64 Master_
_ARM Master_

**Architectures WITHOUT the flashing issue**
Unity 2020.3.21f1
_ARM64 Debug_
_ARM Release_
_ARM Debug_

**Comment by polar-kev** [comment] 2021-11-08 20:18
I'm going to keep this bug open until there is a fix published.

**Comment by polar-kev** [comment] 2021-11-08 20:41
@elbuhofantasma reported today that this is still being seen in HoloeLens 2 ARM64 releases on Unity 2020.3.22f.

**Comment by anthony-simetri** [comment] 2021-11-09 00:04
> @elbuhofantasma reported today that this is still being seen in HoloeLens 2 ARM64 releases on Unity 2020.3.22f.

The release notes on Unity 2020.3.22f only note that this is a known bug. It seems they have not fixed it yet.

**Comment by polar-kev** [comment] 2021-11-15 20:19
The fix for this should be in Unity 2020.3.24 that is targeting Dec 1st.

**Comment by polar-kev** [comment] 2021-11-19 19:47
Unity has confirmed the fix will be in the 2020.3.24 release in this post here,
https://forum.unity.com/threads/flickering-issue-affecting-hololens-2-projects-in-2020-3-21-and-later.1200199/

**Comment by elbuhofantasma** [comment] 2021-12-03 20:54
I am closing this issue, but keeping it pinned since these versions will always be susceptible to this issue. On 12/2/2021 Unity released Unity 2020.3.24f1. I can confirm that this version fixes the screen flashing problem noted in this issue.

We are now recommending Unity 2020.3.24f1 for the latest MRTK supported Unity 2020 LTS.

**Closed by elbuhofantasma** 2021-12-03 20:54 UTC
Labels: External
