### ISSUE TITLE
Disabling Hand Mesh Visualization Modes does not disable Oculus hand mesh

### ISSUE THREAD

**Issue by A1igator** [microsoft/MixedRealityToolkit-Unity#8793] opened 2020-10-13 23:02 UTC
## Describe the bug

I can not disable Oculus hand mesh and use MRTK. Hand Mesh Visualization Modes doesn't disable it, and disabling it manually in the OVRCameraRig seems to just break MRTK with no error.

## To reproduce

1. Go to MixedRealityToolkit config
2. Click on Input
3. Scroll down to Hand Tracking
4. Click on Hand Tracking
5. Set Hand Mesh Visualization Modes to nothing
6. Press play and notice Oculus mesh stays

## Expected behavior

Oculus mesh would disappear

## Your setup

- Unity Version 2019.4.12
- MRTK Version 2.5.0

## Target platform

- Oculus Quest

**Comment by RogPodge** [comment] 2021-05-13 00:25
@imsumittyagi this is when using articulated hand tracking correct? The hand mesh that appears while using the controllers is different (though we can have that visualization be disabled if it's a source of confusion)

I am not able to reproduce this with our current MRTK.

**Comment by imsumittyagi** [comment] 2021-05-13 04:18
@RogPodge I am disabling and enabling it via the script

` MixedRealityInputSystemProfile inputSystemProfile = CoreServices.InputSystem?.InputSystemProfile;
        if (inputSystemProfile == null)
        {
            return;
        }

        MixedRealityHandTrackingProfile handTrackingProfile = inputSystemProfile.HandTrackingProfile;
        if (handTrackingProfile != null)
        {
            handTrackingProfile.EnableHandMeshVisualization = false;
        }`
        
        It was working on MRTK 2.6.0 but not MRTK 2,7.0 Preview

**Comment by RogPodge** [comment] 2021-05-13 17:29
Can you provide a video @imsumittyagi, I can't seem to reproduce this

**Comment by imsumittyagi** [comment] 2021-05-15 08:24
@RogPodge Here is the video and project 
https://user-images.githubusercontent.com/20392525/118353239-038f5380-b583-11eb-821b-cdb236f8e6c7.mp4
https://www.dropbox.com/s/tzb4kk60c7j10wy/MRTKDemo.zip?dl=0

**Comment by RogPodge** [comment] 2021-05-15 19:21
Oh yeah, those hands are actually the "Avatar Hands" from the Oculus Controllers, and not the "hand mesh", which refers to the visuals that are displayed when using articulated hands.

![image](https://user-images.githubusercontent.com/39840334/118375603-8e6a5100-b577-11eb-9747-a8d06ef85009.png)

We will work towards adding a setting to dynamically turn motion controller visualizations on/off, and make it distinction between "articulated hand mesh" and "controller visualizations" more clear. We'll close this specific issue though, new issue is tracked here: #9823

**Closed by RogPodge** 2021-05-15 19:21 UTC
Labels: Bug, Oculus
