### ISSUE TITLE
Duplicated raycast layer mask for the gaze provider

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5924] opened 2019-09-10 19:45 UTC
In order to change the raycast layer mask of the gaze provider, you need to update two locations:

1. The GazeProvider monobehavior on the MixedRealityPlaySpace -> Camera
2. The pointer layer mask on the input pointer configuration in the MRTK input profile.

It *feels* like this should be a single thing to update.

**Comment by wiwei** [comment] 2019-09-10 19:45
@keveleigh @davidkline-ms in case there's some historical context for why they are separate

**Comment by keveleigh** [comment] 2019-09-10 20:57
Basically, it exists if you want the head ray to be able to target or report focus on (or ignore) specific objects that other pointers should target.

All controller pointers have this option:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/89fb1f941856963b0012c6755ddaf61a94d4b999/Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs#L349

Which also leads me to realizing the comment on https://github.com/microsoft/MixedRealityToolkit-Unity/blob/89fb1f941856963b0012c6755ddaf61a94d4b999/Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityPointerProfile.cs#L30 is incorrect, since it's used as a fallback for all pointers, not just gaze:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/89fb1f941856963b0012c6755ddaf61a94d4b999/Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs#L123

The profile one is the global layermask setting, and each pointer can override it as needed.

**Comment by lordlycastle** [comment] 2019-09-11 11:42
@keveleigh does the prioritization not function as intended? I've set it up as shown below but it's still choosing to put the gaze cursor on the spatial mesh rather than UI behind it.

I've also tried it other way around ie UI is element 2 and everything else is element 1.

![image](https://user-images.githubusercontent.com/11729541/64694419-84827780-d491-11e9-98e0-7de5de7a8005.png)

**Comment by keveleigh** [comment] 2019-09-11 15:36
@lordlycastle As far as I'm aware, it functions as intended!

Are the raycast masks set on the GazeProvider as well? Anything set there will override the global settings in the pointer profile.

**Comment by wiwei** [comment] 2019-09-11 21:30
@keveleigh I think there was some feedback that it wasn't working as expected unless you had both changed:

https://holodevelopers.slack.com/archives/C2H4HT858/p1568132784131400

At a minimum, there's probably some doc work we can do here (i.e. explain how to change the layers for the gaze stuff).

**Comment by lordlycastle** [comment] 2020-06-15 01:24
stale you face!

**Comment by lordlycastle** [comment] 2020-06-15 01:24
stale your face stalebot!

**Comment by RogPodge** [comment] 2022-04-08 23:55
Marking as fixed thanks to #10508 unifying things

**Closed by RogPodge** 2022-04-08 23:55 UTC
Labels: Bug, Input System - Gaze
