### ISSUE TITLE
Incompatibilities with Holotoolkit Sharing Service and IL2CPP?

### ISSUE THREAD

**Issue by derekfleming95** [Microsoft/MixedRealityToolkit-Unity#2531] opened 2018-08-01 03:47 UTC
## Overview
I deployed the SharingTest scene (part of the Holotoolkit examples), and I can't seem to get the Hololens to connect to the SharingService running on a computer on the same network. When I deploy using the .NET scripting backend it works fine, but IL2CPP doesn't. There are no error messages during the build, or debugging via Visual Studio. It does work in the editor, but not when deployed to the Hololens.

I have tried using older versions of the MRTK, old versions of Unity, newer versions of Unity, and all yielded the same results.

## Expected Behavior
Hololens connects to the SharingService.exe.

## Actual Behavior
Hololens doesn't connect to the SharingService.exe.

## Steps to reproduce
Setup a blank project.
Import the Holotoolkit and Holotoolkit-Examples.
Apply project settings, capabilities, etc.
Change scripting backend to IL2CPP (in Build Window of MRTK).
Open the scene Holotoolkit-Examples/Sharing/SharingService/Scenes/SharingTest.
Launch the SharingService.exe (MRTK > Sharing > Launch Sharing Service).
Change the Sharing script's IP address to your server's IP Address.
Build & Deploy to Hololens.

## Unity Editor Version
Currently: 2017.4.4f1
Have tried with:
- 2017.4.7f1
- 2017.4.8f1
- 2017.3.1f1

## Mixed Reality Toolkit Release Version
Currently: 2017.4.0.0
Have tried with:
- 2017.2.1.4

**Comment by keveleigh** [comment] 2018-08-02 19:56
I think it's possible this is related to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1784.

Somebody else on my team hit this today, unrelated to the Toolkit. It appears that, by default, the .NET backend assumes `CallingConvention.Cdecl` when accessing DLLs. IL2CPP instead assumes `CallingConvention.StdCall`, so we'll need to explicitly declare this in our `DLLImport`s.

**Comment by derekfleming95** [comment] 2018-08-07 09:51
I don't have any of my own scripts. Should I be going through the relevant MRTK scripts and updating all of the `DLLImport`s to get it to work correctly?

**Comment by markgrossnickle** [comment] 2018-10-10 21:51
I am unable to get sharing to work on IL2CPP as well.

At first I received logs stating that we need to add MonoPInvokeCallback to our callbacks. That is pretty straight forward to work around.
https://answers.unity.com/questions/1229036/callbacks-from-c-to-c-are-not-working-in-540f3.html
I just modified the files directly since I am not very familiar with swig but it appears that should be fairly easy to edit as well:
https://stackoverflow.com/questions/37448882/unmanaged-c-sharp-calls-to-a-static-library

Now I no longer get that exception but I do get an exception saying the callbacks need to be static. A majority of the callbacks I am seeing in these listener files are not static and not easily changed to static manually.  Perhaps it is another simple edit to Swig but I'm not well versed there.  

A this point its not worth the effort for me so I'm going to focus on UNET and Photon but I wanted to leave my findings in case someone else wanted to pick up the cause. :)

**Comment by wiwei** [comment] 2019-04-11 20:13
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:13 UTC
Labels: IL2CPP, Legacy (HoloToolkit), Sharing / Networking

**Comment by fcagnetta** [comment] 2019-04-15 13:15
Still not working here
