### ISSUE TITLE
Failed to resolve assembly UniversalApiContract

### ISSUE THREAD

**Issue by Maikyl** [microsoft/MixedRealityToolkit-Unity#6117] opened 2019-09-27 12:02 UTC
Since upgrading from HoloToolkit to Mixed Reality Toolkit, I am unable to build for hololens. The error unity throws is:

```
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Burst.Compiler.IL.AssemblyLoader.Resolve(AssemblyNameReference name)
   at Burst.Bcl.BclApp.LoadAllAssemblyReferences(AssemblyDefinition asmDef, Dictionary2 visited)
   at Burst.Bcl.BclApp.LoadAllAssemblyReferences(AssemblyDefinition asmDef, Dictionary2 visited)
   at Burst.Bcl.BclApp.FindExecuteMethods(List`1 rootAssemblyPaths)
   at Burst.Bcl.BclApp.GetMethodsToCompile()
   at Burst.Bcl.Program.Main(String[] args)
```

The scene itself is mostly empty, containing only the required gameobjects for MRTK (Directional Light, MixedRealityToolkit and MixedRealityPlayspace, which has the Main Camera as child.)

Unity version 2019.2.6, SDK version 10.0.18362.0

Building a test scene from the MRTK works fine, so it must have something to do with our project.

**Comment by keveleigh** [comment] 2019-09-27 15:57
This looks like the same call stack reported in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6098. Are you on the latest version of Burst, where [it seems like this should be fixed](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6098#issuecomment-535688409) (and it'd be good to know if [you start hitting this after](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6098#issuecomment-535707048) as well)?

**Comment by Maikyl** [comment] 2019-09-27 18:00
I'm at home right now, but I will get back to you first thing Monday morning.

**Comment by Maikyl** [comment] 2019-10-01 08:46
After updating Burst to 1.2.0-preview.5, I am indeed getting the second error in that issue report.
`Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Windows.Foundation.FoundationContract, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Burst.Compiler.IL.AssemblyLoader.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Burst.Bcl.BclApp.FindExecuteMethods(List`1 rootAssemblyPaths)
   at Burst.Bcl.BclApp.GetMethodsToCompileBeforeDynamicDispatch()
   at Burst.Bcl.BclApp.GetMethodsToCompile()
   at Burst.Bcl.Program.Main(String[] args)`

**Comment by keveleigh** [comment] 2019-10-01 16:50
Thanks for the update! I'm going to close this as a duplicate of #6098, which has some additional discussion and a Unity dev on the thread. Please add any additional info you'd like over there.

**Closed by keveleigh** 2019-10-01 16:50 UTC
