### ISSUE TITLE
Object Manupulator failing to apply Release Physics Behavior

### ISSUE THREAD

**Issue by Kaimbelic** [microsoft/MixedRealityToolkit-Unity#9690] opened 2021-04-20 18:22 UTC
The Bug:

When using the Object Manipulator with Spatial Awareness System enabled in the toolkit, objects when release do not keep released physics behavior. 

1. Create a new scene 
2. Add the MRTK to the scene
3. Create an object, I use a sphere
4. Add Component Rigidbody
5. Add Component Object Manipulator
6. Select the MRTK object in the Hierarchy
7. Create a clone of  "DefaultHololens2ConfigurationProfile"
8. Enable Spatial Awareness System on the new cloned profile
9. Build for ARM64
10. Deploy to Hololens2
11. Grab the sphere
12. While sphere is in motion release
13. The sphere will fall straight to the floor

Expected behavior:

When using the Object Manipulator without Spatial Awareness the sphere will maintain the correct physic when released during motion. The Expected behavior with Spatial Awareness enabled should be the same. When objects are released during motion they should maintain the physics when enabled.

The setup:

- Unity Version 2019.4.16f1
- MRTK Version v2.6.1

Target platform:

- HoloLens 2

**Comment by RogPodge** [comment] 2021-04-20 23:47
Can you provide a video of the unexpected behavior, it will help us replicate and better understand the issue.

**Comment by Kaimbelic** [comment] 2021-04-22 14:59
> 
> 
> Can you provide a video of the unexpected behavior, it will help us replicate and better understand the issue.

Here is a simple video of a cube I am trying to "Throw".
https://youtu.be/x2DXkOuZhIg

If I do this same thing but without the Spatial Awareness System enabled it will have the parabolic shape of falling after being thrown.

**Comment by RogPodge** [comment] 2021-04-23 22:48
We'll monitor and take a look at this. Thanks for discovering it!

**Comment by RogPodge** [comment] 2021-04-29 21:50
Update, got a repro, diving deeper now. Thanks for your patience and your help!

**Comment by RogPodge** [comment] 2021-04-30 01:25
We've identified the velocity issue to be due to the XRSDK input sources not currently tracking the devices velocity for articulated hands, and we're fairly sure this is not restricted to just when spatial mapping is on (though it makes sense that it was discovered in this manner, given hololens is the primary use case for articulated hands).

We're looking into a few solutions, such as fixing the XRSDK side of things and making the Object Manipulator not snap match the controller's velocity on release.

Just to clarify @Kaimbelic you were using the XRSDK pipeline right? Just want to check that we're targetting the right areas

**Comment by Kaimbelic** [comment] 2021-04-30 20:22
I am not sure if I am using the XRSDK pipeline. What would be the best way to confirm this?

**Comment by RogPodge** [comment] 2021-04-30 20:27
![image](https://user-images.githubusercontent.com/39840334/116750722-be322a00-a9b7-11eb-8c33-472a32f9cb1c.png)
 go to this part of the project settings and see if you have the following

**Comment by Kaimbelic** [comment] 2021-04-30 21:24
The project is not using the XR Plug-in portion. It is still located under the Player tab.

![image](https://user-images.githubusercontent.com/38118010/116755727-7bc91700-a9d0-11eb-8fd4-088757853b4f.png)

**Comment by RogPodge** [comment] 2021-04-30 21:31
ah thanks, good to know!

Our current bugfix is for XRSDK, when it goes through I'd recommend moving to that platform, since it's going to be the go-to one in the future: 

https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk

Though we haven't tested this on the Legacy XR Pipeline, our fix should address most of the incongruous behavior: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9733

**Closed** 2021-04-30 23:25 UTC
Labels: Bug

**Comment by Kaimbelic** [comment] 2021-05-12 15:18
Can confirm this fix works on the Legacy pipeline as well.
Thank you!
