### ISSUE TITLE
MixedRealityCanvasInspector crash

### ISSUE THREAD

**Issue by cellarmation** [microsoft/MixedRealityToolkit-Unity#8143] opened 2020-07-02 19:12 UTC
## Describe the bug

MRTK includes a custom inspector for the inbuilt canvas component. This can crash in some situations stopping the rendering of the canvas editor UI before it is complete making it unuseable. This seems to occur when there are orphened TMP_SubMeshUI components under the canvas. This exception is also shown in the console whenever you try to look at the canvas component:

ArgumentNullException: Value cannot be null.
Parameter name: source
UnityEngine.Material..ctor (UnityEngine.Material source) (at C:/buildslave/unity/build/Runtime/Export/Shader.bindings.cs:109)
TMPro.TMP_SubMeshUI.CreateMaterialInstance (UnityEngine.Material source) (at Library/PackageCache/com.unity.textmeshpro@1.4.1/Scripts/Runtime/TMP_SubMeshUI.cs:758)
TMPro.TMP_SubMeshUI.GetMaterial (UnityEngine.Material mat) (at Library/PackageCache/com.unity.textmeshpro@1.4.1/Scripts/Runtime/TMP_SubMeshUI.cs:737)
TMPro.TMP_SubMeshUI.get_material () (at Library/PackageCache/com.unity.textmeshpro@1.4.1/Scripts/Runtime/TMP_SubMeshUI.cs:59)
Microsoft.MixedReality.Toolkit.Input.MixedRealityCanvasInspector.GetGraphicsWhichRequireScaleMeshEffect (UnityEngine.Object[] targets) (at Assets/MRTK/Services/InputSystem/Editor/MixedRealityCanvasInspector.cs:171)
Microsoft.MixedReality.Toolkit.Input.MixedRealityCanvasInspector.OnInspectorGUI () (at Assets/MRTK/Services/InputSystem/Editor/MixedRealityCanvasInspector.cs:63)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1647)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

## To reproduce

1) Create a new blank Unity project.
2) Import Microsoft.MixedReality.Toolkit.Unity.Foundation.2.4.0.unitypackage (don't bother doing any of the settings stuff).
3) Import TextMeshPro using Window -> TextMeshPro -> Import TMP Pro Essential Resources.
4) Right click in the scene and select UI > Text - TextMeshPro, this creates a TextMeshProUGUI component on an object as a child of an object with a canvas.
5) Set the font asset to the MRTK provided font "segoeui".
6) Set the text of the TextMeshProUGUI component to be something that uses a character not in the font asset e.g. "©".
7) Delete the TextMeshProUGUI component.
8) Click onto the "Canvas" GameObject that has the Canvas component on it.
9) The MRTK provided custom editor for the Canvas component is now broken and an exception of "ArgumentNullException: Value cannot be null." is generated.

## Expected behavior

The canvas editor should be useable in this situation, just like it would be if MRTK wasn't included in the project.

## Screenshots
A canvas component without a TMP_SubMeshUI under it:
![MixedRealityCanvasInspectorCrash](https://user-images.githubusercontent.com/3090483/86400167-0c937100-bca0-11ea-94cd-d5ff0e082d90.png)

A canvas component with a TMP_SubMeshUI under it:
![MixedRealityCanvasInspectorCrash2](https://user-images.githubusercontent.com/3090483/86400171-0dc49e00-bca0-11ea-83c2-dbbf51128674.png)

## Your setup (please complete the following information)

- Unity Version 2018.4.18f1
- MRTK Version 2.4.0

## Target platform (please complete the following information)

- Editor

## Additional context

This appears to be due to MRTK using a custom inspector for Canvas components. This is done by MixedRealityCanvasInspector.cs, which uses the method GetGraphicsWhichRequireScaleMeshEffect() to get all the components in the children looking for Graphic components and accesses the material property of the graphics. It seems that TextMeshPro generated TMP_SubMeshUI component that are orphened fire this exception if you try to use its material property. This causes the custom inspector to crash half way through drawing the UI making it unusable. If there was no custom inspector the canvas component would still be usable in this situation. I guess the root of this bug is in TextMeshPro but I am reporting it here as the custom inspector probably needs to be more defensive, this is a relatively easy state for someone to get into and would not normally fail so badly.

**Comment by cellarmation** [comment] 2020-07-02 20:50
I have created a [thread ](https://forum.unity.com/threads/exception-thrown-from-the-material-property-of-orphaned-tmp_submeshui-scripts.924389/)on the Unity forums about the underlying TextMeshPro bug.

**Comment by keveleigh** [comment] 2020-07-13 22:34
I wonder if using `.sharedMaterial` here will fix this, since it shouldn't try to create a new material, which is what appears to be the underlying issue.

**Comment by keveleigh** [comment] 2020-08-19 21:35
My previous suggestion of `.sharedMaterial` won't work, becuase `Graphic`s don't actually have that!

Otherwise, I haven't been able to repro this anymore, after the latest updates to the TMPro package. Are you still seeing it @cellarmation?

**Comment by polar-kev** [comment] 2021-08-11 17:59
Hey @cellarmation, we haven't been able to reproduce this so I'm going to close this issue.

**Closed by polar-kev** 2021-08-11 17:59 UTC
Labels: Bug
