### ISSUE TITLE
Hololens clicker not working

### ISSUE THREAD

**Issue by Kartik99999** [microsoft/MixedRealityToolkit-Unity#5397] opened 2019-07-21 04:52 UTC
## Overview
Clicker not working with interactable and other scripts also
## Expected Behavior
Should select or click on the gazed object
## Actual Behavior
Just show a white line when clicked and nothing get selected or clicked. Also deployed to device that is on HoloLens
## Unity Editor Version
2018.4.1
## Mixed Reality Toolkit Release Version
Microsoft Mixed Reality Toolkit v2.0.0 RC2.1

**Comment by keveleigh** [comment] 2019-07-22 20:35
This should be fixed in #5402! Please take a look, if you get a chance.

**Comment by Yoyozilla** [comment] 2019-07-24 03:16
Closing as this should be fixed. please reopen if issues persist.

**Comment by iotMice** [comment] 2019-08-31 08:40
How can I detect the clicker input. I am getting white line in the hololense after clicking from it,
Please help ASAP

**Comment by Kartik99999** [comment] 2019-09-10 06:05
> How can I detect the clicker input. I am getting white line in the hololense after clicking from it,
> Please help ASAP

You must be using MRTK. Use the latest source code of MRTK and make sure that you install the application on the HoloLens. I am building for HoloLens 1 and MRTK don't support HoloLens 1 completely so it's better to use HoloToolkit to build for HoloLens 1

**Comment by iotMice** [comment] 2019-09-10 07:40
Thanks. I think I have figured it out using  InteractionManager_InteractionSourcePressed(InteractionSourcePressedEventArgs args) method rather than using mrtk for controllers

**Comment by keveleigh** [comment] 2019-09-10 15:01
We definitely support HL1 and the clicker with MRTK!

@iotMice Which version of MRTK are you using? I made some updates in the linked PR above (#5402) to better support the clicker. Are you still seeing the white line with the GA 2.0.0 version?

@Kartik99999, what do you mean by the MRTK not supporting HoloLens 1 completely? Please file issues whenever you run into something unexpected.

**Comment by Kartik99999** [comment] 2019-09-10 18:26
> We definitely support HL1 and the clicker with MRTK!
> 
> @iotMice Which version of MRTK are you using? I made some updates in the linked PR above (#5402) to better support the clicker. Are you still seeing the white line with the GA 2.0.0 version?
> 
> @Kartik99999, what do you mean by the MRTK not supporting HoloLens 1 completely? Please file issues whenever you run into something unexpected.

HoloToolkit supported placing anchors in the surroundings. I can't find that in MRTK. Is it available now as it has been 20 days?

**Comment by keveleigh** [comment] 2019-09-10 20:42
>HoloToolkit supported placing anchors in the surroundings. I can't find that in MRTK.

@Kartik99999 We do have the `WorldAnchorManager` in MRTK, which should currently function similarly to the one in HoloToolkit: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/WorldAnchorManager.cs

We're still working on an improved anchor management system as well, hence why that script is currently in the `Experimental` folder.

**Comment by iotMice** [comment] 2019-09-12 03:01
@keveleigh I am using mrtk 2.0.  I am able to detect the click events as mentioned . But I am facing one issue, which is white dotted line comes after I make my first click, and it remains there at the screen.How should I solve it

**Comment by iotMice** [comment] 2019-09-24 06:07
@keveleigh is there any update on the same?

**Comment by davidkline-ms** [comment] 2019-10-04 20:22
I am not able to reproduce this on the latest 2.1.0 code. The clicker selects and interacts without a pointing ray (as expected)

**Closed by davidkline-ms** 2019-10-04 20:23 UTC
Labels: HoloLens, Investigate

**Comment by iotMice** [comment] 2019-11-06 07:19
@davidkline-ms Can you tell me how do you add clicker functionality in any custom application made in Unity by importing Hololens SDK. Which interface are you using to map the click events.

Thanks and Regards

**Comment by marcfischer123467** [comment] 2019-11-07 18:55
Hi,
How can I use the clicker with mrtk 2.1 in unity 2019.2.5f1. It doesn't seem to recognize it as a GGV Hand. I'm not very experienced with HoloLens development but I would like to integrate this tool into my app and would very much appreciate some help.

**Comment by marcfischer123467** [comment] 2019-11-07 19:08
Does the clicker work on Holographic Emulation?
