### ISSUE TITLE
Follow me is not working on Arm64, Unity 2019.3.10f1

### ISSUE THREAD

**Issue by kianng** [microsoft/MixedRealityToolkit-Unity#7912] opened 2020-05-19 17:54 UTC
## Describe the bug

In any pinned Slate window, when you select Follow me, the entire slate window will disappear from view.

## To reproduce

1. Go to 'Hand Interaction Example scene'
2. Click on 'Follow me button on Pan and Zoom Interaction window' or unPin the 'Toggle features' menu
3. Both windows will disappear. There are no ways to get it back either that I am aware off. Follow me on Edge browser works perfectly, either in Shell or in the Hand Interaction scene.

## Expected behavior

Follow me button should unpin the slate window, and started following me.

## Screenshots
![image](https://user-images.githubusercontent.com/32718380/82360508-5ceb9380-99be-11ea-8792-1f1a54fca7bf.png)
![image](https://user-images.githubusercontent.com/32718380/82360549-6aa11900-99be-11ea-8cbe-5c03bdc02ad7.png)

## Your setup (please complete the following information)

- Unity Version [2019.3.10f1]
- MRTK Version [v2.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment] 2020-05-19 17:57
Related to #7624

**Comment by wiwei** [comment] 2020-07-28 22:21
Closing this out as a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7624#issuecomment-665309866

**Closed by wiwei** 2020-07-28 22:21 UTC
Labels: Bug, Solvers
