### ISSUE TITLE
Toggle switches in InteractableExamples do not behave correctly

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#6178] opened 2019-10-02 19:19 UTC
## Describe the bug
When interacting with toggle buttons on the InteractionExamples scene the toggle switches do not behave correctly (see gif).

1. The visuals get  broken 
2. Near field interaction does not work as expected.

![togglebug](https://user-images.githubusercontent.com/17660747/66073859-cb9dde80-e50c-11e9-84ab-dfede8e5b5bd.gif)

## To reproduce

1. Launch the "InteractablesExample.scene" in unity editor
2. Use far field pointer to click on the toggle button. Works as expected.
3. Click again. The dot moves off and does not reset the button visual state.
4. Try to use near field interaction on the toggle button
5. The buttons respond to focus receive events and not click events for some reason (tested in editor only)

## Expected behavior

1. On second click of far field interaction the visual should go back to its original.
2. Near field interaction should either not work on these button or work correctly.. 

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.4f1]
- mrtk_dev branch

**Comment by Troy-Ferrell** [comment] 2019-10-02 19:38
This is dupe of #6169 and #6176

**Comment by ritijain** [comment] 2019-10-02 19:44
@Troy-Ferrell  - part  1 if this bug is fixing the theme. i don't believe this is a dup. Look at the gif.

**Comment by julenka** [comment] 2019-10-02 22:49
Marking this is a release blocker because it is a regression from 2.0

**Comment by julenka** [comment] 2019-10-02 23:20
> The buttons respond to focus receive events and not click events for some reason (tested in editor only)

Looking at your video and trying myself, I actually thing the buttons are responding to touch events -- the button toggles when the finger enters the button region from any direction, since Interactable has no logic to filter out whether presses should be from the front. So I think that behavior is expected.

**Comment by Troy-Ferrell** [comment] 2019-10-02 23:30
Coordinate with @julenka and she is going to put in the fix. This and I believe #6187 are the same bug.

In the original version of code, it would create all themes for all dimensions and then just select the appropriate list for the current dimension.

I accidently re-wrote that to recreate teh list every dimension

**Closed** 2019-10-03 20:25 UTC
Labels: Bug, Release Blocker, UX Controls - Interactable
