### ISSUE TITLE
Fix Bounding Box/Bound Controls to not flicker

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#7935] opened 2020-05-20 22:07 UTC
## Describe the bug
Currently the bounding box which shows handles based on proximity can flicker when it is right at the edge of the near interaction radius. We believe that this happens because when the hand gets into _near interaction range_ those bounds shrink and disappear, which causes them to leave the _near interaction range_, which then causes the pointer to no longer have the "isNearObject" flag set, which causes the bounds to appear again, resulting in a loop of flickering behavior.

@thalbern is this behavior still present with the new bounds controls component? I know we are looking to deprecate the bounding box

## To reproduce
![flicker](https://user-images.githubusercontent.com/39840334/82502093-4111eb80-9aab-11ea-9862-d2616d7b826b.gif)

## Expected behavior
The bounding box should not flicker when the hand approaches it

## Screenshots
See above.

## Your setup (please complete the following information)
Unity Version 2018.4.20f1
MRTK Version 2.4

## Target platform (please complete the following information)
Unity Editor
HoloLens 2

**Comment by thalbern** [comment] 2020-05-21 09:09
duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6220

**Closed** 2020-07-09 20:04 UTC
Labels: Bug
