### ISSUE TITLE
Button labels are misaligned in HandInteractionExample

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#5600] opened 2019-08-12 14:20 UTC
## Describe the bug

The text in the buttons in HandInteractionExample look misplaced. See Screenshot:
![image](https://user-images.githubusercontent.com/36998103/62871945-5552dc00-bd14-11e9-89e1-d5d889016f9e.png)

## To reproduce

Open HandInteractionScene 
Observe misplaced text in Editor
or
Press Play and observe misplaced text in WMR headset

## Expected behavior

Text should be centered in the button

## Your Setup (please complete the following information)

- Stabilization v2.0.0
used latest package from 08-10

## Target Platform (please complete the following information)

- Unity Editor
- WMR immersive

**Comment by thalbern** [comment] 2019-08-12 15:13
![image](https://user-images.githubusercontent.com/36998103/62876079-145ec580-bd1c-11e9-8840-8dacc8fd05cc.png)
another screenshot from the bounding box example

**Comment by cre8ivepark** [comment] 2019-08-12 19:09
I also have experienced this when I pull/switch branch. Deleting the Library folder and restarting Unity resolved the issue. The issue is TextMesh Pro loses its text alignment property (center) and reverts back to default 'left' alignment. Fresh import of the MRTK release package also does not show this symptom.

**Comment by julenka** [comment] 2019-08-12 21:21
Closing as not repro based on Yoon's comments. If people follow upgrade instructions (delete Library folder first), they will not hit this.

**Comment by cre8ivepark** [comment] 2019-08-12 22:26
Found proper solution. Upgrading TextMesh Pro to 1.4.1 resolves the issue. 
![2019-08-12 15_24_38-](https://user-images.githubusercontent.com/13754172/62902791-8ed81700-bd15-11e9-84ee-fce17725e1ea.png)

**Comment by cre8ivepark** [comment] 2019-08-12 22:41
@julenka @thalbern Found the clear solution. Updated manifest file to use the latest version of TextMesh Pro. #5619

**Comment by cre8ivepark** [comment] 2019-08-13 05:42
Fixed with #5619

**Closed by cre8ivepark** 2019-08-13 05:42 UTC
Labels: 4 - In Review, Bug, GA Blocker

**Comment by thalbern** [comment] 2019-08-14 11:10
thanks for looking into it Yoon! 
(just because it was mentioned before, I didn't upgrade a package. i was just starting a project from scratch and importing our latest package)
