### ISSUE TITLE
Unable to connect to Holographic Remoting Player With OpenXR in MRTK 2.6 

### ISSUE THREAD

**Issue by dilmerv** [microsoft/MixedRealityToolkit-Unity#9465] opened 2021-03-08 19:41 UTC
I've been trying to demo some of the new MRTK 2.6 features with OpenXR but it doesn't matter what I do I can't get the new OpenXR Holographic Editor Remoting feature set to connect.

I've verified that I can connect to my HoloLens2 with the Legacy XR so that works great, also I can get to it with Microsoft Hololens App on my PC as well as the portal via IP from my PC.

## OpenXR Feature Set Configuration:
![image](https://user-images.githubusercontent.com/1216121/110371815-b9ca4000-800a-11eb-9f8e-9fa198ae0c39.png)

## Connection Error
![image](https://user-images.githubusercontent.com/1216121/110372022-0150cc00-800b-11eb-9626-ed42ef8180e3.png)

## Connectivity with Windows Device Portal
![image](https://user-images.githubusercontent.com/1216121/110372217-41b04a00-800b-11eb-95a8-2ae2e0bb7991.png)

## Your setup (please complete the following information)

- Unity Version 2020.2.3f1
- MRTK Version 2.6
```
"com.microsoft.mixedreality.openxr": "file:MixedReality\/com.microsoft.mixedreality.openxr-0.1.4.tgz",
"com.microsoft.mixedreality.toolkit.examples": "file:MixedReality\/com.microsoft.mixedreality.toolkit.examples-2.6.0.tgz",
"com.microsoft.mixedreality.toolkit.extensions": "file:MixedReality\/com.microsoft.mixedreality.toolkit.extensions-2.6.0.tgz",
"com.microsoft.mixedreality.toolkit.foundation": "file:MixedReality\/com.microsoft.mixedreality.toolkit.foundation-2.6.0.tgz",
"com.microsoft.mixedreality.toolkit.standardassets": "file:MixedReality\/com.microsoft.mixedreality.toolkit.standardassets-2.6.0.tgz",
"com.microsoft.mixedreality.toolkit.tools": "file:MixedReality\/com.microsoft.mixedreality.toolkit.tools-2.6.0.tgz",
```

## Target platform (please complete the following information)
- HoloLens 2 OpenXR

## Additional context

I also tried deploying to the device and OpenXR MRTK worked ok however I couldn't see my hands at all with the handInteractionExamples scene, it also didn't react to my hands so something is clearly not working.

**Comment by polar-kev** [comment] 2021-03-08 19:57
@dilmerv regarding the handInteractionExamples scene, you'll need to update your profiles to OpenXR. See this page for the specific OpenXR profiles to use. https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk#configuring-mrtk-for-the-xr-sdk-pipeline

**Comment by polar-kev** [comment] 2021-03-08 20:02
@dilmerv, There is currently a Unity bug with Holographic app remoting where it doesn't work with Unity's XR SDK. It looks like we missed this one in the known issues section of our release notes. Thanks for the call out.

**Comment by keveleigh** [comment] 2021-03-08 20:03
I'll also log the remoting issue with the MR OpenXR Plugin team. I've sometimes seen that if I let Unity spin for a bit ("cannot establish a connection"..."restarting OpenXR") it'll eventually connect, but not always.

@polar-kev This is editor remoting for OpenXR, so a slightly different scenario than app remoting with Windows XR plugin.

**Comment by dilmerv** [comment] 2021-03-08 20:56
Thanks @polar-kev and @keveleigh I appreciate the feedback and yes it connects once in a while but it is more times when it fails than that it succeeds. I will also try the profile suggestions this afternoon and get back to you guys.

Thanks a lot for the quick responses.

**Comment by dilmerv** [comment] 2021-03-08 22:16
ok I tried your suggestion but I do remember just using "DefaultOpenXRConfigurationProfile" as suggested in the documentation, then today I tried to clone that and manually settings the profiles as shown below:

![image](https://user-images.githubusercontent.com/1216121/110386146-2bab8500-801d-11eb-8fdf-0a678ebc1939.png)

![image](https://user-images.githubusercontent.com/1216121/110386185-38c87400-801d-11eb-96ed-72210676a6e8.png)

![image](https://user-images.githubusercontent.com/1216121/110386370-6c0b0300-801d-11eb-893d-cff0432de5fb.png)

![image](https://user-images.githubusercontent.com/1216121/110386599-bbe9ca00-801d-11eb-89be-4eecef181ef4.png)

But still no hands so there may be a different issue.

**Comment by keveleigh** [comment] 2021-03-08 22:29
@dilmerv Can you please double check the settings for UWP mentioned at https://docs.microsoft.com/windows/mixed-reality/develop/unity/openxr-getting-started#configuring-xr-plugin-management-for-openxr? It might also be worth looking under OpenXR -> Features and checking that the hand tracking features are checked there for UWP as well.

**Comment by dilmerv** [comment] 2021-03-08 23:07
@keveleigh they are all set but good suggestion :) see below and thanks !

![image](https://user-images.githubusercontent.com/1216121/110393677-39b2d300-8028-11eb-851d-d36c6780d295.png)

![image](https://user-images.githubusercontent.com/1216121/110393710-42a3a480-8028-11eb-998b-d20757eaea8d.png)

![image](https://user-images.githubusercontent.com/1216121/110393742-4f27fd00-8028-11eb-8049-dbd1b175f905.png)

![image](https://user-images.githubusercontent.com/1216121/110393775-5ea74600-8028-11eb-8b15-5845e0785148.png)

**Comment by keveleigh** [comment] 2021-03-08 23:11
Thanks for the screenshots! That definitely looks correct...

Oh! I just remembered, this was a regression I accidentally introduced in MRTK 2.6...fix is at https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9430. We should start work on a 2.6.1 hotfix soon @davidkline-ms

**Comment by keveleigh** [comment] 2021-03-08 23:12
I'm not sure if you can edit the tarball imported files in Library/PackageCache without Unity rewriting them, but that might be worth a try as a workaround until then

**Comment by dilmerv** [comment] 2021-03-08 23:28
@keveleigh I think I can hack it hehe I will try it thanks man !

**Comment by dilmerv** [comment] 2021-03-09 00:10
@keveleigh good news, I was able to modify the Packages files simply within Unity and double clicking on it, I know it will get overwritten later on but is ok for now, this actually works and I can see my hands now when I deploy to the device ! thanks a lot :) 

![image](https://user-images.githubusercontent.com/1216121/110398428-1b050a00-8031-11eb-8638-b611b919eeae.png)

**Comment by yl-msft** [comment] 2021-03-09 02:31
@dilmerv  we are contacting the remoting experts to see how to diagnose next step.  We will ping back here when we have more details on this issue.

**Comment by dilmerv** [comment] 2021-03-09 06:02
> @dilmerv  we are contacting the remoting experts to see how to diagnose next step.  We will ping back here when we have more details on this issue.

Sounds good thank you and looking forward to the results !

**Comment by keveleigh** [comment] 2021-04-27 18:10
@dilmerv The Mixed Reality OpenXR Plugin 0.9.3-preview.1 package that just shipped via the Feature Tool should have a fix for this issue! Please re-open if you're still hitting it after updating.

**Closed by keveleigh** 2021-04-27 18:10 UTC
Labels: Bug, External, OpenXR

**Comment by ProgrammingKiddo** [comment] 2023-04-18 11:58
I'm sorry for reopening such an old issue, but I feel like I might be experiencing the same symptoms described here.

A few weeks ago I wrote a post on the Discussions board ( #11429 ) inquiring about this topic in case it was just similar but unrelated to this issue. However I've since exhausted all other potential solutions I could find/think of (provided, they're not plenty) and I can't pinpoint the issue anywhere else, so I'm left with the conclusion that the issue I'm experiencing must be this very same ( #9465 ), possibly reintroduced unknowingly at some point?

I'm using **Unity 2021.3.20f1** ([as recommended](https://learn.microsoft.com/en-gb/windows/mixed-reality/develop/unity/known-issues)) and **MRTK 2.8.3**.
In my case the **target device** I'm trying to connect to a **HoloLens (Gen1)** (in case it's relevant).
**OpenXR version 1.7.2**. I have double-checked and all my settings are correct, inline with the ones shown in this issue. I can indeed connect with the Microsoft Hololens portal via wifi from my PC.

```{r}
    com.microsoft.mixedreality.openxr@file:C:\UnityProjects\IndomitusReader\Packages\MixedReality\com.microsoft.mixedreality.openxr-1.7.2.tgz
    com.microsoft.mixedreality.toolkit.examples@file:C:\UnityProjects\IndomitusReader\Packages\MixedReality\com.microsoft.mixedreality.toolkit.examples-2.8.3.tgz
    com.microsoft.mixedreality.toolkit.extensions@file:C:\UnityProjects\IndomitusReader\Packages\MixedReality\com.microsoft.mixedreality.toolkit.extensions-2.8.3.tgz
    com.microsoft.mixedreality.toolkit.foundation@file:C:\UnityProjects\IndomitusReader\Packages\MixedReality\com.microsoft.mixedreality.toolkit.foundation-2.8.3.tgz
    com.microsoft.mixedreality.toolkit.standardassets@file:C:\UnityProjects\IndomitusReader\Packages\MixedReality\com.microsoft.mixedreality.toolkit.standardassets-2.8.3.tgz
```

 So far the logs haven't really cleared why this is happening (or I haven't been able to at least), but this is what I've gathered:

```{log}
(Filename: Library/PackageCache/com.microsoft.mixedreality.openxr@d61f9e5c1f21/Runtime/Subsystems/AppRemotingSubsystem.cs Line: 473)

[XR] [MROpenXR][Info   ][11:20:17.914136][tid:4364] XrViewConfigurationSettings_OnXrSessionCreated SupportedViewConfigType=XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO SupportedReprojectionModesCount=0
[XR] [MROpenXR][Info   ][11:20:17.914205][tid:4364] OnSessionCreated GraphicsAPI=XR_TYPE_GRAPHICS_BINDING_D3D11_KHR sessionCreationResult=XR_SUCCESS AppName=IndomitusReader AppVersion=0.1 AppMode=PlayMode openXRRuntimeName=Microsoft Holographic AppRemoting Runtime openXRRuntimeVersion=2.8.1 APIVersion=1.0.25 PartA_PrivTags=33554432
[XR] [MROpenXR][Info   ][11:20:17.914302][tid:4364] RemoteSpeechProvider_RegisterSpeechProvider
[XR] [17252] [11:20:17.918][Verbose] Ignoring event type 1000065006
[XR] [MROpenXR][Info   ][11:20:17.918057][tid:4364] OpenXRContext_OnEvent_XrEventDataSessionStateChanged EventType=XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED session=2 sessionState=XR_SESSION_STATE_IDLE
[XR] [17252] [11:20:17.918][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_UNKNOWN->XR_SESSION_STATE_IDLE session=2 time=684872534245800
[XR] [MROpenXR][Info   ][11:20:17.918714][tid:4364] OpenXRContext_OnEvent_XrEventDataSessionStateChanged EventType=XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED session=2 sessionState=XR_SESSION_STATE_LOSS_PENDING
[XR] [17252] [11:20:17.918][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_IDLE->XR_SESSION_STATE_LOSS_PENDING session=2 time=684872534261800
[AppRemotingSubsystem] Cannot establish a connection to Holographic Remoting Player on the target with IP Address 192.168.137.72:8265.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
```
<img width="473" alt="Unity_2" src="https://user-images.githubusercontent.com/22998388/232770165-69a64306-a664-4f56-82de-3ef3a1294ba3.png">
<img width="736" alt="Unity_4" src="https://user-images.githubusercontent.com/22998388/232770170-33ae3c99-d906-4da4-ba91-93b112eda6ed.png">
<img width="839" alt="Features" src="https://user-images.githubusercontent.com/22998388/232770172-f9d921c6-a08d-44ed-8d7b-00d796865114.png">
<img width="560" alt="Settings_1" src="https://user-images.githubusercontent.com/22998388/232770175-636ae01d-1ab4-4f15-b8a8-9d56ca2219cd.png">
<img width="566" alt="Settings_2" src="https://user-images.githubusercontent.com/22998388/232770176-fed428d8-fc25-44e3-933e-7175ed4a9d26.png">
<img width="537" alt="Settings_3" src="https://user-images.githubusercontent.com/22998388/232770181-dc691e93-9630-401c-913b-94fbb399b5db.png">
