### ISSUE TITLE
Sharing Stage Discovery Client fails to find systems to connect to

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#493] opened 2017-01-31 18:06 UTC
When setting `AutoDiscoverServer == true` the Discovery Client fails to find server.

Repro Steps:

1. Open Sharing test scene.
2. Set `AutoDiscoverServer` to true on the sharing prefab.
3. Start `SharingService` from editor.
4. Observe that the client never connects.

**Comment by NeerajW** [comment] 2017-02-01 18:18
@alexdrenea any thoughts here?

**Comment by DrNeuroSurg** [comment] 2017-02-09 19:28
Any news here ?

**Comment by HodgsonSDAS** [comment] 2017-02-09 19:32
I think part of the issue is embedded into the sharing service binaries that come from the main [HoloToolkit](https://github.com/Microsoft/HoloToolkit) (which is written in C++).

I've been doing a lot of work trying to make sure everything is working again with the test scenes.
Unfortunately I haven't gotten this to work.

**Comment by yacuzo** [comment] 2017-02-14 15:03
I use the Holotoolkit library directly for sharing (not the scripts in this repo), and i have the same problem, so I made an issue at the Holotoolkit repo: https://github.com/Microsoft/HoloToolkit/issues/70.

**Comment by StephenHodgson** [comment] 2017-07-12 21:27
https://github.com/Microsoft/HoloToolkit/pull/106

**Comment by davidkline-ms** [comment] 2018-03-23 20:52
Should be fixed by #1670.

**Closed by davidkline-ms** 2018-03-23 20:52 UTC
Labels: Bug, Sharing
