### ISSUE TITLE
TransformScaleHandler does not work as expected

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5637] opened 2019-08-13 21:55 UTC
## Describe the bug

ScaleMinimum/Max have been deprecated and a TransformScaleHandler is now supposed to be added. If none is added, then one is added dynamically at start with the obsolete ScaleMin & Max values as the defaults. 

It's also very, very confusing to the user that ScaleMinimum and ScaleMaximum are still in the inspector view. There is no flag or indicator that these are deprecated. 

Furthermore, TransformScaleHandler seems a bit overkill for a monobehavior, when really it just needs Start(). Not sure why ScaleMin & Max was deprecated in favor of this? 

Furthermore, you can't reset the initialScale via code

![image](https://user-images.githubusercontent.com/25975362/62979803-a5e03d00-bdd9-11e9-93eb-d524651ef6e6.png)

![bb-scale](https://user-images.githubusercontent.com/25975362/62980007-3585eb80-bdda-11e9-8bf9-eaa2ab821e5f.gif)

## To reproduce

Select a BoundingBox GameObject (like one from handInteractionExamples)
Add TransformScaleHandler component with as-is properties
Run scene
Try to scale using handle
Notice scale jumps up to new minimum value that is not accurate

## Expected behavior
GameObject scales from it's current size

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version Stabilization

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by cre8ivepark** [comment] 2019-08-13 22:40
#5569 I think this was the same issue. When I assigned the object to the Target Transform, it properly worked. Do we have documentation on this **TrasnformScaleHandler** somewhere?

**Comment by julenka** [comment] 2019-09-18 17:13
Looks like the specific issue in expected behavior no longer repros, however there are several other feedback here. @Troy-Ferrell would you mind filing new bugs for the usability issues, if they are still a problem? Closing this as not repro for the behavior issue.

**Closed by julenka** 2019-09-18 17:13 UTC
Labels: Bug, UX Controls - Bounding Box
