### ISSUE TITLE
Pointers cannot be removed (but can be added!) from the Input System Profile; need to explicitly drill into the Pointer Profile

### ISSUE THREAD

**Issue by hendryems** [microsoft/MixedRealityToolkit-Unity#5707] opened 2019-08-17 01:13 UTC
## Describe the bug

I noticed that I wasn't able to remove pointers from the input profile directly (but I can add one!) because I cannot select any of them. I had to go into the pointer profile to do that 🤦‍♂️.

While the documentation does states that:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html

Its not intuitive because the editor UI gives all the visual ques that you can remove pointers.

## To reproduce

1. Go to the MRTK Profile
2. Click on Input
3. Scroll down to Pointers
4. See +|-. Clicking on + works to add a new pointer
5. Attempt to select an existing profile

## Expected behavior

Able to select pointer but can't.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

Documentation:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html

**Comment by Troy-Ferrell** [comment] 2019-08-19 16:30
Yes this is a known bug. Dupe of #5004

**Closed by Troy-Ferrell** 2019-08-19 16:30 UTC
Labels: Bug, MRW Cares
