### ISSUE TITLE
Windows XR Plugin 2.6.x broke XRSDK eye gaze

### ISSUE THREAD

**Issue by brandf** [microsoft/MixedRealityToolkit-Unity#9470] opened 2021-03-09 16:43 UTC
## Overview
It's not clear who/how I should file a but on the Windows XR Plugin package.  I realize it's not actually MRTK code, so feel free to triage this to the appropriate team (or over to Unity if they own this stuff).  Its all "Microsoft stuff" as far as I can tell...

The issue is that eye gaze has been regressed between Windows XR Plugin 2.5.2 and  Windows XR Plugin 2.6.0, and is still regressed in the latest version 2.6.1.

Specifically, in holographic remoting this use to return true, and now it returns false.
                        InputDevice.TryGetFeatureValue(WindowsMRUsages.EyeGazeAvailable, out var gazeAvailable)

As a side note, the api was always buggy and returned a Quaternion in the wrong coordinate system, however we were able to workaround for that by converting to a unity quaternion like so:

                        gazeRotation.Set(-gazeRotation.x, -gazeRotation.y, gazeRotation.z, gazeRotation.w);
                        gazeRotation = gazeRotation * Quaternion.Euler(0, 180, 0);

However, after upgrading to Windows XR Plugin 2.6.1, we can't even get the buggy eye gaze out of the XRSDK, so we're temporarily downgrading to 2.5.2 until you fix this bug.

## Expected behavior
TryGetFeatureValue(WindowsMRUsages.EyeGazeAvailable...) returns true on holographic remoting with HoloLens 2.
the gaze rotation has the workaround above already applied before returning from TryGetFeatureValue(WindowsMRUsages.EyeGazeRotation...)

## Actual behavior
TryGetFeatureValue(WindowsMRUsages.EyeGazeAvailable...) returns false on holographic remoting with HoloLens 2.

## Steps to reproduce
* Using latest Unity 2019.4 LTS, XR Plugin Management 4.0.1, and Windows XR Plugin 2.6.1
  * Gaze didn't work.
* Downgraded to Windows XR Plugin 2.5.2, rebooted unity
  * Gaze work.
* Upgraded to Windows XR Plugin 2.6.0, rebooted unity
  * Gaze doesn't work. (sanity check part 1)
* Downgraded to Windows XR Plugin 2.5.2, rebooted unity
  * Gaze works again (sanity check part 2)

## Unity editor version
2019.4.21f1

**Comment by brandf** [comment] 2021-03-09 16:50
this is related to another (still open) bug I filed about gaze:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8715

**Comment by keveleigh** [comment] 2021-03-09 17:36
>or over to Unity if they own this stuff

Unity owns this plug-in. Please file a bug from the Unity editor. I have insight into how it works and can help drive fixes back to them, but Unity prefers bug reports first.

Looking through the plug-in history, I don't see much that has changed regarding eye tracking since the initial implementation. There's one spot where they adjusted when to ask for gaze input permissions, but on the surface it looks like an okay change. I'll dig in

**Comment by keveleigh** [comment] 2021-03-09 17:38
@brandf Are you remoting or running on-device?

**Comment by keveleigh** [comment] 2021-03-09 17:40
>Specifically, in holographic remoting this use to return true, and now it returns false.

Just saw this line. Yeah, the change I mentioned before is exactly the cause of the issue you're seeing. The plug-in no longer tries to initialize eye gaze over remoting. I'll follow up with Unity.

**Comment by brandf** [comment] 2021-03-09 17:41
I think everyone I work with uses remoting almost exclusively throughout the day.  running on device takes a really long time to iterate because it requires building a player to see the results.  We typically just build a player once in a while to evaluate the 'real' experience, however the real device often goes down different code paths, so it's not 100% the same.

**Comment by brandf** [comment] 2021-03-09 22:12
it's in tracking space (i guess closer to world space) - so the same space as like XRSDK gives you controllers poses in.

fwiw, I don't use the position since we consider the origin the center eye camera, but I can confirm the rotation of the gaze is not relative to the HMD pose.

**Comment by brandf** [comment] 2021-03-09 22:14
Actually I just saw I have this comment about the position - which might be why we're ignoring it and only using the rotation of the gaze:


                        // The position seems to be local to the center eye or something, and is always just about zero...seems buggy, lets just use the center eye

**Comment by brandf** [comment] 2021-03-09 22:19
I also want to remind you of another issues related to this, that might be good to know if you're testing it.  

Even on the older Windows XR plugin where we were getting eye gaze while remoting, it only ever seems to work the first time you run in the editor after starting unity.  My whole team literally restarts unity every time they hit play to get gaze working again (still quicker than building a player).  

If you could fix this it would save everyone a lot of headache, and might even be faster for yourself while fixing the other issues.

Below is the code we're currently using to get gaze & workaround issues, but the Unity reboot issue still doesn't have a workaround so you can see how we're detecting it and telling the developer to reboot Unity manually.

The TLDR is that if you successfully get eye gaze rotation, but the rotation is consistently exactly identity, then you need to reboot Unity to get gaze working again over remoting.

            if (XRHMDDevice.InputDevice.TryGetFeatureValue(WindowsMRUsages.EyeGazeAvailable, out var gazeAvailable) && gazeAvailable)
            {
                if (XRHMDDevice.InputDevice.TryGetFeatureValue(WindowsMRUsages.EyeGazeRotation, out gazeRotation))
                {
                    if (gazeRotation != Quaternion.identity)
                    {
                        gotGaze = true;
                        // The position seems to be local to the center eye or something, and is always just about zero...seems buggy, lets just use the center eye
                        gazePosition = transform.parent.InverseTransformPoint(XRHMDDevice.CenterEye.transform.position);
                        }
                    }
                    else if (Application.isEditor && ++remotingBugCount > 100)
                    {
                        Debug.LogWarning("Gaze is disabled - Holographic Remoting has a bug and requires Unity reboot to work.");
                        remotingBugCount = 0;
                    }
                }
            }

**Comment by keveleigh** [comment] 2021-03-17 18:21
Update!

Unity has just merged fixes for:
1. Eye gaze position not in world space
2. Eye gaze rotation in wrong coordinate system
3. Eye gaze stopped working over remoting

I don't yet have an ETA on the next package drops, but these fixes are now in the pipeline.

>Even on the older Windows XR plugin where we were getting eye gaze while remoting, it only ever seems to work the first time you run in the editor after starting unity. 

I was unable to repro this issue when testing the above fixes. I'm not sure if something that changed with these fixes or has changed recently fixed things. I was also testing Unity 2021, so I wonder if this is something off with 2019.

**Comment by keveleigh** [comment] 2021-04-09 21:15
Windows XR Plugin 2.7.0 has just shipped for Unity 2019.4.24+. Eye gaze should be working over remoting again _and_ is now properly in an expected world coordinate system! Let me know if you run into any issues.

**Closed by keveleigh** 2021-04-09 21:15 UTC
Labels: External
