### ISSUE TITLE
Enable XR shows checked after unchecking

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1394] opened 2017-11-18 20:39 UTC
## Overview
There is inconsistent behavior in the Configure menu. The initial settings in the configure menu are presumably the most common default settings. For some settings, "Enable Sharing Services" for example, once you change them the value (checked or unchecked) retains the new value after you Apply the settings and then later return to the configure menu. 

However, for "Enable VR", if you uncheck the box and Apply, when you next return to the Configure menu it shows as checked, even though the Virtual Reality Supported checkbox (Player Settings | XR Settings) is still unchecked.

## Expected Behavior
Enable VR checkbox shows unchecked if you have unchecked it

## Actual Behavior
Enable VR checkbox shows checked even after unchecking

## Steps to reproduce
1.
Create new project. Select from menu: Mixed Reality Toolkit | Apply Mixed Reality Project Settings, 
Enable VR checkbox is checked by default
Click Apply

Check that in Edit | Project Settings | Player that XR Settings show s Virtual Reality Supported is checked and Virtual Reality SDKs shows Windows Mixed Reality

2.
Repeat process but now uncheck the Enable VR checkbox. Player XR Settings now shows Virtual Reality Unsupported is unchecked.

3.
Open menu: Mixed Reality Toolkit | Apply Mixed Reality Project Settings. Note that Enable VR checkbox shows as checked even though Player XR Settings is still unchecked.

## Unity Editor Version
2017.2.0p1-MRTP
## Mixed Reality Toolkit Release Version
master

**Comment by StephenHodgson** [comment] 2018-02-08 17:03
This was by design, but the menu could be better.

**Comment by wiwei** [comment] 2019-04-11 20:27
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:27 UTC
Labels: By Design, Enhancement
