### ISSUE TITLE
Windows Insider: Unity editor hangs in play mode when using UnityEngine.VR.WSA.Input.GestureRecognizer

### ISSUE THREAD

**Issue by markneville** [Microsoft/MixedRealityToolkit-Unity#464] opened 2017-01-18 00:03 UTC
Latest build version of InputManager.prefab causes Unity to hang.

Unity 5.50f3
Windows 10 

Cheers,
Mark

**Comment by HodgsonSDAS** [comment] 2017-01-18 13:55
I mark, can you provide us with a bit more details?

Were you able to pinpoint the issue with a debugger?

Do you have any reproduction steps?

**Comment by NeerajW** [comment] 2017-01-18 20:21
Looks like I could repro this with:
1. Import latest release asset package into Unity 5.5.0f3 project
2. Use the HoloLensCamera prefab
3. Create Managers object and child a InputManager prefab to it
4. Click Play in editor and observe hang. 

Working on more details.

**Comment by NeerajW** [comment] 2017-01-18 20:29
I remember this not being an issue when I checked in InputTapTest.unity scene. I am reinstalling Unity to see if it helps.

**Comment by NeerajW** [comment] 2017-01-18 21:52
@markneville are you on a Windows Insider Preview build? I could repro this issue only when I upgraded to a selfhost build.

**Comment by NeerajW** [comment] 2017-01-18 23:06
To unblock yourself in the editor consider disabling the GestureInput component under InputManager just when in the editor.

**Comment by markneville** [comment] 2017-01-19 22:04
@NeerajW Yes i'm on the Fast ring for the Windows Insider Preview build. Also the way you repro'ed the issue was exactly the same way I found the issue. I'll try disabling the GestureInput component to see if that helps.

**Comment by NeerajW** [comment] 2017-01-19 22:37
@markneville thanks for confirming. I have filed a Windows OS bug to track this issue and see where the real problem is.

**Comment by 3cst4sy** [comment] 2017-05-04 15:21
Hi, i run into the same issue. Disabling GestureInput helps to start the playmode, but that's not a fix.
Unity: 5.5.2f1 HoloToolkit 1.5.6
Any further informations?

**Comment by ujell** [comment] 2017-05-08 18:59
I started to have this problem since I reinstalled Windows 10 (version 1703). It seems like Windows or Unity bug since I can reproduce it without HoloToolkit; creating a new GestureRecognizer is freezing the editor even in an empty project (in HoloToolkit [this line](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/InputSources/GesturesInput.cs#L34)). I tried Unity 5.5.3p2 and 5.6, both had the issue and Unity log doesn't have any related information.

In addition, someone in Unity forums also encountered [this](https://forum.unity3d.com/threads/unity-freezes-when-creating-a-new-gesturerecognizer-5-5-and-up.468514/).

**Comment by StephenHodgson** [comment] 2017-05-30 16:54
Any update on this?

**Comment by ujell** [comment] 2017-05-31 12:05
I had to clean install Windows (directly from USB instead of "Reset Windows" thingy) because of another issue and this was fixed afterwards by itself 🤷 . Someone on Unity forum said it's because of missing Windows 10 [SDK](https://forum.unity3d.com/threads/unity-freezes-when-creating-a-new-gesturerecognizer-5-5-and-up.468514/#post-3082081), but I'm pretty sure everything was installed correctly when I was having this issue.

**Comment by jessemcculloch** [comment] 2017-08-15 15:00
I think if nobody comments that this is still an issue, we can probably close this one

**Comment by michael-house** [comment] 2017-10-10 05:39
I'm seeing this in Unity 2017.1.1f1. Having `GesturesInputSource` active in the scene causes hang when playing the scene. No error output in the log file. I attached the debugger and couldn't step past the first line in the `Start()` method: `gestureRecognizer = new GestureRecognizer();`. 

Oddly enough, this project was functional on the same computer earlier in the day. After a reboot from some Windows Updates, this problem presented. 
![image](https://user-images.githubusercontent.com/29042601/31370838-a52276ac-ad42-11e7-8b57-97e18422b85a.png)

**Comment by michael-house** [comment] 2017-10-10 05:42
After multiple restarts, reinstalling Unity and reverting source back to a known good state, the problem still persisted.

I enabled Developer Mode in Windows and restarted, now the problem is gone.

**Closed** 2017-10-10 15:29 UTC
