### ISSUE TITLE
Example Eye-Tracking Demo App Crashing in HoloLens 2

### ISSUE THREAD

**Issue by Merterm** [microsoft/MixedRealityToolkit-Unity#11097] opened 2022-10-11 18:07 UTC
## Overview
I am trying to deploy the example eye-tracking app that comes with MRTK to HoloLens 2 using Unity. The app deploys properly and the "Made with Unity" screen shows in HoloLens, but immediately after the app crashes, and it shows red text in the bottom left corner that says 
## Expected behavior
Example Eye tracking App being displayed in HoloLens

## Actual behavior
"Made with Unity" screen shows in HoloLens, but immediately after the app crashes, and it shows red Error text in the bottom left corner that says "A scripted object (probably Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManagerProfile) has a different serialization input when loading. NullPointerException: Object reference is not set to an instance of an object.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
Unity 2021.3.11f1 Personal

## Mixed Reality Toolkit release version
Microsoft Mixed Reality Toolkit v2.8.2

**Comment by MaxWang-MS** [comment] 2022-10-26 01:20
Hi @Merterm, I was not able to reproduce the issue with the MRTK and Unity versions you mentioned. Are you able to deploy and run the HandInteractionExamples scene fine on your HoloLens 2? Also please check the Unity log and share any interesting information with us. You can retrieve the log from the device by going to Windows Device Portal -> System -> File Explorer -> LocalAppData -> Select your app package -> TempState -> UnityPlayer.log

**Comment by keveleigh** [comment] 2022-10-27 00:16
I'm also unable to repro this, using Mixed Reality OpenXR Plugin 1.5.1, Unity's OpenXR Plugin 1.5.3, and Unity editor 2021.3.12f1.

**Comment by MaxWang-MS** [comment] 2022-12-15 00:57
Closing as we were not able to repro, please feel free to reopen if still running into the issue.

**Closed by MaxWang-MS** 2022-12-15 00:57 UTC
Labels: No Repro, Need More Info
