### ISSUE TITLE
Fake Input not working anymore

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1605] opened 2018-01-07 10:35 UTC
## Overview
I remember Unity showing two blue hands when either pressing shift or space (as stated in the docs), but no more. I tried that with the MotionControllerTest scene, which has all the relevant game objects. IF the behaviour is now different it's not documented and I don't know how to perform clicks with the gaze.

## Expected Behavior
Pressing either shift or space shows blue hands to use to click on things

## Actual Behavior
Nothing shows up

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.3.0f3

## Mixed Reality Toolkit Release Version
master or Dev_Working_Branch

**Comment by StephenHodgson** [comment] 2018-01-07 17:28
Duplicate of #1537

**Closed by StephenHodgson** 2018-01-07 17:28 UTC
