### ISSUE TITLE
InputSimulation HelpViewer text is a bit visually intrusive

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#8228] opened 2020-07-29 23:53 UTC
## Describe the bug
![image](https://user-images.githubusercontent.com/168492/88865084-b260cf80-d1bb-11ea-88bd-03fb682d1621.png)

The Input Simulation cheat sheet is a great idea, however whenever I start my HandInteractionExamples scene now, I see some text that overlaps the profiler window, and also provides me with no clear way to dismiss the text. It would be great if we could:

1)  Move the text so it does not overlap the profiler window, perhaps reconsider the design polish.
2) Provide an easy way via a keyboard shortcut to dismiss the help text, without needing to open the input simulation cheat sheet, which then needs to be closed by clicking the close button. Without this, getting into an experience for non-first time MRTK users would add up to 5 seconds of delay as they need to aim at the close button and then close this window.

**Comment by cre8ivepark** [comment] 2020-07-30 17:39
I think it should be screen-space text somewhere in the corner of the screen. Let me check if I can update.

**Comment by keveleigh** [comment] 2020-07-31 00:46
Slightly unrelated, but maybe the solution can solve both things at once. I noticed that Unity prints a warning about using screen space overlays in a VR app:

![image](https://user-images.githubusercontent.com/3580640/88987772-cc69e300-d28b-11ea-8c36-9da31992d068.png)

There appears to be a rendering cost even though it's invisible on-device. This message also prints to the log at runtime, which could lead to confusion.

We have some existing code that displays text in this window a different way:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/0c375f4efaa8921fd5321e1ff8ae5738567c2692/Assets/MRTK/SDK/Features/UX/Scripts/Pointers/MousePointer.cs#L108-L113

This won't make it less immediately intrusive, but there does appear to be a configurable fade-out time, which we could set to be a couple seconds?

>Provide an easy way via a keyboard shortcut to dismiss the help text

Or yeah, a keyboard shortcut to dismiss the text using `RemoveNotification();`

https://docs.unity3d.com/ScriptReference/EditorWindow.ShowNotification.html

**Comment by keveleigh** [comment] 2020-08-03 23:45
@cre8ivepark I'm not sure if this is specific to me, but it seems like a bunch of scripts are missing for me now after #8240:

![image](https://user-images.githubusercontent.com/3580640/89237700-b8362680-d5a8-11ea-8204-e0b68ef5dc65.png)

**Comment by keveleigh** [comment] 2020-08-05 18:28
@cre8ivepark I did some investigating, and it looks like the issue I'm seeing above only repros in Unity 2018. Did you use any Unity 2019-only components to build the UI? Are we missing a package somewhere?

**Comment by MaxWang-MS** [comment] 2020-08-14 01:23
I can confirm the same thing (the missing scripts) happened to me in Unity 2018.4.24f1.

**Comment by RogPodge** [comment] 2020-09-08 18:51
Pinging on the status of this @cre8ivepark I think we successfully adjusted the text to be less intrusive but it sounds like there were some additional compilation related issues?

**Comment by MaxWang-MS** [comment] 2021-06-28 20:58
Fixed via #8565

**Closed by MaxWang-MS** 2021-06-28 20:58 UTC
Labels: Bug, Input Simulation
