### ISSUE TITLE
Controllers not working - Entering MR portal fixes issue temporarily

### ISSUE THREAD

**Issue by milos12345** [Microsoft/MixedRealityToolkit-Unity#1538] opened 2017-12-17 05:46 UTC
## Overview
On Unity Play the Controllers are not active. Pressing Win key on controllers to open MR portal and clicking the app again makes the controllers visible. Every time the play mode is restared the same steps are required to enable controllers

## Steps to reproduce
Happens with example scenes, and also with an empty scene with just MR toolkit activated and project/scene settings applied

## Unity Editor Version
2017.2.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by ivan2007** [comment] 2017-12-17 22:11
I am experiencing the same problem

**Comment by cre8ivepark** [comment] 2017-12-18 20:46
@NeerajW @keveleigh  It seems like this is the regression in Unity 2017.2.1f1. Running the same project in MRTP 5 does not show this symptom. Had the same issue in early MRTP version which has been fixed from MRTP4.

**Comment by StephenHodgson** [comment] 2017-12-18 21:30
Has anyone opened a bug report with Unity yet?

**Comment by ivan2007** [comment] 2017-12-19 22:32
Hi Stephen,
I didn't open a bug report with Unity.

**Comment by StephenHodgson** [comment] 2017-12-19 23:17
Please do so and give us a case number here.

**Comment by hridpath** [comment] 2017-12-19 23:33
With a little Debugging of the MotionControllerVissualizer.cs, I see that the UnityEngine.XR.WSA.Input.InteractionManager does not have any InteractionSourceStates available at the time the script is executed. 
Also when the action of clicking the Windows button to go to portal and then click on application to resume, the MotionControllerVisualizer does not execute the Awake override.  But, the controller models become visible. 
Just wondering if Unity is loading the controllers themselves in this version?

**Comment by ivan2007** [comment] 2017-12-20 14:36
Hi Stephen,
I created a bug report with Unity.
Case 980399.
https://fogbugz.unity3d.com/default.asp?980399_b1hka3slivv4klvn
Ivan

**Comment by hridpath** [comment] 2017-12-22 22:17
I have downloaded and installed Unity 2017.3.0f3 this issue is not present in the Unity version.

**Comment by ivan2007** [comment] 2017-12-26 21:58
I confirm that this issue is not present with Unity 2017.3.0f3.

**Comment by ivan2007** [comment] 2018-01-12 18:38
Official answer from Unity (https://fogbugz.unity3d.com/default.asp?980399_b1hka3slivv4klvn):

Hello,

My name is Denisas and I have been investigating your case.
The issue with the controllers is fixed in the latest version of Unity

Best regards,
Denisas Kirilovas
Unity QA Team

**Comment by sonicviz** [comment] 2018-01-26 09:01
I'm using Unity 2017.3.0f3 and having this problem. It does not appear to be fixed.
I'm using an Acer MR kit as part of Microsoft MR dev program.

**Comment by ivan2007** [comment] 2018-01-26 21:36
I'm using Unity 2017.3.0f3 and the problem is not present.
You don't see nothing or you see two blocks as controllers?

**Comment by sonicviz** [comment] 2018-01-27 02:35
Nothing at all, but switching to MR Portal they show up just fine. The disappear going back to Unity.

**Comment by sonicviz** [comment] 2018-01-27 06:19
Update: My bad, I had not switched the project to Universal Windows Platform. All OK now! ty,

**Comment by cybergoulion** [comment] 2018-02-14 18:02
I'm having the same problem with Unity 2017.2.1f1 and v2017.2.1.1 release. In the answer for the bug in unity reports it is closed and fixed in the latest version of unity. What version they refer to? What is the latest version of unity we should use with the toolkit?

**Comment by ivan2007** [comment] 2018-02-14 22:37
@cybergoulion,
I'm using Unity 2017.3.0f3 with the current release of MRTK.
The problem is not present.

**Comment by cybergoulion** [comment] 2018-02-15 09:01
@ivan2007 Thank you, I was testing it myself just now and I also confirm that it works as expected up to 2017.3.1f1. Generaly I am reluctant to try the latest versions of unity because in the past I had compatibility issues with the toolkit, but it seems we are way past that now :-)

**Closed** 2018-05-17 21:08 UTC
Labels: External, Unity Bug

**Comment by JamesMillsDev** [comment] 2018-10-09 22:21
Happening again on Unity-2017.4.12f1 with MRTK 2017.4.1.0
