### ISSUE TITLE
MRTKExamplesHub can't interact with UGUI examples

### ISSUE THREAD

**Issue by vaoliva** [microsoft/MixedRealityToolkit-Unity#7789] opened 2020-05-05 15:38 UTC
## Describe the bug

When opening Hand Interaction examples scene from the MRTKExamplesHub, hand cannot interact with UGUI controls. Issue was found on 2.4 stabilization but also in 2.3 release branch.

## To reproduce

1. Clone MRTK prerelease/2.4.0_stabilization branch
2. Change build platform to Universal Windows Platform
3. Import TMPro
4. Play MRTKExamplesHub scene
5. Using hub menu, Navigate to HandInteractionExamples scene
6. Try interacting with UGUI controls
7. UGUI does not respond to hand clicks or drags 
8. Issue was replicated in Unity editor and Hololens 1

## Expected behavior

User should be able to interact with UGUI controls, clicking on buttons, toggles, dropdowns or scrolling view.

## Screenshots

![ugui_24_example_hub](https://user-images.githubusercontent.com/16922045/81084925-68cf5400-8eee-11ea-942a-c93579791268.gif)

## Your setup (please complete the following information)

- Unity Version 2018.4.12f1
- MRTK Version prelease stabilization 2.4 / release 2.3

## Target platform (please complete the following information)

- Editor
- Hololens 1

**Comment by keveleigh** [comment] 2020-10-08 17:15
@MaxWang-MS Also might be worth looking into this with your other Unity UI investigations

**Comment by Aupuma** [comment] 2020-10-21 09:32
Same problem here with v2.5. For example my canvas doesn't work if it is child of an object with RadialView component with backplate and so on, but it works if it doesn't have a parent

**Comment by MaxWang-MS** [comment] 2020-10-22 05:05
Duplicate of #6061

**Closed by MaxWang-MS** 2020-10-22 05:05 UTC
Labels: Bug, UX Controls - Unity UI (UGUI)

**Comment by MaxWang-MS** [comment] 2020-10-22 05:16
@Aupuma It seems that what you are hitting might be a separate issue. This issue is specific to scene changes. If you are hitting the problem without scene changes please open a new issue with detailed steps for us to reproduce.
