### ISSUE TITLE
MRTK 2.2 : choosing DefaultHololens1ConfigurationProfile triggers errors

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6777] opened 2019-12-03 11:26 UTC
## Describe the bug

After migrating to MRTK 2.2 (currently stabilization branch),
change the MRTK configuration to DefaultHololens1ConfigurationProfile (sometimes you need to change to DefaultMixedRealityToolkitConfigurationProfile first).

This operation leads to a bunch of errors related to MixedRealityToolkitFacadeHandler :

```
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.DestroyFacades () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:189)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.UpdateServiceFacades () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:129)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.OnSceneGUI (UnityEditor.SceneView sceneView) (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:44)
UnityEditor.SceneView.CallOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:2849)
```

```
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.DestroyFacades () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:189)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.UpdateServiceFacades () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:129)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.OnSceneGUI (UnityEditor.SceneView sceneView) (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:44)
UnityEditor.SceneView.CallOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:2849)
```
closing and reopening the scene does not triggers the erros and execution seems to works fine, but those errors are not triggers by other confiuration profiles.

## To reproduce

-  migrate to MRTK 2.2 (currently stabilization branch)
- change the MRTK configuration to DefaultHololens1ConfigurationProfile (sometimes you need to - change to DefaultMixedRealityToolkitConfigurationProfile first)

## Your Setup (please complete the following information)

- Unity Version [2018.4.13f1]
- MRTK Version [v2.2 stabilization]

**Comment by davidkline-ms** [comment] 2019-12-03 17:15
thanks @gilbdev!

**Comment by Troy-Ferrell** [comment] 2019-12-04 23:10
Dupe of #6794

**Closed by Troy-Ferrell** 2019-12-04 23:10 UTC
Labels: Bug, Investigate
