### ISSUE TITLE
GrabPointer and PokePointer should have a unified FingerCursor

### ISSUE THREAD

**Issue by matthejo** [microsoft/MixedRealityToolkit-Unity#8960] opened 2020-11-19 00:41 UTC
## Describe the problem

When the hand visualization is turned off, the user relies on seeing the far and near cursor to understand if the hand tracking system is successfully tracking their hand, and to understand where the point of interaction will occur.  Currently, there are situations where hand tracking is successful, but no cursor is visible on the hand. For example, if the hand becomes close enough to a grab-interactable object, the far hand ray pointer is disabled because the near GrabPointer becomes active. This pointer does not have a cursor, and so no visual appears on the hand.  If the hand becomes close enough to a poke-interactable object, then the FingerCursor associated with the PokePointer shows up.

This problem has been directly observed to impact our customers as they try to use the app. Customers don't trust that the hand-tracking system is still tracking their hand. In addition, they have difficulty grabbing the edge of grab-interactable windows from directions where the PokePointer is not active.

## Describe the solution you'd like

Ideally, a single FingerCursor would be enabled when either a PokePointer or GrabPointer are active on the hand, and would behave correctly (e.g. as the PokePointer approaches a surface that the FingerCursor can conform to facing). This would ensure that customers always see either the far hand ray cursor or the near finger cursor when hand tracking is working correctly for that hand.

## Describe alternatives you've considered

Changing this behavior in-app without MRTK changes is not straightforward. Associating a separate cursor with the GrabPointer is possible, but it's not straightforward to have two cursors (one for FingerPointer and another for GrabPointer) that work in tandem correctly. The cursor ideally needs to know about both pointers so it can work correctly in all configurations (just Poke, just Grab, and both Poke and Grab).

We also considered enforcing that the PokePointer must be active any time a GrabPointer is active, but this is also not straightforward to achieve, as it requires a completely customized PokePointer that can both detect poke-interactable surfaces but also force itself to be enabled any time a GrabPointer exists on the same hand.

## Additional context

Making this behavioral change will help the MRTK experience match the experience in the shell.

**Comment by davidkline-ms** [comment] 2021-02-03 19:27
What is the behavior in the HoloLens shell? Would implementing this be a break from our shell parity effort?

**Comment by keveleigh** [comment] 2021-02-03 19:33
>What is the behavior in the HoloLens shell? 

Looks like the PokePointer-equivalent visualization hangs around until a grab is detected. I wonder if we can update our pointer state machine to not disable the PokePointer when the GrabPointer is active without any regressions (and we might need to add an additional state when the GrabPointer is actively grabbing, to disable the PokePointer then

**Comment by davidkline-ms** [comment] 2021-02-11 19:16
@RogPodge to work with @matthejo

**Comment by RogPodge** [comment] 2021-02-11 19:18
An update on the progress made on this issue.

We currently have a near term fix which enables the Finger Cursor when near interactions are "enabled" i.e. when the grab pointer or poke pointer raises the IsNearObject flag. Unfortunately, getting the cursor to disappear when a grab event is currently active may take more engineering effort than comfortable for 2.6, so we probably need more time to refactor elements.

**Comment by RogPodge** [comment] 2021-02-11 20:35
Closing and splitting this issue into 2 tracked parts: 
#9287, #9288

**Closed by RogPodge** 2021-02-11 20:35 UTC
Labels: D365, Feature Request
