### ISSUE TITLE
Left-click doesn't act as 'tap' in Unity Editor.

### ISSUE THREAD

**Issue by larsonmattr** [Microsoft/MixedRealityToolkit-Unity#1537] opened 2017-12-17 00:46 UTC
## Overview
The mixed reality toolkit isn't recognizing the left-click (Shift and left mouse button) as an air tap when running a Mixed reality toolkit scene 'TapToPlace'.  

## Expected Behavior
The editor should also work with clicks -> airtap input for all scenes/scripts.  This is required to test scenes in the editor before spending time to upload to the device.

## Actual Behavior
Right mouse works to rotate screen, but "Shift + left-click" isn't creating input events for air taps.  TapToPlace class implements IInputClickHandler, so it seems that the IInputClickHandler is generally broken in the editor with the current mixed reality toolkit unity branch.

## Steps to reproduce
* Clone MixedRealityToolkit-Unity a75c059cac50204c... commit as latest, (December 14th, latest).
* Use any Unity Editor from 2017.1 on.  

## Unity Editor Version
* I am using Unity Editor 2017.3.0f2, but I have tried on several versions of Unity Editor from 2017.1, 2017.2, upwards and all have broken response to IInputClickHandler in the editor.  

## Mixed Reality Toolkit Release Version
Latest master branch as of 2017 December 14th (a7c059cac50204c.. commit).

**Comment by larsonmattr** [comment] 2017-12-17 03:59
I just tried this with the MixedRealityToolkit-Unity release for 2017.2.1f1 and Unity 2017.2.1f1.  When I open the scene for example "TapToPlace", and run it in the editor I am unable to select a box and move it with "Control left-click".   Previously, this worked with the older HoloToolkit, and I am unable to find how to trigger the IInputClickHandler events with the recent MixedRealityToolkit-Unity when running a scene in the editor.

**Comment by GKersten** [comment] 2017-12-19 12:57
I'm experiencing same issues when trying to run my app in Editor. I am not sure how it is supposed to work at the moment. But I figured out things seem to work as the used to in the Editor, when:

First, Turn off Virtual Reality Support in Player Settings.

Next, Edit the script for CustomInputSelector:
`#if UNITY_2017_2_OR_NEWER`
`spawnControllers = !XRDevice.isPresent && XRSettings.enabled && simulateHandsInEditor;`
`#else`
` spawnControllers = simulateHandsInEditor;`
`#endif`

to just
`spawnControllers = simulateHandsInEditor;`

I discovered that the problem is that I had Mixed Reality portal installed, but did not want to use it and just test in the Unity Editor. However XRDevice.isPresent returns true when the portal is installed, even when no device is connected or running.

So next thing I did: I uninstalled the Mixed Reality Portal (where this turned to a crash of Unity in previous versions this seems to be fixed now), and I toggled the Virtual Reality support back on and reverted the changes I made in CustomInputSelector. The result now is that things work correctly again in the Editor, because XRDevice.isPresent = false, so spawnControllers will be true.

I think the ultimate fix would be an adjustment to CustomInputSelector where we can tell if we want to use the Editor or Mixed Reality Portal since XRDevice.isPresent is not reliable for that purpose.

Maybe @StephenHodgson can shine some light on this.

**Comment by StephenHodgson** [comment] 2017-12-19 16:00
I'll be taking a look at this today.

**Comment by StephenHodgson** [comment] 2017-12-19 17:17
I found a more elegant solution that still takes editor into account:

```
#if UNITY_2017_2_OR_NEWER
            spawnControllers = Application.isEditor && simulateHandsInEditor;
#else
            spawnControllers = simulateHandsInEditor;
#endif
```

**Comment by larsonmattr** [comment] 2017-12-20 00:39
I tried patching my local toolkit with #1550's changes.  Works great!  I am excited to be able to move to the latest MRTK.

**Comment by keveleigh** [comment] 2017-12-28 23:05
> However XRDevice.isPresent returns true when the portal is installed, even when no device is connected or running.

@GKersten, which version of Unity are you using? I'm unable to repro that with 2017.2.1f1 with the Mixed Reality Portal installed but no headset attached:
![image](https://user-images.githubusercontent.com/3580640/34425395-3ca3a4c0-ebe0-11e7-92b3-a4cfdc40e45a.png)

The portal launches itself when I hit play in Unity, but tells me to connect a headset and focus stays in Unity.

**Comment by keveleigh** [comment] 2017-12-28 23:13
I'm also unable to repro the originally reported issue with Unity 2017.2.1f1. I'll install 2017.3 now.

![unityhands](https://user-images.githubusercontent.com/3580640/34425537-9d536be2-ebe1-11e7-8fe8-0b8578619ddf.gif)

**Comment by brean** [comment] 2018-01-03 10:44
I'm also not having the problem in 2017.3.0f3.
But I noticed that if you set the compile target to "PC Standalone" instead of UWP the hands are not shown and it does not work (you can look around using the right-click but the hands are not shown and the air-tap [shift+click] does not work). 
I don't know if there are people out there who like to compile their App as Standalone but I think we can ignore that...

**Comment by larsonmattr** [comment] 2018-01-06 03:27
StephenHodgson had submitted a PR, but this never got included.

I found looking at his changes that if:

**Comment by larsonmattr** [comment] 2018-01-06 03:27
No controllers in editor when: 
bool spawnControllers = !XRDevice.isPresent && XRSettings.enabled && simulateHandsInEditor; 

Controllers in editor when only:
bool spawnControllers = !XRDevice.isPresent && simulateHandsInEditor;

**Comment by StephenHodgson** [comment] 2018-05-21 23:55
Pretty sure this was fixed.I was also unable to repro this.

**Closed by StephenHodgson** 2018-05-21 23:55 UTC
Labels: Bug
