### ISSUE TITLE
[MRTK3] world locked rendering or tracking broken on app resume

### ISSUE THREAD

**Issue by pajama** [microsoft/MixedRealityToolkit-Unity#11109] opened 2022-10-13 20:00 UTC
## Describe the bug
App runs fine on fresh launch, but after launching the HL2 home menu then resuming the app, it seems head/space tracking is broken.

## To reproduce
1. launch Simple MRTK3 app with a canvas being positioned from a RadialView solver. 
2.Launch the home menu, 
3. re enter the app, the canvas will now be fixed to the users view. 

## Your setup (please complete the following information)

- Unity 2020.3.38f1
- MRTK 3.preview11

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
I'm using URP
I'm using the default MRTK XR Rig, however I get this warning in my logs
`Camera "Main Camera" does not use a AR Pose Driver or a Tracked Pose Driver, so its transform will not be updated by an XR device.  In order for this to be updated, please add either an AR Pose Driver or a Tracked Pose Driver.`

**Comment by pajama** [comment] 2022-10-13 21:12
I was able to fix the issue by
1. enabling Run In Background
2. adding a tracked pose driver to the camera

I'm not sure which of those steps were the solution.

**Comment by pajama** [comment] 2022-10-13 21:12
reopening in case this is something that should still be fixed mrtk side

**Comment by Zee2** [comment] 2022-10-13 23:50
> adding a tracked pose driver to the camera

@pajama By this, do you mean replacing the `TrackedPoseDriver (Input System)` with the non-Action-based `TrackedPoseDriver`?

i.e., doing this?

<img width="595" alt="image" src="https://user-images.githubusercontent.com/5544935/195731889-2809c0ef-ea15-480e-8be0-e573d401f64b.png">

**Comment by Zee2** [comment] 2022-10-18 01:03
@pajama Just pinging here again :)

**Comment by pajama** [comment] 2022-10-18 05:23
> > adding a tracked pose driver to the camera
> 
> 
> 
> @pajama By this, do you mean replacing the `TrackedPoseDriver (Input System)` with the non-Action-based `TrackedPoseDriver`?
> 
> 
> 
> i.e., doing this?
> 
> 
> 
> <img width="595" alt="image" src="https://user-images.githubusercontent.com/5544935/195731889-2809c0ef-ea15-480e-8be0-e573d401f64b.png">
> 
> 

I added the non action based one but did not remove the input system version.

**Comment by keveleigh** [comment] 2022-10-19 17:54
Interesting...thanks for the confirmation on the Tracked Pose Driver.
Can you please report which version if the Input System package you're using?

**Comment by Zee2** [comment] 2022-12-06 19:26
Adding @Clandguth here to repro the errors on app resume.

**Comment by AMollis** [comment] 2023-03-03 23:25
@srinjoym  can you try to reproduce

**Comment by srinjoym** [comment] 2023-03-29 17:32
Unable to reproduce on the MRTK Dev Template project with Unity 2020.3.44 and Input System 1.4.4. Looks like this is fixed now with the input system package

**Closed by srinjoym** 2023-03-29 17:32 UTC
Labels: Input System - General, Bug, Platform - AR Foundation, MRTK3
