### ISSUE TITLE
Importing the MRTK into new projects generates new warnings

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9603] opened 2021-03-31 22:03 UTC
## Describe the bug

During the MRTK import to a new project, several new warnings are generated. This bug is meant to track all of them instead of having each platform separately filed.

## **OpenXR via MRTK Feature Tool per example import warnings:**

**Pulse Shader Example**
![pulse shader warning](https://user-images.githubusercontent.com/65038391/113213597-42fd1d00-922d-11eb-8cbb-1362a62c736e.png)

**Scrolling Object Collection**
![scrolling object collection warning](https://user-images.githubusercontent.com/65038391/113213836-8788b880-922d-11eb-8c78-488247ffd068.png)

**Experimental - Color Picker**
![experimental color picker warning](https://user-images.githubusercontent.com/65038391/113214163-e817f580-922d-11eb-8b44-299113914262.png)

**Experimental - Examples Hub**
![examples hub warning](https://user-images.githubusercontent.com/65038391/113214277-1990c100-922e-11eb-8f5a-826f8e64fff8.png)

**Experimental - Hand Menu Layout**
![handmenulayout](https://user-images.githubusercontent.com/65038391/113214384-40e78e00-922e-11eb-8012-0e6c3c951a41.png)

## **UPM import into new project OpenXR and Windows MR plugin**
![upm no xr pipeline import](https://user-images.githubusercontent.com/65038391/113216806-bdc83700-9231-11eb-8bf8-7653996fe7cd.png)
![upm no xr pt2](https://user-images.githubusercontent.com/65038391/113216863-d20c3400-9231-11eb-9652-956c7bef0a9a.png)

**This happens when importing example scenes using UPM**
![example scene openxr import](https://user-images.githubusercontent.com/65038391/113220714-87da8100-9238-11eb-864b-02ceb3f8ef6a.png)

**Expanded missing shader warning**
![UPM shader warning](https://user-images.githubusercontent.com/65038391/113217113-434be700-9232-11eb-8dd9-f1023b339407.png)

## **.unitypackage import for UWP, Standalone, and Android warnings - Windows MR Plugin**
![upkgimportwarnings top half](https://user-images.githubusercontent.com/65038391/113215087-32e63d00-922f-11eb-9b2b-4677f3e2ad80.png)
![upkgimportwarnings BOTTOM half](https://user-images.githubusercontent.com/65038391/113215208-5f01be00-922f-11eb-963b-a8f05aa11284.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1
- MRTK Version 2.6.1
- OpenXR Version 0.2.0

**Comment by polar-kev** [comment] 2021-03-31 22:24
@elbuhofantasma can you include the OpenXR version you used here?
Did this occur in Unity 2020 with the Windows MR plugin as well or OpenXR only?

**Comment by elbuhofantasma** [comment] 2021-03-31 22:33
I have updated this issue with the OpenXR Plugin version and reference to which warnings are for which plugin.

**Comment by elbuhofantasma** [comment] 2021-03-31 22:49
One additional warning that I found in OpenXR for importing example scenes with UPM has been added.

**Comment by davidkline-ms** [comment] 2021-04-22 18:37
This can be changed from a warning to a simple message:
![image](https://user-images.githubusercontent.com/13281406/115767894-7596c300-a35e-11eb-839a-7d57db47567d.png)

These have existed in MRTK for quite some time and are caused by the piano model in the Hand Interaction Demo:
![image](https://user-images.githubusercontent.com/13281406/115768029-9ced9000-a35e-11eb-868d-a43c6c7cabc5.png)

This one is coming from Unity and appears to be benign:
![image](https://user-images.githubusercontent.com/13281406/115768440-27ce8a80-a35f-11eb-8499-383ff6def7b7.png)

**Comment by davidkline-ms** [comment] 2021-04-22 18:41
These are related to the Quest provider. @RogPodge may have some insights on them.
![image](https://user-images.githubusercontent.com/13281406/115768661-7419ca80-a35f-11eb-8600-b8ffc07cad12.png)

**Comment by davidkline-ms** [comment] 2021-04-22 18:43
I will investigate these

![image](https://user-images.githubusercontent.com/13281406/115768887-bfcc7400-a35f-11eb-838f-97b337328f8e.png)

![image](https://user-images.githubusercontent.com/13281406/115768957-d5da3480-a35f-11eb-85f7-09854f01de8f.png)

![image](https://user-images.githubusercontent.com/13281406/115769001-e8546e00-a35f-11eb-82c4-328617e42823.png)

**Comment by davidkline-ms** [comment] 2021-04-22 19:32
confirmed that the MSFT_texture_dds warning is preexisting and originates from the gltf utility

**Comment by davidkline-ms** [comment] 2021-04-22 22:28
The "Creating missing ConstraintMananger" warnings are a new behavior in Unity 2020 that informs the developer that a RequiredComponent is being added on their behalf. The examples need to be updated to get rid of that message.

**Comment by davidkline-ms** [comment] 2021-05-04 18:10
@RogPodge, can you take a look at the identifier uniqueness warnings in the quest provider?

**Comment by RogPodge** [comment] 2021-05-05 00:25
@davidkline-ms looked into the Oculus warnings. I don't think we have a good way of solving this.

1. To remove the warning, we'd have to change the Oculus Device Manager to not reference prefabs from the Oculus Integration Pacakage. However, because MRTK package are "immutable" this would make it impossible to set them correctly in the future and have that persist across opening and closing the editor, which would greatly inconvenience our users.

I think this might be solvable in the future via generating "default profiles" that are not locked to being inside the MRTK main package, but that's a much more involved effort

**Comment by davidkline-ms** [comment] 2021-05-05 16:09
Thanks for the investigation @RogPodge. I'll close this issue.

**Closed by davidkline-ms** 2021-05-05 16:09 UTC
Labels: Bug, OpenXR, UPM, Unity 2020, XR SDK

**Comment by keveleigh** [comment] 2021-05-05 16:46
> To remove the warning, we'd have to change the Oculus Device Manager to not reference prefabs from the Oculus Integration Pacakage. However, because MRTK package are "immutable" this would make it impossible to set them correctly in the future and have that persist across opening and closing the editor, which would greatly inconvenience our users.

We could also solve this by removing our dependency on Oculus prefabs. If we have a code-only dependency to pipe Oculus data into our systems, we could remove that need.

**Comment by RogPodge** [comment] 2021-05-05 17:35
> > To remove the warning, we'd have to change the Oculus Device Manager to not reference prefabs from the Oculus Integration Pacakage. However, because MRTK package are "immutable" this would make it impossible to set them correctly in the future and have that persist across opening and closing the editor, which would greatly inconvenience our users.
> 
> We could also solve this by removing our dependency on Oculus prefabs. If we have a code-only dependency to pipe Oculus data into our systems, we could remove that need.

Making a code only dependency could result in hard-coding a prefab path into the class, which I don't think would be ideal.

I think we could maybe do some reflection and do something like "look for the first prefab which has component x", but I think ultimately this could result in errors that are more impactful and blocking for developers, rather than a simple warning that only appears on first import.

**Comment by keveleigh** [comment] 2021-05-05 18:21
>could result in hard-coding a prefab path into the class

I mean we might be able to remove _all_ prefab dependencies. I believe Oculus provides code access to the underlying hand data, which is likely how the prefabs themselves are accessing it. We could remove the middle-man of the prefab scripts and call Oculus' data access APIs directly.

**Comment by RogPodge** [comment] 2021-05-05 18:26
Though that is a potential solution, I'm not sure of how confident I'd be in successfully replicating the behavior they've implemented here 😅

![image](https://user-images.githubusercontent.com/39840334/117190838-bfd36780-ad94-11eb-82b7-f4514159f2b3.png)

**Comment by keveleigh** [comment] 2021-05-05 19:15
I'd say several of those overlap with MRTK. TrackingSpace seems to be MRPlayspace, actually the right/left hand anchors align with the passive transforms we talked about earlier today (so not present today, but certainly that data is accessible), and left/right/center eye + left/right hand are all accessible using Unity's TrackedPoseDriver.

If devs want to drag an OVRManager into their scene, I don't think there's anything in MRTK that would stop them, but it feels like MRTK should only care about getting the hand data out of their APIs. Much of this feels like a parallel system instead of integration into MRTK.

**Comment by RogPodge** [comment] 2021-05-05 20:38
Yeah, though I'm somewhat hesitant to move away from Oculus's implementation at the moment from a "this is what's working and this is how their docs advise you to go about it" standpoint

**Comment by keveleigh** [comment] 2021-06-29 01:40
> I'm not sure of how confident I'd be in successfully replicating the behavior they've implemented here 😅

I've been thinking about this for a bit, and I don't think this is something to worry about. Yeah, the Oculus Integration Package might do things a specific way, but we have established patterns in MRTK as well (our rigged hands, our hands APIs for accessing hand joints, our pointer rays, etc). For MRTK integration, I'd vote that it's best to do things the "MRTK way" as opposed to replicating anything some other package has done for a specific platform.

Of course, if there are patterns we want to generally bring over to MRTK and think they'd improve things across the board, that's good too! But for something like the OVRCameraRig, we have our own camera hierarchy, playspace support, hand visualizations, etc.
