### ISSUE TITLE
Spatial Understanding not respecting rules Create_AwayFromOtherObjects

### ISSUE THREAD

**Issue by acylum** [Microsoft/MixedRealityToolkit-Unity#204] opened 2016-09-08 15:01 UTC
Often, when I use the solver to place objects, I will have interpenetrating objects even though I set SpatialUnderstandingDllObjectPlacement.ObjectPlacementRule.Create_AwayFromOtherObjects with a distance that is 2 to 3 times larger than the halfDimSize of the object.  This happens for Object Quantities of 4 or more.

**Comment by jwittner** [comment] 2016-09-15 02:44
@jevertt Is this a bug or can the algorithm simply fail sometimes and we need an enhanced one?

**Comment by jevertt** [comment] 2016-09-15 15:32
The rules are requirements that shouldn't be able to be violated (unlike the constraints). I haven't seen that, but as acylum describes it, sounds like it could be a bug.

**Comment by izatar** [comment] 2016-09-21 08:53
I have seen this when I have the near center constraint set.

**Comment by HodgsonSDAS** [comment] 2017-01-24 22:31
Hey guys,  Lots of updates to the Spatial Mapping libraries.

Is this still giving you problems?
Do you have detailed reproducible steps?

**Comment by ror5226** [comment] 2017-03-30 03:22
This bug seems to be still occurring within the SpatialUnderstanding-FeatureOverview scene. I just downloaded the newest version of the holotoolkit and am getting the same bug. To replicate the bug: Run the SpatialUnderstandingExample scene, move camera around scene (using default mediumroomwithfurnature) until enough is scanned, airtap, click on Object Placement tab-> On Floor or On Wall. As you will see it places multiple boxes on top of one another/inside each other. From my understanding, the Query_OnFloor() and Query_OnWall() in LevelSolver.cs contain the rule "SpatialUnderstandingDllObjectPlacement.ObjectPlacementRule.Create_AwayFromOtherObjects(halfDimSize * 4.0f)" which should ensure that the objects do not touch. Every once in awhile objects are placed apart from one another, but this result seems to be rare with the mentioned above case of 4 or more objects.

**Comment by StephenHodgson** [comment] 2017-09-04 23:26
Hey guys, any update to this issue?

**Comment by davidkline-ms** [comment] 2018-03-23 20:25
We should continue to investigate this.

**Comment by wiwei** [comment] 2019-04-11 20:28
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:28 UTC
Labels: HoloLens, Investigate, Legacy (HoloToolkit), Release Bug, Spatial Mapping / Awareness
