### ISSUE TITLE
WMR controller Menu Button switched

### ISSUE THREAD

**Issue by SchroerDev** [microsoft/MixedRealityToolkit-Unity#5549] opened 2019-08-08 10:22 UTC
## Describe the bug

The handedness of menu button for windows mixed reality controllers is switched.

I Press the Menu button on the left controller and the InputEventData.Handedness is right.

## To reproduce

Try this class:

```C#
using Microsoft.MixedReality.Toolkit;
using Microsoft.MixedReality.Toolkit.Input;
using UnityEngine;

public class MenuButtonTest : MonoBehaviour, IMixedRealityInputHandler
{

    private IMixedRealityInputSystem inputSystem = null;

    /// <summary>
    /// The active instance of the input system.
    /// </summary>
    protected IMixedRealityInputSystem InputSystem
    {
        get
        {
            if (inputSystem == null)
            {
                MixedRealityServiceRegistry.TryGetService(out inputSystem);
            }
            return inputSystem;
        }
    }

    private void OnEnable()
    {
        InputSystem?.Register(gameObject);
    }

    private void OnDisable()
    {
        InputSystem?.Unregister(gameObject);
    }

    public void OnInputDown(InputEventData eventData)
    {
        Debug.Log("EventDown : " + eventData.MixedRealityInputAction.Description.ToString() 
+ " Handness: " + eventData.Handedness.ToString() + " sourceID: " 
+ eventData.SourceId + "  ----  " + eventData.InputSource.SourceName);
    }

    public void OnInputUp(InputEventData eventData)
    {
        Debug.Log("EventUp : " + eventData.MixedRealityInputAction.Description.ToString() 
+ " Handness: " + eventData.Handedness.ToString() + " sourceID: " 
+ eventData.SourceId + "  ----  " + eventData.InputSource.SourceName);
    }
    
}
```

## MySetup 

- Unity Version  2019.1.11f1
- MRTK Version v2.1

## Target Platform 

- WMR immersive

**Comment by davidkline-ms** [comment] 2019-08-09 17:53
i am unable to reproduce this (prerelease/2.0.0_stabilization branch) using my WMR immersive headset when running a UWP application.

I will try using the same headset running an OpenVR application

**Comment by davidkline-ms** [comment] 2019-08-09 17:55
confirmed that the mappings are for the incorrect handedness in the OpenVR controller mapping

**Comment by davidkline-ms** [comment] 2019-08-09 21:11
Fixed in stabilization. will go into mrtk_development with the next merge.

**Closed** 2019-08-09 21:20 UTC
Labels: 4 - In Review, Bug, GA Blocker
