### ISSUE TITLE
Add articulated hand teleport gesture to all platforms

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8973] opened 2020-11-21 00:19 UTC
## Describe the problem
Currently doing a teleport gesture with articulated hands is only supported on Oculus.

This issue tracks bringing the gesture to all other platforms.

**Comment by keveleigh** [comment] 2020-11-23 19:12
This looks like a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8509

**Closed** 2020-12-04 21:28 UTC
Labels: Feature Request
