### ISSUE TITLE
[pre.12 Blocker] Walking around a scene causes stuttering while in motion.

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#11102] opened 2022-10-12 17:59 UTC
## Describe the bug

When the user is moving/walking around. Scenes will stutter quickly and noticeably, including on video recordings. Its almost like its taking too long to update that the user is actually moving and then corrects it in an ugly way.

## To reproduce

1. Launch Hand Interaction or either of the Tearsheet example scenes
2. Walk around the scene and observe text and all other objects in the scene will stutter

## Expected behavior

I'd expect everything to stay in place as the user is moving.

## Video

https://user-images.githubusercontent.com/110259320/195414512-cd8784c3-6095-4f41-a2dd-d075da587f23.mp4

## Your setup (please complete the following information)

- Unity Version 2021.3.9f1
- Commit Version23edb7e45209b2c01a8f71d6f27b4ef3b7c49228

## Target platform (please complete the following information)

- HoloLens 2 Only

**Comment by Zee2** [comment] 2022-10-12 19:37
No repro on my end. Hand Interaction scene running at 60fps and no stutter.

UI tearsheet scenes don't hit 60fps, though, but we're aware of that. (Even then, the reprojection is working correctly and there's no stutter)

**Comment by Zee2** [comment] 2022-10-13 16:47
Closing for lack of repro.

**Comment by RogPodge** [comment] 2022-10-14 18:43
I was able to repro on that commit hash, going to try on the latest and then binary search to see if there's a specific PR which may be responsible (or if maybe it was always like this)

**Comment by RogPodge** [comment] 2022-10-14 20:11
We were able to root cause the issue:

The larger issue of the whole scene shifting during runtime is a result of the fps dropping while the scene was running. This was only consistently observed when strain was applied to the system, whether it was from moving around the scene rapidly, the scene content being relatively intensive, or the device's battery being low. This is a known issue which only really occurs during performance edge cases, so no action is needed at this time.

Another smaller issue that was observed was some text shifting during runtime. This is due to zwrite not being set on for some free standing text. This issue was relatively minor and can easily be addressed by aseeting zwrite to on on any free standing text in those scenes.

**Closed** 2022-10-14 20:12 UTC
Labels: Bug, MRTK3
