### ISSUE TITLE
Disable MRTK gltf asset importer on Android platform

### ISSUE THREAD

**Issue by adeelshoukat95** [microsoft/MixedRealityToolkit-Unity#11158] opened 2022-11-01 10:18 UTC
## Describe the bug

I imported MRTK v2.8.2 in my project and then i imported Ready player me avatar sdk in my unity project then it shows two errors that multiple scripted importers are targeting the extension 'glb' and 'gltf'
![image](https://user-images.githubusercontent.com/102802944/199209486-46201bd0-4d1b-4420-9e2b-650b1d712c13.png)
To solve this issue i had to disable MRTK gltf importer from Utilities but when i do that it got stuck at importing left oculus controller as shown below.
![image](https://user-images.githubusercontent.com/102802944/199210073-b0bc7311-5150-4a7a-8f3a-0d94146118db.png)
Further debugging in depth i saw missing prefabs of left controller, then i came to conclusion that everything is working fine when you are working on PC or mac platform but as soon as you shift your project to Android platform, prefabs automatically goes missing and you can never disable MRTK gltf asset importer.

## To reproduce

1. Switch your platform to Android 
2. Import MRTK 2.8.2 from Git
3. Import Ready player me Unity sdk
4. Disable MRTK gltf asset importer from Toolbar-Mixed Reality->Utilities->Disable MRTK gltf importer

## Expected behavior

No errors in console and you can easily disable MRTK gltf asset importer

## setup
- Unity Version [e.g. 2021.3.3f1]
- MRTK Version [e.g. v2.8.2]

## Target platform

- Oculus quest 2

**Comment by Zee2** [comment] 2022-11-01 19:47
Assigning this to @RogPodge as it's a gltf thing, for 2.8.

**Comment by RogPodge** [comment] 2022-11-02 22:20
Hey there,

Based on our testing the asset should only go missing after disabling the MRTK gltf importer. The reason for this is because the MRTK gltf importer is able to parse and import the oculus-touch-v2/left.glb file, whereas the other importer is unable to. I wasn't able to reproduce anything indicating that the target platform would cause the model to fail to get imported. 

In my experience I wouldn't experience any hanging behavior, instead I get the following warning but everything resolves itself after a little bit of time:

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/39840334/199613382-460a50db-f9ea-4ed9-86e8-13edde6e5610.png">

Is it possible to disable the Ready player me importer instead of the MRTK one?

**Comment by keveleigh** [comment] 2022-12-13 18:01
I'm going to go ahead and close this as "external" for now. I'd recommend trying a full asset reimport after disabling the MRTK glTF importer and seeing if the new one is able to pick it up. Your step four:

> Disable MRTK gltf asset importer from Toolbar-Mixed Reality->Utilities->Disable MRTK gltf importer

should be removing MRTK's importer from the equation entirely.

**Closed by keveleigh** 2022-12-13 18:01 UTC
Labels: Bug, External

**Comment by adeelshoukat95** [comment] 2022-12-13 18:09
@keveleigh  yea i solved this issue by cleaning project, removing mrtk and readyplayerme and oculus integration plugins and then reimporting them one by one
