### ISSUE TITLE
Mixed Reality Toolkit Version Next

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1754] opened 2018-02-24 21:09 UTC
# What is MixedRealityToolkit-vNext?
The V1 Mixed Reality Toolkit is a collection of scripts and components intended to accelerate development of applications targeting Microsoft HoloLens and Windows Mixed Reality headsets.

This new version of the MixedRealityToolkit aims to further extend the capabilities of the toolkit and also introduce new features, including the capability to support more VR/AR/XR platforms beyond Microsoft's own Mixed Reality setup.

The vNext branch is taking all the best lessons learned from the original Mixed Reality Toolkit and refactoring / restructuring it to both:

* Support a wider audience, allowing solutions to be built that will run on multiple VR / AR / XR platforms such as Mixed Reality,  Steam/Open VR and OpenXR (initially)

* Provide an easier to use SDK, to enable rapid prototyping and ease adoption for new users (or users of previous frameworks)

* Ensure an extensive framework for advanced integrators, with the ability to swap out core components with their own should they wish to, or simply extend the framework to add new capabilities.

> Learn more about the architecture behind [Windows Mixed Reality - vNext](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/MRTK-Version-Next/MRTK-vNext.md) here.

> Learn more about the approach behind the [Windows Mixed Reality - vNext SDK](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/MRTK-Version-Next/MRTK-SDK.md) here.

# Feature areas
The Mixed Reality Toolkit vNext will includes many APIs to accelerate the development of MR / XR / VR / AR projects for a range of supported devices, including (but not limited to)

 - Microsoft HoloLens
 - Microsoft Immersive headsets (IHMD)
 - Steam VR (HTC Vive / Oculus Rift)
 - OpenXR platforms

# FAQ

> **Will my old projects based on the previous version be compatible?**

Short answer, No.  Long Answer, yes, but with some significant work.  We will be providing a detailed change log and an upgrade guide for those of you who want to try and update your projects.

> **When do we expect to see a first production ready version?**

No concrete date has been set, but I think the ideal is sometime in May 2018 to coincide with Build.

> **Is it expected that vNext will be feature complete with the current branch?**

Yes, the new version will have most or all of the same features as the current release. Our hope is to do an A/B test to ensure no features have been lost. That being said, it's likely that some feature areas may be rewritten from the ground up.

> **Should we continue to develop and test against the current branch and if so until what point?**

New development should happen against the Development branch, and bug fixes should go against both Stabilization and Development.

> **Will the current branch continue to be supported / developed against or will it be abandoned?**

We haven't yet decided when to stop support for the current version. But seeing as this is an open source project, I'm sure that generous contributors will continue to post PRs against the older version.

Once vNEXT has matured and replaced the current master branch, then the old version will move from master to a new branch named HoloToolkit-Old or something similar.

**Comment by julenka** [comment] 2018-02-25 19:18
Love this idea! Would there be any extra work to support two handed manipulation in the vnext version of MixedRealityToolkit?

**Comment by StephenHodgson** [comment] 2018-02-25 19:24
Of course. Anything in the current dev branch under the MixedRealityToolkit namespace is subject to review and adoption of vNEXT.

**Comment by genereddick** [comment] 2018-02-25 20:42
Questions:

- Is there a timeline for code we can test? 
- When do we expect to see a first working version? 
- Is it expected that vNext.v1 will be feature complete with the current branch? 
- Should we continue to develop and test against the current branch and if so until what point? 
- Will the current branch continue to be supported / developed against or will it be abandoned?

**Comment by StephenHodgson** [comment] 2018-02-26 15:30
@genereddick, all very good questions.

We're still trying to formulate a plan for what our roadmap and timeline will look like.  Remember, all of us have day jobs and we're doing this in our free time. So those who would like to help, please feel free to join in the discussions and make pull requests.

> When do we expect to see a first production ready version?

To concrete date has been set, but I think the ideal is sometime in May 2018 to coincide with Build.

> Is it expected that vNext will be feature complete with the current branch?

Yes, the new version will have most or all of the same features as the current release.  Our hope is to do an A/B test to ensure no features have been lost. That being said, it's likely that some feature areas may be rewritten from the ground up.

> Should we continue to develop and test against the current branch and if so until what point?

New development should happen against the Development branch, and bug fixes should go against both Stabilization and Development.

> Will the current branch continue to be supported / developed against or will it be abandoned?

We haven't yet decided when to stop support for the current version.  But seeing as this is an open source project, I'm sure that generous contributors will continue to post PRs against the older version.

Once vNEXT has matured and replaced the current master branch, then the old version will move from master to a new branch named HoloToolkit-Old or something similar.

**Comment by wnn413576** [comment] 2018-02-28 13:50
Stephen, great job and kudo's for you guys. 
My own wish list for vNext would be primarily on the non-functional area. Probably a lot of open doors for you, but just to stress that this is important for me and I think other users:

- **Keep code simple**. The complexer the code, the more likely it has bugs. Bugs are not avoidable, but reducable. Example: Some MRT code is very illusive and (thus) leads to (debugging) issues.

- **Use solid design patterns**, e.g. model-view-controller pattern. Example: I extensively use my own library of Syncvars which I put on objects (model) to control the state of menu's, text values, sliders (view, controller). Something like this is now missing. Also sharing between devices requires solid design patterns.

- **Design for performance**: HoloLens still has a weak processor and reaching 60 fps is very hard. Example:  use Update() mainly for time-depedendent operations. Use events/callbacks extensively.

- **Better well tested code than more features**. Example: Current MRT still has quite some bugs and illusive code/designs. (Of course one of the reasons to start vNext). This might be caused by the eager to add more features.

- **Better well documented code than more features**. Example: MRT is now poorly documented, leading to a lot of nice code not being used and reinvented wheels. Unity documentation is a very good example, I like the difference in API and Manual. I do like the example scenes in MRT, but MRT and MRT-Examples is currently not so well separated.

- Multi-device support: Different AR, VR devices + PC/Mac support. Also sharing experiece (UNet) should be designed with all possible devices as clients.

- **Modular design**: Allow us to only include the library-components that we need. Libraries should be loosly coupled and there should be no circular references. Example: Now I still have the complete MRT and MRT-Examples loaded in all apps, which makes the project unnecessary large. Deleting the parts that I do not need is difficult and still a task to do.

**Comment by StephenHodgson** [comment] 2018-02-28 15:10
Yes on all counts!

I think you've hit on everything we've been concerned about as well. As we go forward, please be sure to voice your concerns if we're getting off track.

**Comment by pnolen** [comment] 2018-03-01 17:52
So, to be clear, this will generally be using compiler directives to make the platform usable on non UNITY_UWP platforms? We've found with adding directives to various places the current MRTK does work on the windows platform, for example, but I was never sure if those kinds of changes should be pushed to the v1 branch.

Supporting multiple platforms is definitely a big plus as additional mixed reality solutions come on the market, so I'm happy to see this.

**Comment by HBJKZLH** [comment] 2018-03-02 03:09
Untiy [Universal Windows Platform] Platform does not support.

The Socket code is written and the Thread code is written and the FileStream code is written, you know what?



I used the network communication section to find that this part of the code could not be transferred to the [Universal Windows Platform].

After I tested Unity 2017.2.0f3 (64-bit) version,Unity 2017.3.1f1 (64-bit) version,Unity 2017.2.1f1 (64-bit) version.



They don't support it.



Do you have any feedback on untiy?









When I wrote socket and IO and Thread related code in the program, untiy packaging times was wrong,
The socket.Connect function is not supported.
The socket.Receive function is not supported, and the 
socket.Send function is not supported.
The filestream.close function is not supported,
New Thread(recv) is not supported,
Does not support Thread. IsBackground,
Does not support Thread. To Start,




But if I just write in the code.

The Socket client = null;

Thread the Thread = null;

FileStream filedata = null;



This way, the Universal Windows Platform is passed.

I think it should be the flaw in the Platform library of untiy [Universal Windows Platform].


Please help me to feedback this question,








------------------ 原始邮件 ------------------
发件人: "Peter Nolen"<notifications@github.com>;
发送时间: 2018年3月2日(星期五) 凌晨1:52
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [Microsoft/MixedRealityToolkit-Unity] Mixed Reality ToolkitVersion Next (#1754)




So, to be clear, this will generally be using compiler directives to make the platform usable on non UNITY_UWP platforms? We've found with adding directives to various places the current MRTK does work on the windows platform, for example, but I was never sure if those kinds of changes should be pushed to the v1 branch.
 
Supporting multiple platforms is definitely a big plus as additional mixed reality solutions come on the market, so I'm happy to see this.

**Closed** 2018-05-17 16:36 UTC
Labels: Announcement, BREAKING CHANGE, Enhancement
