### ISSUE TITLE
Pressable Button pulse effect unexpected behavior

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5963] opened 2019-09-17 01:28 UTC
## Describe the bug
Regression: Sometimes, PressableButtonHoloLens2 prefabs show static pulse effect without animation. This could be related to #5962 

## To reproduce
HandInteractionExample scene
Interact with HoloLens2 buttons

## Screenshots
![MRTK_ShaderPulse2](https://user-images.githubusercontent.com/13754172/65004012-b63f7800-d8af-11e9-9841-a75646ffe69f.gif)

![MRTK_ShaderPulse](https://user-images.githubusercontent.com/13754172/65003884-43360180-d8af-11e9-8a80-cca13d6b3ce1.gif)

![2019-09-16 18_20_48-Unity 2018 4 6f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/65003873-39ac9980-d8af-11e9-8c65-ece1094a2d32.png)

**Comment by julenka** [comment] 2019-09-17 17:15
Duplicate of #5962

**Closed** 2019-09-18 15:26 UTC
Labels: Bug, Current Iteration, Release Blocker
