### ISSUE TITLE
Exception when using Canvas Render Mode Screen Space - Camera

### ISSUE THREAD

**Issue by ILikeCreamCheese** [microsoft/MixedRealityToolkit-Unity#7522] opened 2020-03-11 15:20 UTC
## Description

A TargetParameterCountException is being thrown when trying to drag in a Render Camera on a Canvas with Render Mode Screen Space - Camera. Adding the Camera reference to the Canvas script fails and prevents me from using it.

Error Message:
TargetParameterCountException: Number of parameters specified does not match the expected number.
System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <567df3e0919241ba98db88bec4c6696f>:0)
Microsoft.MixedReality.Toolkit.Input.MixedRealityCanvasInspector.AllRootCanvases () (at Assets/MRTK/MixedRealityToolkit.Services/InputSystem/Editor/MixedRealityCanvasInspector.cs:206)
Microsoft.MixedReality.Toolkit.Input.MixedRealityCanvasInspector.OnInspectorGUI () (at Assets/MRTK/MixedRealityToolkit.Services/InputSystem/Editor/MixedRealityCanvasInspector.cs:334)
UnityEditor.UIElements.InspectorElement+<CreateIMGUIInspectorFromEditor>c__AnonStorey1.<>m__0 () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:501)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

## To reproduce

1. Add Canvas to your Scene and set Render Mode to Screen Sapce - Camera
2. Drag in any Camera into Render Camera field on Canvas
3. See error

## Expected behavior

MixedRealityCanvasInspector should not throw an error when trying to use a Render Camera.

## Your setup (please complete the following information)

- Unity Version 2019.2.17f1
- Using MRTK version 2.3

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by ossala** [comment] 2020-04-15 09:29
I've also run into this issue and it's preventing me from using a "screen space - camera" canvas to draw into a render texture. 

Found in Unity Editor
Unity 2018.4.16f1
MRTK 2.2.0

@Cameron-Micka

**Comment by ossala** [comment] 2020-04-15 09:31
A temporary fix that worked for me is to comment out everything in MixedRealityCanvasInspector.cs so the Canvas inspector uses the regular Unity UI.

**Comment by ILikeCreamCheese** [comment] 2020-04-15 11:00
Thanks for posting your fix. It's also what I had to do, although I'd prefer not to.

**Comment by Cameron-Micka** [comment] 2020-04-15 17:23
Sadly I'm not very familiar with the MixedRealityCanvasInspector. @davidkline-ms, do you know who is the current maintainer of this is?

**Comment by keveleigh** [comment] 2020-04-15 17:31
I think this may have been originally written by @Alexees?

Looks like the issue is that the inspector uses `.GetMethod` to obtain a Unity-internal method. My guess is that the parameters for this changed in Unity 2019.

**Comment by keveleigh** [comment] 2020-04-15 17:35
Though, a quick look through https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/GUI/InternalEditorGUILayout.cs#L28 doesn't seem to show a change since 2017

**Comment by Alexees** [comment] 2020-04-15 17:47
I did write it and have used reflection to get stuff running that you wouldn't be able to, yes

**Comment by dudziakl** [comment] 2020-05-07 13:52
There is an error in file Assets/MixedRealityToolkit.Services/InputSystem/Editor/MixedRealityCanvasInspector.cs 
in line 207 there are too many parameters. It should be
`sortingLayerField.Invoke(null, new object[] { Styles.m_SortingLayerStyle, m_SortingLayerID, EditorStyles.popup });`
without "EditorStyles.label" at the end. Line 225 has same command and it has correct number of parameters.

**Comment by keveleigh** [comment] 2020-05-08 16:51
Fixed in 2.4 via #7831

**Closed by keveleigh** 2020-05-08 16:51 UTC
Labels: Bug, UX Controls - Unity UI (UGUI)
