### ISSUE TITLE
Unity UWP Build: Reference Rewriter found some errors

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#3939] opened 2019-04-11 08:31 UTC
## Overview

When Building Unity Project for UWP through the Mixed Reality Toolkit>Build Window, the build succeed, but some errors are displayed at the end : 

> Error: field `System.Numerics.Vector3 Windows.Perception.People.HandMeshVertex::Position` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand::UpdateControllerData(UnityEngine.XR.WSA.Input.InteractionSourceState).
Error: field `System.Numerics.Vector3 Windows.Perception.People.HandMeshVertex::Position` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand::UpdateControllerData(UnityEngine.XR.WSA.Input.InteractionSourceState).
Error: field `System.Numerics.Vector3 Windows.Perception.People.HandMeshVertex::Normal` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand::UpdateControllerData(UnityEngine.XR.WSA.Input.InteractionSourceState).
Error: field `System.Numerics.Quaternion Windows.Perception.People.JointPose::Orientation` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand::UpdateControllerData(UnityEngine.XR.WSA.Input.InteractionSourceState).
Error: field `System.Numerics.Vector3 Windows.Perception.People.JointPose::Position` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand::UpdateControllerData(UnityEngine.XR.WSA.Input.InteractionSourceState).
Error: field `System.Numerics.Vector3 Windows.Perception.Spatial.SpatialRay::Origin` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityEyeGazeDataProvider::Update().
Error: field `System.Numerics.Vector3 Windows.Perception.Spatial.SpatialRay::Direction` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityEyeGazeDataProvider::Update().

> PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1062)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:217)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
Microsoft.MixedReality.Toolkit.Build.Editor.UnityPlayerBuildTools:BuildUnityPlayer(IBuildInfo) (at Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs:115)
Microsoft.MixedReality.Toolkit.Build.Editor.<BuildPlayer>d__2:MoveNext() (at Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs:108)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<BuildPlayer>d__2&)
Microsoft.MixedReality.Toolkit.Build.Editor.UwpPlayerBuildTools:BuildPlayer(UwpBuildInfo, CancellationToken)
Microsoft.MixedReality.Toolkit.Build.Editor.<BuildPlayer>d__1:MoveNext() (at Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs:89)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<BuildPlayer>d__1&)
Microsoft.MixedReality.Toolkit.Build.Editor.UwpPlayerBuildTools:BuildPlayer(String, Boolean, CancellationToken)
Microsoft.MixedReality.Toolkit.Build.Editor.<BuildUnityProject>d__68:MoveNext() (at Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs:1016)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<BuildUnityProject>d__68&)
Microsoft.MixedReality.Toolkit.Build.Editor.BuildDeployWindow:BuildUnityProject()
UnityEditor.EditorApplication:Internal_CallDelayFunctions()

## Expected Behavior
No errors

## Actual Behavior
Build succeed but erros are displayed

## Steps to reproduce
- Create a Project, add MRTK v2RC1, switch to UWP platform, target Hololens x86, backend IL2CPP, Virtual Reality Supported
- Open Mixed Reality Toolkit > Build Window
- click on Build Unity Project

## Unity Editor Version
2018.3.11f1
## Mixed Reality Toolkit Release Version
v2.0.0 RC1

Visual Studio 2017
Microsoft SDK 10.0.18362

**Comment by DaRockJaeger** [comment] 2019-04-11 12:04
Excactly same problem here. 
Even with Scripting Backend set to .NET, I get this error

**Comment by andreasherbig** [comment] 2019-04-11 13:25
We can confirm the same issue.
Tried with Unity Editor Version 2018.3.0b2 and 2018.3.12f1 - same result.

The resulting build can be deployed on the Hololens (1), but it seems like there are still issues related to those mentioned errors popping up in the debugger

**Comment by davidkline-ms** [comment] 2019-04-11 20:54
Thanks for the report!

**Comment by frangagn** [comment] 2019-04-13 21:46
Same problem here! Tried reimporting the MRTK, used completely empty project, still same errors.

**Comment by wiwei** [comment] 2019-04-16 21:58
Following up here, we've reached out to Unity folks and filed a Unity bug on this.

https://fogbugz.unity3d.com/default.asp?1146307_k5pfi2qqltmcvqm5

Looks to be some weird interplay between the reference rewriter and not-yet-out-of-insider SDK. The APIs themselves work (i.e. if you get a hololens 2 that supports these APIs they work)

**Comment by chrisfromwork** [comment] 2019-04-16 23:00
Assigning to @wiwei for Unity follow ups.

**Comment by hanfengsunshine** [comment] 2019-04-18 01:27
https://stackoverflow.com/questions/55687207/how-to-build-and-deploy-a-working-unity-app-with-mrtk-v2-rc-for-hololens-1#   
![856051b5ceaf5b74b6494eb68e1fe83](https://user-images.githubusercontent.com/14012055/56330774-2ab8a280-61bc-11e9-894c-25c6798631df.png)

**Comment by julenka** [comment] 2019-04-18 06:47
These errors can actually be ignored. Good to leave this issue open for reference until it can be fixed, but we should add notes in getting started docs that these errors can be ignored.

**Comment by wiwei** [comment] 2019-06-10 18:00
Clearing the GA blocker tag on this.

We don't have any control over this issue as it's a Unity bug. We can certainly continue to push on Unity to get this fixed, but we cannot make any promises because we have no control over that code.

**Comment by wiwei** [comment] 2019-06-10 18:00
@Yoyozilla see last message FYI

**Comment by Alexees** [comment] 2019-06-15 07:34
> Following up here, we've reached out to Unity folks and filed a Unity bug on this.
> 
> https://fogbugz.unity3d.com/default.asp?1146307_k5pfi2qqltmcvqm5
> 
> Looks to be some weird interplay between the reference rewriter and not-yet-out-of-insider SDK. The APIs themselves work (i.e. if you get a hololens 2 that supports these APIs they work)

The Unity issue seems to be closed. What was the result of it?

**Comment by TautvydasZilys** [comment] 2019-06-17 05:30
It was fixed. The fixes landed to 2019.3.0a6 and 2019.2.0b6 so far, and are on the way to 2019.1 and 2018.4 patches too.

**Closed** 2019-06-19 18:17 UTC
Labels: 0 - Backlog, Bug

**Comment by dfields-msft** [comment] 2019-09-11 22:04
@TautvydasZilys it seems the fix may be incomplete - when evaluated under Mono in the editor, `sizeof(System.Numerics.Vector3)` returns 16, rather than 12 as expected. This means that using a `fixed` block to fill a `System.Numerics.Vector3[]` from native code will (properly) fill in the buffer with a stride of 12 bytes per element, but Mono will index into this memory with a stride of 16 bytes per element. This reproed in 2018.4.6. I suppose we can open a new issue for this, but wanted to comment in the context of this thread for future reference. (PS- This is a general problem, and has nothing to do with MRTK.)

**Comment by TautvydasZilys** [comment] 2019-09-11 22:54
@dfields-msft, this issue sounds unrelated. The original issue was merely a flaw in our referenced APIs logic that emitted warnings if it thought that you're calling into something non-existing. What you're describing, however, seems to be a difference in runtime behaviour.

I tried reproducing this using the following code:

```
using UnityEngine;

public class NumericsTest : MonoBehaviour
{
    unsafe void Start()
    {
        Debug.Log(sizeof(System.Numerics.Vector3));
    }
}
```

However, it prints 12 in both Unity editor and built UWP player. Do you have any more concrete repro steps?

**Comment by dfields-msft** [comment] 2019-09-11 23:41
@TautvdasZilys agreed that this seems separate from the original issue, but it may have been masked by that problem. Interesting that you're seeing different results - which version of the editor were you running? I see this in 2018.4.6. I'll also follow up offline and/or through normal QA channels.

**Comment by TautvydasZilys** [comment] 2019-09-11 23:50
I was trying a newer Unity version. After talking to our Mono folks, I found this:

https://issuetracker.unity3d.com/issues/system-dot-numerics-vector-sizes-are-all-16-bytes-instead-of-8-12-and-16-bytes

Looks like exactly what you're describing and it explains why I didn't manage to repro. We can backport this to 2018.4. How important is this?

**Comment by dfields-msft** [comment] 2019-09-11 23:55
Aha! Perfect, that's exactly the problem. This is pretty important; when could we expect a backport to 2018.4 to be available, and which versions of 2019 have the fix? (We can totally move this discussion to a more appropriate forum as needed.)

**Comment by TautvydasZilys** [comment] 2019-09-12 00:05
You can create thread on Unity forums if you want.

I just cherry-picked the change to 2018.4 branch: https://github.com/Unity-Technologies/mono/commit/33140fdd1d0484ea241552c4d7f0526efc16e84c

Unfortunately, I don't yet know when is the next time Mono changes are going into Unity.

By the way, it will only return 16 inside Unity editor. Built UWP player should work correctly.

**Comment by dfields-msft** [comment] 2019-09-12 00:09
Thanks, I posted a reply to the thread in the Unity Issue Tracker link you sent.
