### ISSUE TITLE
Kiosk mode and USB keyboard Input with the HL2

### ISSUE THREAD

**Issue by iTreby** [microsoft/MixedRealityToolkit-Unity#10342] opened 2021-11-26 15:45 UTC
## Describe the bug

Unity Keyboard Input doesn't work when HL2 is in single app kiosk mode.
I have a menu in a scene and using a USB keyboard I can interact with it.

## To reproduce

Build an application on Unity using MRTK
Enable Kiosk mode from HL2 Portal
Press a key on the USB keyboard
See if there is detection

## Expected behavior

Detection of the key pressed from the USB keyboard
Example situation, on my scene I have a text that change depending on the USB key press.

## Your setup (please complete the following information)

-  Unity Version [2019.4.28f1]
-  MRTK Version [2.7.2]
-  Unity OId Input system
-  OS build 10.0.19041.1154

## Target platform (please complete the following information)

- HoloLens 2
-  XR SDK - WMR

**Comment by MaxWang-MS** [comment] 2021-12-02 02:21
Closing this one as a duplicate of #10053

**Closed by MaxWang-MS** 2021-12-02 02:21 UTC
Labels: Bug
