### ISSUE TITLE
The MRTK3 sample project failed to build the UWP platform

### ISSUE THREAD

**Issue by 91i1** [microsoft/MixedRealityToolkit-Unity#11404] opened 2023-02-22 02:53 UTC
Hello, I downloaded the MRTK3 sample project scenario to build assets to the UWP platform, but packaging failed and there was a BUG as shown in the picture. I plan to run the sample project in Hololens2, how can I solve it?

The Unity version I'm using is 2021.3.4f1c1

The sample project address: https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk3

![2](https://user-images.githubusercontent.com/125975752/220509020-fdab3b3e-5abd-4d92-8cb3-bcd15be908da.png)
![3](https://user-images.githubusercontent.com/125975752/220509032-b07fb75f-3788-4a31-b449-c96c9a818dc1.png)

![BUG](https://user-images.githubusercontent.com/125975752/220508647-d99ca4d3-9b75-4c4a-864d-288674f1268c.png)
![1](https://user-images.githubusercontent.com/125975752/220509006-eefdde01-d834-4094-804a-4d09667e4e0b.png)

**Comment by 91i1** [comment] 2023-02-22 03:48
com.microsoft.mixedreality.openxr: 1.7.0
com.microsoft.mixedreality.visualprofiler: 2.2.0
com.microsoft.mrtk.accessibility: 1.0.0-development
com.microsoft.mrtk.audio: 3.0.0-development
com.microsoft.mrtk.core: 3.0.0-development
com.microsoft.mrtk.data: 1.0.0-development
com.microsoft.mrtk.diagnostics: 3.0.0-development
com.microsoft.mrtk.extendedassets: 3.0.0-development
com.microsoft.mrtk.graphicstools.unity: 0.4.0
com.microsoft.mrtk.input: 3.0.0-development
com.microsoft.mrtk.spatialmanipulation: 3.0.0-development
com.microsoft.mrtk.standardassets: 3.0.0-development
com.microsoft.mrtk.tools: 3.0.0-development
com.microsoft.mrtk.tts.windows: 1.0.0
com.microsoft.mrtk.uxcomponents: 3.0.0-development
com.microsoft.mrtk.uxcomponents.noncanvas: 3.0.0-development
com.microsoft.mrtk.uxcore: 3.0.0-development
com.microsoft.mrtk.windowsspeech: 3.0.0-development

**Comment by dudziakl** [comment] 2023-02-22 12:27
Could you copy and paste the description of the error that starts with BuildFailedException...

I think it might be related to old version of the Burst Compiler. 
Below is my post from HoloDevelopers slack channel that is no longer visible. Please check if you have a similar error. 
![image](https://user-images.githubusercontent.com/12583808/220619485-abe46d01-9b79-4ba3-bc84-dad3d6a39e63.png)

**Comment by Victor-x1** [comment] 2023-02-22 23:50
To save you a Google Search on how to update Burst version:

In package Manager
1. Click the + icon
2. "Add package by name"
3. Type "com.unity.burst"
4. It should update and then ask you to restart editor. Currenty its 1.8.3

**Comment by 91i1** [comment] 2023-02-23 02:03
Thank you very much for your reply, the following is the copy of the content, I upgraded Burst to 1.8.3 but still wrong.




BuildFailedException: Burst compiler (1.8.3) failed running


stdout:
Warning: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.FoundationContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.FoundationContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.FoundationContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Warning: Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Starting 1 library requests
Error: Burst internal compiler error: Burst.Compiler.IL.Aot.AotLinkerException: Burst requires Visual Studio 2017 or greater (in addition, the following Visual Studio components need to be installed via the Visual Studio Installer: (1) the "Universal Windows Platform development" workload, (2) "C++ Universal Windows Platform support for vNNN build tools (ARM64)", (3) "MSVC vNNN - VS NNNN C++ ARM build tools (Latest)", and (4) "MSVC vNNN - VS NNNN C++ ARM64 build tools (Latest)") in order to build a standalone player for UWP with THUMB2_NEON32
Unable to find a valid linker at 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\Hostx64\arm\link.exe'
   �� Burst.Compiler.IL.Aot.AotNativeLink.ValidateExternalToolChain(AotCompilerOptions options)
   �� Burst.Compiler.IL.Aot.AotCompiler..ctor(ExtendedCompilerBackend backend, AotCompilerOptions coreOptions)
   �� Burst.Compiler.IL.Server.LibraryCompiler.LinkAndFinalize(CompilationJob request, CompilerServerJobExecutionContext executionContext, SharedLibraryCompilationState sharedState, Int32 methodGroupIndex, NativeCompiler nativeCompiler, AotCompilerOptions defaultOptions, AotModuleGroup aotModuleGroup)
stderr:


Unity.Burst.Editor.BurstAotCompiler+BclRunner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at ***@***.***/Editor/BurstAotCompiler.cs:1656)
Unity.Burst.Editor.BurstAotCompiler+BclRunner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at ***@***.***/Editor/BurstAotCompiler.cs:1533)
Unity.Burst.Editor.BurstAotCompiler+BclRunner.RunManagedProgram (System.String exe, System.String args, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at ***@***.***/Editor/BurstAotCompiler.cs:1508)
Unity.Burst.Editor.BurstAotCompiler.OnPostBuildPlayerScriptDLLsImpl (Unity.Burst.Editor.BurstAotCompiler+BurstAOTSettings settings, UnityEditor.Compilation.Assembly[] playerAssemblies) (at ***@***.***/Editor/BurstAotCompiler.cs:706)
Unity.Burst.Editor.BurstAOTCompilerPostprocessor.DoGenerate (UnityEditor.Compilation.Assembly[] assemblies) (at ***@***.***/Editor/BurstAotCompiler.cs:265)
Unity.Burst.Editor.BurstAOTCompilerPostprocessor.OnPostBuildPlayerScriptDLLs (UnityEditor.Build.Reporting.BuildReport report) (at ***@***.***/Editor/BurstAotCompiler.cs:189)
UnityEditor.Build.BuildPipelineInterfaces.OnPostBuildPlayerScriptDLLs (UnityEditor.Build.Reporting.BuildReport report) (at <df1a03ec30c146379d803c850c515d48>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)











在 2023-02-23 07:50:43，"Victor Oliveros" ***@***.***> 写道：

To save you a Google Search on how to update Burst version:

In package Manager

Click the + icon
"Add package by name"
Type "com.unity.burst"
It should update and then ask you to restart editor. Currenty its 1.8.3

**Comment by Victor-x1** [comment] 2023-02-24 01:13
@91i1 I had the same issue as you yesterday in Visual Studio 2022 and I managed to fix it.
I was missing C++(v143) Universal Windows Platform support for v143 build tools (ARM64/ARM64EC).


> 

I had the same error as you. I had to

**Comment by Victor-x1** [comment] 2023-02-24 01:17
I attached my Visual Studio 2022 Configuration file below. In the Visual Studio 2022 installer click on Import Configuration.

https://www.youtube.com/watch?v=x4LLQhn8EOE

[MRTK3_VS2022.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/10819778/MRTK3_VS2022.zip)

**Comment by AMollis** [comment] 2023-03-31 04:54
@91i1 thank you for your feedback.  Unfortunately, at this time we are unable to reproduce the issue you are experiencing.  We recommend following up with @Victor-x1 's suggestion:

> @91i1 I had the same issue as you yesterday in Visual Studio 2022 and I managed to fix it.
I was missing C++(v143) Universal Windows Platform support for v143 build tools (ARM64/ARM64EC).

If after trying this you still experience the same issue, please reply to this issue.  In meantime, we're resolving this issue as "not reproducible".

**Closed by AMollis** 2023-03-31 04:54 UTC
Labels: No Repro, Bug, MRTK3
