### ISSUE TITLE
Two pointers active in scene occasionally

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#3250] opened 2018-12-10 09:20 UTC
## Overview
This one is a little hard to track. But every now and then I have two cursors / pointers in my scene active. One is the DefaultCursor I assigned to the Gaze provider on the camera and the other one is my mouse basically in 3D space. I can then use the mouse to select UI elements e.g. but the gaze cursor won't do anything.

## Expected Behavior
Not sure what to expect here to be fair. The least I'd expect is, that the mouse pointer is available always when I hit play and not sometimes because it is handy for selecting things and testing in editor.

## Actual Behavior
Mouse pointer is sometimes not available and only restarting play mode until it appears will help.

## Unity Editor Version
2018.3.0f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by StephenHodgson** [comment] 2018-12-10 16:29
Still thinking about how to support customizing the input experience. Ideally I think that having the mouse input by default is the way to go (even in vr, and it works on the HoloLens with Holographic Emulation as well!) but we've got to keep in mind that the MRTK is cross platform and a standalone platform target is valid.

**Comment by FejZa** [comment] 2018-12-11 18:11
I agree. The mouse input seems pretty handy as a default.

**Comment by Yoyozilla** [comment] 2018-12-12 07:53
Looks like we can close this issue as by design?

**Closed** 2019-01-02 23:20 UTC
Labels: By Design, Input / Interactions, MRTK vNEXT, Question
