### ISSUE TITLE
The MRTK support oculus quest？

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#7322] opened 2020-02-14 03:19 UTC
The MRTK support oculus quest？

**Comment by davidkline-ms** [comment] 2020-02-14 04:16
We have Oculus Quest support on our backlog. #7272 

Thanks!

**Comment by keveleigh** [comment] 2020-02-15 15:08
Closing as duplicate of #7272, #4549, and #3072

**Closed by keveleigh** 2020-02-15 15:08 UTC
Labels: Feature Request
