### ISSUE TITLE
OpenXR Provider Right Hand Input triggering twice on Canvas Button

### ISSUE THREAD

**Issue by FabioMaas** [microsoft/MixedRealityToolkit-Unity#10569] opened 2022-04-29 01:58 UTC
## Describe the bug

Right Input is called twice with OpenXR XRSDK DataProvider on HoloLens 2 on a Canvas Button. If the right hand/AirTap is pressed on the device, the OnClick event will be fired two times instead of once: First time normal 'OnPointerUp', second time on 'OnPointerDown' with only the right hand. This does not happen in the editor. It also does not happen with a non-OpenXR setup (ObsoleteXRSDKInputSystemProfile). Left Hand works as intended. 

## To reproduce

1. Create new Unity Project, install MRTK 2.7.3 Foundation, Extension and Examples via Feature Tool.
2. Configure Project for OpenXR. Set PlayerSettings to UWP and install the OpenXR Plugin package.
3. Check 'Initialize XR on Startup' and 'OpenXR' under XR Plug-in Management in PlayerSettings.
4. Add 'Microsoft Hand Interaction Profile' and 'Eye Gaze Interaction Profile' in OpenXR/Features. 
5. Setup Scene via 'Add to Scene and Configure...', choose 'OpenXRConfigurationProfile'.
6. Create a Canvas, select 'Convert to MRTK Canvas', insert a Button as children and create some visible feedback for the 'OnClick' event, visible on the device (a toggling TestImage for example). 
7. Build and deploy.
8. Use your right hand ray input on the button, the OnClick event will be toggled a second time on release. 

## Expected behavior

One AirTap on Canvas Button with left or right handray should both toggle the event only once.

## Screenshots

Example Canvas with green ButtonImage, toggling the white Image from a small script for testing, but you can choose whatever you prefer, it only has to be a Canvas Button and should be a visible result on the device.
![image](https://user-images.githubusercontent.com/47415890/165869387-9a499151-0149-4659-9fe9-7ce452a1997c.png)

```
using UnityEngine;
using UnityEngine.UI;

public class TestInteraction : MonoBehaviour
{
    [SerializeField] private Image image;

    public void Button()
    {
        image.gameObject.SetActive(!image.gameObject.activeSelf);
    }
}
```

## Your setup (please complete the following information)

- Unity Version 2020.3.8f1 and 2021.2.10f1
- MRTK Version v2.7.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

This doesn't seem to happen on other MRTK Button, like PressableButtonHoloLens2.
If the HoloLens app is running and the device is coming out of standby, this issue is not occuring. However, if the app is completely closed and started again, the described behavior is reoccuring and only with the right hand input.

**Comment by MaxWang-MS** [comment] 2022-04-29 18:46
Hi @FabioMaas, the issue you are experiencing might be related to this known issue #10304. We have created a workaround for that issue, could you try the solution @keveleigh posted at the end of the thread?

**Comment by FabioMaas** [comment] 2022-05-02 11:45
> Hi @FabioMaas, the issue you are experiencing might be related to this known issue #10304. We have created a workaround for that issue, could you try the solution @keveleigh posted at the end of the thread?

Thanks for mentioning it! I tried it and the alternative Interaction Profile seems to work.

**Comment by MaxWang-MS** [comment] 2022-05-02 20:03
Closing this issue as this is an external issue caused by Unity and there is a working workaround.

**Closed by MaxWang-MS** 2022-05-02 20:03 UTC
Labels: External, OpenXR

**Comment by keveleigh** [comment] 2022-05-04 08:15
> Closing this issue as this is an external issue caused by Unity and there is a working workaround.

@MaxWang-MS we might want to test this with the XRI input module as well. If we're seeing double input with that, we should probably re-flag with Unity...
