### ISSUE TITLE
Active Profile Switching - Unity UI is not responding

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6061] opened 2019-09-24 18:46 UTC
## Describe the bug
Unity UI examples in the HandInteractionExample scene do not respond to the input when the scene is loaded through Examples Hub using the Scene System. It works fine when opened as a single scene. 

## To reproduce
1. Open MRTKExamplesHub
2. Run
3. Select Hand Interaction Examples menu (first one from the left)
4. Interact with Unity UI examples on the right side of the scene

## Expected behavior
Can interact with Unity UI 

## Screenshots
<img width="568" alt="2019-09-24 11_46_13-Unity 2018 4 7f1 Personal - MRTKExamplesHub unity - MixedRealityToolkit-Unity - " src="https://user-images.githubusercontent.com/13754172/65540782-f068d500-dec0-11e9-8b78-79a2130eb3c1.png">
<img width="775" alt="2019-09-24 11_45_30-Unity 2018 4 7f1 Personal - MRTKExamplesHub unity - MixedRealityToolkit-Unity - " src="https://user-images.githubusercontent.com/13754172/65540787-f2329880-dec0-11e9-9cec-bf83e103393a.png">

## Your Setup (please complete the following information)
- Unity Version [2018.4.7f1]
- MRTK Version [prelease 2.1.0 stabilization]

## Target Platform (please complete the following information)
Editor and HoloLens 2 device.

**Comment by Railboy** [comment] 2019-09-24 20:58
Here's the problem, as far as I can tell.
- `MixedRealityInputModule` caches an input system reference and a raycast camera reference in`ActivateModule(),` which is called by the event system on startup.
- The `LoadProfilesOnStartup` script causes `MixedRealityToolkit.DestroyAllServices()` to be called, which tears down all services. At that point `MixedRealityInputModule`'s cached references point to a destroyed camera object and destroyed service.
- The event system is never disabled / enabled from that point forward, so `MixedRealityInputModule.ActivateModule()` is never called again and the module no longer functions.

This is going to be a problem for anyone switching profiles regardless of scene loading.

As a kludge we could manually disable / enable the event system in our scene system load / unload calls, but that only helps people using the scene system, and it doesn't help anyone switching profiles outside of a scene load operation.

I'm experimenting with ways to manually activate the module from within the input system, but this is tricky because we have to work around the event system's life-cycle.

**Comment by AdamMitchell-ms** [comment] 2019-09-26 17:04
I wonder if this is also the root cause of #5887

**Comment by julenka** [comment] 2019-09-27 18:10
Not a regression from 2.0, @cre8ivpark removed UnityUI from the examples hub for this reason. Removing release blocker.

**Comment by AdamMitchell-ms** [comment] 2019-10-02 00:01
I have a hacky fix here.  It shows what functions need to be called to get it working again after switching scenes.  But I haven't figured out when to do those things.  As in, what event or where in code should I trigger the execution of those things.

https://github.com/AdamMitchell-ms/MixedRealityToolkit-Unity/commit/7a8a7d4c5481f6926f97554bb7e74bf92e847609

**Comment by sostel** [comment] 2019-11-26 02:50
@AdamMitchell-ms Have you checked in your "hack"? What does your hack involve? I just tested the latest and the UI elements still don't seem to work.

**Comment by julenka** [comment] 2019-11-26 15:52
> @AdamMitchell-ms Have you checked in your "hack"? What does your hack involve? I just tested the latest and the UI elements still don't seem to work.

+1. Adam if you could please share your workaround then perhaps somebody can take it over / look further.

**Comment by AdamMitchell-ms** [comment] 2019-11-26 18:23
@sostel and @julenka,

I've dropped this investigation and don't have time to pursue it at this time.  But here are my changes if someone wants to pick them up.

https://github.com/AdamMitchell-ms/MixedRealityToolkit-Unity/commit/7a8a7d4c5481f6926f97554bb7e74bf92e847609

With those changes, after switching scenes, I would add an `InputModuleReactivate` anywhere in the scene, which would then call `MixedRealityInputModule.Reactivate()`.  Then Unity UI input would work again.

The next steps would be determine when to call this properly.  We'd need to find an event or function that fires at the right time to call it.  You can see I had tried a few places in my changes, but none of them had worked yet.

**Comment by davidkline-ms** [comment] 2020-02-13 23:47
when switching profiles, the pointing ray is going through the unity ui panel. it is as if the panel has lost it's layer or something similar

**Comment by tank-t-bird** [comment] 2020-04-20 17:16
Will Unity UI continue to be supported moving forward? I ask because besides running into this issue myself, [this porting guide](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-porting-guide) suggests "Rebuild canvas-based UI with quads, colliders, and TextMeshPro text". Sometimes we just need a simple flat button UI without all the added bells and whistles (themes, 3d animations, multiple interaction types, etc).

**Closed** 2020-10-31 02:18 UTC
Labels: Bug, Investigate
