### ISSUE TITLE
Build fails on first try

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5299] opened 2019-07-12 14:06 UTC
## Describe the bug

Since about the beginning of the week, the MixedRealityToolkit seems to fail the build process on first try. It's always the OnValidate process of MixedRealityToolkit.cs that throws this:

```
MissingReferenceException: The object of type 'MixedRealityToolkit' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.InitializeInstance () (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:606)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.RegisterInstance (Microsoft.MixedReality.Toolkit.MixedRealityToolkit toolkitInstance, System.Boolean setAsActiveInstance) (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:730)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.OnValidate () (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:1543)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

## To reproduce

I am not sure yet. I guess having a scene with MixedRealityToolkit in it, recompiling a bit of code and then build the scene should be enough.

## Expected behavior

The build process should always work and not be interrupted by a missing instance of MRTK only relevant to to the Editor

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version mrtk_development

**Comment by Railboy** [comment] 2019-07-12 16:12
Related to #5131

**Comment by wiwei** [comment] 2019-07-15 17:14
Closing this one out as it's a dupe of #5131

**Closed** 2019-07-16 22:54 UTC
Labels: Bug
