### ISSUE TITLE
Motion Controller not working with Unity UI Buttons

### ISSUE THREAD

**Issue by Marbl70** [Microsoft/MixedRealityToolkit-Unity#1205] opened 2017-10-19 21:23 UTC
Tried to use Motion Controllers together with Unity UI buttons, using latest MixedRealityToolkit from master branch, Unity 2017.2 f3 MRTP, Windows Fall Creator Update and the "InputManagerTest" sample scene from HoloToolkit examples.

When starting the InputManagerTest scene and moving the cursor above the UI canvas button, the cursor is correctly drawn above the button and the button is highlighted.

But after the first click on the button, suddenly the cursor jumps to a different spot and is not drawn above the button anymore when moving over it. 

And even worse: clicks are not triggering the button onClick event anymore.

Tried different things but failed to get the motion controller working properly with ui buttons, so that the ui button can be pointed at with the motion controller cursor and pressed by a motion controller button click.

Is there a working sample that shows how point and submit works with motion controllers and ui buttons?

**Comment by StephenHodgson** [comment] 2017-10-19 22:12
Hmm, this sounds like a bug.

Which example scenes were you using?

**Comment by Marbl70** [comment] 2017-10-19 22:26
Hi Stephen,

I used the „InputManagerTest“ scene from "HoloToolkit-Examples/Input/Scenes“.

This scene has a ui canvas button which I tested using the Mixed Reality Portal Simulator as well as a real acer headset device + controller

Thanks,
Martin

**Comment by StephenHodgson** [comment] 2017-10-19 22:33
Sorry I wasn't able to duplicate this in the latest MRTK, editor, using the HMD and controllers.

![image](https://user-images.githubusercontent.com/13334553/31797355-c1520b60-b4e2-11e7-8ed6-4b723f743713.png)

Could you provide me with some more details?

**Comment by StephenHodgson** [comment] 2017-10-19 22:40
Actually I was able to duplicate it.

I realized that my Gaze was what was "pointing" at the canvas, but when the controller takes over it no longer registers correctly.

**Comment by StephenHodgson** [comment] 2017-10-19 22:42
Hmm. I've had two different tests have different results. 

I was able to get the controller to "take" focus and click, highlight, etc.

I was also able to duplicate it.  We need to figure out exactly what's happening to get a conclusive result with a fix.

**Comment by StephenHodgson** [comment] 2017-10-19 22:49
Okay, I'm pretty sure I figured it out. There's already an open issue about how when you turn your body the motion controllers become de-synced from your view.

This affects what you're pointing at and raycasting against.  I noticed that the focus was happening when I wasn't gazing nor pointing at the UI.

**Comment by StephenHodgson** [comment] 2017-10-19 22:55
I'm going to close this as a duplicate of the other issue.

**Closed by StephenHodgson** 2017-10-19 22:55 UTC
Labels: Bug, WMR HMDs
