### ISSUE TITLE
Articulated hand mesh not tracking in MRTK 2.7.2 and Unity 2020.3.24f1 (and lower)

### ISSUE THREAD

**Issue by tommensink** [microsoft/MixedRealityToolkit-Unity#10373] opened 2021-12-13 14:39 UTC
## Describe the bug

When enabling the hand mesh option, the hands are shown and an incorrect pose and then will not move with the hands or with a long delay

## To reproduce

1. Create an empty Unity 3D project
2. Import the MRTK 2.7.2 packages, including the samples
3. Run the samples from the main samples menu and press the hand mesh button in the floating bar below
4. Observe the pose and tracking of the articulated hand mesh

## Expected behavior

The handmesh should show and follow the hand and fingers.
Instead it appears at the wrong pose and it does not follow the hand movement, or with a long delay of about 10 seconds.

## Your setup (please complete the following information)

- Unity 2020.3.21f1..2020.3.24f1. 
- MRTK Version 2.7.2
- Windows Mixed Reality (not tested with OpenXR)

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

It does work with the hand joints option

**Comment by arunrajselvaraj** [comment] 2022-04-21 09:03
We also facing the lag in hand mesh, Any fixes available 
@davidkline-ms @keveleigh

**Comment by keveleigh** [comment] 2022-04-21 20:44
> We also facing the lag in hand mesh, Any fixes available @davidkline-ms @keveleigh

No workarounds that I'm aware of, unfortunately, but the bug fix has been merged into Windows XR Plugin and is entering their release process.

**Comment by keveleigh** [comment] 2022-04-21 20:47
I'm going to close this issue as a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10443, which is newer but has more information and discussion.

**Closed by keveleigh** 2022-04-21 20:47 UTC
Labels: Bug, External
