### ISSUE TITLE
Runtime error when build mixed reality project with unity and visual studio (LOG FILE ATTACHED )

### ISSUE THREAD

**Issue by lionrig** [microsoft/MixedRealityToolkit-Unity#4445] opened 2019-05-17 07:12 UTC
Overview

When we have built the solution, a runtime error appears in one eye on a corner. Is imposible to read and we are tested in debug, release, master... and the error persist. In editor mode on Unity, the error dont appear. The experience is the same but is a little annoying. Any solution ?

Expected Behavior

No runtime error

Actual Behavior

Runtime error

Steps to reproduce

Create project on Unity 2019
Build for Windows Universal Platform on VR
Open the solution in Visual Studio 2017
Compile and play or compile and make a appx

Unity Editor Version

2019.1.0f2

Mixed Reality Toolkit Release Version

v2.0.0-RC1

########### LOG FILE ###############

```
Logging to C:/Users/MyPC/AppData/Local/Packages/MyProject_vvjrt7vn67k36/TempState/UnityPlayer.log
Loading native plugins
  Loading AudioPluginMsHRTF.dll
Module information:
 Built with Compiler Ver '191627012'
 Built from '2019.1/staging' branch
 Version is '2019.1.0f2 (292b93d75a2c)'
 Release build
 Application type 'D3D'
 OS 'Windows 10 (10.0.17763) 64bit'
PlayerConnection initialized from E:/UNITY_2019_PROJECTS/BUILD VISUAL STUDIO/build/bin/x64/Release/AppX/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55050
Multi-casting "[IP] 172.30.13.181 [Port] 55050 [Flags] 2 [Guid] 737340049 [EditorId] 0 [Version] 1048832 [Id] UWPPlayerX64(MyPC) [Debug] 0 [PackageName] MyProject_vvjrt7vn67k36" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55050]
PlayerConnection already initialized - listening to [0.0.0.0:55050]
Plugins: Failed to load 'WindowsMRXRSDK' because one or more of its dependencies could not be loaded.
 
(Filename: C:\buildslave\unity\build\Runtime/Misc/Plugins.cpp Line: 223)

GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c82)
    Vendor:   
    VRAM:     4018 MB
Initialize engine version: 2019.1.0f2 (292b93d75a2c)
Failed to find spatial stage root, falling back to stationary tracking space type!
 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 591)

Created eye textures with a "texture array" layout.  The "single-pass instancing" stereo mode will be used.

Windows Mixed Reality spatial locatability state changed to Activating.
 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 374)

The referenced script (Unknown) on this Behaviour is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 197)

The referenced script on this Behaviour (Game Object '<null>') is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 333)

A scripted object (probably Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSimulationProfile?) has a different serialization layout when loading. (Read 76 bytes but expected 288 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
 
(Filename: C:\buildslave\unity\build\Runtime/Serialize/SerializedFile.cpp Line: 2012)

UnloadTime: 41,373700 ms
Windows Mixed Reality spatial locatability state changed to Inhibited.
 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 374)

Setting up 3 worker threads for Enlighten.
  Thread -> id: 36ac -> priority: 1 
  Thread -> id: 4944 -> priority: 1 
  Thread -> id: 5280 -> priority: 1 
Windows Mixed Reality spatial locatability state changed to Active.
 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 374)

Windows Mixed Reality spatial locatability state changed to Inhibited.
 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 374)

Windows Mixed Reality spatial locatability state changed to Active.
 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 374)

Trimming D3D resources.

```
########### LOG FILE ###############

Same with master version... other way would be disable runtime errors in headset screen... any way to do this ?

thanks !

**Comment by genereddick** [comment] 2019-05-20 17:37
This looks like the same issue as in #3971.

**Comment by lionrig** [comment] 2019-05-21 07:43
thanks genereddick, i I have read your thread and i understand that @davidkline-ms is looking for a solution (eliminate serialization warning on startup). Any temporal solution ? or... we need to wait for a new release of Mixed Reality Toolkit (MRTK v2 RC2) ?
We have to deliver a job soon... 

Thanks all !

**Comment by lionrig** [comment] 2019-05-21 07:45
Or any way to "hide" console in headset, our game works well but this runtime error is annoying ( and only visible in one eye )

**Comment by genereddick** [comment] 2019-05-21 18:59
I have found no solutions. Happens for me on all WMR deploys in all modes (release, debug). I have tried commenting out every debug statement through all the code but doesn't help. 

I don't understand the pattern but sometimes the debug console only shows when first loaded -- which is good -- then goes away, other times it stays and drops the fps far enough to make the app unusable.

**Comment by keveleigh** [comment] 2019-05-21 19:27
Thanks for filing! Duplicate of #3971, which we'll use for tracking and discussion going forward.

**Comment by keveleigh** [comment] 2019-05-21 19:27
Duplicate of #3971

**Closed by keveleigh** 2019-05-21 19:27 UTC
Labels: 0 - Backlog, Question
