### ISSUE TITLE
[Partner Hack] MixedRealityToolkit preventing Play mode from starting

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5077] opened 2019-06-26 22:53 UTC
Repro steps: 
After importing the Mixed Reality Toolkit into any version of Unity between 2018.3 and 2019.*

Description: 
MixedRealityToolkit was preventing Play mode from starting in Unity, which is impacting developer productivity when building applications. It highlighted MixedRealityToolkit object in scene, but no error in console was shown, and "Play" was impossible to press.

Would be convenient to be able to toggle MRTK profile settings quickly, without having to clone and reassign the profile script first.​

Workaround: Solved by restarting Unity​.

Partner: 
Digital Surgery

Filed for: @SarahSexton

**Comment by Troy-Ferrell** [comment] 2019-07-04 00:00
This is a dupe of #4121

**Closed by Troy-Ferrell** 2019-07-04 00:00 UTC
Labels: Bug
