### ISSUE TITLE
NearInteraction TouchableVolume cannot be instantiated at runtime

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#8507] opened 2020-09-09 15:42 UTC
## Describe the bug

It is not possible to instantiate an object at runtime, add both a collider and a NearInteractionTouchableVolume to it such that the object then responds to touch interactions.

## To reproduce

TODO: create sample code to reproduce the issue

## Expected behavior

Running the code above should generate a cube that responds to touch events.

**Comment by afarchy** [comment] 2020-09-09 17:48
Here's some sample code:

```
var touchable = gameObject.AddComponent<NearInteractionTouchableVolume>();
touchable.EventsToReceive = TouchableEventType.Touch;
touchable.TouchableCollider = GetComponent<Collider>();    // <-- Doesn't compile
```

**Comment by polar-kev** [comment] 2021-01-20 19:07
Closing as a duplicate of #9143 which has more detail. Still aiming for the 2.6 milestone.

**Closed by polar-kev** 2021-01-20 19:07 UTC
Labels: Bug, Input System - Near Interaction
