### ISSUE TITLE
Previous hand rays are visible when blooming out and back in 

### ISSUE THREAD

**Issue by mgrman** [microsoft/MixedRealityToolkit-Unity#4196] opened 2019-05-06 22:47 UTC
## Describe the bug

Hand rays getting stuck if you "bloom" out of the app and going back. Old hand rays get stuck and new hand rays pop up. So you can see 3 or more hand rays at the same time. 

## To reproduce

On device, in app, if you hit the home button with hand rays visible and then bloom to shell. And open the app the previous hand rays are visible and new ones come up.

NOTE: This does not reproduce on Unity 2018.3.9f1, Release build using .NET backend

## Expected behavior

Only new hand rays are visible

## Your Setup (please complete the following information)

- Unity Version 2019.1.1
- MRTK Version v2.0.0 
- IL2CPP
- Master build

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by julenka** [comment] 2019-05-06 23:02
Marking as Urgency-Soon because it is a user-visible defect.

**Comment by Yoyozilla** [comment] 2019-05-09 21:32
@julenka  is this something you can fix, or should this go to luis?

**Comment by julenka** [comment] 2019-05-09 23:02
I caaI think either of us could do it, I'm happy to do it. I've got quite a number of issues on me, I'm currently doing this one: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4176. Might be good to give to Luis if he is not actively working on urgency-soon issues. But otherwise I can keep it on me.

**Comment by mgrman** [comment] 2019-05-10 16:23
This seems to happen also with finger pointers, not just hand rays. 
There is a KeyAlreadyExists exception thrown in OnSourceDetected in MixedRealityInputModule (refresh version), changing the file to version from mrtk_development branch prevents exception but pointers are still stuck.

**Comment by julenka** [comment] 2019-05-10 16:28
Great! It's on me right now, I'm currently on #4176 but will look at this as soon as that PR is out. If it's P0 urgency-now issue, we may want to try finding somebody else to look at it, since I'll probably only have the PR for #4176 out by mid-day today.

**Comment by julenka** [comment] 2019-05-10 17:13
Started on this.

**Comment by julenka** [comment] 2019-05-10 17:27
Hi @mgrman I am actually not able to repro this on the latest mrtk_development branch, on my particular HoloLens 2 device. Could you please verify that you are seeing this behavior in the HandInteractionAllExamples scene in the latest mrtk_development? You could also send me your application package and I can test if it is fixed in my OS version (perhaps there was an OS level change to fix application on pause not working that may have fixed this issue).

**Comment by mgrman** [comment] 2019-05-10 17:30
this is happening in v2 refresh for us. would you recommend then updating to mrtk_development?

**Comment by mgrman** [comment] 2019-05-10 17:43
I will test with mrtk_development update and report back

**Comment by julenka** [comment] 2019-05-10 18:11
Also verified that the finger cursors correctly disappear in the handinteractionallexamples scene

**Comment by mgrman** [comment] 2019-05-10 18:47
mrtk_development did not help, I will try with default profile

**Comment by julenka** [comment] 2019-05-10 18:55
Can you confirm that in your mrtk_development branch that in the HandInteractionExamples scene the rays do not disappear? If we can verify that then we know there is a difference between the example implementation and your implementaiton.

**Comment by julenka** [comment] 2019-05-10 18:56
Marking this as no repro because it does not reproduce in the MRTK example scene, however it does reproduce in the customer application. The issue might be with the mgrman's application itself, not MRTK.

**Comment by mgrman** [comment] 2019-05-10 21:06
ok, I will do further investigations on our side. Seem we can reproduce it with Unity 2018.3 and 2019.1.

**Comment by julenka** [comment] 2019-05-11 03:47
I further verified that this does not repro in 2018.3 IL2CPP release build, I think the issue is unfortunately with the customer application, not MRTK.

**Closed by julenka** 2019-05-11 03:47 UTC
Labels: 0 - Backlog, Bug, DDE Partner, No Repro, Urgency-Soon
