### ISSUE TITLE
UnityException: Speech recognition is not supported on this machine.

### ISSUE THREAD

**Issue by payyavula** [Microsoft/MixedRealityToolkit-Unity#3538] opened 2019-02-28 00:40 UTC
## Overview
Wrote simple app to test voice commands. While running the app on Hololens using visual studio, I get excepction "UnityException: Speech recognition is not supported on this machine."

## Expected Behavior
Expected speech recognition to work reliably. I see some times it works and other times, it throws an excpetion.
## Steps to reproduce
* Hololens installed with latest OS release as of 2/27
* simple app for speech recognition and print out detected commands.
* run the app on hololens using visual studio in debug mode.

## Unity Editor Version
2018.3.6f1
## Mixed Reality Toolkit Release Version
2017.4.30

**Comment by Alexees** [comment] 2019-02-28 15:14
Look into #1190, which makes this a duplicate

**Comment by keveleigh** [comment] 2019-04-11 17:14
Closing as a duplicate of #1190.

**Closed by keveleigh** 2019-04-11 17:14 UTC
