### ISSUE TITLE
Exiting and returning to app sometimes messes up head tracking

### ISSUE THREAD

**Issue by MrMatthias** [Microsoft/MixedRealityToolkit-Unity#1383] opened 2017-11-17 12:28 UTC
## Overview
I exit the app by pressing the windows button and return to the app by selecting its open window and the positional tracking sometimes doesn't work anymore. 
## Expected Behavior
When I return to the app i expect the camera to behave the same way as when i left. Moving my head forward moves the camera forward.

## Actual Behavior
When I return the Camera sometimes doesn't move anymore. I can still rotate it but not move.
I move forward with my head but the camera doesn't move. Instead the motion controller is moving forwards by the distance I moved my head forward.

## Steps to reproduce
1. Start app
2.  press windows button
3. return to app by selecting app window
4.  test head movement.
4.1 movement is correct: continue with 2. (repeat several times)
4.2 head doesn't move: start crying, but without moving your head
5. Profit

I'll test this on the repo examples
## Unity Editor Version
MRTP 4
## Mixed Reality Toolkit Release Version
from yesterday

**Comment by cre8ivepark** [comment] 2017-11-20 18:02
Experiencing the same issue. When the app is resumed from the cliff house, it loses tracking and the scene is moving with the headset. The only way to recover tracking is closing the app using x button on window and fresh start.
***This only happens when you deploy the app through Visual Studio. Unity's game mode does not show this symptom.**

**Comment by MrMatthias** [comment] 2017-11-21 07:58
Waiting for MRTP 5

**Comment by MrMatthias** [comment] 2017-11-23 14:49
@StephenHodgson fixed in MRTP 5

**Comment by cre8ivepark** [comment] 2017-11-24 00:13
@MrMatthias @keveleigh @StephenHodgson Confirmed with my app too. It is fixed in MRTP5 :)

**Comment by keveleigh** [comment] 2017-12-29 00:38
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.

**Closed by keveleigh** 2017-12-29 00:38 UTC
Labels: Fixed in Dev Branch, Immersive HMD, Unity Bug
