### ISSUE TITLE
Interactable setting IsGlobal to true makes nothing else movable clickable in the scene

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4376] opened 2019-05-15 17:41 UTC
Ported to Github, reference 20963951

Find an interactable in HandInteractionAllExample scene
Check IsGlobal so it is true

![](https://microsoft.visualstudio.com/8d47e068-03c8-4cdc-aa9b-fc6929290322/_apis/wit/attachments/b96260d7-9a8b-4ac0-a00b-83fe053922e1?fileName=image.png)

Run the scene, and try to move something with hand rays
Expected: I can move things around with hand rays
Actual: I can't moving anything around, the interactable is stealing all input

**Comment by wiwei** [comment] 2019-05-15 17:41
![b96260d7-9a8b-4ac0-a00b-83fe053922e1](https://user-images.githubusercontent.com/5840182/57796852-f9b98800-76fd-11e9-9075-d5cc91bd7ab2.png)

**Comment by wiwei** [comment] 2019-05-15 17:42
@killerantz can you comment a bit about the original intent of the Is Global property?

**Comment by killerantz** [comment] 2019-05-15 21:18
The Is Global value was meant for things like a fitting guide (buttonless UI) or modal, or where we used to say, "air tap anywhere to continue." It's meant to be a button that gets all input, no matter if the button has focus or not. Normally this would be the only button that cares about input at a given time.

**Comment by julenka** [comment] 2019-05-16 05:35
@killerantz it sounds like you're suggesting that this is by design, is that correct?

**Comment by killerantz** [comment] 2019-05-16 15:34
The eventData.Use() methods were added recently, so the IsGlobal didn't stop the events propagating before, but from a design stand point, there should be one global button at a time consuming events. One scenario could be the Menu button on the controller, I could setup a global Interactable to listen for the menu button and wire up a panel to activate with the OnClick Unity event. Previously I could have had multiple interactables listen for the menu button and do stuff, but that seems really messy and potentially buggy.

**Comment by julenka** [comment] 2019-05-17 15:37
Resolving as by design for now.

**Closed by julenka** 2019-05-17 15:37 UTC
Labels: 0 - Backlog, Bug, Interactions
