### ISSUE TITLE
"Frame not in module" exception when launching MRTK 2.5.1 on HoloLens 2 Release ARM 64 

### ISSUE THREAD

**Issue by cmorschel** [microsoft/MixedRealityToolkit-Unity#9219] opened 2021-02-03 12:36 UTC
After building the app in VS2019 I get a "Frame not in module" exception once the HoloLens app starts.

**To reproduce:**
Deploy an app with MRTK 2.5.1 in Release, targeting ARM64.

My setup:
- Unity Version 2019.4.9f
- MRTK Version 2.5.1
- HoloLens 2

**My workaround:**
Rolling back to MRTK 2.4.0 solved the issue. Running MRTK 2.5.0 worked in Debug mode with some unexpected display errors.

**Comment by henryo12** [comment] 2021-02-17 21:28
I also ran into this error during the [PUN Tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-03) using MRTK 2.5.4 with Release ARM 64. Deploying in Debug from Visual Studio seemed to work. I have previously deployed MRTK 2.5.3 apps to the Hololens 2 without issue.

**Comment by adambehringer** [comment] 2021-02-25 18:42
I am having a similar crashing bug after adding UnityUI slate content to my scene, though I have not yet isolated the issue definitively. I am using MRTK 2.5.1, Unity 2019.3.13f1, Hololens 2, ARM64 Release or Master build. Crash log says ""Frame not in module". App works in Unity Editor with Holographic remoting, and also with ARM 32-bit build (though there are other issues that prevent me from using ARM 32 as a solution).

**Comment by elbuhofantasma** [comment] 2021-03-03 18:32
## Describe the bug

 This issue only happens on Legacy XR + Release + ARM64 builds that do not have the Unity debug options (Development Build, Script Debugging) selected in File > Build Settings and has a Slate in it. The Hand Interaction Examples and Slate Example scenes throw an exception when deploying to HoloLens 2 with Legacy XR + Release + ARM64 selected in Visual Studio (latest version), but will deploy to device when using Legacy XR + Debug + ARM64. The deployment of apps with Legacy XR + Release + ARM64 and a Slate, will install the app on device but stop execution with the 'Frame not in module' exception. However the app will run on device when manually launched from the Shell.

When using Legacy XR + Debug + ARM64 the apps will deploy to device. When testing the Hand Interaction Examples with this condition, the UGUI examples do not respond to far/near interaction. Only the Slate scale/position can be interacted with.

## To reproduce

Steps to reproduce the behavior:

1. Create a new Unity project and import MRTK 2.5.X
2. Open Hand Interaction Examples and change the profile to DefaultHoloLens2ConfigurationProfile
3. Build without the Unity Build debug options
4. In Visual Studio set the configuration to Release and ARM64 and configure the HoloLens 2 IP address
5. Deploy to device
6. See exception

## Your setup (please complete the following information)

- Unity Version 2019.4.X
- MRTK Version 2.5.X

## Target platform (please complete the following information)

- HoloLens 2
-Legacy XR

## Additional context

This seems to be an issue with Slates and ARM64 specifically.

**Comment by MaxWang-MS** [comment] 2021-03-06 03:44
I am able to reproduce this bug as well (MRTK 2.5.4, UPM, VS 16.8.x, hand interaction example scene). This seems like a compiler bug to me and after updating VS from 16.8 to 16.9 the issue is no longer reproducible for me. Please update the Visual Studio installation to 16.9 and let me know if the issue goes away. Alternatively, since I was not able to reproduce with MRTK 2.6 you can also try updating to that if you cannot update VS.

**Comment by polar-kev** [comment] 2021-03-08 18:47
@cmorschel, please let us know how things go on VS 16.9

**Comment by polar-kev** [comment] 2021-03-18 17:43
Since this is no longer reproducible on VS 16.9, I'll close this issue. If you see otherwise @cmorschel, feel free to reopen.

**Closed by polar-kev** 2021-03-18 17:43 UTC
Labels: Bug
