### ISSUE TITLE
Dynamic creation and Layout of InteractiveRadialSet-Items

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1137] opened 2017-10-12 12:58 UTC
Hi,

I need to dynamically add and remove items from the InteractiveRadialSet, depending on some other button press. I suggest creating a Script that has a prefab for an InteractiveToggle as well as a List of InteractiveToggle data (title, ...) as well as some parameter for max. rows.
So What I am looking for is a Horizontal/Vertical Layout group but for 3D.

**Comment by StephenHodgson** [comment] 2017-10-12 15:10
Is this a duplicate of your other issue?

**Comment by brean** [comment] 2017-10-12 15:33
Not, its an addition. I don't think there is any layouting for UI-Elements yet. I will provide a small example for it.

**Comment by brean** [comment] 2017-10-14 21:45
Here is my example:
https://github.com/brean/MixedRealityToolkit-Unity/commit/596eea002337bcd74ea676eda4596c3c81f505ee

In this fictional scenario you have the choice to create a "normal" or a "warning" message. 
When you air-tap on one of the buttons the shown text snpippets you can select change directly. 
You can also configure the amount of elements after which a new column is added to save space.

Screenshots:
![](http://andreasbresser.de/normal_message.png)
![](http://andreasbresser.de/warning_message.png)

I think it needs some cleanup/a nicer integration into the existing code so something like
```
LabelTheme lblTheme = Set.Interactives[i].gameObject.GetComponent<LabelTheme>();
lblTheme.Default = title;
```
would look nicer if the Interactive-Object would have a setter for the label text, but I did not want to change too much on the existing toolkit-example code just jet.

If it is OK I will provide a pull request with this example after cleanup.

**Comment by StephenHodgson** [comment] 2017-10-15 19:04
Looking forward to that PR!

**Comment by brean** [comment] 2017-11-24 15:24
I was just about to close this but I found a bug: The layouting does not always update correctly when data changes. Instead of calculating it myself I will provide a fix that uses the Unity-internal Grid Layout Manager  similar to the [PanelLayout](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/Prototyping/Scenes/PanelLayout.unity)

**Comment by brean** [comment] 2018-01-02 19:27
With the last pr just merged today ( https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1491 ) I close this now.

**Closed** 2018-03-07 17:31 UTC
Labels: Enhancement, Fixed in Stabilization
