### ISSUE TITLE
ManipulationHandler with gamepad gives Invalid worldAABB and IsFinite errors

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#5883] opened 2019-09-04 23:09 UTC
## Describe the bug
Clicking -- with a controller for example -- on an object with an attached ManiuplationHandler throws numerous errors. The object (the sphere in the ManipulationHandlerExample demo scene for example) disappears and the following errors are thrown:

Invalid worldAABB. Object is too large or too far away from the origin.
Assertion failed on expression: 'IsFinite(d)'
Assertion failed on expression: 'IsFinite(outDistanceForSort)'
Assertion failed on expression: 'IsFinite(outDistanceAlongView)'
Invalid AABB aabb
Invalid parameter pos in Rigidbody.WritePose because it was infinity or NaN
Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "MixedRealityPlayspace/ManipulationRoom/MoveableSphere"
transform.position assign attempt for 'DefaultCursor(Clone)' is not valid. Input position is { NaN, NaN, NaN }.
UnityEngine.Transform:set_position(Vector3)
Microsoft.MixedReality.Toolkit.Input.BaseCursor:LerpToTargetTransform() (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs:459)
Microsoft.MixedReality.Toolkit.Input.BaseCursor:UpdateCursorTransform() (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs:449)
Microsoft.MixedReality.Toolkit.Input.BaseCursor:Update() (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs:349)

## To reproduce
Open a new project, load release code. Run ManipulationHandlerExample scene. In Unity Editor with XBox controller, click on the sphere.

## Expected behavior
No error.

Object should be selected.

## Your Setup (please complete the following information)
Unity 2019.2.3f1
MRKT v2.0 (also happens with latest dev branch)

## Target Platform (please complete the following information)
- HoloLens
- HoloLens 2

**Comment by wiwei** [comment] 2019-09-04 23:59
@julenka FYI

**Comment by genereddick** [comment] 2019-09-05 02:07
Not fully understanding the code, but after stepping through a great deal of code, I came to Update methdo  in TwoHandMoveLogic.cs

` public Vector3 Update(MixedRealityPose pointerCentroidPose, Quaternion objectRotation, Vector3 objectScale, bool isNearMode, bool usePointerRotation, MovementConstraintType movementConstraint)
        {
            if (!isNearMode || usePointerRotation)
            {
                Vector3 headPosition = CameraCache.Main.transform.position;
                float distanceRatio = 1.0f;

                if (movementConstraint != MovementConstraintType.FixDistanceFromHead)
                {
                    // Compute how far away the object should be based on the ratio of the current to original hand distance
                    var currentHandDistance = Vector3.Magnitude(pointerCentroidPose.Position - headPosition);
                    distanceRatio = currentHandDistance / pointerRefDistance;
                }

                Vector3 scaledGrabToObject = Vector3.Scale(objectLocalGrabPoint, objectScale);
                Vector3 adjustedPointerToGrab = (pointerLocalGrabPoint * distanceRatio);
                adjustedPointerToGrab = pointerCentroidPose.Rotation * adjustedPointerToGrab;

                return adjustedPointerToGrab - objectRotation * scaledGrabToObject + pointerCentroidPose.Position;
            }
            else
            {
                return pointerCentroidPose.Position + pointerToObject;
            }
        }
    }`

The problems seems to begin here: 

`distanceRatio = currentHandDistance / pointerRefDistance;`

 As in this case, currentHandDistance & pointerRefDistance are both == 0, so you get 

    distanceRatio == NaN

This then propagates to 

` Vector3 adjustedPointerToGrab = (pointerLocalGrabPoint * distanceRatio);`

and adjustedPointerToGrab = {NaN, NaN, NaN}

Which then returns to ManipulationHandler.HandleOneHandMoveUpdated()

`Vector3 targetPosition = moveLogic.Update(pointerPose, targetRotation, hostTransform.localScale, IsNearManipulation(), rotateInOneHandType != RotateInOneHandType.RotateAboutObjectCenter, constraintOnMovement);
`

where targetPosition == {NaN, NaN, NaN}, and then

`Vector3 smoothedPosition = Vector3.Lerp(hostTransform.position, targetPosition, lerpAmount);`

likewise smoothedPosition

Maybe there is more after that, but I got tired of stepping!

**Comment by genereddick** [comment] 2019-09-05 05:04
And working back a bit more

    var currentHandDistance = Vector3.Magnitude(pointerCentroidPose.Position - headPosition);

Where pointerCentroidPose.Position == headPosition, so that the currentHandDistance is 0

headPosition is just the camera

    Vector3 headPosition = CameraCache.Main.transform.position;

And pointerCentroidPose.Position comes from

    MixedRealityPose pointerPose = new MixedRealityPose(pointer.Position, pointer.Rotation);

Which comes from 

    PointerData pointerData = GetFirstPointer();
    IMixedRealityPointer pointer = pointerData.pointer;

Which comes from here

    ` private PointerData GetFirstPointer()
        {
            // We may be able to do this without allocating memory.
            // Moving to a method for later investigation.
            return pointerIdToPointerMap.Values.First();
        }`

The pointerIdToPointerMap seems to be added to here:

    pointerIdToPointerMap.Add(id, new PointerData(eventData.Pointer, initialGrabPoint));    

The eventData is passed into the ManipulationHandler.OnPointerDown method:

     public void OnPointerDown(MixedRealityPointerEventData eventData) 

And, look at what gets passed in, it looks like the Xbox controller pointer click is of type:

    {Microsoft.MixedReality.Toolkit.Input.GazeProvider+InternalGazePointer}

Still not sure I understand all the implications here, but this seems to suggest that the gazePointer is considered to be at the same location as the head -- versus say where the Raycast is hitting the object?

**Comment by genereddick** [comment] 2019-09-05 05:19
So, my quick fix is simply to check that distanceRatio is != 0. As distanceRatio in initialized with a value of 1.0f, 

    `Vector3 headPosition = CameraCache.Main.transform.position;
                float distanceRatio = 1.0f;

                if (movementConstraint != MovementConstraintType.FixDistanceFromHead)
                {
                    // Compute how far away the object should be based on the ratio of the current to original hand distance
                    var currentHandDistance = Vector3.Magnitude(pointerCentroidPose.Position - headPosition);

                    if (Math.Abs(currentHandDistance) > float.Epsilon)
                    {
                        distanceRatio = currentHandDistance / pointerRefDistance;
                    }
                }`

This stops the error at least. I assume that this is meant to be used in a tap hold an drag action and so the error results from a tap and release w/o any movement in which case the right result is for the object not to move, but not sure of any of it.

**Comment by julenka** [comment] 2019-09-05 17:09
Duplicate of #5829

**Closed by julenka** 2019-09-05 17:09 UTC
Labels: 0 - Backlog, Bug, Current Iteration, UX Controls, UX Controls - ManipulationHandler
