### ISSUE TITLE
SteamVR takes over UnityEditor on Play MRTKV-Next

### ISSUE THREAD

**Issue by KatVHarris** [Microsoft/MixedRealityToolkit-Unity#3087] opened 2018-11-06 20:11 UTC
Mixed Reality Toolkit V-Next

When setting up a new scene, configuring for v-next, and hitting play, SteamVR takes over, freezing Unity and causing the user to TaskManager EndTask on Unity to regain control. 

**Unity Editor Version**
Unity 2018.3.0b8

**Mixed Reality Toolkit Release Version**
Using the V-Next unity package - https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2018.9.0-Beta

**To Reproduce**
Unity 
- Build Settings - UWP 
- Mixed Reality Toolkit > Configure
- "Play"

**Expected behavior**
Example scene should run within the Editor

**Actual behavior**
SteamVR takes control and opens the empty scene in their portal, freezing unity. I can move within SteamVR but that's about it. Trying to exit pops up a dialog telling the user that Unity will exit too. When the user hits close anyway the Unity editor does not close because it has crashed. 

**Screenshots**
![steamvrtakeover1](https://user-images.githubusercontent.com/3465352/48090762-aa2d5900-e1bc-11e8-8000-426e450133cb.png)

![steamvrtakeover](https://user-images.githubusercontent.com/3465352/48090709-8f5ae480-e1bc-11e8-9b39-f7cbb389d559.png)

**Possible Solution**
Just warn people that if steamVR is up (or on the initial start of the headsets and MRP), it may take control over the editor.

**Comment by StephenHodgson** [comment] 2018-11-06 20:52
We don't fully support SteamVR yet, but we are talking with Valve engineers about the best way to support this.

Related to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3073

Thanks for reporting!

**Comment by StephenHodgson** [comment] 2018-11-06 20:57
Is this also sounds like something that _may_ be reproducible outside of the MRTK.

I'll keep you posted

**Comment by SimonDarksideJ** [comment] 2018-11-07 11:15
OK, this is actually a Unity bug and not related to the MRTK.
There is also a bug where SteamVR will be used on the WSA platform, if VR is enabled on Standalone but not WSA 📦 

Unity also has a VERY annoying feature if the standalone build has VR enabled on startup, whereby Unity will launch SteamVR before the editor starts.  It "should" eventually resolve it self and start.

My recommendation would be to open the MRPortal first, then start SteamVR manually, before opening Unity in Standalone or hitting play.
Alternatively, start your Project in WSA mode (possible thanks to the hub), which does not start any VR  "thing"

**Comment by SimonDarksideJ** [comment] 2018-11-07 14:11
As a simple test, to show this isn't related to the MRTK:

* Create a new Unity project
* Enable VR and select OpenVR
* save and close Unity
* Start Unity

You will find that it automatically tries to launch SteamVR to help VR devs when using Unity for VR.  

> Hint, It DOES NOT

**Comment by Yoyozilla** [comment] 2019-04-16 23:36
closing since this is not an MRTK bug.

**Closed by Yoyozilla** 2019-04-16 23:36 UTC
Labels: Beta, Editor, External, OpenVR, Unity Bug, Windows UWP
