### ISSUE TITLE
Fatal error when using Interaction Manager

### ISSUE THREAD

**Issue by arctop-sk** [Microsoft/MixedRealityToolkit-Unity#2268] opened 2018-06-07 12:51 UTC
## Overview
See screen shot attached. Essentially when using MixedRealityToolkit Input prefabs, it will register and unregister every time you enter/exit play mode.
Apperently there is a limit on how many times this is allowed to happen. As such in the normal working flow over a day, you ultimately get this error and be forced to quit.
This happens when you hit play, so at that point, if you have any changes you didn't get a chance to save yet, you will lose your work.

![unity crash](https://user-images.githubusercontent.com/37613957/41100536-548ba1c4-6a6a-11e8-936f-e9dac8885efe.png)

## Steps to reproduce
Use a scene with the input manager prefab, and enter and exit play mode until it happens

## Unity Editor Version
2017.4.4 , was present before hand as well

## Mixed Reality Toolkit Release Version

Latest

I have also reported this bug to unity - https://fogbugz.unity3d.com/default.asp?1046722_14ld905qnl4g63hj

**Comment by StephenHodgson** [comment] 2018-06-07 13:35
Duplicate of another open issue.

Thanks for the link to the bug report

**Comment by keveleigh** [comment] 2018-06-07 18:30
Other issues for this are #1955 and #2220.

**Comment by StephenHodgson** [comment] 2018-06-07 18:33
Actually I'll leave this one open cause of the bug report

**Closed** 2018-08-03 14:16 UTC
Labels: External, Unity Bug
