### ISSUE TITLE
Content is head-locked after sleep and resume

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedRealityToolkit-Unity#9516] opened 2021-03-17 01:03 UTC
## Describe the bug

After sleeping and waking the HoloLens 2, app content becomes head-locked.

## To reproduce

Create new Unity project with UWP support (2020.3.0f1)
Import MRTK Foundation,Tools,Examples @ 2.61
Open an example scene (I used MRTK/Examples/Demos/UX/BoundsControl/Scenes/Bounds Control Examples)
Change configuration profile to DefaultHoloLens2XRSDKConfigurationProfile
Install XR Plugin Management (Project Settings/XR Plugin Management) and enable Windows Mixed Reality for UWP
Switch platform to UWP and accept default MRTK project configurator (enable capabilities)
Build Unity project for HoloLens, ARM64, D3D
Build VS project and start without debugging on device (Release, ARM64)

(Alternatively download the project files produced via this method here: https://drive.google.com/drive/folders/1x35mDFTQ1JkvZgCJV9TPO6w2HvPzTq0d?usp=sharing)

On the device:
1. Observe scene runs as expected
2. Minimize app via start menu (Home button)
3. Resume app
4. Observe still running as expected
5. Put headset to sleep via power button
6. Wake headset, resume app via start menu
7. Observe content is head locked. Note app is not frozen and interaction is still possible (though difficult due to disassociation of head and hands, see video)

## Expected behavior

Resuming app after headset sleep behaves the same as resuming app via a regular pause

## Video

https://user-images.githubusercontent.com/19278856/111398560-d3a90880-8717-11eb-94e4-c5f470f8f8a5.mp4

## Your setup (please complete the following information)

Unity: 2020.3.0f1
MRTK: 2.6.1
XR Plugin Management: 4.0.1
Windows XR Plugin: 4.4.1
Windows Holographic 10.0.19041.1140 (Insider?)

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment] 2021-03-17 01:08
Thanks for the report! This is a known Unity bug. We've been tracking this under bugs like #9165, and the Unity bug can be found at https://issuetracker.unity3d.com/issues/xr-sdk-tracked-pose-driver-stops-working-after-suspending-play-while-run-in-background-is-unchecked

**Comment by camnewnham** [comment] 2021-03-17 01:17
Thanks @keveleigh - from the comments it does sound like the same issue - though I would note that Run In Background _is_ checked in this case so perhaps actually sleeping the headset emulates the pause/resume behaviour.

Cheers

**Comment by keveleigh** [comment] 2021-03-17 01:24
>though I would note that Run In Background is checked in this case

I think in investigations on our side (@RogPodge?) we found that Run In Background didn't affect the bug unfortunately (even though the public bug report says otherwise)

**Comment by RogPodge** [comment] 2021-03-18 18:21
Yeah I think this is the case, the root cause should be similar in any case.

**Comment by keveleigh** [comment] 2021-05-26 22:15
This should be fixed in the latest Windows XR Plugin releases. Please re-open if not!

**Closed by keveleigh** 2021-05-26 22:15 UTC
Labels: Bug, External, XR SDK
