### ISSUE TITLE
spatial understanding and unity mecanim humanid rig issue

### ISSUE THREAD

**Issue by zer00p** [Microsoft/MixedRealityToolkit-Unity#228] opened 2016-09-22 13:21 UTC
when having a mecanim humanoid character(rig) in the scene when activating the spatial understanding dll using "SpatialUnderstandingDll.Imports.SpatialUnderstanding_Init()" it breaks unity's mecanim system and makes all characters twitch / spaz all over the scene.

*Note this doesn't happen in the editor, nor with “generic” rigs.
i'm using unity 5.4.0f3 HTP

**Comment by HodgsonSDAS** [comment] 2016-09-22 13:32
Hmm, Interesting. @zer00p, do you have a test scene we can try out?

**Comment by zer00p** [comment] 2016-09-22 13:58
https://www.wetransfer.com/downloads/b20fe3ef61ee0e7c312803323386df5a20160922135702/3b95f73d76c98b5de7d3bddc3b6f161b20160922135702/35fa8a

scene is called teddy

**Comment by HodgsonSDAS** [comment] 2016-09-22 14:09
Can't access your link at work, but I might take a look at it later this evening.

**Comment by zer00p** [comment] 2016-09-22 14:11
how would you want me to send it ? i can't attach it here.
not even as a zip file.

**Comment by HodgsonSDAS** [comment] 2016-09-22 14:22
Well, you could always make a repository here on GitHub

**Comment by izatar** [comment] 2016-09-23 00:32
I have humanoid rigs that work fine with the scanner is running.  But I notice you say this happens when you call SpatialUnderstandingDll.Imports.SpatialUnderstanding_Init().  I load this with the provided prefab that initalizes at startup.  Apparently you are doing this in the middle of animation?  Running something cpu intensive while animations are running could easily mess up the animation timing.
I think just initializing at start is the solution.
Also note I have seen issues with multiple world anchors,  so I only use one.

**Comment by zer00p** [comment] 2016-09-26 09:56
link to sample project : https://github.com/zer00p/TeddyBear 
@izatar  i am also using the holokit prefabs and (on my main project) the animated object is instantiated after the scan has ended.

**Comment by nealee93** [comment] 2016-12-15 17:32
I also encountered the same problems as you, can you tell me how you finally resolved please？

**Comment by zer00p** [comment] 2016-12-18 13:04
we didn't,
we ended up using FinalIK from the AssetStore.

**Comment by myreee** [comment] 2017-01-07 06:15
@zer00p @nealee93 I'm having this issue as well. How did you resolve it?

**Comment by nealee93** [comment] 2017-01-07 10:25
@myreee No,we can't find any way to resolve this issue, it just happens only to a few people,incredible...

**Comment by myreee** [comment] 2017-01-07 23:05
@nealee93 so all of your characters are still twitching? I really need a fix for this! Soon!

Any help would be appreciated!

cc
@HodgsonSDAS 
@izatar

**Comment by HodgsonSDAS** [comment] 2017-01-09 13:12
@myreee, Sorry, I haven't seen any fixes for this.

Anyone with insight is welcome to share their learnings.

**Comment by myreee** [comment] 2017-01-09 22:51
@HodgsonSDAS Thanks!

I tested with different avatars and still see the issue. It only starts after the Spacial Understanding gameobject is activated and if there is an active animation. 

Spacial Mapping game object causes no issues

**Comment by HodgsonSDAS** [comment] 2017-01-09 23:14
Hopefully some of the updates to the spatial understanding namespaces might resolve this issue. I'd try pulling the PR https://github.com/Microsoft/HoloToolkit-Unity/pull/459 and testing that out as well.

**Comment by myreee** [comment] 2017-01-12 22:14
@HodgsonSDAS Anything else I can do to help identify the cause of this problem? I am unable to use the new spatial understanding until this is resolved

**Comment by HodgsonSDAS** [comment] 2017-01-13 12:57
Unfortunately I can't really think of anything.  I'd also try opening a ticket with Unity just to be sure it's not a bug with the engine (which it may or may not be). Just be sure to provide them with the reproduction project.

**Comment by AzureRok** [comment] 2017-03-11 10:38
Anyone managed to find the solution to this?

**Comment by MatzeBehm** [comment] 2017-03-27 07:50
We had some Trouble dealing with this issue too. Our fix for this Problem is to right click all your "Rotation" Parameters in the Animation Window (where you have the timeline etc.) and choose Quaternion Euler ... this worked for us. It might be a Problem with gimbal lock´s, iam not so deep into the algorithmic stuff so don't be sure about that :)

Hope this helps.

**Comment by myreee** [comment] 2017-03-31 07:34
I'll give that a try, Thanks!

**Comment by ForrestTrepte** [comment] 2017-05-18 00:25
In issue #520, I noticed that Spatial Understanding was changing the floating point rounding mode and that was causing strange problems when I later tried to capture photos. In #656, I changed Spatial Understanding to restore the rounding mode after it is called. It is possible that your issues with animation could be caused by the same underlying issue, so you may want to check if this is still a problem in recent versions of HoloToolkit that have the 5fc993c commit.

**Comment by StephenHodgson** [comment] 2017-09-04 23:24
I will close this issue unless someone claims to repro is in the latest version.

**Closed by StephenHodgson** 2017-09-04 23:24 UTC
Labels: Bug, Help Wanted
