### ISSUE TITLE
Decision matrix for OpenXR and XR SDK

### ISSUE THREAD

**Issue by ModischFabrications** [microsoft/MixedRealityToolkit-Unity#9468] opened 2021-03-08 20:49 UTC
## Describe the issue
I have just ported my application from XR SDK to OpenXR because some essential features were broken, but now I see that OpenXR is lacking other essential features. I need to use Unity 2020, QR codes, eye and hand tracking, it feels like there is no combination that allows all of them. 

## Feature area
I would like to get a decision matrix to choose either OpenXR or XR SDK while both are feature incomplete. 

XR SDK has broken hands (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9238) and is lacking eye gaze (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7284), OpenXR has hands and eye gaze but no QR (https://docs.microsoft.com/de-de/windows/mixed-reality/develop/unity/openxr-supported-features#whats-coming-soon). 

I am imagining a matrix with different frameworks/platforms as rows and capabilities as columns, but I am happy for any layout.

## Additional context

Follow up question: Is any of the two going to be feature complete in the next few weeks?

**Comment by keveleigh** [comment] 2021-03-08 22:11
Regarding QR codes, it looks like our translated docs are a little stale for OpenXR. We shipped a new plugin last week that included support for SpatialGraphNodes (and thus QR codes): https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-supported-features#qr-codes

**Comment by ModischFabrications** [comment] 2021-03-09 10:45
> QR codes

Nice, didn't expect changes between languages, especially considering the /de-de/ version was also in english. Thanks for the info. I haven't been able to adapt my code the last few hours so that QR codes are in the right position, but it's probably just a different interface, the event is fired. 

What I just realized is that I understood hand tracking wrong: While OpenXR is able to track hands (according to docs), there is no hand mesh, pointer or any other feedback.  I was unable to touch or far select objects, but I am unsure if there is no tracking or if I am just missing. This means that I have the choice between broken hands in XR SDK or no hands in OpenXR. 

Is there any trick that I missed?

**Comment by keveleigh** [comment] 2021-03-09 20:08
>there is no hand mesh, pointer or any other feedback. I was unable to touch or far select objects, but I am unsure if there is no tracking or if I am just missing. This means that I have the choice between broken hands in XR SDK or no hands in OpenXR.

The missing hand mesh is work that I have currently in review on the plug-in side. Hoping to get that in asap for an upcoming release.

As far as the missing pointer etc, are you using 2.6? If so...a combination of Unity release plus a change I made caused a regression that broke MRTK support for OpenXR. There's some more info at https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9465#issuecomment-793156345. I'm working on getting out a 2.6.1 hotfix.

**Comment by ModischFabrications** [comment] 2021-03-10 08:22
> hand mesh

Awesome, would be nice to be able to stay on OpenXR with every feature available, it feels like OpenXR runs a bit better than XR SDK.

> 2.6

Yes, it seems like newer isn't always better. Thanks for looking into it!

Do you have a rough timescale on the releases? I am unable to work on it for much longer than next week...

**Comment by soshogoh** [comment] 2021-05-20 03:55
Could you please update when this issue will be fixed?

**Comment by keveleigh** [comment] 2021-05-20 16:25
@soshogoh Which issue are you referring to? The decision matrix being created?

**Comment by MaxWang-MS** [comment] 2021-07-27 01:21
The Mixed Reality OpenXR plugin has been graduated from the preview state and as of now the latest version is 1.0.1. It is expected to be better than or on par with the XRSDK/Windows XR plugin in every aspect. As such, we recommend you to use OpenXR. Please remember to get the latest MRTK release (as of now 2.7.2) for the best experience.

**Closed by MaxWang-MS** 2021-07-27 01:21 UTC
Labels: Documentation
