### ISSUE TITLE
[Bounds Control] Activate by proximity and pointer not working

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#9959] opened 2021-06-10 16:35 UTC
## Describe the bug

When I create a Bounds control for a 3D model (even primitive like cube), with the setting Activation to "Activate by proximity and Pointer", a simple white bounds appear by default and never fade away.

My use case is to put an object at children of a GameObject with the BoundsControl. But the issue appear even with the component directly on the object.

## To reproduce

1. Create a cube in a scene
2. Add Bounds control
3. Set Activation to "Activate by proximity and Pointer"
4. Play
5. Option : Deactivate the MeshRenderer to see the bounds

## Expected behavior

No bounds should appear if I don't touch/point the object.

## Screenshots

![WhiteBound](https://user-images.githubusercontent.com/11636956/121562472-c56a4000-ca19-11eb-8c24-55831ae41f15.png)

Note : I deactivate the MeshRenderer of the object (a cube) to better see the bounds.

## Your setup (please complete the following information)

- Unity Version 2019.4.22f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment] 2021-06-14 18:13
Hi, thanks for reporting this. I'll investigate this along with the other `BoundsControl` issues I'm checking out.

**Comment by Zee2** [comment] 2021-06-28 23:22
This is interesting. This seems to be a "working as intended" situation, but I am inclined to agree with you that this is not what the end user ought to expect. I'll open a discussion with the team. Linking @CDiaz-MS @thalbern to this.

The situation is that everywhere in `BoundsControl` code, the "bounds" (really, the `Links`) are not coded to obey the current visibility rules. If they're configured in their config profile to be visible, then they will _always_ be visible (as long as the target/attached object is visible). The handles (rotation, scale, translation) are coded to obey an `isVisible` boolean, defined as:

```
bool isVisible = (active == true && wireframeOnly == false);
```

You'd think that `wireframeOnly` would then, in fact, determine whether the "wireframe" (I guess, the links?) would be visible; but it does not. The links are never toggled according to any visibility rule.

```
links.Reset(active, actualAxis); // "active" is simply whether the entire BoundsControl system is active or not
```

That's why this seems like it's a "working as intended" situation; everything in the code points to the links being intended to always be visible if the entire BoundsControl is active.

Again, I'd be inclined to agree with @Kent1LG that it is very strange that the links/box does not follow the visibility/activation logic that the rest of the BC system does.

**Comment by Kent1LG** [comment] 2021-06-29 08:30
Hey Finn,

Thank you for the update, I understand the situation. Even if the code is not intended for now to make appearing the link/wireframe with the proximity. 
Currently, the project I am working on have unity 2019.4 dependency, so until I found a way to use Unity 2020.3 I will not update my MRTK version. I may miss the fix when it will be released. Thereby, did you know a way (even a tricky one) to make it work on the MRTK 2.6.1 ?

**Comment by Zee2** [comment] 2021-06-29 16:26
So, it is actually very easy to hide the links display!

Check out the BoundsControlExampleScene. The coffee cups in that scene are configured in many different ways, and most of them have the links disabled. You can disable the links by going into the BoundsControl inspector, and toggling "links visible" in the configuration profile. (You may need to create a config profile asset through the dropdown, as shown in the second picture.)

![image](https://user-images.githubusercontent.com/5544935/123833986-c75a4d00-d8bb-11eb-834f-0bec5ae467fe.png)
![image](https://user-images.githubusercontent.com/5544935/123833996-ca553d80-d8bb-11eb-91cc-5234765c119b.png)

The result of this will be that the links display is permanently disabled. You will still have an outline of the box/bounds, through the Box Display.

![image](https://user-images.githubusercontent.com/5544935/123834201-025c8080-d8bc-11eb-88ba-233627eb9279.png)

Again, the issue discussed above is only for _automatically_ disabling the wireframe. As you can see in the bounds control example scene, you can just disable the wireframe/links in the profile and you'll be fine!

**Comment by Kent1LG** [comment] 2021-06-30 11:45
Awesome, thank you for the information!

**Comment by Zee2** [comment] 2021-07-19 21:24
OK, I'm going to close this now; this seems to be intended behavior at least for now. We may want to look into this in the future to improve `BoundsControl`, but the provided solution works for the functionality expected by the customer.

**Closed by Zee2** 2021-07-19 21:24 UTC
Labels: Bug
