### ISSUE TITLE
Interactions&colliders are not detected in multi-scene system

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#9460] opened 2021-03-07 12:22 UTC
## Describe the bug

Colliders are not detected in multi-scene system - hence all other functionality is not working.

## To reproduce

1. Create a multi-scene system profile with content scenes (manual managed builds)
2. Open PrimaryPointerExample and set it as first content scene
3. Assign the profile
4. Load first  
5. Run the project
6. Cheese is not detected - ie. pointer is not hitting the collider

## Expected behavior

Interactions should be available.

## Your setup

- Unity Version 2020.2.6
- MRTK Version 2.6.0

## Target platform

- Oculus
- Standalone

**Comment by polar-kev** [comment] 2021-03-17 18:08
@elbuhofantasma, can you please repro this on Oculus?

**Comment by davidkline-ms** [comment] 2021-05-24 20:35
@eusebiu, are you able to reproduce this on the Unity 2020 LTS (2020.3)?

**Comment by eusebiu** [comment] 2021-05-25 08:46
> @eusebiu, are you able to reproduce this on the Unity 2020 LTS (2020.3)?
I haven't tested on that version. If this is not reproducible on the LTS, you can close it.

**Comment by elbuhofantasma** [comment] 2021-05-25 19:53
@eusebiu I was unable to repro this on the LTS or with the versions that you listed above. I am closing this issue since it seems to be fixed in the LTS.

**Closed by elbuhofantasma** 2021-05-25 19:53 UTC
Labels: Bug
