### ISSUE TITLE
Functionality of eye tracking fails depending on the language.

### ISSUE THREAD

**Issue by adrian-ArXr** [microsoft/MixedRealityToolkit-Unity#10603] opened 2022-05-20 14:48 UTC
## Describe the bug

 The funcionality of eye tracking is failing when we execute the program in English but when we do that in German is working properly. I use the script "Gazeprovider" from Microsoft and I don't know if is a bug from  MRTK or if someone has the same problem. This problem is detected in HL2.

## Expected behavior
Eye gaze should have the same behaviour in English as in German. 

## Your setup 

- Unity Version [2020.3.34f1]
- MRTK Version [v2.7.2]
-
![image](https://user-images.githubusercontent.com/105932042/169553680-9431d1db-392b-4bcb-8b78-b8e5bf0d9b71.png)

## Target platform

- HoloLens 2
- OpenXR

.

**Comment by MaxWang-MS** [comment] 2022-05-23 18:20
Closing as this is a duplicate of #10604.

**Closed by MaxWang-MS** 2022-05-23 18:20 UTC
Labels: Bug
