### ISSUE TITLE
The pointer you are trying to remove does not exist in the mapping dict!

### ISSUE THREAD

**Issue by dahaideyu** [microsoft/MixedRealityToolkit-Unity#11783] opened 2023-09-19 05:26 UTC
## Describe the bug

when I  air tap any button 
it will happen
## To reproduce

1. Go to 'sense'
2. Click on 'Button'
 

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.40f1]
- MRTK Version or Commit [e.g. v2.0] [e.g. [b026319](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/b0263190f4cf7636ec4aacb08d4224bcc5ec5719)]

## Target platform (please complete the following information)

 
- HoloLens 2
 

## Additional context

The pointer you are trying to remove does not exist in the mapping dict!
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler.OnSourceLost (Microsoft.MixedReality.Toolkit.Input.SourceStateEventData) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Services/InputSystem/MixedRealityInputModule.cs:435)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem/<>c:<.cctor>b__244_1 (Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler,UnityEngine.EventSystems.BaseEventData) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Services/InputSystem/MixedRealityInputSystem.cs:963)
UnityEngine.EventSystems.ExecuteEvents:ExecuteHierarchy<Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler> (UnityEngine.GameObject,UnityEngine.EventSystems.BaseEventData,UnityEngine.EventSystems.ExecuteEvents/EventFunction`1<Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler>)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:DispatchEventToObjectFocusedByPointer<Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler> (Microsoft.MixedReality.Toolkit.Input.IMixedRealityPointer,Microsoft.MixedReality.Toolkit.Input.BaseInputEventData,bool,UnityEngine.EventSystems.ExecuteEvents/EventFunction`1<Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler>) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Services/InputSystem/MixedRealityInputSystem.cs:696)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:HandleEvent<Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler> (UnityEngine.EventSystems.BaseEventData,UnityEngine.EventSystems.ExecuteEvents/EventFunction`1<Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler>) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Services/InputSystem/MixedRealityInputSystem.cs:464)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:RaiseSourceLost (Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource,Microsoft.MixedReality.Toolkit.Input.IMixedRealityController) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Services/InputSystem/MixedRealityInputSystem.cs:953)
Microsoft.MixedReality.Toolkit.Input.BaseInputSimulationService:RemoveControllerDevice (Microsoft.MixedReality.Toolkit.Utilities.Handedness) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Providers/InputSimulation/BaseInputSimulationService.cs:178)
Microsoft.MixedReality.Toolkit.Input.BaseInputSimulationService:UpdateControllerDevice (Microsoft.MixedReality.Toolkit.Input.ControllerSimulationMode,Microsoft.MixedReality.Toolkit.Utilities.Handedness,object) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Providers/InputSimulation/BaseInputSimulationService.cs:88)
Microsoft.MixedReality.Toolkit.Input.InputSimulationService:LateUpdate () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Providers/InputSimulation/InputSimulationService.cs:386)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:LateUpdate () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Services/BaseDataProviderAccessCoreSystem.cs:67)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:LateUpdate () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Services/InputSystem/MixedRealityInputSystem.cs:271)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit/<>c:<LateUpdateAllServices>b__74_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Services/MixedRealityToolkit.cs:1071)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder (System.Action`1<Microsoft.MixedReality.Toolkit.IMixedRealityService>) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:LateUpdateAllServices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Services/MixedRealityToolkit.cs:1071)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:LateUpdate () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@3bad99c89252/Core/Services/MixedRealityToolkit.cs:735)

**Comment by AMollis** [comment] 2023-10-31 16:08
Closing issue since it's missing valid description and valid reproduction steps.  Please create a new issue if you are able to provide.

**Closed by AMollis** 2023-10-31 16:08 UTC
Labels: Bug
