### ISSUE TITLE
NearInteraction not working with MRKeyboardInputField prefabs

### ISSUE THREAD

**Issue by Spoon2311** [microsoft/MixedRealityToolkit-Unity#9579] opened 2021-03-30 14:48 UTC
## Describe the bug

Entering the HandInteractionExamples Demo, there is a MRKeyboardInputField_UGUI which calls the Keyboard when entering into it with the index finger (near interaction).
Using either the MRKeyboardInputField_TMP or MRKeyboardInputField_UGUI prefab from the MRTK it won't call the Keyboard when near interacting with it.

## To reproduce

1. Create a Scene
2. Drag both MRKeyboardInputField_TMP and MRKeyboardInputField_UGUI prefabs into the scene
3. Build scene onto Hololens
4. using far interaction the keyboard will be called, using near interaction it won't.

## Expected behavior

I would expect the Prefabs to behave the same as in the Demo Scene. 
(Or have I missed to add some scripts, did check though? :S)

## Your setup (please complete the following information)

- Unity Version 2019.4.21f1
- MRTK Version 2.6.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment] 2021-03-30 16:12
@MaxWang-MS Do these prefabs need NearInteractionTouchable or something added to them for near interaction?

**Comment by Spoon2311** [comment] 2021-03-30 16:15
@keveleigh  I tried adding the NearInteractionTouchable (plane) and then in an other try adding a boxcollider, both didn't work.

Also I can't find a difference to the Demo scene in terms of components that might be different to the prefabs.

**Comment by MaxWang-MS** [comment] 2021-03-30 20:13
I do not think that is the expected behavior. Could you try the MixedRealityKeyboard Example scene and let us know whether that works for you?

**Comment by Spoon2311** [comment] 2021-03-31 12:21
@MaxWang-MS Hey Max, just tested the MixedRealityKeyboard Example scene.
Sadly it didn't work either, using Far Interaction the Keyboard popped up, using Near Interaction for both InputFields the Keyboard didn't show.

**Comment by Spoon2311** [comment] 2021-04-12 09:17
@MaxWang-MS Hey Max, thanks for Triaging the bug.
Can you already say by when it will be fixed or in which next MRTK release it will come?

We're going to need this feature for our clients.
Thanks

**Comment by MaxWang-MS** [comment] 2021-04-13 04:45
After looking into the issue I realized that this is not a bug in code - it's just the MixedRealityKeyboardExample scene is not configured for near interaction. In that scene select the Canvas GameObject, then in the inspector click on the "Add NearInteractionTouchableUnityUI" button under the Canvas section, and then go to the newly added near interaction section select pointer in the events to receive dropdown. Please let me know if this works for you.

**Comment by MaxWang-MS** [comment] 2021-05-19 18:44
Fixed via #9816

**Closed by MaxWang-MS** 2021-05-19 18:44 UTC
Labels: Bug
