### ISSUE TITLE
Spatial Observer on Hololens 1 when using XR SDK

### ISSUE THREAD

**Issue by 0tobsam0** [microsoft/MixedRealityToolkit-Unity#8201] opened 2020-07-22 12:54 UTC
## Bug Description

When using MRTK 2.4.0 with the Unity XR SDK to develop for Hololens 1, the Spatial Observer Mesh is offset dramatically from reality.

## Issue Reproduction

- Create a new project, import MRTK 2.4.0 (Foundation, Tools and Extensions)
- Switch Platform to UWP (Device: Hololens, Architecture: x86)
- Add the XR Plugin Management package using Unity's Package Manager
- Use MRTK Utilities to apply project Settings and configure the scene
- Configure MRTK to use the XR SDK Profile
- Activate the Spatial Observer with visible Mesh
- Export to Hololens and enjoy the offset environment mapping

## Expected behavior

Same as without using XR SDK.

## Screenshots

Not noticable in screenshots, because it's a depth offset.

## Your setup (please complete the following information)

- Unity Version 2019.4.4f1
- MRTK Version 2.4.0

## Target platform (please complete the following information)

- HoloLens 1 using XR SDK

## Additional context

- Clean project, no overhead stuff running, tried different Spatial Observers other than "XR SDK Windows Mixed Reality Spatial Mesh Observer", which should be the right one.

**Comment by keveleigh** [comment] 2020-07-22 17:02
This sounds like the same root cause as https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8024. A fix is in progress

**Comment by 0tobsam0** [comment] 2020-07-23 06:31
Yeah, seems similar, can definitely confirm that behaviour for Unity 2019.4.4f1 LTS.

**Comment by keveleigh** [comment] 2020-07-24 17:16
I'm gonna close this issue and use #8024 for tracking the underlying problem.

**Closed by keveleigh** 2020-07-24 17:16 UTC
Labels: Bug, XR SDK
