### ISSUE TITLE
Scene Understanding: selected surface types in inspector differ from actual behaviour

### ISSUE THREAD

**Issue by mihaits** [microsoft/MixedRealityToolkit-Unity#10306] opened 2021-11-10 13:27 UTC
## Describe the bug

This is happening to me when setting the surface types in the MRTK profile in inspector. It seems like the SpatialAwarenessSurfaceTypes enum isn't properly mapped to the dropdown. All I can say for sure is that Unknown corresponds to Floor now.
Setting IMixedRealitySceneUnderstandingObserver.SurfaceTypes flags in code works fine.

## To reproduce

Enable Spatial Awareness System.
Add a Windows Scene Understanding Observer.
Check  Infer regions, Request Plane Data, Request Mesh Data.
Select desired surfaces.
Observe as the returned meshes/planes differ from the desired ones.

## Your setup

- Unity 2021.1.28f1
- MRTK 2.7.3
- Scene Understanding 0.6.0 package

## Target platform

- HoloLens 2

**Comment by mihaits** [comment] 2021-11-10 13:29
might be a duplicate of #9987 but it's closed

**Comment by MaxWang-MS** [comment] 2021-11-19 23:37
Closing as this is a duplicate of #9987 and the fix will be shipped soon!

**Closed by MaxWang-MS** 2021-11-19 23:37 UTC
Labels: Bug, Urgency-Soon
