### ISSUE TITLE
Input action references are ill-defined

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4330] opened 2019-05-14 00:09 UTC
(Ported to GitHub, reference 21340634)

Input actions are created by adding an entry to the table of input actions in the input actions profile. On creation, they get their ID set to their index in the table. When a user sets an input action in a script property, e.g. the pose action in a pointer, the ID gets serialized with it. This is problematic because:

1. Removing and adding entries in the actions table may yield actions with the same ID
2. Assuming that IDs are unique within an input actions profile, they don't uniquely identify actions across profiles. As we don't serialize a reference to the profile with the ID, when loading it you don't really know which action it originally referred to.

My preferred solution for this is to make actions assets (scriptable objects), so they can referred to from any scene in a well defined manner.

**Comment by keveleigh** [comment] 2019-05-14 18:09
Dupe of #4083

**Closed by keveleigh** 2019-05-14 18:09 UTC
Labels: Bug
