### ISSUE TITLE
MixedRealityKeyboard doesn't work well

### ISSUE THREAD

**Issue by AlexPiro** [microsoft/MixedRealityToolkit-Unity#8957] opened 2020-11-17 17:10 UTC
I try to use the MixedRealityKeyboard and use the sample script provided in the exemple. I'm doing something like a form but not using the Unity UI elements, as there is too much bugs.
My keyboard opens well and work well the first time, I can hide it or commit my text it works very well. Then if I try to re-open it, the keyboard appear but nothing happens when 'touching' letters. The MixedRealityKeyboardPreview doesn't show any character.

1. Modify the method "OpenSystemKeyboard" of "SystemKeyboardExemple" like that : 
`        public void OpenSystemKeyboard(string text)
        {
#if WINDOWS_UWP
            wmrKeyboard.ShowKeyboard(text, false);
#elif UNITY_IOS || UNITY_ANDROID
            touchscreenKeyboard = TouchScreenKeyboard.Open(string.Empty, TouchScreenKeyboardType.Default, false, false, false, false);
#endif
        }`
2. Create a 2 buttons and a gameobject with the modified "SystemKeyboardExemple" script
3. Link actions to buttons to open the keyboard with each button and add a specific text 
4. Compile and run
5. Click on the first button, you will see the keyboard with the first text in the preview.
6. Close to hide keyboard ==> Keyboard and preview disappear
7. Click on the second button, the  keyboard appears and the second text appears in the preview, but nothing happens on touching keys ...

It seems to work if we don't hide the preview .. It's probably related to that, but I did so many tests, I'm a little bit lost ... I'm stuck with this problem for a week now. I thought that keyboard input was a basic of a toolkit like that MRTK, we probably don't have the same priorities ...

My setup :
- Unity Version 2019.4.8 and 2019.4.14
- MRTK Version 2.5.1 from UPM

Target platform
- HoloLens 2

**Comment by MaxWang-MS** [comment] 2020-12-16 21:02
Could you try the #9038 PR and let me know if the issue persists? I was not able to reproduce using that PR so it should be fixed by that.

**Comment by MaxWang-MS** [comment] 2021-01-27 22:25
Closing the issue for now and please feel free to reopen if the problem still persists in the mrtk_development branch.

**Closed by MaxWang-MS** 2021-01-27 22:25 UTC
Labels: Bug, Keyboard
