### ISSUE TITLE
Oculus Hands (From Hand Tracking) visible at sides when using Controller

### ISSUE THREAD

**Issue by imsumittyagi** [microsoft/MixedRealityToolkit-Unity#9684] opened 2021-04-19 08:34 UTC
Oculus hands are visible at the sides when a user picks up the controllers, It is hindering the view.

## Your setup (please complete the following information)

- Unity Version [2020.2.6f1]
- MRTK Version [2.6.1]

## Target platform (please complete the following information)

- Oculus Quest2

**Comment by keveleigh** [comment] 2021-04-19 16:04
@RogPodge Is this the issue fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9589?

**Comment by RogPodge** [comment] 2021-04-19 16:54
You can toggle the hands off when visualizing the Oculus Controllers with this setting under the XRSDK Oculus Device Manager

![image](https://user-images.githubusercontent.com/39840334/115274065-213cda80-a0f5-11eb-950a-845c982c812d.png)

We realize it's a bit unintuitive given that it's in a separate place from the visualization settings, we're looking to address this in a future framework update.

**Comment by imsumittyagi** [comment] 2021-04-20 05:12
@RogPodge The problem is not about the Controller visualization but about a separate hand mesh that is still visible at the side (near the user's left ear ) when we pick controllers, it disappears when we use hands. Your solution only toggles the controller and hands visuals. That extra hand problem still persists.

**Comment by RogPodge** [comment] 2021-04-20 23:43
We'll need some time to take a closer look at this since it sounds like pretty surprising behavior. Will update in the future.

**Comment by imsumittyagi** [comment] 2021-04-26 04:52
@RogPodge Any solution for this yet ?

**Comment by RogPodge** [comment] 2021-04-26 23:25
On my tracker for this week 🤞

**Comment by RogPodge** [comment] 2021-04-27 22:49
He @imsumittyagi I've tried reproducing this error on Unity 2019.4.19 and 2020.3.5f1 on our latest code and wasn't able to do it. Do you have a video of the behavior or a solution project that reproduces this error?

Thanks!

**Comment by imsumittyagi** [comment] 2021-04-28 08:33
https://user-images.githubusercontent.com/20392525/116372795-69ad7400-a82a-11eb-89d4-19dc1e1f1118.mp4

@RogPodge Here is the video attached for the issue when we pick controller extra hand is visible but not during the hand tracking.

**Comment by RogPodge** [comment] 2021-04-28 19:18
hey @imsumittyagi still having some trouble reproducing locally. Do you have a minimally reproducible example that I might be able to refer to? Information on the profile you are using would also help out here

**Comment by imsumittyagi** [comment] 2021-04-29 04:49
I will share a demo project with you soon

**Comment by imsumittyagi** [comment] 2021-05-01 09:45
@RogPodge  here is the link for the project
Unity Version : 2020.2.6f1
https://www.dropbox.com/sh/mw042pspbyrc91p/AABAXUyzLe7m41zrdQK_AtxGa?dl=0

**Comment by RogPodge** [comment] 2021-05-03 19:21
Good news, this issue seems to be fixed on our latest MRTK version! (currently Version 2.7.0-preview.4 in the feature tool)

As for why it's fixed, does anything come to mind to you @keveleigh? Nothing immediately comes to mind when looking at our commits since 2.6.1, but maybe it ended up getting addressed as you were tackling the OpenXR work items?

**Comment by keveleigh** [comment] 2021-05-03 20:54
@RogPodge Hmm...it's possible! I don't recall anything Oculus-specific, but there were some general XR SDK lifecycle improvements that could have fixed this.

My initial thought was that it could have been https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9338, but that looks like it made it into 2.6.0.

**Comment by RogPodge** [comment] 2021-05-03 21:12
We've had some reports of this happening on hololens, where I had a similar experience with seeing the behavior fixed in 2.7.0. Just wanted to check!

**Comment by imsumittyagi** [comment] 2021-05-04 05:03
@RogPodge that's great news, when we can expect the 2.7.0 in MIxed Reality Feature Tool or Unity Package Manager?

**Comment by RogPodge** [comment] 2021-05-04 18:34
No explicit date yet, but I believe preview packages for 2.7 should be visible currently in the feature tool. Can you confirm @davidkline-ms?

**Comment by RogPodge** [comment] 2021-05-05 18:46
Closing this issue since we've confirmed that it's fixed on Oculus and Hololens in our 2.7.0 builds.

**Closed by RogPodge** 2021-05-05 18:46 UTC
Labels: Bug, Oculus
