### ISSUE TITLE
What is a right way to delete object from Scrolling Object Collection?

### ISSUE THREAD

**Issue by KrasnovPavel** [microsoft/MixedRealityToolkit-Unity#8064] opened 2020-06-16 11:23 UTC
I want to add and remove objects inside Scrolling Object Collection.
Adding is not a problem, but when i am trying to remove object using this code:
`Destroy(ScrollBar.Find("Container").Find("test3")?.gameObject);
ScrollBar.GetComponent<ScrollingObjectCollection>().UpdateCollection()`
I get this:
![image](https://user-images.githubusercontent.com/5003831/84768085-48f67a00-afdc-11ea-94d2-6717c002134a.png)
and also exceptions:

> MissingReferenceException: The object of type 'BoxCollider' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Microsoft.MixedReality.Toolkit.Experimental.UI.ScrollingObjectCollection.HideItems () (at Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1664)
Microsoft.MixedReality.Toolkit.Experimental.UI.ScrollingObjectCollection.LateUpdate () (at Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1038

Is there a better way to remove object?

Specs: Unity 2018.4, MRTK 2.4.0, Hololens 1st gen

**Comment by wiwei** [comment] 2020-06-16 18:04
@vaoliva @thalbern as we talk about doing scrolling object collection graduation.

**Comment by vaoliva** [comment] 2020-06-17 11:25
@wiwei Adding this issue to the scroll graduation list.

**Comment by tank-t-bird** [comment] 2020-06-26 11:04
We have a similar issue if we disable the Collection object and try to reenable it later on. All objects that were in a "masked" state when the object is disabled, remain disabled on reenabling the collection object and the same error gets thrown:  

> "MissingReferenceException: The object of type 'BoxCollider' has been destroyed but you are still trying to access it.
> Your script should either check if it is null or you should not destroy the object."

**Comment by vaoliva** [comment] 2020-07-09 15:33
> We have a similar issue if we disable the Collection object and try to reenable it later on. All objects that were in a "masked" state when the object is disabled, remain disabled on reenabling the collection object and the same error gets thrown:

@tank-t-bird Could you please open a different issue with more info for the reenabling problem you are facing? I have tried to replicate your steps but I couldn't reproduce the error.

**Comment by vaoliva** [comment] 2020-07-09 15:33
Closing as fixed on #8154

**Closed by vaoliva** 2020-07-09 15:33 UTC
Labels: Documentation

**Comment by shahiltp** [comment] 2020-10-06 07:06
i made a fix 

Destroy (object);
after that Invoke("method name ",0.5f);

call scrolling object collection (). updatecollection(); from that new function 

this will make fix

**Comment by Spiderguy-F** [comment] 2024-02-23 14:01
I fixed it by unparenting before destroying the object. Still feels like a bug, though
