### ISSUE TITLE
Migration Window 2.4->2.5 throws error and gets stuck

### ISSUE THREAD

**Issue by TheRisenPhoenix** [microsoft/MixedRealityToolkit-Unity#8733] opened 2020-10-02 05:21 UTC
## Describe the bug

When following the upgrading guide (https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/Updating.html), once I reach the step where I use the migration window to apply migrations with all 3 profiles, for each profile an error "It is not allowed to open a scene in a read-only package" appears.
Console prints the error "ArgumentException: Cannot open scene with path "Packages/com.microsoft.mixedreality.toolkit.foundation/SDK/StandardAssets/Scenes/DefaultLightingScene.unity".
The progressbar for the migration tool gets stuck, the cancel button isn't doing anything. You have to shut down Unity completely.
This happens for all 3 migration profiles.

## Your setup

- Unity Version 2019.4.11f
- MRTK Version 2.4 => 2.5

**Comment by deibu** [comment] 2020-10-02 16:07
It looks like this is being caused by several scenes that are not under "Samples" in the UPM packages.

**Comment by davidkline-ms** [comment] 2020-10-02 16:58
Thanks for filing this. We are investigating.

**Comment by wiwei** [comment] 2020-10-05 21:39
Closing this out, as I believe the change to ignore the packages folder was added with #8740

**Closed by wiwei** 2020-10-05 21:39 UTC
Labels: Bug, Package Management - UPM
