### ISSUE TITLE
Hand tracking Quest 2: InputActionReferences Select and SelectValue not firing action.performed

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#10856] opened 2022-08-10 15:08 UTC
## Describe the bug

@Zee2 [showed me how to trap InputActionReferences directly](https://github.com/LocalJoost/BlogComments/issues/421#issuecomment-1184713692), without doing difficult things like looking up controllers. I detailed what I did [here ](https://localjoost.github.io/MRTK2-to-MRTK3-a-MUCH-SIMPLER-way-to-intercept-a-raw-air-tap-like-with-IMixedRealityPointerHandler/). This works fine on HoloLens2. This does not seem to work on  Quest2. This puzzles me a bit as all other interactors seem to be working fine. Using the controllers, it works fine

## Expected behavior

I expect the Select and SelectValue's action.performed to be triggered on the Quest 2 as well when I use hand tracking and perform an 'air tap'

## Setup 

- Unity Version 2020.3.35f1
- MRTK Version 3 Pre 9
- Mixed Reality OpenXR plugin 1.4.3
- 
## Target platform

- Quest 2

## Additional comments

If requested, I can deliver a full working repo

**Comment by Zee2** [comment] 2022-08-10 18:03
Hey @LocalJoost ! This is actually because Quest (the device itself) doesn't actually generate any input/interactions from their hands, unlike other platforms like HoloLens. So, from the Input System's perspective, unless you go query Facebook-specific OpenXR extensions, there's literally no action at all  :(

Right now, the way we get around this is by "polyfilling" the missing input in our `ArticulatedHandController`s. Basically, if there's no interaction profile/input actions bound for Select, we read joints from our subsystem and fill in the missing information. So, the `XRController`'s `selectInteractionState` will always be correct, regardless of what is going on with the input actions.

I'm aware this is significantly less nice than just binding to the input action...

This was sort of the "quick and dirty" approach, because a more robust way to "polyfill" this would be by actually spinning up "fake" input devices for hands without input actions (i.e., there'd be an entire synthetic input device that would stand in for the missing interaction profile). 

In the future, we will end up getting actual input actions/bindings from Quest for hands. There's actually a cross-vendor OpenXR extension currently in draft (maybe actually ratified by this point? @keveleigh ) that will get us nice pinch/grab/point/etc actions no matter the vendor of hand; the Hand Interaction Profile!

I'm going to close for now as "known, won't fix" but this _**will**_ be improved in the future, either with a more comprehensive polyfill (that actually creates an input device) and/or the platform itself submitting interaction profiles/bindings when the new Hand Interaction Profile is ratified and implemented.

**Closed by Zee2** 2022-08-10 18:03 UTC
Labels: Bug, MRTK3

**Comment by LocalJoost** [comment] 2022-08-10 18:09
Thanks for the clear explanation. So this only works when you are interacting WITH something. The actual gesture does not generate any events. Do I understand that correctly?

**Comment by Zee2** [comment] 2022-08-10 18:16
The flow of input in MRTK3 generally works as follows:

OpenXR device implements an _interaction profile_, which is essentially a spec for what sorts of user actions a device can generate. This includes poses, buttons, triggers, tracking state, velocities, etc.

These interaction profiles then bind to specific input action references in Unity. For example, we have a `Select` input action that things like `trigger` or `primaryButton` will bind down to. 

The `XRController`s on the rig listen to these input actions, and then tell the interactors to fire when the input actions do.

This is the _ideal_ situation. The problem is that some devices (like Quest hands!) don't implement an interaction profile! This means that the hands can have joint data (i.e., the individual joint poses), but **they don't actually bind to an input action.** By default, Quest doesn't submit an actual input "control" for something like "pinch". Therefore, there's nothing that gets bound to our Select input action! 

We resolve this (currently) by making a modification to the `XRController`. Instead of _only_ listening to the input actions, it also combines whatever it hears from input actions with the joint data/pinch progress (from the hand joint subsystem). So, the XRController will set its `selectInteractionState = Active` if the input action tells it to, _**OR**_ the joint data from the hand says it is pinching.

So, the input action still won't work on Quest (for now), but the XRControllers "fill in the gap" with the joint data.

In the future: Quest will implement a hand interaction profile, which will result in valid input actions on Quest.
