### ISSUE TITLE
SurfaceMagnetismSpatialAwarenessExample MRTK 2.4 Hololens2

### ISSUE THREAD

**Issue by roalchaq** [microsoft/MixedRealityToolkit-Unity#8003] opened 2020-06-01 14:23 UTC
## Describe the bug

SurfaceMagnetismSpatialAwarenessExample not working on Hololens2. Working just fine for HoloLens 1. At runtime an error is shown at the bottom left corner saying: Physics: 'BV4 midphase only supported on Intel platforms'.

## To reproduce

Unity 2019.3.14.f1 - Load SurfaceMagnetismSpatialAwarenessExample from MRTK 2.4 and build for ARM64 @ HoloLens 2.

## Expected behavior

As described here: https://docs.microsoft.com/en-us/windows/mixed-reality/surface-magnetism

## Screenshots

https://media.giphy.com/media/eh12wfF1vZugoMk2DF/source.mp4

## Your setup (please complete the following information)

- Unity Version 2019.3.14.f1
- MRTK Version  v2.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment] 2020-06-01 16:40
@roalchaq can you try using 2018.LTS?

@keveleigh looks like a Unity ARM64 issue possibly (https://issuetracker.unity3d.com/issues/bv4-midphase-only-supported-on-intel-platforms-appears-when-exporting-for-android). Note that it has the word 'android' in the link but folks are also reporting this for HL (i.e. ARM64)

**Comment by roalchaq** [comment] 2020-06-01 17:32
Hi there! I tried and it works for Unity 2018 LTS. Could it be related to this other issue? 

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7624

**Comment by brookman** [comment] 2020-06-01 19:22
I can confirm the problem using HL2 with:

- Unity 2019.3.15f1
- MRTK 2.4
- ARM64
- Release

For some reason I don't always see the error message. Sometime the feature fails silently and the object which should stick to the mesh in this example is barely visible and seems to be stretched weirdly or intersecting the mesh.

It works when switching to Debug mode. Of course then the performance is bad.
This is the second problem I have discovered today which only happens in Release mode.
See #7931

**Comment by wiwei** [comment] 2020-06-11 17:33
We've seen a bunch of other reports here around ARM64, but yeah these are all related AFAICT to the linked issue #7624 

We're trying to dig into that now - closing out this issue as a dupe of that one.

**Closed** 2020-06-11 17:33 UTC
Labels: Bug
