### ISSUE TITLE
UPM module doesn't copy shaders correctly when using Unity Editor on MacOS

### ISSUE THREAD

**Issue by ptc-ccrabb** [microsoft/MixedRealityToolkit-Unity#8908] opened 2020-11-05 20:48 UTC
Assets/MRTK/StandardAssets/EditorUtilities/OnLoadUtilities.cs fails to copy shaders when running on MacOS due to a filename sensitivity issue.

The constant `private const string ShaderSentinelFile = "MRTK.Shaders.Sentinel";` refers to a file that is actually named `MRTK.Shaders.sentinel` with a lowercase `s` on `sentinel`.

 On MacOS DirectoryInfo.GetFiles appears to be case-sensitive even if the underlying filesystem is not. This causes the script to not find `MRTK.Shaders.sentinel` and thus not be able to copy the shaders.

## To reproduce

On MacOS

1. Create a new Unity Project
2. Quit Unity
3. Update manifest.json according to the documentation for using MRTK via UPM packages.
4. Launch Unity
5. See error in the console and note that the Shaders did not get copied into the project's assets.

## Expected behavior

No error in the console on launch and Shaders are properly imported into the project's assets.

## Your setup (please complete the following information)

- Unity Version 2019.4.3f1
- MRTK Version v2.5.1

## Target platform

- iOS

**Comment by MaxWang-MS** [comment] 2020-11-05 21:16
@davidkline-ms Looks like a duplicate of #8826

**Comment by ptc-ccrabb** [comment] 2020-11-05 21:38
Agreed; sorry for the dup; this can be closed in favor the existing one.

**Closed** 2020-11-05 21:39 UTC
Labels: Bug
