### ISSUE TITLE
Interactables Not Triggerd by Input Action Voice

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4008] opened 2019-04-17 21:30 UTC
## Describe the bug

Interactables, like PressableButton, are not triggered by Input Action voice commands. However, they _are_ triggered by their own voice commands, which causes confusion.

## To reproduce

Under MRTK Input configuration, create an action:

![image](https://user-images.githubusercontent.com/5230670/56321754-f649d580-612c-11e9-923e-2c2359e6e64e.png)

Under speech commands, create a command that will trigger the action:

![image](https://user-images.githubusercontent.com/5230670/56321828-1e393900-612d-11e9-81ab-964c4aa519b2.png)

Add a **PressableButton** to the scene and subscribe to the OnClick event:

![image](https://user-images.githubusercontent.com/5230670/56321942-5f314d80-612d-11e9-9ed8-9cd5f4573591.png)

Under the **Interactable** section, select the same action defined above but _do not_ define a voice command.

![image](https://user-images.githubusercontent.com/5230670/56322021-88ea7480-612d-11e9-90cc-6081090c4d8d.png)

Run the app and notice that the OnClick handler doesn't fire even when the voice command is spoken. 

If you return to the editor and supply a voice command within the Interactable section it _will_ fire. However it's confusing why this extra voice command exists in the first place.

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version RC1

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

**IMPORTANT:** We highly recommend that this be resolved using a generic handler such as the one described in #4006

**Comment by julenka** [comment] 2019-05-29 16:48
Duplicate of #4598

**Closed by julenka** 2019-05-29 16:48 UTC
Labels: 0 - Backlog, Bug, Speech, UX Controls, UX Controls - Interactable
