### ISSUE TITLE
Near hand interaction is not accurate in the remote player mode

### ISSUE THREAD

**Issue by cz2011301070** [microsoft/MixedRealityToolkit-Unity#11534] opened 2023-05-03 15:05 UTC
## Describe the bug
I used usb connected Hololens 2 to my computer and ran the remote player mode on my hololens.
When I run the Demos (e.g., HandTracking) , the near object interaction using index finger is not accurate.
However, if I deploy the project to my hololens 2, using the index finger to touch buttons was accurate

## To reproduce

1. Go to 'Assets\MRTK\Examples\Demos\HandTracking'
2. Click on 'HandInteractionExamples' unity scene
3. play
4. use index finger to touch buttons or the piano key
5. the Hand cursor is far from the pinch finger. If you use thumb to touch button, it's relatively accurate

## Screenshots
![image](https://user-images.githubusercontent.com/17682668/235956045-c3c89638-42ed-47cb-95c0-8bda21a57f41.png)

## Your setup (please complete the following information)

- Unity Version [2021.3.18f1]
- MRTK Version [v2.0]

## Target platform (please complete the following information)

- Unity editor, USB remote player

**Comment by AMollis** [comment] 2023-05-03 23:16
@cz2011301070  are you remoting from the Unity Editor?  Or remoting from a compiled PC application?

**Comment by cz2011301070** [comment] 2023-05-05 08:48
Yes. I am using the remote player and running the program from my computer unity editor

**Comment by cz2011301070** [comment] 2023-05-05 08:58
BTW, if I deploy the program to Hololens, the near interaction worked fine. However, I have to use the remote player mode in my project due to some performance considerations. Is there any solution to this problem?

**Comment by AMollis** [comment] 2023-05-06 04:08
@cz2011301070 I'm unable to reproduce the problem you've described in Unity 2021.3.23f1.   It appears that you are using the "HandInteractionExamples" scene.  Did you make any changes to this scene?

Here's what I tried:
1. Opened HanInteractionExamples scene in Unity 201.2.23
2. Selected Windows Standalone build target
3. Project Settings > XR Plug-in Management > Windows Settings
    1. Checked Open XR 
    2. Checked Windows MR feature group
    3. Checked Holographic Remoting remote app feature group
4. Project Settings > XR Plug-in Management > OpenXR > Windows Settings
   1. Added "Eye Gaze Interaction Profile"
   2. Added "Microsoft Hand Interaction Profile"
   3. Kept all other defaults
5. Project Settings > XR Plug-in Management > Project Validation > Windows Settings
   1. Resolved all errors and warnings
6. Mixed Reality > Remoting > Holographic Remoting for Play Mode
    1. Enter host name/ip
    2. Enable Holographic Remoting for Play Mode
    3. Enabled Audio
    4. Kept all other defaults
7. Hit play
8. Verified 'poke cursor' is at finger tip, and verified that all near touch and grab interactions work as expected

I'm using the latest MRTK2 and latest Mixed Reality Open XR Plugin. @cz2011301070 please verify you are using the same versions.

1. **MRTK2** version 2.8.3
2. **Mixed Reality Open XR Plugin** version 1.8.0

@cz2011301070 can you also share a sample project that demonstrates the misalignment?  Perhaps there is a specific project or scene configuration that is causing the misalignment. I can verify this if you provide a sample.

**Comment by cz2011301070** [comment] 2023-05-06 11:23
Thanks so much for your reply. It's really good to know you can successfully use the near touch in the remote play mode.

However, I still cannot make it on my computer. I tried again and still failed. Here is how I did:
1. git clone the latest version of the MRTK from here: https://github.com/microsoft/MixedRealityToolkit-Unity
2. Open the project with Unity 2021.3.18f1 (Note: I was using this version while not Unity 2021.3.23 or Unity 2021.2.23 which were mentioned in your reply above)
3. Build Settings->Player settings-> XR Plug-in Management-> Windows Settings-> toggled the OpenXR (the Windows Mixed Reality feature group was toggled by default, By now there is no Holographic Remoting app feature group)
4. open the MixedRealityFeatureTool.exe downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=102778
5. added the path of the MRTK unity project to the MixedRealityFeatureTool.exe and selected Platform Support->Mixed Reality OpenXR plugin 1.8.0->get features->import to unity 
6. go back to unity XR Plugin-in Management-> OpenXR. Added "Eye Gaze Interaction Profile" Added "Microsoft Hand Interaction Profile"; Checked Holographic Remoting remote app feature group and Windows Mixed Reality under the OpenXR feature Groups. 
7. Switch platform to Universal windows platform
8. fix all the errors in the XR plugin-in Management use the project validation
9. right click on the asset window->reimport all
10. run the "HandInteractionExamples" scene
11.  use index finger to touch the button above the piano. when the index finger get close to the button, the Poke cursor shows but is far from the index finger
![image](https://user-images.githubusercontent.com/17682668/236620994-6ff106cb-4412-4cac-879d-e6ce38f05f11.png)

BTW, I checked my Holographic Remoting Player in my hololens and found its version is v2.9.1.0. I downloaded it from the Microsoft store. I cannot find the version 10.0.22621.1064 you mentioned



![image](https://user-images.githubusercontent.com/17682668/236621046-46c9cf1a-02fc-4f68-845c-21516186aabf.png)

**Comment by cz2011301070** [comment] 2023-05-06 13:09
One of the differences between deploying the app to the headset and running it in unity through remote player is  the former enabled "Initialize XR on Startup" in the XR plugin management. The remote mode and the initialize XR on startup cannot be selected at the same time.

**Comment by AMollis** [comment] 2023-05-06 23:26
@cz2011301070  oops....I was looking at the incorrect app in the device portal.  I am also using Holographic Remoting Player version 2.9.1.0.  Updating my previous comment

**Comment by AMollis** [comment] 2023-05-06 23:52
@cz2011301070 while wearing the device, does the cursor align to your finger?

I ask because remoting doesn't support the Holographic 3rd Renderer.  Meaning that PV camera images won't align correctly with holograms.  When remoting, PV camera images are composited with the holograms from the perspective of the right eye.

Non-remoting scenarios support the 3rd rendered.  Meaning that holograms are re-rendered from the PV camera's perspective, so holograms will align correctly with PV camera images.  

All this is not very well documented, but in the MRTK2 camera settings, you can find this
![image](https://user-images.githubusercontent.com/36461279/236650761-52438ae5-e10d-4444-926d-e27914cbb286.png)

**Comment by cz2011301070** [comment] 2023-05-07 09:53
While wearing the device the cursor didn't align to my finger when my finger approached to the buttons （when the Poke cursor was activitated）. This is the reason why I report this problem here

I made the screen shot using the Windows Device Portal and as you said the PV camera images didn't align correctly with holograms as well. However, I don't care about this. I want to figure out how to make accruate near object touching interaction inside the Headset using the remote player mode.

**Comment by AMollis** [comment] 2023-05-08 04:08
@cz2011301070 unfortunately we still can't reproduce the issue on our side.  Can you share the sample project you are using?

**Comment by cz2011301070** [comment] 2023-05-08 11:29
I just used the latest MRTK project git cloned from here: https://github.com/microsoft/MixedRealityToolkit-Unity.git
I installed the Openxr plugin using the MixedRealityFeatureTool.exe
And I made no more change to the project.

From your side, can you accurately touch the button above the pinao? or Can you play the piano accurately just use your index finger?
If so, can you plz share your unity version and MRTK version? And it would be really helpful if you can share a screen short to demonstrate the interaction from your side

**Comment by cz2011301070** [comment] 2023-05-08 11:53
I just used the latest MRTK project git cloned from here: https://github.com/microsoft/MixedRealityToolkit-Unity.git
I installed the Openxr plugin using the MixedRealityFeatureTool.exe
And I made no more change to the project.

From your side, can you accurately touch the button above the pinao? or Can you play the piano accurately just use your index finger?
If so, can you plz share your unity version and MRTK version? And it would be really helpful if you can share a screen short to demonstrate the interaction from your side

**Comment by cz2011301070** [comment] 2023-05-08 11:57
![image](https://user-images.githubusercontent.com/17682668/236817129-572a7b07-9c68-4ea3-a172-eb444b18b11f.png)

As you can see, I enabled Hand Mesh visualization mode and Hand joint visualiztion mode in the Editor. However, I never saw my hand joint in the remote player mode. I learnt from the internet that it would be not supported to show the mesh in the remote player mode however, the hand joint mode should be supported in the editor remote player mode. However, it didn't work.

My plan was to show the Hand joint and check whether the Poker cursor is aligned with the index hand joint or not. However, the Hand joint can not be shown in my project. Can you please try and maybe kindly show the screen shot if it works in your side?
Thanks so much for your help

**Comment by AMollis** [comment] 2023-05-08 17:51
@cz2011301070 as mentioned earlier a screenshot will always demonstrate misalignment, since remote holograms in the PV Camera are always rendered from the right eye perspective, and not the from the PV Camera.   So not sure how this would help :)

I'll take a look at your project.

Also, can you please provide the OS version that you are using?

**Comment by AMollis** [comment] 2023-05-08 20:47
@cz2011301070 Thank you for your issue and your willingness to provide additional information.  Unfortunately, at this time, I don't believe this issue is MRTK related.  The issue is likely something wrong with the HoloLens remoting platform.

Given this, can you please open a new issue with our support team?  Go to [aka.ms/hlsupport](https://aka.ms/hlsupport), click through the forms, and enter in the following details:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/36461279/236930615-68dfe4b8-ec59-473d-858e-5a9ce1319ebc.png)

- **Product Family.** Mixed Reality
- **Product.** HoloLens Devices
- **Product Version.** HoloLens 2
- **Issue.** Tools
- **Describe Issue.**  Unity - Remoting

After you submit this support form, our support team will be in touch with you.

In the meantime, I will be closing this issue as Not Reproducible with respects to MRTK.  Thank you again for your time.

**Closed by AMollis** 2023-05-08 20:47 UTC
Labels: Bug, Need More Info
