### ISSUE TITLE
FacadeHandler destroys facade objects in order, throws error

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6794] opened 2019-12-04 20:31 UTC
## Describe the bug

The FacadeHandler in DestroyFacades, does destruction in order of the for loop which causes an invalid enumerator. The loop should be done in reverse so the enumerator is not corrupted as objects are removed. 

## To reproduce

Select None as MRTK profile
Look at console of errors

## Expected behavior

Should destroy all facades correctly without error

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by keveleigh** [comment] 2019-12-04 20:43
Duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6777?

**Comment by keveleigh** [comment] 2019-12-04 22:46
Possibly also https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6762

**Comment by Troy-Ferrell** [comment] 2019-12-04 23:10
@keveleigh yes and yes

**Closed** 2019-12-05 02:20 UTC
Labels: Bug, Editor, Release Blocker
