### ISSUE TITLE
OpenXR Reading Mode Doesn't Seem to Function as Intended

### ISSUE THREAD

**Issue by ARGs-code** [microsoft/MixedRealityToolkit-Unity#11405] opened 2023-02-23 18:06 UTC
## Describe the bug
Using The Reading Mode Demo from the MRTK Examples with OpenXR does not result in any change in behavior of the application, except for a downstepping of the resolution of the application when using the slider.

This is not the intended behavior as I understand it, as Reading Mode is supposed to allow for a crisper image on the display in exchange for a reduced Field of View. Neither of these things occur in the Sample Scene when using Unity with OpenXR.

## To reproduce

1. Start a Unity Project with Unity 2020.3.x
2. Switch to UWP Platform
3. Use MRTK Feature tool to install MRTK 2.8.3 and OpenXR support
4. Complete the setup for MRTK 2.8.3 and setup your project with OpenXR when prompted by the setup process of MRTK
5. Import the Reading Mode Sample Scene from the MRTK Samples Package
6. Open the Reading Mode Sample Scene add it to your build list and build and deploy to your Hololens 2
7. In the deployed application turn reading mode on and off, notice there is no change in the application behavior.
8. In the deployed application use the slider to drag left and right, notice the only change is that the display resolution massively decreases when the slider is slide to the left and returns to normal when slid all the way to the right.

## Expected behavior

Turning on Reading Mode should improve presentation of text and images and reduce the FOV of the display.

## Your setup (please complete the following information)

- Unity Version 2020.3.41f1
- MRTK Version 2.8.3
- OpenXR

## Target platform (please complete the following information)
- HoloLens 2

## Additional context

This problem was initially reported a while back and appears to have never been resolved as I am seeing the exact same behavior in my current project: 
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9595

**Comment by keveleigh** [comment] 2023-02-27 20:56
Ahh yeah, I never really hooked this up for OpenXR, iirc. We may need some support on the OpenXR runtime or Mixed Reality OpenXR Plugin side (pinging @yl-msft). This issue can probably be closed as a duplicate of #9595, but I no longer have triage permissions 🙃

**Comment by ARGs-code** [comment] 2023-03-01 16:20
Thanks for this insight @keveleigh sorry to hear you can no longer triage.

We are hoping this can be resolved or triaged soon, as OpenXR is the pipeline suggested and pushed by MRTK's own documentation and it's the pipeline we use for all our projects.

**Comment by AMollis** [comment] 2023-03-07 00:29
Closing as a duplicate of #9595

**Closed by AMollis** 2023-03-07 00:29 UTC
Labels: Bug, MRTK2
