### ISSUE TITLE
MRTK + OpenXR + Oculus Quest2

### ISSUE THREAD

**Issue by stychu** [microsoft/MixedRealityToolkit-Unity#9497] opened 2021-03-12 21:57 UTC
## Describe the bug

I was trying to play with Oculus Quest and MRTK. I've downloaded respective packages from the MRTK tool and adjusted XR plugin management in Unity for the OpenXR (without checking the Windows Mixed Reality feature set under OpenXR)

Few things I noticed. (I just wanted to play with examples using only controllers no hand tracking)

1. After setting DefaultOpenXRConfigurationProfile in some example scenes every time I enter the Play Mode the `MixedRealityPlayspace` is always above all UI/UX elements. (Like 5 meters above)

2. On close view to the UI Letters seems crisp but when getting far away from the UI elements especially those ones on the blue background I can see Every letter being overlapped with a white box

3. White Boundary on the blue UI elements is getting hella jaggy when getting far away. (seems okay on the close range)

4.  **Important one** when I'm in Play Mode via Oculus Link and I enter the Oculus Home menu and try to quit play mode from within the pulpit in Oculus environment  after play mode exits and couple of seconds later there seems to occur some crash in Unity which closes whole Unity application

## Expected behavior

1. After entering playmode I should be placed around the same level as the UX elements
2. Letters should not be getting the size white box overlap when getting away from UI
3. UI should not jitter so hard
4. Should not kill Unity after exiting playmode

## Screenshots

![image](https://user-images.githubusercontent.com/9383657/111000509-73663f80-8382-11eb-9b31-b8ebd2698ec9.png)
![Unity_oaeAviFsxR](https://user-images.githubusercontent.com/9383657/111002661-1d939680-8386-11eb-9512-3a4608829cfc.png)

![OculusScreenshot1615585697](https://user-images.githubusercontent.com/9383657/111002735-37cd7480-8386-11eb-8cec-1d84f40bc260.jpeg)

![OculusScreenshot1615585758](https://user-images.githubusercontent.com/9383657/111002754-3e5bec00-8386-11eb-879b-a6813cfa5c39.jpeg)

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.2.3f/2020.3.0f1]
- MRTK Version [e.g. v2.6.1]

## Target platform (please complete the following information)

- OpenVR

**Comment by RogPodge** [comment] 2021-03-12 22:44
Hey @stychu , thanks for filing the issue! Just a few comments and question on your points

1. We're currently working on a way to normalize setting the floorHeight for VR applications. The reason for the current behavior is likely the OculusDataProvider moving the camera rig based on the floorHeight set within the Quest itself, and offsetting the camera that many units from the origin. We don't have the best way of fixing this right now, though the floor offset does make it so you can teleport down to ground level and have the behavior be reasonable.

2. How far away are you when you notice the white outline appearing on the letters? I'm wondering if there exists a solution like we did for icons here https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8739 that we can also do for text @Cameron-Micka 

3. Probably a similar thing with making our shaders work better on VR devices

4. Unfortunately we don't officially support using MRTK wtih Oculus Link yet, look for a better/improved experience with this particular development experience in the future.

**Comment by stychu** [comment] 2021-03-14 16:14
> 2\. How far away are you when you notice the white outline appearing on the letters? I'm wondering if there exists a solution like we did for icons here #8739 that we can also do for text @Cameron-Micka

In the *Hand Interaction Example*
Having set the `MixedRealityPlayspace ` at 0,0,0 origin (position and rotation)

I'm starting to see the outline of the letters when I move the whole `SceneComponent` to:
```
Position - Vector3(-0.419999987, 1.38999999, 0.829999983)
Rotation - Quaternion(0.010094991,0.0563500561,-0.000569844968,0.998359919)
(Assuming the problem with the Camera Rig offset in place #1)
```
(Looking at the middle UI component "Hand Interaction Examples" title under the MRTK logo)



> 4. Unfortunately we don't officially support using MRTK wtih Oculus Link yet, look for a better/improved experience with this particular development experience in the future.

Sure, I will surely do it! That's not that big of a problem at the moment. I love the out of the box functionalities that MRTK provides! It's amazing. Want to incorporate it in my prototype <3

*Small question* How can I enable Hand models for controllers and also have `near interaction with interactables. I really would like to have the ability to do Far and Near interactions using controllers.

**Comment by Cameron-Micka** [comment] 2021-03-15 18:33
Thank you for reporting these issues @stychu. I don't have a concrete solution for some of these. But, have some suggestions.

> White Boundary on the blue UI elements is getting hella jaggy when getting far away. (seems okay on the close range)

This is aliasing caused by the high contrast white border and background. You could increase the `Border Light > Width %` on the HolographicBackPlate material. But, that will only help so much. You can also adjust the `Edge Smoothing Value` on the same material. That will "blur" the interior edges of the border a bit to reduce aliasing. If the backplate material is marked as transparent it will "blur" the interior AND exterior edges to reduce aliasing. But, then you have to deal with transparency sorting and overdraw pitfalls.

> On close view to the UI Letters seems crisp but when getting far away from the UI elements especially those ones on the blue background I can see Every letter being overlapped with a white box

I'm not quite sure what is going on here. @RogPodge might be correct in that we need a smarter way to sample the SDF font texture from far away. There are also some great suggestions in this thread since this text is being rendered with text mesh pro: https://forum.unity.com/threads/textmeshpro-text-anti-aliasing-from-a-distance-in-vr.486289/

**Comment by RogPodge** [comment] 2021-03-15 21:25
> Small question How can I enable Hand models for controllers and also have `near interaction with interactables. I really would like to have the ability to do Far and Near interactions using controllers.

At the moment, the grab pointer implementation unfortunately has some reliance on getting articulated hand joints, so that won't work out of the box with Unity (we can probably refactor out some of it's functionality like we did for the teleport pointer).

Currently testing to see if the poke pointer works as is with controllers, I'll update this post later today once my devices finish updated 😭

**Closed** 2021-03-15 22:17 UTC
Labels: Bug
