### ISSUE TITLE
ManipulationHandler is sluggish when moving in y-direction (HL v1)

### ISSUE THREAD

**Issue by ei2kpi-ptc** [microsoft/MixedRealityToolkit-Unity#5775] opened 2019-08-25 00:29 UTC
## Overview
When I use ManipulationHandler (MRTK 2.0.0) with a HoloLens v1 on a GameObject, I can target the object with my gaze, press down with my hand and can move it around.

When I move my hand right / left or forward / backward (relative to my head) it seems to work as expected but when I move my hand up / down, the object moves a lot more sluggishly

## Expected Behavior
Movement in all axes should work the same. I remember there being a HandGrabbable.cs script in HoloToolkit that worked great!

## Steps to reproduce
1. Set up MRTK with default HoloLens 1 profile
2. Create a GameObject
3. Drop ManipulationHandler on it with the following settings:
![image](https://user-images.githubusercontent.com/44373229/63644038-a1efcd00-c6ad-11e9-92fd-4dd4f95e7693.png)
4. Hit Play, and use the input simulation service to target the object by gaze and then try to manipulate it's position by using Space + the mouse to tap on the object and then move the mouse to move the "hand"
5. Moving the mouse left and right works great, moving it up and down is really sluggish moving the mouse forward / backward (rolling mouse wheel) works great too

## Unity Editor Version
Unity 2019.2.0f1

## Mixed Reality Toolkit Release Version
v2.0.0

**Comment by clementsauvard** [comment] 2019-08-29 12:27
I can also confirm that this is a bit annoying compared to RC2.1 To me it seems like a sensitivity issue, 
moving the object to the left/right or forward/backward look the same compared to RC2.1, but when moving it up or down it doesn't move as far as i would expect it to go.

See below:
![SmartSelect_20190829-132816_Drive](https://user-images.githubusercontent.com/15730879/63939703-2f456f80-ca68-11e9-8130-1894a46a7dc5.gif)


This makes me think about X-axis and Y-axis mouse sensitivity settings found in certain FPS games. 
It could be interesting to add such parameters to the ManipulationHandler script, although i don't know if it would create issues with other parameters like Smoothing.

**Comment by wiwei** [comment] 2019-08-29 23:37
@julenka, @thalbern

It looks like the difference between GGV (HL1 style) and hand ray (HL2 style) is that the rotation fields are actually critical to the up/down functionality:

```csharp
public Vector3 Update(MixedRealityPose pointerCentroidPose, Quaternion objectRotation, Vector3 objectScale, bool isNearMode, bool usePointerRotation, MovementConstraintType movementConstraint)
        {
            if (!isNearMode || usePointerRotation)
            {
                Vector3 headPosition = CameraCache.Main.transform.position;
                float distanceRatio = 1.0f;

                if (movementConstraint != MovementConstraintType.FixDistanceFromHead)
                {
                    // Compute how far away the object should be based on the ratio of the current to original hand distance
                    var currentHandDistance = Vector3.Magnitude(pointerCentroidPose.Position - headPosition);
                    distanceRatio = currentHandDistance / pointerRefDistance;
                }

                Debug.Log("Distance ratio: " + distanceRatio);
                Debug.Log("Pointer centroid pose: " + pointerCentroidPose.Position);
                Debug.Log("Local grab point: " + pointerLocalGrabPoint + " object local grab point: " + objectLocalGrabPoint);
                Debug.Log("Rotation: " + pointerCentroidPose.Rotation);

                Vector3 scaledGrabToObject = Vector3.Scale(objectLocalGrabPoint, objectScale);
                Vector3 adjustedPointerToGrab = (pointerLocalGrabPoint * distanceRatio);
                adjustedPointerToGrab = pointerCentroidPose.Rotation * adjustedPointerToGrab;

                if (Math.Abs(pointerCentroidPose.Rotation.x) > .2 ||
                    Math.Abs(pointerCentroidPose.Rotation.y) > .2 ||
                    Math.Abs(pointerCentroidPose.Rotation.z) > .2)
                {
                    Debug.Log("yay");
                }

                Debug.Log("New location: " + (adjustedPointerToGrab - objectRotation * scaledGrabToObject + pointerCentroidPose.Position));
                return adjustedPointerToGrab - objectRotation * scaledGrabToObject + pointerCentroidPose.Position;
            }
            else
            {
                return pointerCentroidPose.Position + pointerToObject;
            }
        }
```

If you set a breakpoint on Debug.Log("yay") it'll never get hit on HL1 style interactions, because the x rotation is always 0 (i.e. there is no rotation of the hand for the GGV style, but on HL2 it's based I think on the direction of the ray).

**Comment by thalbern** [comment] 2019-08-30 10:28
adding @MenelvagorMilsom - he's our manipulationhandler move expert now :)

**Comment by MenelvagorMilsom** [comment] 2019-08-30 10:32
> If you set a breakpoint on Debug.Log("yay") it'll never get hit on HL1 style interactions, because the x rotation is always 0 (i.e. there is no rotation of the hand for the GGV style, but on HL2 it's based I think on the direction of the ray).

Damn, I should noticed this. I know what the issue is here. I can have a look soon enough.

**Closed** 2019-09-09 16:14 UTC
Labels: 0 - Backlog, Bug, Consider for Next Iteration, UX Controls, UX Controls - ManipulationHandler
