### ISSUE TITLE
Bounds Extension uses world space incorrectly

### ISSUE THREAD

**Issue by EricWilson-SG** [microsoft/MixedRealityToolkit-Unity#4273] opened 2019-05-10 19:15 UTC
## Describe the bug
the bounds extension to get bound corners returns incorrect world space values.
this function is meant to return the world positions of the corners of a given bounds. However, it uses the Bounds.center which is a world space position, making corner calculation operate in local space in relation to the world position. the wording is confusing but it should be operating off of the zero position which is the local center.

## To reproduce
1. create bounds with center other than the world's origin. 
2. attempt to get the position of the corners by calling the function GetCornerPositions in the script BoundsExtensions.cs
3. create empty gameobjects at the output positions, and see that they do not relate to the object's corner positions

## Expected behavior
get correct corners in world space

## Your Setup (please complete the following information)

MRTK 2017.2.1.2, but it seems like it is in the current repo branch as well.

## Additional context
Fix: the fix is fairly simple, but will have to be applied to other relevant functions. for this particular function, do the following:
- Change [line 106](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9ab0e9b69afe45f7856b5731436ae427c3fe7cc4/Assets/MixedRealityToolkit/Extensions/BoundsExtensions.cs#L106) to:
Vector3 center = transform.position - bounds.center; 

this will set the center to the offset of the bounds center from the transform center in local space, which is the space this expects to be working in.

**Comment by djohnsomsft** [comment] 2019-05-13 21:40
There is a secondary bug here as well where the bounds is initialized to the default center=(0,0,0), size=(0,0,0), and using Extend on this will always include the world origin. The fix to this is initialize with the first valid bounds instead of using Extend on the default value.

**Comment by djohnsomsft** [comment] 2019-05-13 22:33
This also does not account for scale. If an object is at 0.01 scale to start off, for example, the bounding box will be at 0.0001 scale.

**Comment by meulta** [comment] 2019-05-14 20:16
It might be the same cause as for this #4151

**Comment by julenka** [comment] 2019-05-29 05:21
Reading the bounding box code, it turns out bounding box extensions are not actually used by the bounding box ux control. Removing bounding box label and urgency-soon tag, since I believe Urgency-Soon was added because this was related to bounding box.

**Comment by julenka** [comment] 2019-05-29 05:57
> However, it uses the Bounds.center which is a world space position,

I see where you are coming from since getting BoxCollider.Bounds does give bounds in world space. However, reading the code more, I think that `bounds` in `GetCornerPositions(this Bounds bounds, Transform transform, ref Vector3[] positions)` is intended to be passed in using local space bounds, not world space bounds.

For example, the following code, which grabs the corners using [Mesh.bounds](https://docs.unity3d.com/ScriptReference/Mesh-bounds.html) which is in local space, puts the corners correctly in space, both for a cube that is not at the origin, and a cube that is scaled to size 0.01

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Microsoft.MixedReality.Toolkit.Utilities;
using Microsoft.MixedReality.Toolkit;
public class BoundsWorldSpaceTest : MonoBehaviour
{
    // Update is called once per frame
    void Update()
    {
        Bounds bounds = GetComponent<MeshFilter>().mesh.bounds;
        Vector3[] corners = new Vector3[8];
        bounds.GetCornerPositions(transform, ref corners);
        for (int i = 0; i < corners.Length; i++)
        {
            DebugUtilities.DrawPoint(corners[i], Color.cyan);
        }
    }
}
```

You can also see on [Line 369](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9ab0e9b69afe45f7856b5731436ae427c3fe7cc4/Assets/MixedRealityToolkit/Extensions/BoundsExtensions.cs#L369) that the method is using local space bounds by calling using Bounds.center and bounds.extents.

I'm going to close this as By Design for now, and will clarify the intended method usage in comments in a PR.

**Comment by julenka** [comment] 2019-05-29 05:59
Added comment clarifying GetCornerPositions usage in #4592

**Closed by julenka** 2019-05-29 05:59 UTC
Labels: 0 - Backlog, Bug, DDE Partner, Interactions
