### ISSUE TITLE
WMR controllers do not work in MRTK set up with Nuget

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6391] opened 2019-10-26 06:31 UTC
## Overview
While MRTK 2.1 installed via packages shows WMR controllers as expected, WMR controllers do not show up when using a project that has MRTK installed via NuGet

## Steps to reproduce
1. Create a new Unity project 
2. Set up the project to compile for UWP platform
3. Set up MRTK via NuGet
4. Create new scene and add MRTK
5. Connect WMR headset
6. Hit play 

## Expected Behavior
I see controllers

## Actual Behavior
No controllers show up, and no indication that the system received SourceDetected events from WindowsMixedReality.

## Unity Editor Version
2019.2.5f1

## Mixed Reality Toolkit Release Version
2.1

**Comment by SimonDarksideJ** [comment] 2019-10-27 13:39
Could this be due to the Unity WMR package not being installed?

**Comment by jwittner** [comment] 2019-10-28 18:14
I can confirm I experience the same issue. If I import the .unitypackage the basis for each controller is rendered. If I only have the nuget package, then I don't see anything. No warning appear in the logs, though when it works ( from .unitypackage ) I do get info logs about the controllers being created.

**Comment by keveleigh** [comment] 2019-11-21 17:49
Should be fixed with #6649

**Closed by keveleigh** 2019-11-21 17:49 UTC
Labels: Bug, Current Iteration, Package Management - NuGet, Release Blocker, Urgency-Soon
