### ISSUE TITLE
EventSystem - what is UIRaycastCamera?

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1442] opened 2017-11-27 03:06 UTC
What is the RaycastCamera on the EventSystem, which is part of the InputManager? Why does it include a Camera that is default not active, and what does this non-active camera do? What does InputManager's Raycast Layer Masks do, and what does it affect? Does it affect the gaze cursor, or the motion controller's cursor, any cursor? How does this layer mask differ from the RaycastCamera's CullingMask layers?

I'm working on RoboRaid (if any of you have worked on it, please let me know), and I want to know how to get the SR data to "turn off" after the game gets running so the cursor NEVER lands on it. But it can still light up (be shown). I don't know if this should be accomplished by putting the layer onto one that the cursor would never hit, or ... what?

thanks

**Comment by StephenHodgson** [comment] 2017-11-27 03:44
It only raycasts against ugui elements.

**Comment by erichfrazer** [comment] 2017-11-27 04:02
Not helpful enough of an answer. First off, what's a UIRaycastCamera? I didn't mention that object in my question. Second, what is a Ugui element? Ugui? Never heard of it. 

And, assuming that you meant the RaycastCamera that is attached to the EventSystem (and I'm having trouble thinking you did), why is this different than the other Layer Masks on the InputManager's Raycast Layer Masks?

Could you *please* go through my original question and answer the questions one by one? Or point me to docs that explain how these two Layer Masks work and how they differ? Each question in my original question is pretty important to me.

I know, demanding, but the answers to these questions will help more people than just me, i'm sure.
thanks

**Comment by erichfrazer** [comment] 2017-11-27 04:03
Yeah, please explain everything. Including why the camera is default not active? What's the point? And why did you call it a UIRaycastCamera when that object doesn't exist? Are you intending to rename it at a future date to UIRaycastCamera? :-)

**Comment by StephenHodgson** [comment] 2017-11-27 04:04
Well, I was still writing out the answers to the rest of your questions, but you didn't give me time 😆

**Comment by erichfrazer** [comment] 2017-11-27 04:29
I suspected so! Ha ha ha! Funny, since I figured that’s what was going on.

But I’ve been frustrated at this all weekend, so… quick to reply?

😊

**Comment by StephenHodgson** [comment] 2017-11-27 05:14
The `RaycastCamera` _should_ be named `UIRaycastCamera`, as it is the value reflected in the `FocusManager` property with the same name.  That type must have slipped past me when creating the system.

[uGUI is short for Unity GUI](https://docs.unity3d.com/Manual/UISystem.html) and is Unity's defacto UI system that's typically used for 2d screens, but recently has seen people use it for Mixed Reality Applications anyway.  To use this system in 3d space one needs to change each [Canvas](https://docs.unity3d.com/Manual/UICanvas.html) **Render Mode** to `WorldSpace`.

Unity has 3 raycasting types that we have to consider:
- [`PhysicsRaycaster`](https://docs.unity3d.com/ScriptReference/UI.GraphicRaycaster.html)  for casting against 3D Physics components that inherit from [`Collider`](https://docs.unity3d.com/ScriptReference/Collider.html)
- [`Physics2DRaycaster`](https://docs.unity3d.com/ScriptReference/EventSystems.Physics2DRaycaster.html) for casting against 2D Physics components that inherit from [`Collider2D`](https://docs.unity3d.com/ScriptReference/Collider2D.html)
- [`GraphicRaycaster`](https://docs.unity3d.com/ScriptReference/UI.GraphicRaycaster.html) to raycast against Graphic elements that inherit from [`UIBehaviour`](https://docs.unity3d.com/ScriptReference/EventSystems.UIBehaviour.html).

Unfortunately, Unity's uGUI system was designed with 2d screens in mind, and has minimal support for handling 3d UI effectively (but for some reason people still insist on using it).  Additionally, one would think that doing a simple `Physics.Raycast` would effectively raycast against all three types, but only covers the first two.  An additional `EventSystem.current.Raycast` has to also be considered, and custom logic is needed to calculate if a graphic element happens to be closer to the camera than the physics object.

All the `UIRaycastCamera`'s does is to move to each pointer position and to a raycast against any `Canvas` in the scene who's `renderMode` is `WorldSpace` and has the `UIRaycastCamera` set as its `worldCamera`.  It has no impact of the SR meshes you're trying to raycast against because they're considered physics objects.  This `UIRaycastCamera` camera component is disabled to increase performance, as we don't need to actually render any objects using this camera, and as a result it's culling mask doesn't matter.

>What does InputManager's Raycast Layer Masks do, and what does it affect?

It's a [layer](https://docs.unity3d.com/Manual/Layers.html) mask that you can update to filter out specific layers from being raycasted against.  This layer mask works for both physics and graphic `GameObjects`.

Essentially to get your SR mesh to render, but not get included in the raycasts, you need to exclude that layer via the `FocusManager.PointingRaycastLayerMasks`.  I believe the SR physics layer is 31 if you're using the toolkit (although is may be different for your project).  If you don't see it in the drop down list you'll need to manually name the layer.  You can edit the project's layers by the layer dropdown located at the top right corner of the application.
![image](https://user-images.githubusercontent.com/13334553/33251836-b0f5affe-d2ee-11e7-96fd-899bad1cf6cd.png)


One named, you should see it in the layer mask list.
![image](https://user-images.githubusercontent.com/13334553/33251819-8f261d32-d2ee-11e7-97e7-f5e89ce62981.png)

**Comment by wiwei** [comment] 2019-04-11 20:26
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:26 UTC
Labels: Question
