### ISSUE TITLE
Gaze cursor shows up when hands are in near touch mode

### ISSUE THREAD

**Issue by sostel** [microsoft/MixedRealityToolkit-Unity#5580] opened 2019-08-09 18:58 UTC
## Describe the bug
The gaze cursor shows up when the hands go into near mode. 

## To reproduce
1. Sync to the latest '2.0.0_stabilization' branch 
2. Start Unity and move the HandsInteractionAll scene to the first place in the Build Settings
3. Open the VS project and enable the "Gaze Input" capability
4. Compile and deploy to HoloLens 2

*Please note:*
This issue doesn't occur if the "Gaze Input" capability is disabled. However, in this case, once the hands are not detected anymore, the head gaze cursor will not show up automatically. Instead the user has to say "Select" first.

## Expected behavior
The gaze cursor should only show up if either "no hands" are detectable and/or "no hands" + an activation command (e.g., say select) is issued.

## Screenshots
![image](https://user-images.githubusercontent.com/32180789/62802461-cdaf6800-ba9c-11e9-9a93-9189198aca6d.png)

## Your Setup (please complete the following information)
- Unity 2018.4.0f1
- MRTK 2.0.0_stabilization

## Target Platform (please complete the following information)
HoloLens 2

**Comment by julenka** [comment] 2019-08-09 22:58
This might be my bug caused by showing / hiding cursors in the cursor state machine. @wiwei and @keveleigh are you guys planning to look at this Friday or Monday? I can help. I was under impression Kurtis and will were busy with other things.

**Comment by wiwei** [comment] 2019-08-12 16:42
@julenka I think your cursor state machine changes were pretty long ago though - I just tried pulling latest stabilization and wasn't able to hit this (first tried in editor just because it's faster, then tried deploying to device and also wasn't able to hit this).

I'm pinging some others now to see if they can see this on their devices.

**Comment by sostel** [comment] 2019-08-12 18:49
I just tested after syncing to the latest in the stabilization branch. I don't see the issue occur in the Editor, but I do see it on the device 🤔

**Comment by sostel** [comment] 2019-08-13 00:19
To add:
I've tested with the "Gaze Input" capability disabled and the cursor will _not_ show up automatically in that case. Instead the user has to say "select" to make it show up again. I've updated the description above.

**Comment by cre8ivepark** [comment] 2019-08-13 16:40
@sostel Confirmed. The gaze cursor shows up when 'Gaze Input' is checked in the Visual Studio.

**Comment by cre8ivepark** [comment] 2019-08-13 17:26
@sostel Isn't this expected behavior for ET? Checking 'Gaze Input' shows the gaze cursor and user have to change the cursor prefab to EyeGazeCursor to make it subtle?
If I uncheck the 'Gaze Input' in VS, I don't see the cursor.

**Comment by sostel** [comment] 2019-08-13 17:31
@cre8ivepark I thought that the expectation is that the behavior would be consistent to the head gaze cursor in that the cursor does not show up automatically. Even if we would hide the cursor, buttons would still light up when the hands go into near mode, simply because the user is looking at them. This is not the intended behavior. Having said that, I kind of like that the cursor automatically shows up when the hands are out of view, but yes, in that case the cursor should be more subtle.

**Comment by sostel** [comment] 2019-08-13 18:02
Fixed the issue in the above mentioned PR. Very easy fix once I understood where the visibility of the gaze cursor is set. However, the cursor still shows up by default as a opaque head cursor instead of a more subtle eye gaze cursor. Not super urgent, but definitely something to be aware of.

**Comment by cre8ivepark** [comment] 2019-08-13 18:18
@sostel Yes, without Gaze Input, I see proper shell behavior: gaze cursor only shows when I say 'Select'. And it disappears when I raise a hand. 
For the ET enabled with 'Gaze Input' checked, situation, I am not sure if we have ever implemented the behavior. I'll also test your changes with HL1/2. Thanks!

**Comment by sostel** [comment] 2019-08-13 18:28
@cre8ivepark  I only made changes to the eye gaze part, so this shouldn't have any effect on the behaviors for HL1. 
Just FYI: Apparently - I at least wasn't aware of it - this was a conscious decision (not a bug) that the eye gaze pointer would be active in near mode based on comments that I found in the test script from Lars.

**Closed** 2019-08-14 07:00 UTC
Labels: Bug, GA Blocker, Urgency-Soon
