### ISSUE TITLE
Endless Searching - Ability to manually enter IP would be nice.

### ISSUE THREAD

**Issue by BenWoodford** [Microsoft/MixedRealityToolkit-Unity#1116] opened 2017-10-11 10:30 UTC
My subnet is a touch larger than the average (255.255.0.0) so most scanning tools take a decade to work on it, and the build window in MRTK is no different.

It would be nice if I could cancel the search and manually enter the IP of my HoloLens.

**Comment by StephenHodgson** [comment] 2017-10-11 15:16
I don't think the IP scanning is even enabled.

**Comment by StephenHodgson** [comment] 2017-10-11 15:16
Currently it's only usb

**Comment by StephenHodgson** [comment] 2017-10-11 15:23
I saw your PR that fixed searching. Thanks!

**Comment by StephenHodgson** [comment] 2017-10-11 15:30
Been this is kinda a duplicate of #1020. Could you close this and add your comment there?

**Closed** 2017-10-11 19:54 UTC
