### ISSUE TITLE
UI Buttons Not Responding in HoloLens

### ISSUE THREAD

**Issue by charlesMP** [Microsoft/MixedRealityToolkit-Unity#1365] opened 2017-11-14 21:03 UTC
## Overview
I can't select UI Buttons when I build out to the HoloLens. They work in Editor and on the HoloLens the cursor seems to still see my hand and the tap gesture. 

## Expected Behavior
I select a button and get the behavior out of it. 

## Actual Behavior
Nothing, the tap gesture doesn't seem to effect Unity UI Buttons anymore. 

## Steps to reproduce
Create a Unity UI Button
Add a Behavior to it.
Build and try to select the Button on HoloLens.

## Unity Editor Version
Unity 2017.2.0p1

## Mixed Reality Toolkit Release Version
v1.2017.2.0

**Comment by StephenHodgson** [comment] 2017-11-14 21:27
Please be sure to search for issues before submitting.

Duplicate of #1267

This will be addressed in an upcoming release.  For now follow all instructions regarding HoloLens development in the v1.2017.2.0 release

![image](https://user-images.githubusercontent.com/13334553/32805865-927c6012-c93f-11e7-8694-afe9d6380980.png)

**Closed by StephenHodgson** 2017-11-14 21:27 UTC
