### ISSUE TITLE
[Partner Hack] MRTK Scene Object Breaks Additive Scene Loading

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5081] opened 2019-06-26 22:58 UTC
Description: 
Partners wanted to use Unity additive scene loading. They have MRTK in a "Main" scene and then load child scenes additively. However, this results in the MRTK object missing from the child scenes which causes many of the MRTK inspectors to break.

This Teams thread states that MRTK can be configured without being in the scene, but  GitHub pull request 4099 states "Other services and demos will be updated to use the new registry pattern over the next few PRs".

 

According to Lars, this will be available very soon. See docs here. Almost all of it is in mrtk_development branch but needs PR4455 to be complete.

 

Documented by the customer at #4935.

Partner: Theoris

Filed for: @jbienzms  during Paris hack

**Comment by wiwei** [comment] 2019-07-24 23:27
Dupe of #4935, closing

**Closed by wiwei** 2019-07-24 23:27 UTC
Labels: Bug
