### ISSUE TITLE
[MRTK3 pre.8 build call] Add poke scrolling to VirtualizedList

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10816] opened 2022-08-02 16:22 UTC
## Describe the problem

Scrolling through the list seems slow/clunky

## Describe the solution you'd like

Allow the user to press down on the main list, and drag the list in a direction which then scrolls the view up/down

## Describe alternatives you've considered

Anything past button functionality, as a list with this will get slower and slower to navigate as more items are added

## Additional context
Video added based on what the user wants to do.

https://user-images.githubusercontent.com/110259320/182424420-9057070f-46fc-4851-85fd-cba310fb9e9c.mp4

**Comment by Zee2** [comment] 2022-08-02 18:09
This work is being done in #10795 .

**Comment by Zee2** [comment] 2022-08-03 06:01
Closing as duplicate of #10736.

**Closed by Zee2** 2022-08-03 06:01 UTC
Labels: UX Controls, Feature Request, UX Controls - Scroll View, MRTK3
