### ISSUE TITLE
MotionController with Positional tracking off.

### ISSUE THREAD

**Issue by song1shuai** [Microsoft/MixedRealityToolkit-Unity#1293] opened 2017-11-03 19:51 UTC
Is there a way to reset the motion controller 's position when 
 I turn on this flag `UnityEngine.XR.InputTracking.disablePositionalTracking = true;` ?

**Comment by keveleigh** [comment] 2017-12-06 22:47
Duplicate of #1376. Closing this in favor of that one with more discussion and a bug report.

**Closed by keveleigh** 2017-12-06 22:47 UTC
Labels: Question
