### ISSUE TITLE
White screen on load on desktop when there is no WMR headset

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#5534] opened 2019-08-07 13:38 UTC
## Describe the bug

Hello,
I need to configure my Hololens project to make it workable on desktop. However after installing and launching the msix on my Win10 computer, the application is stuck on a white screen and it starts the official WMR application.

I don't have this problem when:
- I have a WMR headset plugged but I want to be able to use the app without headset
- Virtual Reality support is disabled in Unity project settings, but I want to have the same build for both desktop and Hololens
- Project is built for Windows standalone in Unity, but it brokes the MRTK and I want only one build

I have not tested on a computer without the official WMR application.

I tried to disable XR support at start but it does not work:

```
private void Start()
    {
DisableXR();
    }

void DisableXR()
    {
        StartCoroutine(LoadDevice("", false));
    }

IEnumerator LoadDevice(string newDevice, bool enable)
    {
        XRSettings.LoadDeviceByName(newDevice);
        yield return null;
        XRSettings.enabled = enable;
    }
```

## To reproduce

Create a basic MRTK application, install it on a desktop computer and start it without headset.

## Expected behavior

MRTK camera is rendered on screen.

## Your Setup (please complete the following information)

- Unity Version 2019.1
- MRTK Version RC2.1

## Target Platform (please complete the following information)

- Desktop

**Comment by Troy-Ferrell** [comment] 2019-08-07 22:13
It is a bit hidden knowledge but the solution should be two fold. Also FYI, related item #3154 

Note: I am using 2018.4.5f1 of Unity LTS 
1) In your XR Player settings, you want to click the "+" button and add *None* SDK to the list. **IMPORTANT** Make sure it is after the *Windows Mixed Reality* entry
![image](https://user-images.githubusercontent.com/25975362/62661377-be59de80-b925-11e9-89b7-5fbd5e14ee47.png)

2) After building a VS solution from unity, open the appx manifest file and make sure the target device family is set to Universal (which I assume you have since you get a white screen but to be explicit for others reading this)

```
<Dependencies>
   <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.10240.0" MaxVersionTested="10.0.10586.0" />
</Dependencies>
```

There is also additional documentation for shipping to the store here:
https://docs.microsoft.com/en-us/windows/mixed-reality/submitting-an-app-to-the-microsoft-store

**Comment by Troy-Ferrell** [comment] 2019-08-07 22:16
Closing as a dupe of #3154

**Closed by Troy-Ferrell** 2019-08-07 22:16 UTC
Labels: Bug

**Comment by benjamincoven** [comment] 2019-08-08 09:33
Thank you very much for your reply, the trick 1 works very well!

I missed the other issue sorry. Yes I already changed the Target device and I tested the mouse provider but it does not work very well as it is, I will maybe create my own provider.

**Comment by Troy-Ferrell** [comment] 2019-08-08 16:17
Great to hear! 

No worries, I referenced the other issue primarily to note it's still on us to create better documentation. Can you elaborate on why the mouse data provider does not work well? If it sounds like a bug, please file an issue with details
