### ISSUE TITLE
Upgrade to Unity 2019.2 causes Missing reference exceptions "Execute Events"

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#4931] opened 2019-06-18 05:51 UTC
## Describe the bug

Importing the MRTK into a 2019.2 project causes critical warnings to appear, noting a missing reference exception for "ExecuteEvents".
This is due to Unity removing the UI system from the core Unity engine and moving it to it's own package.

The simple resolution to this is to add a reference to "Unity.UI" to all asmdef's that require the UI system, e.g. Core and SDK.

## To reproduce

1. Create new project in 2019.2
2. Import MRTK
3. Observe errors

## Expected behavior

It should work

## Your Setup (please complete the following information)

- Unity Version 2019.2
- MRTK Version - all

## Target Platform (please complete the following information)

- All

## Additional context

Resolved in the XRTK here
https://github.com/XRTK/XRTK-Core/pull/201
Confirmed, it causes no backwards compatibility issues as Unity ignores references it cannot resolve.

**Comment by keveleigh** [comment] 2019-06-19 18:28
Duplicate of #4545

**Closed by keveleigh** 2019-06-19 18:28 UTC
Labels: Bug, Duplicate

**Comment by Railboy** [comment] 2019-06-19 18:46
>The simple resolution to this is to add a reference to "Unity.UI" to all asmdef's that require the UI system, e.g. Core and SDK.

Not sure if this changes anything, but Unity overlooked the fact that [there's no way for DLLs to access the Unity UI system](https://forum.unity.com/threads/ui.673504/#post-4534411) with this recent change. This was their plan moving forward:

> For 19.2 we will automatically compile asmdefs with the UI reference. This way there shouldn't be a need to manually add the reference yourself. For 19.3+ we are hoping to have a more robust system in place but we are still unsure what this will look like.

As of June 4th they say [a fix landed](https://forum.unity.com/threads/ui.673504/#post-4613233) in b6 but I'm not sure what it looks like. @SimonDarksideJ do you want to investigate?
