### ISSUE TITLE
Directional Indicator

### ISSUE THREAD

**Issue by tletie** [microsoft/MixedRealityToolkit-Unity#6357] opened 2019-10-23 17:21 UTC
## Describe the problem
Directional Indicator (HeadsUpDirectionIndicator) was part of HLToolkit is not porting over to MRTK.

## Describe the solution you'd like
Need to be ported over since it requires for the app to provide capability of focusing user to certain areas.

**Comment by Troy-Ferrell** [comment] 2019-10-24 17:11
Dupe of #5115

**Closed by Troy-Ferrell** 2019-10-24 17:11 UTC
Labels: Feature Request, HTK Parity
