### ISSUE TITLE
SpeechInputHandler not Calling hooked in methods if "Is Focus Required" option is turned on

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/MixedRealityToolkit-Unity#2911] opened 2018-10-11 20:06 UTC
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
If you add SpeechInputHandler script to a GameObject as component, the gameobject does not receive the speech events if the "Is Focus Required" is checked. If the option is unchecked the hooked in handler functions are called properly based on the keyword.

**To Reproduce**
In a new project config the profiles as needed with key words and actions. 
1. Create a cube in the hierarchy
2. Add Speech Input Handler Script to it. Configure the Keywords and Unity Actions.
3. Check the "Is Focus Required" in the component.
**Expected behavior**
When the Keycode for the keyword is pressed while the app is playing in Unity, the action corresponding to that should be called. 

**Actual behavior**
When the Keycode for the keyword is pressed while the app is playing in Unity, the action corresponding to that is not getting called. 

**Screenshots**
![focusrequired off](https://user-images.githubusercontent.com/14880339/46830801-a221fb00-cd6f-11e8-8a1a-bdba4167bf20.PNG)
![focusrequired on](https://user-images.githubusercontent.com/14880339/46830802-a221fb00-cd6f-11e8-9336-4dfa433220e8.PNG)

**Unity Editor Version**
Unity 2018.2.11f1

**Mixed Reality Toolkit Release Version**
mrtk_development

**Additional context**

**Comment by StephenHodgson** [comment] 2018-10-11 22:45
Duplicate of #2883?

**Comment by krishnan-unni** [comment] 2018-10-11 23:18
Looks like that. I can close it then

**Comment by krishnan-unni** [comment] 2018-10-11 23:43
Looks like I closed it too soon. The behavior described in 2883 is just opposite. There the focus is enabled and the Speech is executed when not focused. In my case when the Focus is required it doesnt execute at all whether focused or not.

**Comment by StephenHodgson** [comment] 2018-10-11 23:58
Haha that is why I was asking, cause I couldn't tell if they we're describing the same thing or not 😅

**Comment by krishnan-unni** [comment] 2018-10-12 00:00
Lol yeah, I started reading it and then realized it. I dont even have an Interactable in my cube

**Comment by krishnan-unni** [comment] 2018-10-12 00:01
@StephenHodgson  I added a question on Gestures in 2626. Not sure if it is a bug. Could you please recommend? If you think it is then I'll open a separate bug on that.

**Comment by StephenHodgson** [comment] 2018-10-13 15:09
The root cause is described in #2918

**Closed** 2018-10-13 17:11 UTC
Labels: Investigate, MRTK vNEXT, Speech
