### ISSUE TITLE
unity closing unexpectedly

### ISSUE THREAD

**Issue by RICKASHEYE** [Microsoft/MixedRealityToolkit-Unity#1343] opened 2017-11-12 04:35 UTC
## Overview
Unity Closing Automatically looking for a fix
## Expected Behavior
run correctly
## Actual Behavior
after a period of when the controllers are visible unity automatically closes
## Steps to reproduce
1. Open unity
2. added the toolkit
3. made a basic scene
4. played
5. time after controllers
6. closes
## Unity Editor Version
2017.2.0f3
## Mixed Reality Toolkit Release Version
newest version
2017.2.0 I think it is

**Comment by DDReaper** [comment] 2017-11-12 11:58
With the MRTP4 build I've seen fewer crashes, so please confirm if you are using the latest MRTP build
Does this crash happen over time, or when you click buttons on both controllers together?

**Comment by RICKASHEYE** [comment] 2017-11-12 20:48
i downloaded it only like 10 hours ago

**Comment by DDReaper** [comment] 2017-11-13 20:07
So does the new build resolve your crashing issue. Or are you experiencing one of the other crashes reported in the issues (like controller buttons?)

**Comment by RICKASHEYE** [comment] 2017-11-14 06:20
the old build works better than the new build I downloaded which was 2017.2.0 250 Idk I downloaded it from somewhere and it works better than the new current version I want the new current version because 1 its more updated and 2 I can learn better with it too

**Comment by MrMatthias** [comment] 2017-11-14 09:15
Happens in MRTP 4 too. The last Editor log message is this:
```
Assertion failed
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Assert(Boolean)
HoloToolkit.Unity.InputModule.FocusManager:GetPointer(IPointingSource) (at Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:713)
HoloToolkit.Unity.InputModule.FocusManager:GetSpecificPointerEventData(IPointingSource) (at Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:433)
HoloToolkit.Unity.InputModule.InputManager:RaiseSourceUp(IInputSource, UInt32, InteractionSourcePressInfo, Object[]) (at Assets\HoloToolkit\Input\Scripts\Utilities\Managers\InputManager.cs:430)
HoloToolkit.Unity.InputModule.InteractionInputSource:InteractionManager_InteractionSourceReleased(InteractionSourceReleasedEventArgs) (at Assets\HoloToolkit\Input\Scripts\InputSources\InteractionInputSource.cs:919)
UnityEngine.XR.WSA.Input.InteractionManager:OnSourceEvent(EventType, InteractionSourceState, InteractionSourcePressType) (at C:\buildslave\unity\build\Runtime\VR\HoloLens\ScriptBindings\GestureSource.cs:481)

(Filename: Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs Line: 713)
```

**Comment by StephenHodgson** [comment] 2017-11-14 09:17
Duplicate of #1344

**Closed by StephenHodgson** 2017-11-14 09:17 UTC
Labels: Duplicate
