### ISSUE TITLE
Reading Mode Doesn't work with URP

### ISSUE THREAD

**Issue by pajama** [microsoft/MixedRealityToolkit-Unity#10337] opened 2021-11-22 21:54 UTC
Reading Mode Doesn't work with URP. Likely because OnPreCall is never called. RenderPipelineManager events needs to be implemented. 

Also RenderViewportScale doesn't work with URP, but I'm guessing this is an underlying Unity OpenXR issue?

## To reproduce
Switch to URP. Try the ReadingModeDemo.

## Expected behavior

Reading mode demo should perform as expected.

- Unity Version 2020.3.20f1
- MRTK Version 2.7.2
- HoloLens 2
-OpenXR

**Comment by polar-kev** [comment] 2021-11-24 18:50
Thanks for filing @pajama

**Comment by polar-kev** [comment] 2021-11-24 18:51
FYI @KevinKennedy.

**Comment by Zee2** [comment] 2022-08-31 17:47
@Cameron-Micka , is this something we're thinking about for MRGT?

**Comment by Cameron-Micka** [comment] 2022-08-31 17:51
Oh, what is the "reading mode" demo?

**Comment by keveleigh** [comment] 2022-08-31 18:41
Info on reading mode: https://docs.microsoft.com/hololens/hololens2-display#what-improvements-are-coming-that-will-improve-hololens-2-image-quality

Some MRTK2 background: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8344, https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8651, https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8808

**Comment by Cameron-Micka** [comment] 2022-08-31 21:14
Thanks @keveleigh, I had no idea this was a feature. This is not something we've considered for MRGT but could be something we think about. We already have defines in place to conditionally compile URP specific logic so should be too hard to support both pipelines. 

I'm open to tracking this issue here: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues or if someone has time to make the change, I'm happy to review the PR. 😊

**Comment by Zee2** [comment] 2022-08-31 22:23
@Cameron-Micka, created an issue for ya :)

**Comment by Cameron-Micka** [comment] 2022-08-31 22:24
Thanks!

**Comment by Zee2** [comment] 2022-09-02 16:01
Closing as duplicate of the new MRGT issue (https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/97)

**Closed by Zee2** 2022-09-02 16:01 UTC
Labels: Bug, URP
