### ISSUE TITLE
Depth buffer sharing disables itself due to IHolographicCameraRenderingParameters2

### ISSUE THREAD

**Issue by FlyingFlambe** [microsoft/MixedRealityToolkit-Unity#6971] opened 2020-01-02 22:17 UTC
## Describe the bug

When Depth Buffer Sharing is enabled in XR Settings, the following warning generates:
- "IHolographicCameraRenderingParameters2 interface unavailable; disabling depth buffer sharing"

When disabling Depth Buffer Sharing manually in XR Settings, a different warning is generated:
- "Depth Buffer Sharing is not enabled to improve hologram stabilization. See Mixed Reality Toolkit > Utilities > Optimize Window tool for more information to improve performance"

Warning is reproduced by setting up MRTK and Unity scene as usual. Have seen this warning in every project over the last few months in MRTK v2.1 too.

![image](https://user-images.githubusercontent.com/22328598/71696723-5a73fe80-2d7b-11ea-934c-e42ec648caf3.png)

## Expected behavior

Ideally no warning appears and Depth Buffer Sharing doesn't disable itself.

## Your setup (please complete the following information)

- Unity 2019.1.14f1
- MRTK v2.2

## Target platform (please complete the following information)

- HoloLens

**Comment by keveleigh** [comment] 2020-01-03 20:28
Which Windows 10 version are you running?

**Comment by FlyingFlambe** [comment] 2020-01-03 22:55
10.0.18362 Build 18362

**Comment by wiwei** [comment] 2020-01-29 00:12
@FlyingFlambe is that your SDK version, or the actual windows version?

i.e. if you do:
Win+R -> then type "winver"
This will launch a dialog showing your windows version.

That interface was added to Windows a looooong time ago (i.e. back in 2017) so unless you're stuck on a really old build, that interface should exist. i.e. if you see a winver build or 15063 or greater than it should be good (anything less and the problem is your windows version is too out of date).

The other possibility is that your version of windows is up to date, but your interface/registry hive has gotten fubar-ed (this can happen if you ever run registry cleaners or any other random utilities), in which case the solution is more complicated - the simplest thing would be to unfortunately pave windows (and get the latest version in the process via (https://www.microsoft.com/en-us/software-download/windows10)

At this point this doesn't seem like an MRTK issue (more like an issue on the OS/Unity side because of problems finding fundamental interfaces and files).

**Comment by wiwei** [comment] 2020-02-07 16:47
Closing this issue as this seems to be a development environment configuration issue, please reopen if you have more information to share.

**Closed by wiwei** 2020-02-07 16:47 UTC
Labels: Bug
