### ISSUE TITLE
Assertion failed: Removing Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#1345] opened 2017-11-12 12:14 UTC
## Overview
When opening the MRTK MASTER branch for the first time, the following error appears:
```
Assertion failed: Removing 
Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
```

## Expected Behavior
No errors when opening project.

## Actual Behavior
```
Assertion failed: Removing Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
```
Is displayed in the console on startup.

## Unity Editor Version
MRTP4

## Mixed Reality Toolkit Release Version
MASTER

**Comment by StephenHodgson** [comment] 2017-11-12 15:38
Sounds like something didn't get checked into the repo properly.

@DDReaper could we confirm this is a clean, new project and no library/temp folders exist before opening the project?

**Comment by StephenHodgson** [comment] 2017-11-12 16:13
I wasn't able to reproduce this with a clean pull of the repository.  This could have happened because the import settings on the cursor asset was changed and did not reflect your local copy of the repo.

**Comment by DDReaper** [comment] 2017-11-12 22:41
Before testing, I always do a sync and clean, to remove any artefacts.
Will try on a clean clone tomorrow, but I would be very surprised if it was any different

**Comment by StephenHodgson** [comment] 2017-11-12 22:50
I think cleaning the repo will remove empty folders for you, is this correct?  Which would cause the issue you're seeing.

**Comment by StephenHodgson** [comment] 2017-11-12 22:52
In either case, that folder should be removed anyway seeing as it doesn't have anything in it.

**Comment by keveleigh** [comment] 2017-11-13 00:06
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1305#discussion_r149527717

**Comment by DDReaper** [comment] 2017-11-16 14:19
Tested on a fresh copy of the repo and the issue still exists.  Even on the latest master.

**Comment by keveleigh** [comment] 2017-12-29 00:36
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.

**Closed by keveleigh** 2017-12-29 00:36 UTC
Labels: Bug, Fixed in Dev Branch
