### ISSUE TITLE
Speech recognition and predifined VC don't work in editor

### ISSUE THREAD

**Issue by yeahbunny** [microsoft/MixedRealityToolkit-Unity#11717] opened 2023-07-19 14:34 UTC
## Describe the bug

Speech recognition and VC don't work for new project (configured for Mixed Reality) as well as for example MRTK project in Editor. I have installed the latest MRTK package and enabled all necessary capabilities in Player -> Publishing -> Capabilities. I checked in many different applications the microphone works fine. My project is configured for UWP platform and I have configured the profile for the MixedRealityToolkit script in the scene. Unfortunately, VC like "select" or predefined VC for specific buttons won't work in Unity Editor. I tested it on a clean MRTK project and for my own app.

## To reproduce

1. Instal Unity 2021.3.8f1
2. Instal latest MRTK
3. Run Speech example scene from MRTK
4. VC ("rotate") doesn't work

## Expected behavior

VC works as it should. 

## Your setup (please complete the following information)

- Windows 11 Version 22H2
- Unity Version 2021.3.8f1
- MRTK Version or Commit v2.8.3 (https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.8.3)

## Target platform (please complete the following information)

- Editor
- HoloLens 2

**Comment by AMollis** [comment] 2023-07-19 21:46
@yeahbunny please ensure you have enabled the speech recognition on your HoloLens.

> HoloLens Settings App > Privacy > Speech > Turn on > Speech recognition (and maybe Online speech recognition ).

If running in Editor, make sure voice services are also enabled in Windows.

> Windows Settings App > Privacy & Security > Speech > Turn on > Online speech recognition

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/36461279/4270111c-bf54-43e9-8580-5382087da611)

Once you've verified these settings, please reply to this issue.

**Comment by yeahbunny** [comment] 2023-07-20 08:28
Hi,
Thank you for your answer. Yes, I have it enabled.

**Comment by yeahbunny** [comment] 2023-09-27 06:27
@AMollis Hi, any update here?

**Comment by AMollis** [comment] 2023-10-31 16:58
@yeahbunny , I unfortunately can't reproduce this issue (tries with Unity 2021.3.30)

A couple of tips....

1. Most of the voice controls require the object to be focused with a pointer.  For example, your eye gaze or hand ray.  Try pointing your hand ray at the target and speak the voice command
2. If you want eye gaze to work, make sure you've added the  "Eye Gaze Interaction Profile" to the XR Plugin settings (Project Settings > XR Plug-in Management > OpenXR > UWP (and Standalone) > Enabled Interaction Profiles > + > Eye Gaze Interaction Profile).  Also make sure your UWP app has requested eye input permissions (Project Settings > UWP > Publishing Settings > Capabilities > GazeInput)
3. If running in Editor, I found that I had to speak rather loudly, and near the microphone, for the voice input to work (but this could just be my setup).

Going to close this issue as "Not Reproduceable"   Please reach out to us if you have further questions.

‼️ Important.   For all new applications, we highly recommend using MRTK3 instead of MRTK2.  MRTK3 is better supported.  You can find MRTK3 documentation at https://mixedrealitytoolkit.org

**Closed by AMollis** 2023-10-31 16:58 UTC
Labels: No Repro, Bug, MRTK2
