### ISSUE TITLE
Mixed Reality Feature Tool crashes after clicking "Discover" button

### ISSUE THREAD

**Issue by bendrexl** [microsoft/MixedRealityToolkit-Unity#9533] opened 2021-03-21 05:18 UTC
Using latest Mixed Reality Feature Tool (1.0.2103.2- Beta), I'm able to select the location of my Unity project but the Tool exits without error after I click the "Discover Features" button.

I've tried on fresh projects using Unity v2020.3.0f1 & v2020.2.7f1, same behavior. 

Windows 10 Build 19042

**Comment by davidkline-ms** [comment] 2021-03-23 18:45
@bendrexl, can you look in c:\users\<yourname>\AppData\Local\MixedRealityFeatureTool and find the log file? That may point to a cause of the issue.

Thanks!

**Comment by bendrexl** [comment] 2021-03-27 09:52
> @bendrexl, can you look in c:\users<yourname>\AppData\Local\MixedRealityFeatureTool and find the log file? That may point to a cause of the issue.

Thanks! The log doesn't look very helpful, but here it is:
`Mixed Reality Feature Tool 1.0.2103.2
[3/20/2021 22:14:35] Loading feature catalog.
`

**Comment by bendrexl** [comment] 2021-03-28 02:51
@davidkline-ms - I downloaded the latest Feature Tool. It still exits without error, but there's a little more in the log:

> Mixed Reality Feature Tool 1.0.2103.3
> [3/27/2021 19:47:32] Loading feature catalog.
> [3/27/2021 19:47:39] Loading the project manifest.
> [3/27/2021 19:47:39] Project manifest successfully loaded.
> [3/27/2021 19:47:39] Looking for previously imported features.
> [3/27/2021 19:47:39] Found 0 imported features.
> Project Unity version 2020.3.0f1

**Comment by davidkline-ms** [comment] 2021-03-30 00:20
Thanks! That gives me a few things to look at.

**Comment by davidkline-ms** [comment] 2021-03-30 00:21
Can you try version 1.0.2103.3? That might have more info.

**Comment by davidkline-ms** [comment] 2021-04-09 22:09
I believe I have a fix that will release in the coming days (1.0.2104.0).

**Comment by bendrexl** [comment] 2021-04-20 20:20
@davidkline-ms , any guess when the next release will be? I'm still running into errors trying to follow the documentation to get MRTK packages installed and configured without the Feature Tool, and the documentation seems to be missing the 'legacy' manual installation steps.

**Comment by keveleigh** [comment] 2021-04-21 16:37
@bendrexl 1.0.2104.0 is available now! https://www.microsoft.com/en-us/download/details.aspx?id=102778

**Comment by laufenes** [comment] 2021-04-22 09:49
hi @keveleigh I have downloaded the latest update but it's still crashing after pressing discover. here is my log:

Refreshing feature catalog.
ERROR: Failed to get data from Primary.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedInternalAsync[T](Uri uri, String authenticationToken) in D:\a\1\s\Source\AzureDevOps\AdoFeed.cs:line 165
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedAsync(Uri registryUri, Boolean isEarlyAccess, String organization, String projectId, String feedId, String authenticationToken) in D:\a\1\s\Source\AzureDevOps\AdoFeed.cs:line 66
   at Microsoft.MixedReality.FeatureTool.Core.FeedManagement.Refresh(FeedConnectionData connectionData, String feedName, FileInfo feedCacheFile) in D:\a\1\s\Source\Core\FeedManagement.cs:line 75
InnerException:
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
InnerException:
System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
[22/04/2021 10:41:41] ERROR: Primary catalog not be refreshed.
System.InvalidOperationException: Feed address appears to contain no data
   at Microsoft.MixedReality.FeatureTool.Utilities.FeedData.Refresh() in D:\a\1\s\Source\UI\Windows\MixedRealityFeatureTool\Utilities\FeedData.cs:line 66

**Comment by davidkline-ms** [comment] 2021-04-22 16:10
Thanks for the update @laufenes. I will investigate and hope to find a solution soon.

**Comment by raffael0** [comment] 2021-05-01 20:12
Hi. I experienced a the same issue as @bendrexl and managed to "fix" it. It stopped crashing after I deleted the c:\users<yourname>\AppData\Local\MixedRealityFeatureTool folder.

**Comment by sinajahromi** [comment] 2021-07-02 10:12
Hi , is there any new updates regarding the issue? have the same one :(
1.0.2104.4 Beta
Thanks in advance

**Comment by sinajahromi** [comment] 2021-07-02 10:56
Hi,is there any new updates regarding the issue?
Best,
Sina

**Comment by mhussar** [comment] 2022-02-15 18:11
Apparently this issue has not been resolved yet. I am having the same problem. Sometimes won't even open when clicking in the exe. Sometimes it get as far as discovery and then it crashes. I have a good internet connection, the absolute latest version of Windows 10, .net 5 installed, restarted computer but this tool will not work. Hopefully this can be resolved soon. But, given there are certainly a number of people out there who are dealing with this issue (probably many that are too discouraged to bother reporting these issues), can whomever that is in charge modify the official docs to include a clear, concise help file that guides developers on how to manually install the required Unity packages without this clearly buggy tool? Thanks!

**Comment by davidkline-ms** [comment] 2022-02-15 20:35
@mhussar, we have a fix in flight. Hopefully, will be able to publish a new build soon.

**Comment by mhussar** [comment] 2022-02-15 21:09
Thanks for your reply. Looking forward to the new build.

**Comment by davidkline-ms** [comment] 2022-02-15 21:17
This issue should be fixed with v1.0.2111.1-Preview at https://aka.mrfeaturetool (available now)

**Closed by davidkline-ms** 2022-02-15 21:17 UTC
Labels: Bug

**Comment by mhussar** [comment] 2022-02-15 22:16
This site can not be accessed: https://aka.mrfeaturetool/

![Capture](https://user-images.githubusercontent.com/4655568/154158880-18bff861-650e-4344-ad0e-e45ac7b8edc8.JPG)

**Comment by mhussar** [comment] 2022-02-15 22:22
I went to the original URL: https://www.microsoft.com/en-us/download/details.aspx?id=102778  and downloaded the version you updated but it still is working the same as the previous version. Need to double-click the exe 5-6 times to get it to open.

**Comment by keveleigh** [comment] 2022-02-15 22:39
The link was missing some characters: https://aka.ms/mrfeaturetool, but it sounds like you found it anyway.
@davidkline-ms this may be a different issue! Sometimes crashing on launch as opposed to just after the "Discover" button.

**Comment by RThompson153** [comment] 2022-04-02 14:57
[davidkline-ms](https://github.com/davidkline-ms) 

I'm running the latest version 1.0.2203.0.Preview and the same exception is being thrown:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9533#issuecomment-824700750

**Comment by doctor-strange-lab** [comment] 2022-05-06 06:59
Hi, I have the latest version of the feature tool: 'MixedRealityFeatureTool-1.0.2203.0-Preview' and it is still crashing.  I'm using Windows 11 - is that a problem for this tool?

**Comment by HjoshM** [comment] 2022-06-13 07:38
Do we still really need `.NET5` for the tool? Would it not work properly with `.NET6`? When I double-click the exe file to run it (just to have MRTK installed) I am prompted to install `.NET5` but when I am taken to the page, there is this warning that this release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as 6.0 Runtime. Is `.NET5` strictly required?

**Comment by RubensTen** [comment] 2022-07-19 06:13
Hello guys!, do you know how fix it?, I have the same error, here my log:

`Mixed Reality Feature Tool 1.0.2206.1
[19/07/2022 01:08:55 a. m.] Refreshing the Primary catalog.
[19/07/2022 01:08:55 a. m.] Reading Primary feed
Failed to read Primary feed
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Se ha forzado la interrupción de una conexión existente por el host remoto..
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedInternalAsync[T](Uri uri, NetworkCredential credential)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedAsync(Uri registryUri, Boolean isEarlyAccess, String organization, String projectId, String feedId, NetworkCredential credential)
[19/07/2022 01:08:56 a. m.] ERROR: Primary catalog not be refreshed.
System.InvalidOperationException: Feed address appears to contain no data
   at Microsoft.MixedReality.FeatureTool.Utilities.FeedData.Refresh(Boolean updateCache)
[19/07/2022 01:09:02 a. m.] Loading the project manifest.
[19/07/2022 01:09:02 a. m.] Project manifest successfully loaded.
[19/07/2022 01:09:02 a. m.] Looking for previously imported features.
[19/07/2022 01:09:02 a. m.] Found 0 imported features.
Project Unity version 2020.3.36f1
[19/07/2022 01:09:03 a. m.] Refreshing the Primary catalog.
[19/07/2022 01:09:03 a. m.] Reading Primary feed
Failed to read Primary feed
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Se ha forzado la interrupción de una conexión existente por el host remoto..
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedInternalAsync[T](Uri uri, NetworkCredential credential)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedAsync(Uri registryUri, Boolean isEarlyAccess, String organization, String projectId, String feedId, NetworkCredential credential)
[19/07/2022 01:09:03 a. m.] ERROR: Primary catalog not be refreshed.
System.InvalidOperationException: Feed address appears to contain no data
   at Microsoft.MixedReality.FeatureTool.Utilities.FeedData.Refresh(Boolean updateCache)
`

**Comment by davidkline-ms** [comment] 2022-08-18 17:31
@RubensTen && @ianklineCTG,

Can you try deleting the settings json file in %userfolder%\AppData\Local\MixedRealityFeatureTool and try again? I have seen a few instances of some bad data causing crashes,

Thanks!

**Comment by ianklineCTG** [comment] 2022-08-18 17:39
Hey David,

I deleted the settings.json file and ran the tool. This time, instead of crashing I was able to successfully "Discover" the features I wanted and validate them. Now I'm able to see the MRTK features in my Unity project.

Here is my log file of a successful execution
[MixedRealityFeatureTool.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/9376233/MixedRealityFeatureTool.log)
.

Thanks so much for the help! -Ian

**Comment by bamuir** [comment] 2022-09-16 23:57
I am running into the same issues as the others, but I have no settings json file, and deleting the %userfolder%\AppData\Local\MixedRealityFeatureTool is not solving the issue for me. I also am having issues at times even getting the .exe to open, and when/if it does, I see this error in the logs after the crash:

Mixed Reality Feature Tool 1.0.2209.0
[9/16/2022 4:53:15 PM] Refreshing the Primary catalog.
[9/16/2022 4:53:15 PM] Reading Primary feed
Failed to read Primary feed
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedInternalAsync[T](Uri uri, NetworkCredential credential)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedAsync(Uri registryUri, Boolean isEarlyAccess, String organization, String projectId, String feedId, NetworkCredential credential)
[9/16/2022 4:53:16 PM] ERROR: Primary catalog not be refreshed.
System.InvalidOperationException: Feed address appears to contain no data
   at Microsoft.MixedReality.FeatureTool.Utilities.FeedData.Refresh(Boolean updateCache)
[9/16/2022 4:53:29 PM] Loading the project manifest.
[9/16/2022 4:53:29 PM] Project manifest successfully loaded.
[9/16/2022 4:53:29 PM] Looking for previously imported features.
[9/16/2022 4:53:29 PM] Found 0 imported features.
Project Unity version 2020.3.39f1
[9/16/2022 4:53:30 PM] Refreshing the Primary catalog.
[9/16/2022 4:53:30 PM] Reading Primary feed
Failed to read Primary feed
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedInternalAsync[T](Uri uri, NetworkCredential credential)
   at Microsoft.MixedReality.FeatureTool.AzureDevOps.AdoFeed.GetFeedAsync(Uri registryUri, Boolean isEarlyAccess, String organization, String projectId, String feedId, NetworkCredential credential)
[9/16/2022 4:53:30 PM] ERROR: Primary catalog not be refreshed.
System.InvalidOperationException: Feed address appears to contain no data
   at Microsoft.MixedReality.FeatureTool.Utilities.FeedData.Refresh(Boolean updateCache)

**Comment by jeff85008** [comment] 2023-02-14 01:06
I put the MixedRealityFeatureTool.exe file in the same folder as my Unity Projects (not the actual project I was selecting) and it worked :) Maybe the problem is running it from your download folder that required user permissions. I tried running as administrator as well but that didn't work. Hopefully this helps :)

**Comment by MarkoXR** [comment] 2023-11-01 17:45
Using mobile hotspot solved this issue.
