### ISSUE TITLE
CompoundButton OnButtonClicked and OnButtonPressed firing twice

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#2341] opened 2018-06-25 13:48 UTC
## Overview
Debugging why functions hooked to OnButtonClicked  or OnButtonPressed are called twice I found them actually being called twice internally for no particular reason.
The cause is that OnInputDown and OnInputClicked both call DoButtonPressed, which in turn always calls OnButtonPressed and OnButtonClicked.
Since OnInputReleased comes right in between Down and Clicked, a bool to avoid the second click to come in is not possible to use.
OnInputClicked should not call OnButtonPressed and OnInputDown should not call OnButtonClicked.
Maybe that's a relic from Hololens only times (not supporting Clicked or something like that), but with MotionControllers that's not working

## Expected Behavior
Just called once each click

## Actual Behavior
Called twice each click

## Steps to reproduce
- Apply Mixed Reality Scene Settings to a scene, add a holographic button to it and hook something up to one or both those events.
- Play the scene and press the button

## Unity Editor Version
2017.3.1p3

## Mixed Reality Toolkit Release Version
june18_dev

**Comment by keveleigh** [comment] 2018-06-26 19:45
Duplicate of #1879, which I'm working on now.

**Closed by keveleigh** 2018-06-26 19:45 UTC
