### ISSUE TITLE
Add Teleport support for HoloLens

### ISSUE THREAD

**Issue by skyzdev** [microsoft/MixedRealityToolkit-Unity#5843] opened 2019-08-31 20:38 UTC
Please add Teleport support for HoloLens with a sample scene that handles teleport.

**Comment by wiwei** [comment] 2019-09-04 00:02
This is something that some other folks have also requested (around navigating around larger areas without having to physically move that much).

@skyzdev do you have any more information about your scenario (whatever you're willing/able to share) and what type of teleportation experience (i.e. ground level, or arbitrary-in-space teleportation?).

With VR it's somewhat clear where you teleport to (floors). With AR maybe it's the same thing.

@davidkline-ms FYI

**Comment by skyzdev** [comment] 2019-09-04 01:23
Thank you @wiwei 
Having teleportation is very useful for examining a large object at scale (e.g. Saturn five rocket) in a virtual museum or engineering meeting or traversing a large virtual scene with lots of objects. 
**Basic version** would involve an air tap with the gaze cursor focused on the floor in front of you, and then the user's mainCamera dashes across the scene. 
For **HoloLens2**, we could use a custom hand gesture. For example, use Spiderman's web-shooting pose to invoke a far interaction, and then jerk hand to pull you body toward the target like the Spiderman.  
For "AR experiences", the teleportation implementation should have an option to distinguish objects anchored to spatial mapping from other virtual content. The teleport should move us through a large scene of virtual objects while keeping the spatial mapping anchored to the real world. :)

**Comment by Troy-Ferrell** [comment] 2019-10-25 17:03
Dupe of #4451

**Closed by Troy-Ferrell** 2019-10-25 17:03 UTC
Labels: 0 - Backlog, Feature Request, Teleport System
