### ISSUE TITLE
Hand tracking feedback regression

### ISSUE THREAD

**Issue by Xispeo** [microsoft/MixedRealityToolkit-Unity#10443] opened 2022-02-02 13:47 UTC
## Describe the bug

Hand tracking feedback is broken

## To reproduce

- Create a basic scene with MRTK 2.7.3 and Unity 2020.3.27
- Deploy on Hololens 2
- Try to visualize your virtual hands
- Hand mesh does not appear properly. You can see properly hand joints but not the ArticulatedHandMesh, which appears to stay at their original position or move from time to time.

## Expected behavior

ArticulatedHandMesh would be located at the same position than your real hands, as hand joints are

## Screenshots

![file](https://user-images.githubusercontent.com/31275185/152165492-f2db4f28-3a75-4b24-8841-6b9f7d03b54b.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.27
- MRTK Version 2.7.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I have the problem also with MRTK 2.7.2, my app is broken because of that

**Comment by polar-kev** [comment] 2022-02-02 18:38
@elbuhofantasma, can you take a look at this?

**Comment by keveleigh** [comment] 2022-02-03 00:34
@Xispeo, thanks for confirming that this is happens across both MRTK 2.7.2 and 2.7.3.
Can you please confirm if you're using OpenXR or Windows XR Plugin?

**Comment by Xispeo** [comment] 2022-02-03 09:02
The problem occured with Windows XR Plugin.
I switched to OpenXR but the project is now messed up, deployed app does not launch anymore and crashes Hololens 2.
I have restarted from scratch a new project and am injecting previously code & content with OpenXR plugin, functions like a charm.

**Comment by elbuhofantasma** [comment] 2022-02-03 23:33
Thank you for the additional information @Xispeo, I am taking a look at this now and will report back soon with my findings.

**Comment by jloehr** [comment] 2022-02-11 09:54
Hey, we're experiencing the same issue after upgrading from Unity 2020.3.20 (and Windows MR/XR Plugin 4.6.0) to 2020.3.28 (using either Windows MR 4.6.1 or 4.6.2), while still on MRTK 2.7.0.

[Unity 2020.3.24](https://unity3d.com/unity/whats-new/2020.3.24) bumps the WMR XR SDK Plug-on to 4.6.1:
> - XR: Updated WMR XR SDK Plug-on to 4.6.1. Release notes available here:
https://docs.unity3d.com/Packages/com.unity.xr.windowsmr@4.6/changelog/CHANGELOG.html

The com.unity.xr.windowsmr changelog for 4.6.1 states:

> - Fix hand jitter on HoloLens2 when holding hands steady.

Using Unity 2020.3.20 with the Windows MR/XR Plugin 4.6.1 yields the same issue, indicating this is an issue with the Windows MR/XR Plugin 4.6.1.

**Comment by jloehr** [comment] 2022-02-21 09:07
I opened a Unity Ticket. Here's the public Issue Tracker link: https://issuetracker.unity3d.com/issues/articulated-hand-mesh-is-stuck-at-its-initial-position-when-using-windows-xr-plugin-in-hololens-2

**Comment by keveleigh** [comment] 2022-03-09 23:40
I've narrowed this down to a regression in Windows XR Plugin 4.6.1, exactly due to the fix @jloehr pointed out. I've opened a PR with Unity to fix this and will update here when it is released.

**Comment by elbuhofantasma** [comment] 2022-03-29 19:52
This issue seems to have been fixed in Windows XR Plugin 4.6.2, so I am closing this issue. Please re-open this if you find that the Windows XR Plugin 4.6.2 does not fix the issue for you.

**Comment by jloehr** [comment] 2022-03-30 07:15
> This issue seems to have been fixed in Windows XR Plugin 4.6.2, so I am closing this issue. Please re-open this if you find that the Windows XR Plugin 4.6.2 does not fix the issue for you.

@elbuhofantasma Hey, dunno if that's a typo and you meant 4.6.**3**. If not, please reopen this issue, because this bug does exists in Windows XR Plugin 4.6.2.

**Comment by keveleigh** [comment] 2022-03-31 22:06
Yeah, the fix hasn't shipped yet that I'm aware of. Will work on getting an update!

**Comment by elbuhofantasma** [comment] 2022-04-06 16:22
@jloehr I apologize for closing this bug too early. I must have gotten into a weird state with my project that did not reproduce the issue on Windows XR Plugin 4.6.2 when I was retesting this issue last week, or I accidentally tested with OpenXR Plugin.  I am re-validating this bug again right now to confirm it still exists.

**Comment by elbuhofantasma** [comment] 2022-04-06 20:50
This issue was not fixed in Windows XR Plugin 4.6.2. I must have crossed the streams and used a build from one of the other MRTK projects that I used for exploring this issue.

**Comment by keveleigh** [comment] 2022-04-26 18:25
Update: The bug fix has been merged into Windows XR Plugin and is entering their release process.

**Comment by keveleigh** [comment] 2022-05-17 18:52
@jloehr @Xispeo @tommensink @arunrajselvaraj

This fix has been fixed with the 2.9.3 and 4.6.3 releases for Unity 2019 and Unity 2020 respectively. Please let me know if you're still running into issues!

**Closed by keveleigh** 2022-05-17 18:52 UTC
Labels: External
