### ISSUE TITLE
Unity Editor crash

### ISSUE THREAD

**Issue by jerrygg** [Microsoft/MixedRealityToolkit-Unity#2220] opened 2018-05-31 08:49 UTC
## Overview
After I've saved the code in Visual Studio, crashing back into the updated code in Unity, with some sporadic.Detailed error information please see the figure
![qq 20180531163937](https://user-images.githubusercontent.com/7133614/40772433-899b9996-64f2-11e8-95ed-c8e566ddea51.png)

## Expected Behavior
don't crash 
## Actual Behavior
Editor crash 
## Unity Editor Version
Unity 2017.4.3.f1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by StephenHodgson** [comment] 2018-05-31 16:31
Looks like an error from Unity's base XR Namespace for the interaction manager.

Do you have repro steps?

**Comment by eirikhollis** [comment] 2018-06-01 08:21
This happens sporadically with our project as well. If you have a project over a certain size, try clicking play 30-40 times in a row. As mentioned in the error, some kind of buffer gets filled up and forces Unity to restart. I think the issue is Unity-related and there is already a ticket submitted for it (has 2 votes last I checked).

**Comment by StephenHodgson** [comment] 2018-06-07 18:33
Closed in favor of 2268, it has a bug report to unity attached.

**Closed by StephenHodgson** 2018-06-07 18:33 UTC
Labels: Investigate, No Repro, Unity Bug
