### ISSUE TITLE
Requesting access to Extended Eye Tracking API and enabling the custom capability.

### ISSUE THREAD

**Issue by 962557346** [microsoft/MixedRealityToolkit-Unity#10238] opened 2021-09-26 14:23 UTC
## Describe the problem

Hi!
I'm currently working on a project that requires left and right eye gaze vectors for obtaining eye gaze depth. Current Eye tracking SDK of HoloLens 2 doesn't provide left and right eye gaze vectors, only offering the single (cyclopean) eye gaze direction and hit position.

## Describe the solution you'd like

We found [Extended Eye Tracking SDK](https://github.com/magdavuko/mixed-reality-1/blob/d7531c7d233adf33af188c24f2a194b6696db9bf/mixed-reality-docs/mr-dev-docs/develop/native/extended-eye-tracking.md) provides `TryGetLeftEyeGazeInTrackerSpace` and `TryGetRightEyeGazeInTrackerSpace` functions for calculating left eye gaze and right eye gaze. The extended ET API is a custom capability. So I need to [request access to the API](https://github.com/magdavuko/mixed-reality-1/blob/4f087f80ac5f8a6c13877f3b2cd4875e3eb9cb51/mixed-reality-docs/mr-dev-docs/design/requesting-access-to-extended-et-api), if I want to publish my uwp to the Microsoft Store. However, I just want to run my application on HoloLens 2 in developer mode. [The document](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#custom-capabilities) states running in developer mode doesn't need to custom capability. So I try to use the [EyeGazeTrackerWatcher](https://github.com/magdavuko/mixed-reality-1/blob/d7531c7d233adf33af188c24f2a194b6696db9bf/mixed-reality-docs/mr-dev-docs/develop/native/extended-eye-tracking.md#ExtendedEyeTrackingSDK-EyeGazeTrackerWatcher) class of Extended Eye Tracking SDK in the Unity script, but the unity reports that "The type or namespace name 'EyeGazeTrackerWatcher' could not be found (are you missing a using directive or an assembly reference?)". 

In brief, my questions can be three-fold as follows:
- 1. I just want to run the Extended Eye Tracking SDK in the developer mode of HoloLens 2. Do I need to request the custom capability? If don't need, how can I compile the script in Unity that uses the EyeGazeTrackerWatcher class successfully?
- 2. If need, how can I contact the Microsoft Mixed Reality team? We found the [URL](https://github.com/magdavuko/mixed-reality-1/blob/4f087f80ac5f8a6c13877f3b2cd4875e3eb9cb51/mixed-reality-docs/mr-dev-docs/design/requesting-access-to-extended-et-api). The instructions request us to reach out to Microsoft Mixed Reality team (mail: TDB). However, I don't know the specfic email. I posted the question in [#10230](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10230) , but it seems to have no follow-up development. 
- 3. If need, how can I obtain the [Signature Hash of the uwp signing cert](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/hardware-support-app--hsa--steps-for-app-developers)? I tried many methods but they don't work. The [issue](https://github.com/MicrosoftDocs/windows-driver-docs/issues/2270) describes this question, but I also don't know how to sign the sln of Visual Studio 2019 with SHA256 cert?

I really appreciate any help you can provide.

## Describe alternatives you've considered

Additionally, for our use case, falling back to single (cyclopean) eye gaze tracking is not an option.
Thank you very much.

## Additional context

![image](https://user-images.githubusercontent.com/24918185/134811872-9f8f8d60-0049-4471-a71c-e3892ad81490.png)

**Comment by polar-kev** [comment] 2021-09-28 00:12
Hi @962557346, I'll be closing this as a duplicate of #10230. I will add the specific questions you mentioned here to the first issue you opened on this topic.

**Closed by polar-kev** 2021-09-28 00:12 UTC
Labels: Feature Request
