### ISSUE TITLE
can not see any thing whitout cursor

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#4493] opened 2019-05-21 06:11 UTC
## Describe the bug
It's ok when unity remote connected hololens, but i can not see any thing after deploy to hololen 
 

## To reproduce

1. Build scene InputManagerTest by SDK "Build all";
2. install .Appx and Dependencies by ip ;
3. run app in hololens;
4. can not  See anything whitout cursor;

## Screenshots

 
![image](https://user-images.githubusercontent.com/38685433/58072408-2ecc4b80-7bd2-11e9-8fa4-f7cfe6a6f6d3.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.12f1 ,2018.3.09f1 , 2018.4 ]
- HoloToolkit 2017.4.3.0 - Refresh

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by wiwei** [comment] 2019-05-21 17:18
Closing this out, as it's a duplicate of another issue filed a few minutes later.

**Closed by wiwei** 2019-05-21 17:18 UTC
Labels: Bug
