### ISSUE TITLE
MicStreamSelector library no longer supported?

### ISSUE THREAD

**Issue by Porupu** [microsoft/MixedRealityToolkit-Unity#7385] opened 2020-02-25 01:21 UTC
Hi,

If I understand correctly, the MicStreamSelector library is no longer maintained in the current version of the MRTK, are there any future plans to include it again in the Toolkit in the near future? Unless there is another way to access the individual microphones on HoloLens through the current version of MRTK (via Unity)?
Thanks.

**Comment by Troy-Ferrell** [comment] 2020-02-27 00:19
Hi @Porupu thanks for filing this issue. There is also an old known issue for this. Closing this item as a dupe of #2505

**Closed by Troy-Ferrell** 2020-02-27 00:19 UTC
