### ISSUE TITLE
MRTK Interactable speech keywords does not work

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#4187] opened 2019-05-06 20:06 UTC
## Describe the bug

Interactable speech keywords requires IsGlobal to be on (See OnSpeechKeywordRecognized()). However, this means the other interfaces on the button will respond to global select events. 

Further, the voice command should be a toggle enum like SpeechInputHandler.cs

## To reproduce

1) If IsGlobal on and RequiresFocus off, then speech works but button responds to global select events as well. 
2) If IsGlobal off and regardless of RequiresFocus state, button will not respond to speech events. 

## Expected behavior

Should allow for global speech input without rest of button being global. Behavior should be similar to SpeechInputHandler component. 

Also bonus points for allowing easier navigation to the speech profile to add new keywords which isn't obvious to new users

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version RC1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Yoyozilla** [comment] 2019-05-09 21:33
@wiwei  could you please take a look at this one?

**Comment by julenka** [comment] 2019-05-29 16:52
Duplicate of #4598

**Comment by julenka** [comment] 2019-05-30 16:20
Anton explained to me that this issue and the Interactables issue are actually different. This issue covers lower level input system issues. #4598 is specific to Interactable. So I removed duplicate.

**Comment by googlan** [comment] 2019-06-21 15:05
This issue ended up containing multiple sub-issues in it. Let's split them up:
- When interactable is `IsGlobal = true` and regardless of `RequiresFocus` value interactable was receiving all input events, not only speech events. 
-- This part is fixed in PR #4716 by base event system change and registering specifically for speech events. Works both for `RequireFocus = true` and `RequireFocus = false`.
- When interactable is `isGlobal = false`, speech commands don't work regardless of `requireFocus` value.
-- This part is not fixed, but it has a workaround of setting `isGlobal = true` and `requireFocus = true`, because setting global only triggers listening to speech events now.
- Ux improvements.
-- This part is better described and covered by issue #4598.

As 2 parts have been fixed, it is safe to mark this issue as a dupe now.

**Comment by googlan** [comment] 2019-06-21 15:07
Duplicate of #4598

**Closed** 2019-06-21 15:10 UTC
Labels: 0 - Backlog, Bug, DDE Partner, GA Blocker, Speech, UX Controls - Interactable, Urgency-Soon
