### ISSUE TITLE
Request example with ui buttons with motion controller or gaze

### ISSUE THREAD

**Issue by linojon** [Microsoft/MixedRealityToolkit-Unity#1219] opened 2017-10-22 03:10 UTC
hi, I've reviewed the example scenes but don't see an example for Immersive VR of a UI canvas with buttons that work with hand controllers (when on and tracked) or gaze (with generic select including motion controller trigger or other input). And ensure that the OnClick is actually triggers. I tried making my own example but befuddled by a variety of things not working for me. A clean simple example may help.

**Comment by StephenHodgson** [comment] 2017-10-22 19:48
All the example scenes with uGUI should work well, provided that you don't turn your body too much.

There's a bug right now, where the further you turn your body and the controller become desynced.

Take a look at the CanvasUiRaycast test scene.
Also InputManagerTest scene. It does have a single button in it.

**Comment by Marbl70** [comment] 2017-10-23 08:59
There is the issue that a button's OnClick method is not invoked when pressing a controller button/trigger. 

The button is highlighted when the controller is pointing "on" the button and the button also shows the pressed transform state when the controller trigger button is pressed - but the OnClick is not invoked.

It works only when attaching a small script at each button (but I do not hope that this is the intention how to do use UI button): 

public class WMRButtonTap : MonoBehaviour, HoloToolkit.Unity.InputModule.IInputClickHandler
{
    public void OnInputClicked(HoloToolkit.Unity.InputModule.InputClickedEventData eventData)
    {
        if (GetComponent<Button>())
            GetComponent<Button>().onClick.Invoke();
        eventData.Use(); // Mark the event as used, so it doesn't fall through to other handlers.
    }
}

This is a major issue for developing MR apps with Unity right now, at least for us. Not sure if this is related to the sync issue mentioned above or a separate issue,

**Comment by linojon** [comment] 2017-10-23 21:38
I concurr with @Marbl70 , i wrote a similar script. 

And, the InputManagerScene, for me, highlights the UI button with gaze initially. When i pull the motion controller trigger, then cursor control switches to the hands not gaze, and then the button does not highlight or trigger..

**Comment by StephenHodgson** [comment] 2017-10-23 23:58
I'm pretty sure this is related to #1205 which I closed because it was a duplicate of #1179.

This affects what you're pointing at and raycasting against. I noticed that the focus was happening when I wasn't gazing nor pointing at the UI.

![image](https://user-images.githubusercontent.com/13334553/31797645-3c2e3358-b4e4-11e7-9c2b-6fc20266cbeb.png)

**Comment by StephenHodgson** [comment] 2017-10-27 16:15
Okay guys, I've got an update. There is def a bug in the way we're doing our raycasting against uGUI elements.

The raycasts are calc from the user's gaze, not the pointer tip.  I'll be opening an issue dedicated to tracking this bug.

**Comment by wiwei** [comment] 2019-04-11 20:27
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Closed by wiwei** 2019-04-11 20:27 UTC
Labels: Enhancement
