### ISSUE TITLE
Graphics Tools/Standard shader does not work with URP

### ISSUE THREAD

**Issue by alexandermeijersavanade** [microsoft/MixedRealityToolkit-Unity#11248] opened 2022-11-28 18:14 UTC
## Describe the bug
I have created a Unity project with the MRTKDevTemplate project. Everything works fine out of the box. All scenes look good and work perfectly. 

- I have added the Universal RP package to the project.
- Created a Universal Render Pipeline Asset
- Assigned the pipeline asset to Graphics --> Scriptable Render Pipeline Settings
- Project automatically starts converting to URP

## Result
Several materials based on the Graphics Tools/Standard Canvas are causing materials to become purple. Example material would be Canvas Backplate Quad. 

## screenshot

![image](https://user-images.githubusercontent.com/116972250/204350755-6f5be6d0-e224-4a53-abcd-fd0cf8b57b89.png)

According to the documentation (https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-graphicstools/features/standard-shader)  these shaders do support the standard Unity URP

## Your setup 

- Unity Version 2021.3.11f1 (but other  versions same issue)
- MRTK Version 3

## Target platform
- VR

**Comment by alexandermeijersavanade** [comment] 2022-11-28 18:14
![image](https://user-images.githubusercontent.com/116972250/204350696-9b60bdd4-d1ea-4a65-ae00-7b2062f8dce6.png)

**Comment by Zee2** [comment] 2022-11-29 00:23
Hmmm, thanks for calling this out. They definitely *should* support URP, in fact most internal projects here are URP. Pinging @Cameron-Micka  here :)

**Comment by Cameron-Micka** [comment] 2022-11-29 00:40
Hi @alexandermeijersavanade, if you select the shader the magenta materials are using (sounds like it is the `Graphics Tools/Standard Canvas` shader) do you see any errors in the inspector?

If not, what happens if you right click on the shader and select reimport? I've occasionally seen Unity's shader caching system be overzealous when switching render pipelines.

**Comment by alexandermeijersavanade** [comment] 2022-11-29 06:32
Hi @Cameron-Micka It is indeed the Graphics Tools/Standard Canvas shader. There are no errors in the inspector except the warning about the depth buffer. But that warning was already there before I even enabled URP. And the shader was working. I tried to reimport the shader. But that has no effect.

**Comment by alexandermeijersavanade** [comment] 2022-11-29 06:33
the same issue is for the Magic Window Backplate_190x62 material what is using the Graphics Tools Standard

**Comment by alexandermeijersavanade** [comment] 2022-11-29 08:52
I noticed something else. If I change the shader to Graphic Tools/Canvas/Backplate it seems to work. See screenshot. Not sure if this is the right direction. And still the other shader(s) have an issue.

![image](https://user-images.githubusercontent.com/116972250/204482924-2e5a6795-59b6-4bc2-890f-8c43037e522c.png)

**Comment by Cameron-Micka** [comment] 2022-11-29 20:02
Thanks for the extra info @alexandermeijersavanade!

Could you try closing Unity and deleting your Library folder? (That is where your project's shader cache lives.)

I'm not able to reproduce this locally (and we use URP for almost everything). Maybe I'm on a different version of the URP. What URP version are you using? 

Also, shader errors are normally reported in this area of the shader file's inspector: 
![image](https://user-images.githubusercontent.com/13305729/204636013-e4039b76-f4f0-482b-b150-31eb775d72ed.png)

**Comment by alexandermeijersavanade** [comment] 2022-11-29 20:43
Hi @Cameron-Micka yes!!! that did the job. For some reason there were still artifacts in the library folder. it looks as it should be and completely running on  URP :)

**Comment by Cameron-Micka** [comment] 2022-11-29 20:53
That is excellent to hear, thanks for troubleshooting that @alexandermeijersavanade!

**Comment by Zee2** [comment] 2022-11-29 21:03
Closed! Thanks for the huge help @Cameron-Micka  :))

**Closed by Zee2** 2022-11-29 21:03 UTC
Labels: Shaders / Materials, Bug, MRTK3
