### ISSUE TITLE
LeftController is not valid

### ISSUE THREAD

**Issue by raedbenz** [Microsoft/MixedRealityToolkit-Unity#1248] opened 2017-10-27 20:20 UTC
Running toolkit example scene for motion controller in unity latest MRTP, with .NET3.5/4.6 and getting the following error from within the scene. please advice.

transform.localRotation assign attempt for 'LeftController' is not valid. Input rotation is { NaN, 0.000000, 0.000000, 0.000000 }.
UnityEngine.Transform:set_localRotation(Quaternion)
HoloToolkit.Unity.InputModule.MotionControllerVisualizer:Update() (at Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs:128)

**Comment by StephenHodgson** [comment] 2017-10-27 20:51
Duplicate of #1200

**Closed by StephenHodgson** 2017-10-27 20:51 UTC
Labels: Bug
