### ISSUE TITLE
MRTK Standard shader issue (pink) after updating to RC2 from RC1

### ISSUE THREAD

**Issue by comicxmz001** [microsoft/MixedRealityToolkit-Unity#4873] opened 2019-06-13 12:14 UTC
## Describe the bug

After updating to RC2 from RC1, all materials using MRTK Standard Shader become pink.

## To reproduce

For new project:
1. Start a new project
2. Import RC2
3. Create a materials, set shader to "MRTK Standard"
4. Pink.

For RC1(including refresh) project: 
1. Follow instructions to import RC2 
4. All materials using MRTK standard shader become pink.

## Expected behavior

Materials using the shader should not be affected.

## Your Setup (please complete the following information)

- Unity Version 20184.1f1
- MRTK Version v2.0.0 RC2

## Target Platform (please complete the following information)

-UWP

## Additional context

"Roll back" to RC1 (reimport RC1 back to Unity without deleting any RC2 stuff), shader starts working.

**Comment by wiwei** [comment] 2019-06-13 13:10
@Cameron-Micka FYI

**Comment by IsaacSurfraz** [comment] 2019-06-13 14:35
Also experienced this, rollback stopped it

**Comment by Cameron-Micka** [comment] 2019-06-13 16:41
Hi @comicxmz001 & @IsaacSurfraz,

Sadly I was not able to reproduce this by:

1) Creating a new Unity 2018.4.1f1 LTS project
2) Importing the [RC2 Foundation package](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/download/v2.0.0-RC2/Microsoft.MixedReality.Toolkit.Unity.Foundation-v2.0.0-RC2.unitypackage)
3) Creating a new material and selecting the MRTK/Standard shader

![Capture](https://user-images.githubusercontent.com/13305729/59450861-08f42a00-8dbf-11e9-97eb-18d8e34b92ba.PNG)

A pink material hints at a missing shader or a shader compilation error. Does the pink material have the MRTK/Standard shader specified?

![Material](https://user-images.githubusercontent.com/13305729/59450960-4062d680-8dbf-11e9-891b-0a7e07803b37.PNG)

If the material does have the MRTK/Standard shader specified, do you see any shader compilation errors? You should see them here:

![Errors](https://user-images.githubusercontent.com/13305729/59450961-40fb6d00-8dbf-11e9-9433-64c4e83aebf7.PNG)

**Comment by Cameron-Micka** [comment] 2019-06-13 16:45
If possible could you please attach a minimum reproduction Unity project? I will close this issue until then.

**Closed by Cameron-Micka** 2019-06-13 16:45 UTC
Labels: Bug

**Comment by comicxmz001** [comment] 2019-06-20 00:29
The issue is resolved in RC2.1.

**Comment by comicxmz001** [comment] 2019-06-20 00:30
> If possible could you please attach a minimum reproduction Unity project? I will close this issue until then.

The issue is resolved in RC2.1.

**Comment by Cameron-Micka** [comment] 2019-06-20 16:08
That is great to hear @comicxmz001, thank you for the information!
