### ISSUE TITLE
Saving Spatial Mapping and Understanding - Meshes totally scrambled after loading

### ISSUE THREAD

**Issue by Weasy666** [Microsoft/MixedRealityToolkit-Unity#1559] opened 2017-12-21 15:14 UTC
## Overview
The saving of Spatial Map Mesh and/or Spatial Understanding Mesh is working, but when you load the saved meshes they are completely scrambled (Spatial Map Mesh) or are jittering (Spatial Understanding Mesh) like crazy.
I believe this worked when i was trying it a few weeks back, but right now in following development environment, its not working.

**Unity Editor:** 2017.2.0f3
**Visual Studio:** Enterprise 2017 15.5.2
**MixedRealityToolkit:** HoloToolkit-Unity-v1.2017.2.0, same with 2017.2.1
**MixedRealityToolkit-Examples:** HoloToolkit-Unity-Examples-v1.2017.2.0, same with 2017.2.1
**HoloLens:** 10.0.14393.1944

## Expected Behavior
Loaded mesh replaces current mesh without any problem/hickup

## Actual Behavior
Loaded mesh is
1. totally scrambled (Spatial Map Mesh), meaning the triangles/vertices are not in the correct place
or
2. jittering (Spatial Understanding Mesh) like crazy

## Steps to reproduce
Create new Unity project, import Holokit asset and Holokit-Example asset from [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.2.0).
Use the SaveSpacialUnderstanding and/or SaveSpatialMapping scene from the Examples and start.
After a short while of mapping, save with the FileSurfaceObserver and then load with the FileSurfaceObserver and see scrambling or jittering.

**Comment by krishnan-unni** [comment] 2017-12-26 22:12
Hi @StephenHodgson ,I am just adding my test case here too. I tried the same with Unity 2017.3.0f3. When trying it in unity editor with fbx format room models in spatial mapping, all is well. Saves fine and loads fine too. Buit once I try it in the hololens emulator with .xef files then I see the above mentioned behavior. All scrambled. Not only that I copied the room mesh saved from emulator and loaded it in unity and inspected it. Noticed that it also is creating a duplicate of every stored mesh. I manually removed the duplicate and still I could see that it is all scrambled. I tried adding material to it to see if I could understand a pattern. Looks like its all inside out. I'm not sure of that though.

**Comment by krishnan-unni** [comment] 2018-01-06 22:36
Hi @StephenHodgson are there any updates on this one mate? Any work around or fix coming?

**Comment by StephenHodgson** [comment] 2018-01-06 22:39
Don't know, sorry.  It's not a priority for me.  Maybe someone else will be able to provide a solution?

**Comment by Weasy666** [comment] 2018-01-09 21:13
I'm also still interested in this.
To tell you something about my use case, i want to map a building or the floor of a building with one HoloLens, save the SpatialMapping Mesh and transfer it to another HoloLens, where it is loaded and used. The second (or other) was never in the building before, but should work as if it was after loading the mesh.
I thought about the problem again and i remembered that the problem might happening when the loaded mesh is set as the new Surface Observer or rather when it is set as mapping source with `SetSpatialMappingSource`.
Hope that helps.

**Comment by krishnan-unni** [comment] 2018-01-10 00:47
@Weasy666 I tried that, but as I mentioned I am not setting the saved mesh as a mapping source I am using the mesh as a simple gameobject in my scene. So I do not think this is the issue. Also, it works perfectly in unity editor. it becomes scrambled only when I run the application in the Hololens emulator. As I mentioned in my previous comment it is creating duplicate of each surface planes in the saved mesh and it is also scrambled.

**Comment by krishnan-unni** [comment] 2018-01-19 02:21
@Weasy666 this might sound silly but I just noticed, since the mesh saver is working fine in unity but not in emulator - the room models in emulator is of type xed (Kinect studio) while in unity they are either room or fbx extensions. xed is the one which is not getting saved\loaded properly. I'll investigate and let know if I find anything. Sad thing is I see atleast 3 open issues related to mesh saving and people are interested in the feature but no fixes on it yet :(

**Comment by Norair1997** [comment] 2019-02-28 09:06
> I'm also still interested in this.
> To tell you something about my use case, i want to map a building or the floor of a building with one HoloLens, save the SpatialMapping Mesh and transfer it to another HoloLens, where it is loaded and used. The second (or other) was never in the building before, but should work as if it was after loading the mesh.
> I thought about the problem again and i remembered that the problem might happening when the loaded mesh is set as the new Surface Observer or rather when it is set as mapping source with `SetSpatialMappingSource`.
> Hope that helps.

How did you achieve this? I need almost excactly the same thing. HL1 scans, exports 
HL2 imports and can update the room and export again...
When I import the Surfaces in HL2 and I create a new Source and add the surfaces to it, and at the end I do SetSpatialMappingSource(generatedSource) 
And then I say StartObserving() to update the room...But the SurfaceObserver creates new Surfaces instead taking the ones I gave it...

**Comment by Yoyozilla** [comment] 2019-04-11 21:22
Could you please move to MRTK v2 and see if the issue repros.

**Closed by Yoyozilla** 2019-04-11 21:22 UTC
Labels: Release Bug

**Comment by keveleigh** [comment] 2019-04-11 21:25
It's possible this was fixed via https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2325
