### ISSUE TITLE
Bounding box far rotate about x axis is not correct

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5666] opened 2019-08-15 17:05 UTC
## Overview
Rotation using the handles of the bounding box should be intuitive, along all axes. Currently, the bounding box does not rotate correctly when you grab interaction handles on the far side of the bbox, when using far interaction.

![image](https://user-images.githubusercontent.com/168492/63111991-e4920680-bf43-11e9-8ea2-50b518a150ac.png)

## Steps to reproduce
Please see the following video for the issue:

https://www.dropbox.com/s/n09uw38i88wslf6/MRTKRC2.1BBoxIssue.mp4?dl=0

In the video, the near gizmo will rotate clockwise or counterclockwise to up/down hand movement, while the far gizmo will do the opposite. 

## Expected Behavior
The far gizmo should rotate the cube in the same direction as the near gizmo in response to up/down movement.

## Actual Behavior
When you grab the far gizmo, it rotates in the opposite direction as the near gizmo in response to up/down movement

**Comment by thalbern** [comment] 2019-09-26 15:44
so i thought about this and tried several things - the actual problem here is the editor far interaction simulation. Our rotation behavior is right. If you try to do this on device and you put your hand closer to yourself to make the forward rotation movement of far back handle with your far hand interaction you'll see that it actually does what it should. In the case of the editor simulation we're not moving the hand in depth which causes this to look weird, but actually it's correct in that scenario - in the far back handle you're closer to the back site of the cube, so moving your hand straight down should actually rotate it in that direction. you'd have the same behavior if you do a near interaction.

See the below gif where I move the simulated hand (far interaction) and in addition of the y axis movement also change the z position of the hand - with this scenario the rotation looks correct because we're actually shortening the distance of hand to cube - far interaction just behaves like having a long (sticky) stick in your hand and if you have a slightly tilted cube where you touch the back of it and then move the stick down it will rotate towards the back - if you grab it and pull it towards yourself while moving it down it will rotate to the front.

![rotation_far_boundingbox](https://user-images.githubusercontent.com/36998103/65703556-dd026900-e07c-11e9-8ef7-8a7dbb9fe723.gif)

**Comment by thalbern** [comment] 2019-09-27 09:43
closing as won't fix - works as intended

**Closed by thalbern** 2019-09-27 09:43 UTC
Labels: Bug, Current Iteration, UX Controls, UX Controls - Bounding Box
