### ISSUE TITLE
Constraint On Rotation from Rotation Axis Constraint does not work setting by code

### ISSUE THREAD

**Issue by Seikon** [microsoft/MixedRealityToolkit-Unity#7339] opened 2020-02-17 11:17 UTC
## Describe the bug

When I add Rotation Axis Constraint + Manipulation handler behaviours and try to set ConstraintOnRotation by code to wherever Axis, this does not reflect the changes in editor and the functionality part does not work too.

However when I set HandType parameter to two handed (for example) this work perfectly

## To reproduce

1. Add behaviours
2. On Added behaviours listener or whatever line of code after behaviour have been added set:

rac.ConstraintOnRotation =AxisFlags.ZAxis; 
(rac means RotarionAxisConstraint instance)
## Expected behavior

In editor I should see Constraint On Rotation set to Z Axis and also trying to rotate the game object around that axis could not rotate.

## Your setup (please complete the following information)

- Unity Version 2019.3.1f1
- MRTK Version 2.3.0

## Target platform

- HoloLens

**Comment by wiwei** [comment] 2020-02-19 00:27
@thalbern @MenelvagorMilsom FYI

@Seikon can you add some more details on how you're hitting this? We have tests that show that setting the constraint at runtime works:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/186fc4eaf95ea4d3f3525afdefe7864026a5c961/Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs#L578

I'm guessing that if you're just setting the RotationAxisConstraint it's missing the additional setting here:

```c#

        public RotationConstraintType ConstraintOnRotation
        {
            get => constraintOnRotation;
            set
            {
                constraintOnRotation = value;
                rotateConstraint.ConstraintOnRotation = RotationConstraintHelper.ConvertToAxisFlags(constraintOnRotation);
            }
        }
```

**Comment by wiwei** [comment] 2020-02-19 00:29
Also I think that the reworked ManipulationHandler avoids this issue entirely (see ObjectManipulator.cs) - I think I'd recommend using that over ManipulationHandler at this point  (unless @MenelvagorMilsom says otherwise)

**Comment by MenelvagorMilsom** [comment] 2020-02-19 10:25
So, I may understand what's happening here. Let me make a guess:

```csharp
GameObject gameObject; // assume this is initialized somewhere

var manipHandler = gameObject.AddComponent<ManipulationHandler>();
var rotateConstraint = gameObject.AddComponent<RotationAxisConstraint>();

rotateConstraint.ConstraintOnRotation = AxisFlags.ZAxis;
```

If you're doing something similar in order to add these two components, then I understand the issue. When you add `ManipulationHandler` to the object, `ManipulationHandler` initialization adds a `RotationAxisConstraint` if none exists already (see [here](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/186fc4eaf95ea4d3f3525afdefe7864026a5c961/Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs#L321)). When you then use add your own `RotationAxisConstraint`, a second component is added and it's not the same as the one added and used by the `ManipulationHandler`. As a result, the changes you make to that component don't have any effect.

This works if you add a `RotationAxisConstraint` via the inspector, as `EnsureComponent` will use the existing `RotationAxisConstraint`.

The problem is that `ManipulationHandler` is not designed to work with user defined `RotationAxisConstraints`. All constraints, including `RotationAxisConstraint`, are designed to be used with `ObjectManipulator`. `ManipulationHandler` only piggybacks on some of these constraints by adding its own copies of the constraints to the object. This was done so that the constraint logic wasn't duplicated across multiple locations.

The advised way to constrain the rotation axis for `ManipulationHandler` is to do the following:
```csharp
GameObject gameObject; // assume this is initialized somewhere

var manipHandler = gameObject.AddComponent<ManipulationHandler>();
manipHandler.ConstraintOnRotation = RotationConstraintType.ZAxisOnly;
```

If you need to use `RotationAxisConstraints` for some other reason, such as only wanting to constrain rotation about a single axis, rather than two, then you should be using `ObjectManipulator`. This component provides all of the functionality of `ManipulationHandler` and works a lot better with constraints. See #7345 for some documentation on `ObjectManipulator` and constraints.

You can use the migration window to upgrade your objects/scenes to use `ObjectManipulator`. See this docs page for details:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/MigrationWindow.html

**Comment by Seikon** [comment] 2020-02-19 11:01
Thank you both @MenelvagorMilsom @wiwei for your awnsers. The problem was the manipulation handler initialization. I am using a custom children class from ManipulationHandler created by me called "FurnitureManipulationHandler" for broadcasting all events from manipulation to another component. For some reason in this version, the Manipulation handler does not "ensure" the rotation RotationAxisConstraints and when I´m gonna to use it, it seems to be null. I think ObjectManipulator works better for dinamic roatation/movement constaints in a near future I plan to migrate to it, anyways I have solved my problem adding an extra method in my custom child that allow  rotateConstraint setting after Manipulationhandler initialization.

**Comment by wiwei** [comment] 2020-02-19 16:28
Cool, thanks @Seikon for clarifying - I think I'm going to close this issue in favor of using ObjectManipulator - feel free to open a new issue on that if you're still seeing that issue at that time.

**Closed by wiwei** 2020-02-19 16:28 UTC
Labels: Bug
