### ISSUE TITLE
MicrophoneStreamSelector library

### ISSUE THREAD

**Issue by Porupu** [microsoft/MixedRealityToolkit-Unity#7376] opened 2020-02-22 12:01 UTC
Hi,

on the front page of https://github.com/microsoft/MixedRealityToolkit it shortly describes the usage of different libraries of the Toolkit, most of them usable in Unity.

This branch (https://github.com/microsoft/MixedRealityToolkit-unity) doesn't seem to maintain the MicrophoneStreamSelector library as the older version did.

1. Is there a way to use https://github.com/microsoft/MixedRealityToolkit-unity .unitypackage files to access the individual microphones? I know there are old demos such as https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Examples/Input/Scripts/MicStreamDemo.cs or https://github.com/microsoft/MixedRealityToolkit/tree/master/Input/MicStreamSelector but I can't seem to manage to load the plugins/libraries correctly into Unity, which brings me to
2. is there a detailed guide on how to load the (old) plugins/libraries into Unity? https://github.com/microsoft/MixedRealityToolkit/wiki/Getting-Started described a way to setup an independent build environment (if I understand it correctly), but can it be loaded into Unity in an easier way? If there isn't, could someone please briefly explain to me how to load the plugins (specifically the Microphone Stream Selector) into Unity and what all is needed?
Thanks.

**Comment by Troy-Ferrell** [comment] 2020-02-27 00:19
Hi @Porupu thanks for filing this issue as well. There is also an old known issue for this. Closing this item as a dupe of #2505

**Closed by Troy-Ferrell** 2020-02-27 00:19 UTC
Labels: Documentation
