### ISSUE TITLE
Assertion failed: Main camera does not exist!  Error

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1381] opened 2017-11-17 08:50 UTC
## Overview
I get assertion failed errors when I am using the `MixedRealityCameraParent`.
The `MixedRealityCamera` inside the parent is tagged as `MainCamera`.

It works with the `HololensCamera` prefab.

## Expected Behavior
The application should run with no errors.

## Actual Behavior
There are 3 assertion errors like this:
`Assertion failed: Main camera does not exist!
UnityEngine.XR.WSA.HolographicSettings:get_IsDisplayOpaque()
HoloToolkit.Unity.Boundary.BoundaryManager:RenderFloorQuad() (at Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs:107)
HoloToolkit.Unity.Boundary.BoundaryManager:Awake() (at Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs:94)`

## Unity Editor Version
2017.2.0f3

## Mixed Reality Toolkit Release Version
Last master https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/272d5fd10c0b836a2a7bcb021a655dcf2288d7e9

**Comment by StephenHodgson** [comment] 2017-11-17 09:03
Duplicate of #1369

**Closed by StephenHodgson** 2017-11-17 09:03 UTC

**Comment by davidslight** [comment] 2018-05-10 00:26
Unity editor 2017.2.1p2 and MRTK 2017.2.1.4
