### ISSUE TITLE
Add ability to set min/max values for pinch slider

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5674] opened 2019-08-15 20:27 UTC
## Overview
The Pinch Slider's min / max values are currently hard coded to 0 and 1. But what if I want a slider to control a value from -5 to 5? I need to write my own component. It would be nice if instead we could configure the min / max values directly on pinch slider.

## New Fields
The following new public properties would be added, with private serialized backers:

- MinValue - minimum value of slider. Default is 0.
- MaxValue - maximum value of slider. MaxValue > MinMvalue. Default is 1.
- Value would be updated so that MinValue <= Value <= MaxValue

## Tests to Add
- [ ] If code tries to set  MinValue > MaxValue, throw and error
- [ ] When Value gets updated, verify that slider moves to correct position. Set Min = -1, Max = 1, then set value to 0. Verify that value thumb is at correct position. Test for other Min and Max values.
- [ ] Move slider with hand. Change Min and Max Values. Check that the Value of the slider is correct. If slider is in middle and min = 2, max = 4, then value should be 3. If min = 3 and max = 11 then value should be 7.

## Documentation to Add
- [ ] Add docs describing min and max value fields

**Comment by Zee2** [comment] 2022-08-31 17:32
Duplicate of #10803 .

**Closed by Zee2** 2022-08-31 17:32 UTC
Labels: UX Controls, Feature Request, Help Wanted, UX Controls - Slider
