### ISSUE TITLE
MRTK 2.5.1 by Package Manager Problem

### ISSUE THREAD

**Issue by bear8203** [microsoft/MixedRealityToolkit-Unity#8950] opened 2020-11-16 02:20 UTC
## Overview
Windows Mixed Reality Eye Gaze Provider Type Missing
(Try Repair is not working as well)

## Expected behavior
There should be "WindowsMixedRealityEyeGazeDataProvider"

## Actual behavior
It is Red Indicating in Inspector with Missing.

Console is :
Unable to register IMixedRealityInputDeviceManager data provider (Windows Mixed Reality Eye Gaze Provider) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, String, SupportedPlatforms, Object[]) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/BaseDataProviderAccessCoreSystem.cs:206)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, String, SupportedPlatforms, Object[]) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/BaseDataProviderAccessCoreSystem.cs:159)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Services/InputSystem/MixedRealityInputSystem.cs:275)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Services/InputSystem/MixedRealityInputSystem.cs:236)
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__63_0(IMixedRealityService) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:994)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:1109)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:994)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:523)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:639)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:789)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:get_Instance() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Services/MixedRealityToolkit.cs:614)
Microsoft.MixedReality.Toolkit.Editor.MixedRealityToolkitInspector:OnInspectorGUI() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.1/Core/Inspectors/MixedRealityToolkitInspector.cs:25)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
Unity3D 2020.1.12f1

## Mixed Reality Toolkit release version
MRTK 2.5.1 (Installed in Unity Package Manager in Internal Editor)

**Comment by yacuzo** [comment] 2020-12-18 09:19
I think this is a duplicate of #7284

**Closed** 2021-03-08 23:37 UTC
