### ISSUE TITLE
Failed to get IHolographicCameraRenderingParameters from main camera for updating rendering parameter.

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6807] opened 2019-12-05 19:21 UTC
## Describe the bug

This error is logged when a hand enters the frame during remoting with HoloLens2.
```
Failed to get IHolographicCameraRenderingParameters from main camera for updating rendering parameter.
```

![image](https://user-images.githubusercontent.com/53493796/70265971-622a8e00-1750-11ea-8cf1-75458592dcc0.png)

## To reproduce

1. Install remoting app on HoloLens 2 device
2. Import latest unity foundation and examples packages, open hand interaction examples scene
3. Window > XR > Holographic Emulation, enter ip address displayed through device 
4. https://docs.microsoft.com/en-us/windows/mixed-reality/unity-play-mode

## Your Setup 

- Unity Version 2018.4.13f1
- MRTK Version v2.2

## Target Platform 
- HoloLens 2 Remoting

**Comment by davidkline-ms** [comment] 2019-12-06 00:03
i cannot reproduce this with the latest Windows Mixed Reality XR package (1.0.15) on Unity 2018.4.13f1

**Comment by Troy-Ferrell** [comment] 2020-01-08 21:41
@davidkline-ms / @keveleigh 
I can reproduce this on 2019.2.17f1

Looks like maybe Unity bug underneath?
https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographiccamerarenderingparameters

**Comment by keveleigh** [comment] 2020-02-21 01:03
Spent a bit debugging this. Looks like a Unity issue, possibly caused / exacerbated by any perf cost of hand visualization / remoting. Unfortunately doesn't have an obvious fix that I can see, but I'll keep my eye on it.

**Comment by nooxouille** [comment] 2020-03-03 09:00
Hi there! Issue reproduced on Unity **2018.4.18f1** (LTS) + latest MRTK version

**Comment by keveleigh** [comment] 2020-03-03 18:39
We've identified a potential fix with Unity. I'll update this thread when I get an expected version number.

**Comment by ceitel** [comment] 2020-03-05 23:08
Also reproduced with Unity 2019.3.3f1, no MRTK installed, WMR 4.2.1 package installed

**Comment by matware** [comment] 2020-03-23 10:20
Seeing this in 2019.3.6f1 in clean scene with MR toolkit 2.3.0 (no hand mesh) . Also not seeing anything on device, it connects, screen goes black and nothing, but I see a room mesh/camera movement in the scene, so there is data going back to Unity.

Using the new XR plugin management system and the Windows XR Remoting plugin I do get video output, but no hand meshes etc.

Does anybody have Holographic Remoting working reliably with Unity day to day? If so, how?

**Comment by keveleigh** [comment] 2020-03-23 17:47
Looking like the fix for this should ship in Unity 2019.3.7 and 2018.4.19.

**Comment by nooxouille** [comment] 2020-03-27 16:24
> 
> 
> Looking like the fix for this should ship in Unity 2019.3.7 and 2018.4.19.

Nice! Many thanks ;)

**Comment by ceitel** [comment] 2020-03-27 18:00
2019.3.7 is now available! (as well as 2018.4.20)

**Comment by matware** [comment] 2020-03-28 23:11
Yay, i finally checked and can also confirm that it work.

**Comment by keveleigh** [comment] 2020-03-30 22:27
Closing as fixed in Unity 2019.3.7 and 2018.4.19. Please comment if you're still seeing it in those versions!

**Closed by keveleigh** 2020-03-30 22:27 UTC
Labels: Bug, External, Holographic Remoting
