### ISSUE TITLE
Issues using the keyboard prefab on PC

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1370] opened 2017-11-15 16:08 UTC
## Overview
When using a uGUI text field and the virtual keyboard prefab on PC, both the virtual keyboard and OS keyboard shows up in the application.

HoloLens is unaffected.

## Expected Behavior
A single keyboard

## Actual Behavior
OS and keyboard prefab shows up

## Steps to reproduce
- Open keyboard test scene
- Play in editor
- Attempt to write in text field

## Unity Editor Version
2017.2.0p1 MRTP4

## Mixed Reality Toolkit Release Version
db59a1c7fa0c0c463466028c5f3e70088bbfda52

**Comment by markgrossnickle** [comment] 2018-01-05 06:58
This is still active in 2017.2.1p1

It also should be noted that even if you do not have uGUI elements in your scene the issue will still occur because of the InputField that is within the Keyboard.prefab itself.

**Comment by MatrixInception** [comment] 2018-01-28 17:12
I found a less-than-perfect workaround: set InputField 's interactable bool to false. This will prevent the OS keyboard from showing up, and upon user click, it bring up only the MRToolKit keyboard. However, this comes at a price... you wouldn't get the interactable features of the InputField UI, such as highlighting selection and caret... 

Like Mark mentioned, this also needs to be done for the InputField within the Keyboard.prefab itself. In addition, I recommend changing the Disabled colour to white and adding the following script into SliderInputField.cs to set caret position at the end upon user click: 

        public override void OnPointerClick(PointerEventData eventData)
        {
            base.OnPointerClick(eventData);
            MoveTextEnd(false);
        }

**Comment by ivan2007** [comment] 2018-02-09 09:27
I am experiencing the same issue with my app.
Unity documentation say:
Windows Store Apps: On Universal Windows 10 Apps the touch screen keyboard is only supported in XAML based applications with touch input support.
My app is with Build Type D3D and not xaml so this is the first strange thing (did they intend .Net scripting backend?)
However since the keyboard is shown we can try to disable the touch input support.
To do this we can define a new BaseInput used by the BaseInputModule where touchSupported is overrided and setted to false.
BaseInputModule has a protected property m_InputOverride that we can use to tell unity to use the new BaseInput.
That said, as a temporary workaround, I made the attached script that can be added to the EventSystem game object of the scene or to another game object (in the latter case you must set the field BaseInputModule with the current input module).
In my case it seems to work (the native keyboard is not shown).
Can someone try this workaround so we can be more confident using it?.
Thank you
[HideUnityTouchScreenKeyboard.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1710401/HideUnityTouchScreenKeyboard.zip)

**Comment by 265lutab** [comment] 2018-02-09 09:31
What changed in the last few days? The build on 2/06/18 did not bring up the OS keyboard now it does. Also in my project at least it opens the keyboard prefab, then opens the OS keyboard, then closes the OS keyboard and opens it again.

**Comment by ivan2007** [comment] 2018-02-09 09:40
@265lutab, I don't know.
Can you try the workaround?
Thanks

**Comment by 265lutab** [comment] 2018-02-09 19:52
The build I made today does not show the system keyboard. I'm not aware of any changes I've made that would effect it. I don't know why it is now working correctly.

**Comment by 265lutab** [comment] 2018-02-09 19:58
In fact the builds I made that displayed the OS keyboard yesterday now don't. My guess is something in the mixed reality portal that was changed enabling the keyboards for a little while.

**Comment by 265lutab** [comment] 2018-02-09 21:08
Is anyone else still having the problem?

**Comment by 265lutab** [comment] 2018-02-09 21:46
@ivan2007 I did try bringing your script into the project anyways to see what would happen. I'm getting this error
"Assets/Scripts/HideUnityTouchScreenKeyboard/HideUnityTouchScreenKeyboard.cs(14,49): error CS1644: Feature `expression bodied members' cannot be used because it is not part of the C# 4.0 language specification" I am using IL2CPP for my project.

**Comment by 265lutab** [comment] 2018-02-09 21:47
I have the Scripting Runtime Version set to 3.5 and the Api Compatibility Level set to 4.6. (I'm guessing the error is from the Scripting Runtime Version being 3.5 instead of 4.6.

**Comment by ivan2007** [comment] 2018-02-09 22:19
You can change the body of the property
public  bool touchSupported { get { return false; } }

**Comment by 265lutab** [comment] 2018-02-13 08:39
Thanks I did start having the keyboard error again so I used your script. It did mostly work for me. I'm not getting the system keyboard 90% of the time, but I did have it come up once. I haven't been able to repeat it so I'm not sure what caused it to be shown. Do you know if there is a call that can be used to close the system keyboard as a backup if it opens for some users?

**Comment by ivan2007** [comment] 2018-02-16 08:28
@265lutab,
TouchScreenKeyboard has a field 'active' but it is not static.
The keyboard is opened by the InputField as you can see here (code from InputField):
 private void ActivateInputFieldInternal()
    {
      if ((UnityEngine.Object) EventSystem.current == (UnityEngine.Object) null)
        return;
      if ((UnityEngine.Object) EventSystem.current.currentSelectedGameObject != (UnityEngine.Object) this.gameObject)
        EventSystem.current.SetSelectedGameObject(this.gameObject);
      if (TouchScreenKeyboard.isSupported)
      {
        if (this.input.touchSupported)
          TouchScreenKeyboard.hideInput = this.shouldHideMobileInput;
        this.m_Keyboard = this.inputType != InputField.InputType.Password ? TouchScreenKeyboard.Open(this.m_Text, this.keyboardType, this.inputType == InputField.InputType.AutoCorrect, this.multiLine) : TouchScreenKeyboard.Open(this.m_Text, this.keyboardType, false, this.multiLine, true);
        this.MoveTextEnd(false);
      }
      else
      {
        this.input.imeCompositionMode = IMECompositionMode.On;
        this.OnFocus();
      }
      this.m_AllowInput = true;
      this.m_OriginalText = this.text;
      this.m_WasCanceled = false;
      this.SetCaretVisible();
      this.UpdateLabel();
    }
m_Keyboard is protected.
You can make a script to access this field with reflection.
During my test I noted that the script always work if you haven't set a breakpoint in the code (debug configuration)
So when you build with Master or Release configuration in my case the script works.

**Comment by Alexees** [comment] 2018-02-25 07:51
@ivan2007 I tested the reflection code and it's not working on Hololens. As soon as an KeyboardInputField is focused, the console starts spamming NullReferenceExceptions. I read somewhere, that the Hololens requires the InputSystem to be the StandaloneInputModule.

**Comment by ivan2007** [comment] 2018-02-25 08:59
@Alexees 
Thanks for your test
I don't know what you can do with HoloLens (I can't do any test on it).
I saw that exception also without the script during the test with HMD.
If you find any workaround please share here.

**Comment by StephenHodgson** [comment] 2018-02-25 15:50
When the HoloLens gets the rs4 update this will no longer be a problem.  Also reflection is probably not the best solution.

Simplest fix is to probably just check if the keyboard is opaque and return.

**Comment by ivan2007** [comment] 2018-02-25 23:31
Hi Stephen,
I am sorry but I don't understand if your fix is also for HMD and where to check if the keyboard is opaque.
However I have seen that the keyboard already uses a custom InputField (SliderInputField).
If we make an override of LateUpdate like this:
`        protected override void LateUpdate()
        {
            base.LateUpdate();
            if (m_Keyboard != null )
            {
                m_Keyboard.active = false;
                m_Keyboard = null;
            }
        }
`
the problem seems fixed (no second keyboard appear and no exception is thrown).
LateUpdate calls ActivateInputFieldInternal and opens the keyboard.
The script is no more necessary. 
In my case I see that the keyboard is not null only one time
Tested with Unity 2017.3.1p1 and HMD.

**Comment by StephenHodgson** [comment] 2018-02-25 23:34
Editing my response above.

I meant to check if the device is opaque via holographic settings API.

**Comment by Alexees** [comment] 2018-04-09 16:15
@ivan2007 I was wrong about your reflection fix, it could work on Hololens, the NullRef was caused by something else.

**Comment by ivan2007** [comment] 2018-04-09 17:49
@Alexees,
to avoid reflection now I am using this (inside SliderInputField):
`protected override void LateUpdate()
        {
            try
            {
                base.LateUpdate();
            }
            catch { }
            if (m_Keyboard != null)
            {
                m_Keyboard.active = false;
                m_Keyboard = null;
            }
        }`

**Comment by Alexees** [comment] 2018-04-10 13:45
@ivan2007 I tried that on my KeyboardInputFields and it does not work when built to MR, the Keyboard still shows up (Unity 2017.3.1p3)

**Comment by ivan2007** [comment] 2018-04-10 14:25
@Alexees, did you try it with 'SliderInputField' of MRTK?

**Comment by Alexees** [comment] 2018-04-10 15:58
@ivan2007 That class is doing nothing on its own, not even opening the 3D Unity Keyboard, or am I missing something?

**Comment by ivan2007** [comment] 2018-04-11 07:13
@Alexees, SliderInputField is the InputField used by MRTK keyboard prefab.
Unity initializes the system keyboard inside LateUpdate of InputField.
My code overrides LateUpdate, you must put it inside SliderInputField.
I use it with HMD and in my case it works.

**Comment by Alexees** [comment] 2018-04-12 10:56
@ivan2007 I'm really at a loss here and don't understand what the difference is. I've put your code into both, KeyboardInputField and SliderInputField, though I wasn't using the latter. I can confirm by logging that the keyboard is not null, deactivated and then set to null. Even though this code executes every time I gaze at the InputField and LateUpdate captures the keyboard it still shows up unfazed. Doesn't matter if I build a regular or debug build from Unity and then run either of those in VS in Release or Debug configuration. The behavior is always the same. It only happens with the real device though, it does not when using the simulator.
I really do not know what to do here.

**Comment by ivan2007** [comment] 2018-04-12 12:14
@Alexees, 
I am using Unity 2017.3.1p1, MRTK 2017.2.1.0 and HMD.
Which versions are you using?

**Comment by ivan2007** [comment] 2018-04-13 21:34
@Alexees,
I upgraded Unity to 2017.4.1f1 and now I have your same problem.
Waiting for a real solution I made a custom SliderInputField where I have completely removed the code that instantiate the TouchScreenKeyboard. 
I used reflection to access private field, properties and methods **so this is not a solution but is only being temporary workaround**. 
You can find the code in the attachment. Hope this helps.
[SliderInputField.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1909327/SliderInputField.zip)

**Comment by Alexees** [comment] 2018-06-22 12:08
@ivan2007 thanks for confirmation and the code you're using. I should have mentioned that I was on 2017.3.1p3. I kinda did the same thing, reverting to a text field and emulating the Behaviour of an InputField.

**Comment by Alexees** [comment] 2018-08-08 10:01
@StephenHodgson is this still an issue? can this be handled from the Toolkit side, or is that basically a bug or feature Unity needs to fix or expose to be disablable?

**Comment by swatvel** [comment] 2018-10-25 19:21
@ivan The fix which you have mentioned will work in Keyboardinputfield script as well ?

**Comment by ivan2007** [comment] 2018-10-25 21:31
@swatvel I'm using MRTK 2017.4.0.0, Unity 2017.4.11f1 and this  [SliderInputField.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/2516792/SliderInputField.zip)
In the Keyboard class I commented:
- InputField.ActivateInputField() (PresentKeyboard() function)
- InputField.keyboardType = (TouchScreenKeyboardType)(-1); (Awake function)
With these two lines there were NullReferenceExceptions building with VS

**Comment by Yoyozilla** [comment] 2019-04-11 21:15
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 

Also we moved on to use OSK instead of the keyboard prefab in v2. 

Thanks!
Yoyo

**Closed by Yoyozilla** 2019-04-11 21:15 UTC
Labels: Immersive HMD, Release Bug
