### ISSUE TITLE
Unity UI text edit field should make virtual keyboard appear

### ISSUE THREAD

**Issue by danielhofmann-ms** [microsoft/MixedRealityToolkit-Unity#3970] opened 2019-04-15 15:30 UTC
## Overview
Open the _HandInteractionExamples_ scene and select a text edit control. This should cause a virtual keyboard to show up by default.

## Mixed Reality Toolkit Release Version
MRTK v2

**Comment by chrisfromwork** [comment] 2019-04-15 16:08
I've hit this pain as well. It would be nice to have this behaviour just work by default. Android and iOS seem to work without any additional logic.

**Comment by julenka** [comment] 2019-05-15 18:48
Removing Yoyo since she is not actively working on this.

**Comment by julenka** [comment] 2019-05-15 18:50
@keveleigh is this a bug in Unity?

**Comment by julenka** [comment] 2019-07-10 01:45
Marking as GA blocker because many partners actually use Unity UI

**Comment by Troy-Ferrell** [comment] 2019-08-02 16:43
@julenka / @keveleigh any update on this one?

**Comment by julenka** [comment] 2019-08-02 20:53
I'm on vacation until 8/8, I don't have any updates. I believe we assigned this to Kurtis since the issue is actually a problem with how Unity makes the Windows API calls for [InputPane.show](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.ViewManagement.InputPane).

**Comment by davidkline-ms** [comment] 2019-08-09 17:15
> I believe we assigned this to Kurtis since the issue is actually a problem with how Unity makes the Windows API calls for InputPane.TryShow.

Per the above, moving this to "consider for next iteration"

**Closed** 2020-03-25 21:08 UTC
Labels: 0 - Backlog, Bug, Consider for Next Iteration, Hack Week, Urgency-Soon
