### ISSUE TITLE
Cannot Ray Cast a Hand Ray to the floor when head orientation is at a steep angle

### ISSUE THREAD

**Issue by ARGs-code** [microsoft/MixedRealityToolkit-Unity#10516] opened 2022-03-25 18:55 UTC
## Overview
It is not possible for me to use a far interaction on an element that is on the floor near my feet.

## Expected behavior
I should be able to use far hand interactions on objects, regardless of their location relative too my head position

## Actual behavior
I can raycast to objects in front of me, above me and some objects that are below me, but after a certain angle of downward gaze the far interaction raycasts completely shut off and no longer function.

## Steps to reproduce
See the linked video and try it out yourself. This even occurs in the shell environment so it might not be just an MRTK Issue.
[https://i.gyazo.com/d0a2c14a4d00179e994c64282bd12b3e.mp4](url)

## Unity editor version
2020.3.30f1

## Mixed Reality Toolkit release version
2.7.3

**Comment by Strepto** [comment] 2022-03-27 09:09
+1 👍 

I think this is decided in the HoloLens OS today, but if this could be disabled or enabled on a per app basis it would be nice. There are a number of use-cases where interacting with stuff below you is valuable, such as XRay vision beneath the floor, or making a game where you control elements your floor.

**Comment by ARGs-code** [comment] 2022-03-29 14:25
Hi folks, if this is in fact decided by the HoloLens OS, where would I open a ticket/bug report about this issue? This issue makes several requirements we have from clients impossible until it is changed and I need to get some idea of whether we can move forward or if I have to simply explain that it's not possible to use far interactions with objects on the floor (to which I have already been asked why this is the case).

**Comment by elbuhofantasma** [comment] 2022-03-29 22:58
Hello @ARGs-code and thank you for hand tracking submission. I also see some weirdness when looking at a steep angle towards the ground in MRTK 2.7.3, however in the main branch when trying to repro this, one is able to point just a little bit closer to their feet but the same weirdness presents itself. I am not sure what the cause of this weirdness is, but it will get better inside of MRTK in the next release.

As for where to file OS level bugs, please use the [Submit Feedback feature](https://docs.microsoft.com/en-us/hololens/hololens-feedback) as described in the linked article.

Since this appears to be external to MRTK, I am going to close this issue. Please re-open this issue or file a new issue if you need any further assistance.

**Closed by elbuhofantasma** 2022-03-29 22:58 UTC
Labels: OS Bug, HoloLens 2, External

**Comment by ARGs-code** [comment] 2022-04-01 18:56
All right... pretty frustrating that this appears to be at a system level. The far interaction pointers in the Hololens are basically our mouse. This is like having a whole section of our display unable to be interacted with the mouse, despite having content and other items placed there. The feedback submissions to windows rarely seem to go anywhere but I will give it a shot and for now will have to tell our clients that what they want is not doable.

**Comment by keveleigh** [comment] 2022-04-27 17:51
Hey @ARGs-code, are you using OpenXR or Windows XR Plugin?

**Comment by ARGs-code** [comment] 2022-05-02 12:35
@keveleigh We are using OpenXR when doing our MRTK Development.

I'm not sure what plugin we are using is important though. As I mentioned, this issue even appears in the Windows Holographic for Business shell environment, when no applications are running.
