### ISSUE TITLE
One hand grab manip handler in VR, HL1 causes object to visibly move

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6108] opened 2019-09-26 23:11 UTC
## Overview
Objects should not jump significant distances when grabbed by VR motion controllers, but they do.

This is a regression from 2.0.

## Steps to reproduce
Load up HandInteractionExamples in VR, and grab any object with one motion controller. Notice that the object visibly jumps in Z / depth.

## Expected Behavior
Object should have minimal movement when being grabbed if hand does not move.

## Actual Behavior
Object jumps significantly.

## Mixed Reality Toolkit Release Version
prerelease/2.1.0_stabilization

**Comment by julenka** [comment] 2019-10-02 00:14
Also reproduces on HL1, when I grab the lunar module or the earth, especially when I grab an object that's below me (looking down), the object visibly moves.

**Comment by MenelvagorMilsom** [comment] 2019-10-02 14:02
@julenka, @thalbern Some findings from this morning:
- The problem appears to only be in editor. When you build and run for HMD through VS, you no longer see this jumping (see .gifs below)
  This bug is still annoying, but I'm not sure it's as severe as initially thought. If we don't find the cause of the issue in the next few days, we should possibly reconsider it as a Release Blocker
- As you can see from the in editor .gif, the cup isn't the only thing jumping, the profiling panel is also jumping. When I debugged, I confirmed that the head position appears to be jumping upwards when the controller trigger was pressed. This occurs independent of whether you're pointing at an object or not. It doesn't appear to happen for any other buttons/controls.
- I'm going to have a look at HL1 now and confirm that it is also only an editor problem.

### In editor:
![HMD_inEditor](https://user-images.githubusercontent.com/47415945/66048973-740a6d80-e522-11e9-9ac6-bf58a08c40c3.gif)

### Built for x64 running on local machine:
  ![HMD_built](https://user-images.githubusercontent.com/47415945/66049093-a9af5680-e522-11e9-8b34-7050f3ad3ac4.gif)

**Comment by MenelvagorMilsom** [comment] 2019-10-02 14:27
> * I'm going to have a look at HL1 now and confirm that it is also only an editor problem.

Just checked in editor and on device for HL1 and I couldn't reproduce this issue.

**Comment by keveleigh** [comment] 2019-10-02 15:28
Head moving up/down in the editor looks like a result of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5853

**Comment by MenelvagorMilsom** [comment] 2019-10-03 13:15
Tried again on HL1 with latest `prerelease/2.1.0_stabilization` but I still can't reproduce any significant or repeatable jumping. There's a little bit of jumping here and there, but no more than in the HL1 shell. Here's a .gif:
![HL1_noJump](https://user-images.githubusercontent.com/47415945/66129644-3c65f900-e5e8-11e9-9c20-c049fb3e1f67.gif)

**Comment by MenelvagorMilsom** [comment] 2019-10-03 15:24
> Head moving up/down in the editor looks like a result of #5853
> 
> > New input axis "UpDown" to control camera movement along the Up vector. Defaults to Q/E keys and the 3rd game controller axis (triggers)

@lukastoenneMS FYI

**Comment by MenelvagorMilsom** [comment] 2019-10-04 10:02
Fixed in #6193

**Closed by MenelvagorMilsom** 2019-10-04 10:02 UTC
Labels: Bug, Current Iteration, Editor, Input Simulation, Release Blocker
