### ISSUE TITLE
Something wrong :trying to map your surrounding

### ISSUE THREAD

**Issue by loveXMTX** [Microsoft/MixedRealityToolkit-Unity#2551] opened 2018-08-06 02:47 UTC
## Overview
Add A city model in Hololens , error： the APP will be stuck in Trying to map your surrounding.

## Actual Behavior
**2018.11.15Update**
I rebuilt this scene and exported it to Hololens Emulator,I found this error log
```
If your machine has multiple graphics adapters, Unity may have created a WindowContext on the wrong adapter. If you experience a black screen when playing, please restart the Editor.
 
(Filename: C:\buildslave\unity\build\Runtime/VR/VRDevice.cpp Line: 218)


The referenced script on this Behaviour is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Mono/MonoBehaviour.cpp Line: 1510)


The referenced script on this Behaviour (Game Object 'International City_0') is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Mono/MonoBehaviour.cpp Line: 1753)


Setting up 1 worker threads for Enlighten.

  Thread -> id: 550 -> priority: 1 

UnloadTime: 6.645600 ms

Holographic Tracking State Lost. New State: 1
 
(Filename: C:\buildslave\unity\build\Runtime/VR/HoloLens/HoloLensWorldManager.cpp Line: 166)


Failed to get spatial stage statics - can't retrieve or interact with boundaries! Error code: '0x80040154'.
```
And the display in Hololens Emulator is 
![hololenerror](https://user-images.githubusercontent.com/33478880/48537198-c2535580-e8eb-11e8-9e58-9908c160caf6.png)

-------------------------------------------------------
** I build a app on Hololens.I hadn't added spatial mapping,but there is error in my app.When I open app, it will always be stuck in this ** 
![tim 20180806094958](https://user-images.githubusercontent.com/33478880/43693994-ac227372-9963-11e8-80bc-387a24dced1d.png)

And I tested that everything was removed but a city model which was exported by CityEngine with a format of .FBX in the same Unity project,sure there were still same MRTK configure scene components，this error still existed. Finally, I just used a cube and removed the city model to test. In the same project ,same configure setting , this error didn't exist.

The city model is about 27 mb ,  the Unity interface is as bellow:
 

![tim 20180806095950](https://user-images.githubusercontent.com/33478880/43694238-f89bf0ba-9964-11e8-8312-fb766e5ab5a1.png)

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.4

**Comment by StephenHodgson** [comment] 2018-08-06 13:16
Have you tried launching other apps to see if the problem is hardware specific?

**Comment by StephenHodgson** [comment] 2018-08-06 13:17
Also, try removing the tooklit completely and just putting an empty scene with the fbx model.

**Comment by davidkline-ms** [comment] 2018-08-07 02:39
This is not a message that the toolkit displays, it is coming from the HoloLens operating system.

**Comment by loveXMTX** [comment] 2018-08-07 04:41
- Yeah, I tried, other app in Hololens is okay. Meanwhile, I reinstall Hololens emulator , this error still exist, so I am sure the hardware is ok.
- And I just tested only the city model in the scene ,and build an .exe ,there is still no problem.

What's up?Should I change a version of MRTK or Unity?

**Comment by Yoyozilla** [comment] 2019-04-11 21:54
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo

**Closed by Yoyozilla** 2019-04-11 21:54 UTC
Labels: HoloLens, Investigate, Legacy (HoloToolkit)
