### ISSUE TITLE
Solver Handler not switching hands when tracking both left and right Interactors

### ISSUE THREAD

**Issue by srinjoym** [microsoft/MixedRealityToolkit-Unity#11434] opened 2023-03-24 20:55 UTC
Bug found during investigation of validating surface magnetism solver.

**Comment by srinjoym** [comment] 2023-03-24 20:58
Validated on MRTK 3 - the core solver seems to be working as expected. The only issue was in the Solver Handler script - if it is set to track both hands through two interactors, then it will always prefer the left hand even if it's not currently tracked. This probably needs to be fixed as I would expect the solver to start tracking the right hand if the left goes out of view

Here's a video of the current state:

https://user-images.githubusercontent.com/7866060/227638284-24280b33-8d0f-4857-8e12-7f291794756e.mp4

**Comment by AMollis** [comment] 2023-03-27 16:32
@srinjoym , this seems like a duplicate of this #11398 can you please confirm?

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11398

**Comment by AMollis** [comment] 2023-05-04 18:29
@holomatt was still able to reproduce this issue with XRI 2.3.1.   I assume this still repros with XRI 2.3.0

Reopening bug.

**Closed** 2023-05-04 18:31 UTC
Labels: Bug, MRTK3
