### ISSUE TITLE
Scroll is not working while using Hand Gestures

### ISSUE THREAD

**Issue by ragavendranbala** [microsoft/MixedRealityToolkit-Unity#11093] opened 2022-10-10 12:06 UTC
## Describe the bug

Scroll is not working while using Hand Gestures VirtualizedScrollRectList Scene on Dev Template

## To reproduce

1. Open VirtualizedScrollRectList Scene from MRTK- Dev template
2. Stop the scrolling of rect by pressing any one of the button
3. Use Left shift key to enable left hand and try to scroll the scrollable UI by clicking the left mouse button
4. The scrolling won't work and work while scrolling using mouse

## Expected behavior

The Scroll used work on hand gestures as similar to mouse gestures

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.33f1]
- MRTK Version [e.g. v3.0]

## Target platform (please complete the following information)
- HoloLens 2

## Additional context

Tried adding uGUI draggable script on viewport gameobject, same result.

**Comment by Zee2** [comment] 2022-10-10 18:01
Closing as duplicate of #10736

**Closed by Zee2** 2022-10-10 18:01 UTC
Labels: Bug
