### ISSUE TITLE
Solver - broken unexpected behavior on device when built with ARM64

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#8219] opened 2020-07-28 14:59 UTC
## Describe the bug
Objects using any Solver (RaidialView, HandConstraint, etc) shows unexpected behavior on the device (object squashed, flying, disappeared, etc) when built with ARM64.

- Works fine when built with ARM.
- Works fine in the Unity editor.

**Comment by Kent1LG** [comment] 2020-07-28 15:18
Hi @cre8ivepark,

This seems to be the big compiler issue of the moment.
I gave a feedback about it : #8185 where @wiwei told me to disable smoothing on the HandConstraint.

I hope is gonna solve your situation until a compiler fix.

**Comment by wiwei** [comment] 2020-07-28 22:21
Closing as a duplicate of this:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7624#issuecomment-665309866

I thought that we could do a workaround but I actually couldn't find one that would work in all cases (aside from just turning off smoothing for solvers). So for now that's our best option.

**Closed by wiwei** 2020-07-28 22:21 UTC
Labels: Bug
