### ISSUE TITLE
Bug when installing MRTK and MRTK examples

### ISSUE THREAD

**Issue by crhodes2** [Microsoft/MixedRealityToolkit-Unity#4040] opened 2019-04-20 01:11 UTC
So I've installed the latest version: HoloToolkit 2017.4.3.0 - Refresh, and its example on my project and it introduced me to new issues.

This is what's happening now...

Either I install it by drag-and-drop into the Assets folder of my project, or I just double-click on the MRTK files themselves, it is the exact same scenario.

This is the latest error I'm getting...

Assets\HoloToolkit-Examples\SpectatorView\Scripts\SpectatorViewNetworkManager.cs(4,25): error CS0234: The type or namespace name 'Preview' does not exist in the namespace 'HoloToolkit.Unity' (are you missing an assembly reference?)

Assets\HoloToolkit-Examples\SpectatorView\Scripts\SpectatorViewNetworkManager.cs(19,13): error CS0246: The type or namespace name 'SpectatorView' could not be found (are you missing a using directive or an assembly reference?)

I don't know when am I ever going to complete this project? I have been doing this for the past 3-4 weeks to NO avail!
Every time I attempt to install MRTK and MRTK-Examples on my project--even new projects--
Errors. Nothing but errors. This is FRUSTRATING with all letters in capital!

**Comment by julenka** [comment] 2019-04-21 22:59
Hi, thanks for asking a question. For troubleshooting questions like this it would be great to ask the question on stackoverflow with the tag "MRTK", since then other people can benefit from searching for your questions (many people don't know to search the issues on github). Please include your exact environment and repro steps so that we can reproduce your issue.

Reading the other conversation, it sounds like this might be more of a configuration issue rather than a bug, so hopefully the stackoverflow community can help. Closing this for now, but If this ends up being a bug with Holotoolkit or MRTK that others can reproduce we can re-open the issue.

**Closed by julenka** 2019-04-21 22:59 UTC
Labels: Bug, Legacy (HoloToolkit)

**Comment by davidkline-ms** [comment] 2019-04-22 16:55
> Assets\HoloToolkit-Examples\SpectatorView\Scripts\SpectatorViewNetworkManager.cs(4,25): error CS0234: The type or namespace name 'Preview' does not exist in the namespace 'HoloToolkit.Unity' (are you missing an assembly reference?)
Assets\HoloToolkit-Examples\SpectatorView\Scripts\SpectatorViewNetworkManager.cs(19,13): error CS0246: The type or namespace name 'SpectatorView' could not be found (are you missing a using directive or an assembly reference?)

These errors indicate that the spectator view example requires HoloToolkit-Unity-Preview-2017.4.3.0-Refresh.unitypackage (https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/download/2017.4.3.0-Refresh/HoloToolkit-Unity-Preview-2017.4.3.0-Refresh.unitypackage)
