### ISSUE TITLE
Input on Unity UI not working with 2017.2 and MRTK 2017.2 DEV branch

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#1173] opened 2017-10-16 18:59 UTC
Hi,

I just updated my Unity to 2017.2 and checked out the latest DEV branch commit for 2017.2. Exported the unity package and imported it into my project that was running fine previously. 

Now with Unity 2017.2 and the latest MRTK any input on Unity UI elements is not working anymore. Also gazing at a button e.g. will not trigger on pointer enter or exit. This worked fine previously.

It seems like Unity UI does not get any input events anymore.

Has anyone experienced the same?

**Comment by FejZa** [comment] 2017-10-16 19:00
I tried it with a new project too. Setup:

- New project with Unity 2017.2
- Import MRTK 2017.2 DEV package
- Add HoloLensCamera prefab
- Add InputManager prefab
- Create simple UI with a button
- Make sure EventSystem is created

UI not responsind to any input.

**Comment by genereddick** [comment] 2017-10-16 19:17
I'm having the same issue. I've tried with both the 2017.2.0f3 and 2017.2.0f3.MRTP versions. 

I get various errors:
The InputManager singleton has not been initialized. 
InputManager singled instance is being accessed while it is null.
Errors on SetGlobalListener

**Comment by StephenHodgson** [comment] 2017-10-16 19:39
I'll be sure to check this out asap

**Comment by StephenHodgson** [comment] 2017-10-16 19:40
Be sure to use the `MixedRealityCamera.prefab` instead of the `HoloLensCamera.prefab`.

**Comment by StephenHodgson** [comment] 2017-10-16 19:56
Guys check out #1162 and see if this PR fixes some of the issues you're seeing.

@genereddick I think that is separate issue involving the way we updated Singletons and has been fixed, but not merged back into the Dev branch yet.

**Comment by StephenHodgson** [comment] 2017-10-16 19:58
@FejZa I'm unable to reproduce this in the `InputManagerTest` scene.  

Are you using a HoloLens or the VR Headsets?

**Comment by StephenHodgson** [comment] 2017-10-16 23:26
I was playing around in the InputManagerTest scene. The only two things I found to be broken was the pop up modal and the hand dragging.

I was able to get OnInputClicked, OnInputDown, OnInputUp, OnFocusEnter, and OnFocusExit.

**Comment by StephenHodgson** [comment] 2017-10-17 00:40
One thing I also ran into was the input might not work if you're targeting the wrong SDK for each version of the editor.

**Comment by StephenHodgson** [comment] 2017-10-17 00:59
Okay, so I _was_ able to duplicate this issue, but only when Building for the HoloLens with Unity 2017.2.0f3 MRTP and the 16.0.16299.0 SDK.

HoloLens Builds only work in the Vanilla Releases of the Editor.

**Comment by FejZa** [comment] 2017-10-17 06:23
I was able to solve my problems by fetching changes made in #1162. Thanks for the support!

**Comment by StephenHodgson** [comment] 2017-10-17 06:31
You can probably use the latest release and be good.

**Closed by StephenHodgson** 2017-10-17 06:31 UTC
