### ISSUE TITLE
Disabling Interactable on PressableButton prefab doesn't disable near interactions.

### ISSUE THREAD

**Issue by asugaya-apx** [microsoft/MixedRealityToolkit-Unity#5833] opened 2019-08-30 16:15 UTC
## Describe the bug

Setting the Enabled field of the Interactable script to false doesn't disable the Interactable.

## To reproduce

1. Load an example scene with pressable buttons (eg, "PressableButtonExample").
2. Choose a button, and uncheck "Enabled" in the Interactable script in the inspector.
3. Run the scene.
4. Far interactions are disabled, but near interactions (ie, presses) will still function.

## Expected behavior

Near interactions should be disabled if the Interaction script has the "Enabled" field set to false.

## Screenshots
![PressableButtonDisable](https://user-images.githubusercontent.com/7772477/64035585-04a9f400-cb06-11e9-9fd1-cc073966506f.gif)

## Your Setup (please complete the following information)

- Unity Version: 2019.1.8f1
- MRTK Version: mrtk_release

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment] 2019-09-04 00:10
@julenka FYI

I feel like with buttons (which are being highlighted in this issue) there are a number of other things that go into how it works, where simply removing a single script, I wouldn't expect that it would turn off the combination of the N other scripts that make it work.

I think that there's a more general question here though that this could go:

1. Is the desire here to have this work with the most basic interactable (i.e. just a basic object with the interactable attached to it?).
1. Or is the desire specifically with pressable buttons - i.e. is there the desire to have a 'disabled' state for buttons that is stylistically and functionally disabled?

I think the way the issue can go can vary depending on if the ask is the former or the latter.

**Comment by wiwei** [comment] 2019-09-04 00:10
As for the combination of N other scripts, I don't think that's a good thing - as called out in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5463 I think that buttons as a whole could really be designed as an "API" more than just a "prefab with a bunch of scripts"

**Comment by julenka** [comment] 2019-09-04 16:38
@wiwei I think this is a legitimate bug. Maybe though to focus the bug we can rephrase it like this:

Title: HoloLens2Prefab button raises OnClick() events on touch even when disabled

The issue is probably actually with Physical Press Event Router, which I think invokes on click when the button is pressed. You can see that at distance the button is correctly disabled. But when near, the component that invokes the Interactable OnClick is actually PhysicalPressEventRouter.

@wiwei I think it's reasonable to expect that if Interactable.Enabled == false, then Interactable.OnClick should not get raised by MRTK scripts.

**Comment by julenka** [comment] 2019-09-04 16:38
Moving to current since this is an existing functional defect.

**Comment by julenka** [comment] 2019-09-04 16:39
It should be an easy fix -- just need to modify physicalpresseventrouter to not raise onclick when interactable is disabled. Longer term fix will be to get rid of physicalpresseventrouter

**Comment by julenka** [comment] 2019-09-24 18:00
I've verified the following fix works, but it needs tests:

```
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using Microsoft.MixedReality.Toolkit.UI;
using UnityEngine;

namespace Microsoft.MixedReality.Toolkit
{
    ///<summary>
    /// This class exists to route <see cref="Microsoft.MixedReality.Toolkit.UI.PressableButton"/> events through to <see cref="Microsoft.MixedReality.Toolkit.UI.Interactable"/>.
    /// The result is being able to have physical touch call Interactable.OnPointerClicked.
    ///</summary>
    public class PhysicalPressEventRouter : MonoBehaviour
    {
        [Tooltip("Interactable to which the press events are being routed. Defaults to the object of the component.")]
        public Interactable routingTarget;

        /// Enum specifying which button event causes a Click to be raised.
        public enum PhysicalPressEventBehavior
        {
            EventOnClickCompletion = 0,
            EventOnPress,
            EventOnTouch
        }
        public PhysicalPressEventBehavior InteractableOnClick = PhysicalPressEventBehavior.EventOnClickCompletion;

        private void Awake()
        {
            if (routingTarget == null)
            {
                routingTarget = GetComponent<Interactable>();
            }
        }

        private bool CanRouteInput()
        {
            return routingTarget != null  && routingTarget.Enabled;
        }

        public void OnHandPressTouched()
        {
            if (CanRouteInput())
            {
                routingTarget.SetPhysicalTouch(true);
                if (InteractableOnClick == PhysicalPressEventBehavior.EventOnTouch)
                {
                    routingTarget.SetPress(true);
                    routingTarget.TriggerOnClick();
                    routingTarget.SetPress(false);
                }
            }
        }

        public void OnHandPressUntouched()
        {
            if (CanRouteInput())
            {
                routingTarget.SetPhysicalTouch(false);
                if (InteractableOnClick == PhysicalPressEventBehavior.EventOnTouch)
                {
                    routingTarget.SetPress(true);
                }
            }
        }

        public void OnHandPressTriggered()
        {
            if (CanRouteInput())
            {
                routingTarget.SetPhysicalTouch(true);
                routingTarget.SetPress(true);
                if (InteractableOnClick == PhysicalPressEventBehavior.EventOnPress)
                {
                    routingTarget.TriggerOnClick();
                }
            }
        }

        public void OnHandPressCompleted()
        {
            if (CanRouteInput())
            {
                routingTarget.SetPhysicalTouch(true);
                routingTarget.SetPress(true);
                if (InteractableOnClick == PhysicalPressEventBehavior.EventOnClickCompletion)
                {
                    routingTarget.TriggerOnClick();
                }
                routingTarget.SetPress(false);
                routingTarget.SetPhysicalTouch(false);
            }
        }
    }
}
```

**Closed** 2019-09-30 17:59 UTC
Labels: 0 - Backlog, Bug, Current Iteration, DDE Partner, Release Blocker, UX Controls, UX Controls - Buttons, UX Controls - Interactable
