### ISSUE TITLE
Shader error when building Android for URP

### ISSUE THREAD

**Issue by thePostFuturist** [microsoft/MixedRealityToolkit-Unity#10449] opened 2022-02-04 18:19 UTC
Upon using URP, the MRTK Standard shader will prevent the app from compiling. This error is thrown:

Shader error in 'Mixed Reality Toolkit/Standard': Non system-generated input signature parameter () cannot appear after a system generated value. at line 775 (on vulkan)

When using the update tools, the app will compile, but the error is still there. This will prevent you choosing the shader from the material dropdown. However, after app restart, the shader error will prevent the app from compiling again.

- Unity Version [v2020.3.26f1]
- MRTK Version [v2.7.3.0]

- OpenXR
- Oculus Utilities

**Comment by elbuhofantasma** [comment] 2022-02-04 18:45
Thank you for submitting this shader error @thePostFuturist! I will investigate this issue and report back shortly.

**Comment by thePostFuturist** [comment] 2022-02-08 01:50
Update: I have removed Vulkan and am building solely using OpenGLES3. 

A similar error,
`
Non system-generated input signature parameter () cannot appear after a system generated value. GLES3X`

is thrown, although now builds are no longer failing. Can also now select the shader from the material dropdown.

**Comment by derekdominoes** [comment] 2022-04-12 22:59
yep... stuck on this issue too!

**Comment by ezar** [comment] 2022-04-23 17:06
Same here!

**Comment by keveleigh** [comment] 2022-04-25 19:21
> Non system-generated input signature parameter () cannot appear after a system generated value. at line 775 (on vulkan)

Just to clarify, does this prevent a successful build? This sounds like #5844, #10532, similar to #6359. In my investigations of those, the error only seemed to log on first build but didn't actually prevent the build from succeeding. Are you able to confirm that your logs say the build failed?

**Comment by LukassaOne** [comment] 2022-04-27 14:44
Log says building player has failed has failed.

Shader error in 'Mixed Reality Toolkit/Standard': Non system-generated input signature parameter () cannot appear after a system generated value. at line 775 (on gles3)

Compiling Subshader: 0, Pass: Main, Vertex program with INSTANCING_ON STEREO_MULTIVIEW_ON
Platform defines: SHADER_API_GLES30 SHADER_API_MOBILE UNITY_ASTC_NORMALMAP_ENCODING UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_LIGHTMAP_RGBM_ENCODING UNITY_NO_CUBEMAP_ARRAY UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_RGBM UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3
Disabled keywords: LIGHTMAP_ON UNITY_COLORSPACE_GAMMA UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF2 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_UI_CLIP_RECT UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_VIRTUAL_TEXTURING _ALPHABLEND_ON _ALPHATEST_ON _BORDER_LIGHT _BORDER_LIGHT_OPAQUE _BORDER_LIGHT_REPLACES_ALBEDO _BORDER_LIGHT_USES_HOVER_COLOR _CHANNEL_MAP _CLIPPING_BORDER _CLIPPING_BOX _CLIPPING_PLANE _CLIPPING_SPHERE _DIRECTIONAL_LIGHT _DISABLE_ALBEDO_MAP _EMISSION _ENVIRONMENT_COLORING _HOVER_COLOR_OVERRIDE _HOVER_LIGHT _HOVER_LIGHT_HIGH _HOVER_LIGHT_MEDIUM _IGNORE_Z_SCALE _INDEPENDENT_CORNERS _INNER_GLOW _IRIDESCENCE _LOCAL_SPACE_TRIPLANAR_MAPPING _METALLIC_TEXTURE_ALBEDO_CHANNEL_A _NEAR_LIGHT_FADE _NEAR_PLANE_FADE _NORMAL_MAP _PROXIMITY_LIGHT _PROXIMITY_LIGHT_COLOR_OVERRIDE _PROXIMITY_LIGHT_SUBTRACTIVE _PROXIMITY_LIGHT_TWO_SIDED _REFLECTIONS _REFRACTION _RIM_LIGHT _ROUND_CORNERS _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULAR_HIGHLIGHTS _SPHERICAL_HARMONICS _TRIPLANAR_MAPPING _USE_SSAA _VERTEX_COLORS _VERTEX_EXTRUSION _VERTEX_EXTRUSION_SMOOTH_NORMALS

Unity 2021.2.17

**Comment by LukassaOne** [comment] 2022-04-27 15:08
Just found out: if i hit build -> the build will success
but if i hit build and run -> the build will fail

**Comment by LukassaOne** [comment] 2022-04-27 15:34
But the resulting api wont launch so the problem remains

**Comment by csritter** [comment] 2022-06-13 20:12
Any news about this bug?

**Comment by Cameron-Micka** [comment] 2022-06-16 23:01
Hello, just an FYI since this might not be an ideal solution for many. I believe this issue is fixed in the latest version of the MRTK Standard shader found in the[ Graphics Tools](https://github.com/microsoft/MixedReality-GraphicsTools-Unity) package. 

Graphics Tools is our new graphics focused package that comes automatically with MRTKv3 or can be used independently (or side by side with MRTKv2).

I’ve been building to Android (Quest 2) almost daily and haven’t encountered this error. But if anyone encounters it when using Graphics Tools please report the issue [here](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues).

**Closed** 2022-07-06 22:49 UTC
Labels: Bug

**Comment by ahmed-shariff** [comment] 2022-10-06 07:18
@Cameron-Micka, I might be missing something here. Installing the Graphics Tools with the git URL doesn't seem to have an effect. Should I be doing anything else?

**Comment by Cameron-Micka** [comment] 2022-10-06 18:07
Hey @ahmed-shariff! Could you provide some extra details on what you are seeing? Are you seeing the above error from the 'Graphics Tools/Standard' shader or just the 'Mixed Reality Toolkit/Standard' shader?

The 'Mixed Reality Toolkit/Standard' shader should still emit errors with Graphics Tools installed if any materials being built still reference the 'Mixed Reality Toolkit/Standard' shader. 

You will want to replace the shader of any materials using the 'Mixed Reality Toolkit/Standard' shader with the 'Graphics Tools/Standard' shader. This should be easy-ish with materials you have created (but might prove harder if you have readonly materials within any packages).

**Comment by ahmed-shariff** [comment] 2022-10-06 23:26
Ah I see, I think I misunderstood. Appreciate the clarification. I had assumed it replaces the default materials from the packages. The errors I get are from the 'Mixed Reality Toolkit/Standard` shaders:
```
Shader error in 'Mixed Reality Toolkit/Standard': Non system-generated input signature parameter () cannot appear after a system generated value. at line 775 (on gles3)

Compiling Subshader: 0, Pass: Pass 0, Vertex program with INSTANCING_ON STEREO_MULTIVIEW_ON
Platform defines: SHADER_API_GLES30 SHADER_API_MOBILE UNITY_ASTC_NORMALMAP_ENCODING UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HARDWARE_TIER1 UNITY_LIGHTMAP_RGBM_ENCODING UNITY_NO_CUBEMAP_ARRAY UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_RGBM UNITY_NO_SCREENSPACE_SHADOWS UNITY_PASS_FORWARDBASE UNITY_PBS_USE_BRDF3
Disabled keywords: LIGHTMAP_ON UNITY_COLORSPACE_GAMMA UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF2 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_UI_CLIP_RECT UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_VIRTUAL_TEXTURING _ALPHABLEND_ON _ALPHATEST_ON _BORDER_LIGHT _BORDER_LIGHT_OPAQUE _BORDER_LIGHT_REPLACES_ALBEDO _BORDER_LIGHT_USES_HOVER_COLOR _CHANNEL_MAP _CLIPPING_BORDER _CLIPPING_BOX _CLIPPING_PLANE _CLIPPING_SPHERE _DIRECTIONAL_LIGHT _DISABLE_ALBEDO_MAP _EMISSION _ENVIRONMENT_COLORING _HOVER_COLOR_OVERRIDE _HOVER_LIGHT _HOVER_LIGHT_HIGH _HOVER_LIGHT_MEDIUM _IGNORE_Z_SCALE _INDEPENDENT_CORNERS _INNER_GLOW _IRIDESCENCE _LOCAL_SPACE_TRIPLANAR_MAPPING _METALLIC_TEXTURE_ALBEDO_CHANNEL_A _NEAR_LIGHT_FADE _NEAR_PLANE_FADE _NORMAL_MAP _PROXIMITY_LIGHT _PROXIMITY_LIGHT_COLOR_OVERRIDE _PROXIMITY_LIGHT_SUBTRACTIVE _PROXIMITY_LIGHT_TWO_SIDED _REFLECTIONS _REFRACTION _RIM_LIGHT _ROUND_CORNERS _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULAR_HIGHLIGHTS _SPHERICAL_HARMONICS _TRIPLANAR_MAPPING _USE_SSAA _VERTEX_COLORS _VERTEX_EXTRUSION _VERTEX_EXTRUSION_SMOOTH_NORMALS
```

If the issue reported is not directly fixed by the Graphics Tools package, wouldn't it be better to have the issue still remain open until it's address directly?

**Comment by ahmed-shariff** [comment] 2022-10-06 23:27
For now I am using @LukassaOne 's solution.

**Comment by ahmed-shariff** [comment] 2022-10-06 23:29
This seems to have been introduced in #4947

**Comment by Cameron-Micka** [comment] 2022-10-06 23:33
> For now I am using @LukassaOne 's solution.

Glad that unblocked by removing the VFACE semantic. Note, if you are lighting any back facing triangles your lighting will look incorrect (but that is not a common use case).

**Comment by Cameron-Micka** [comment] 2022-10-06 23:36
> If the issue reported is not directly fixed by the Graphics Tools package, wouldn't it be better to have the issue still remain open until it's address directly?

That's a valid concern. @keveleigh should we leave this issue open or closed if it is fixed in MRTKv3? The root issue is within Unity (last I spoke with them a PR with a fix was coming). Without that fix we would be doing some guess and check to see how we work around the root issue.

**Comment by sjando** [comment] 2022-10-11 00:24
Whether a build succeeds or not depends on whether the [BuildOptions.StrictMode](https://docs.unity3d.com/ScriptReference/BuildOptions.StrictMode.html) flag is enabled when building. Without strict mode enabled, the shader error is logged but the build succeeds. With strict mode enabled however, the shader error fails the build. By default, the Unity build window will enable strict mode when using the "Build and Run" button but will NOT enable it when using the "Build" button (don't ask me why, but you can see this in action [in the UnityCsReference source](https://github.com/Unity-Technologies/UnityCsReference/blob/bd9b94527df6a9c6a4536c7671d4a7a3c04ba245/Editor/Mono/BuildPlayerWindow.cs#L133)). Hence the different behaviour of the two buttons with regard to this shader error.

Separately, there is the question of when the shader error is thrown. In 2020.3.X, it is thrown once when the shader is first compiled for Android and never again (unless the shader is reimported). So, this issue isn't too painful; your first Android build, if it happens to be via "Build and Run" (or otherwise enables strict mode), will fail but after that you're good. However, in 2021.3.X, this behaviour seems to have changed. Even when the shader is not recompiled, the error is somehow cached and will be rethrown on every build attempt. The net result of this is "Build and Run" (or any other use of strict mode) is broken out of the box on Android + Mixed Reality Toolkit/Standard + 2021 LTS. Annoying as it is, this new behaviour seems more correct to me, errors should not just be forgotten, so I have to imagine this is intentional on Unity's part.

The consequences of the 2021 changes are even further reaching if you're switching platforms. If you build for Android (strict or otherwise), invoking the shader compilation and triggering the error, and then switch platform to something else, strict mode builds will STILL be failed by the cached error even though it only applies to GLES3/Android. So, if you're working on a UWP project, build once for Android as an experiment/for fun, and then switch back to UWP you might still find yourself stuck. This part definitely seems like a Unity bug. Workaround is to reimport the shader after platform switch.

If you don't want to modify the shader in your project, you can use [RegisterGetBuildPlayerOptionsHandler](https://docs.unity3d.com/Documentation/ScriptReference/BuildPlayerWindow.RegisterGetBuildPlayerOptionsHandler.html) to set up a handler that will strip out the strict mode flag and restore functionality to the "Build and Run" button. But this is a bit of a hack and I'd sooner enable strict mode by default for all builds than start disabling it in places. Especially if you're doing CI builds you probably want strict mode enabled to fail the build rather than find out later that materials are missing (even if this particular error isn't very impactful, others that you are now allowing through might be), which is where this becomes a real issue for my team under 2021.

**Comment by ahmed-shariff** [comment] 2022-10-11 07:23
@sjando Appreciate the breakdown 👍👍👍

**Comment by Cameron-Micka** [comment] 2022-10-12 19:57
Let me reach out to Unity again about this. It was fixed in [2020.2](https://issuetracker.unity3d.com/issues/oculus-a-non-system-generated-input-signature-parameter-blendindices-cannot-appear-after-a-system-generated-value), but maybe it regressed.

**Comment by BarboraAtVResearch** [comment] 2022-10-28 16:15
Is there any way to just exclude MRTK Standard shader from build if it's unused?

**Comment by Cameron-Micka** [comment] 2022-10-28 16:55
Hey @BarboraAtVResearch, Unity should exclude the shader from your build if it is not referenced by any scenes in your build settings, any assets in your StreamingAssets folder(s), and not in the project's always include shader list. That being said the shader is used all over MRTK, so it might be hard not to reference. 

I've not heard back from Unity yet with a workaround or potential engine update to fix this. But if people are blocked by this and want to do a local change, I recommend removing the use of the facing variable:

Change this [line](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d44e5c1d76965d3ccce956aaf1d352b5c299c5a2/Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader#L775) from this:

`fixed4 frag(v2f i, fixed facing : VFACE) : SV_Target`

to this:

`fixed4 frag(v2f i) : SV_Target`

And change this [line](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d44e5c1d76965d3ccce956aaf1d352b5c299c5a2/Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader#L956) from this:

`worldNormal = normalize(worldNormal) * facing;`

to this:

`worldNormal = normalize(worldNormal);`

Finally, change this [line](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d44e5c1d76965d3ccce956aaf1d352b5c299c5a2/Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader#L959) from this:

`worldNormal = normalize(i.worldNormal) * facing;`

to this:

`worldNormal = normalize(i.worldNormal) ;`

**Note** this will make two-sided lighting look incorrect. But not many scenarios utilize two-sided lighting.

I'll post back here when I hear back from Unity. I should also mention this issue does not reproduce in MRTK3. So hopefully this issue is behind us in the future. That being said, I'd still like to fix it for MRTK2.x. 😊

**Comment by k3rn3l-paN1c** [comment] 2022-12-17 02:02
This is still an issue ....

**Comment by Cameron-Micka** [comment] 2023-01-03 20:03
> This is still an issue ....

Unfortunately, after some testing I believe this issue lies in Unity's shader compiler (before it is passed to FXC). 

If you are starting a new project, or open to upgrading, I'd recommend using [MRTK3 ](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/)which does not trigger this issue.

Or, if your project doesn't require back face lighting you can make this local modification: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10449#issuecomment-1295233907

**Comment by ri5c** [comment] 2023-01-09 04:32
MRTK3 passthrough does not work.  So this answer does nothing...

**Comment by ri5c** [comment] 2023-01-10 20:06
So MRTK2 and MRTK3 are broken on Unity. Now I ran into the shader issue, and the proposed fix never worked. Then I tried an older version of Unity. While this compiled on 2020.3.43 passthrough was broken. Hand tracking could have been better, and hand images were missing. Below are people trying to get passthrough on MRTK3, and then hand tracking is broken. So, nothing works on the quest/android side. You recommend using MRTK3, but passthrough is not supported. Documentation could be better. Unreal support is nonexistent, and that's how I ended up having to use Unity in the first place. When someone asks a question, most comments say, "should work." I am just trying to develop a prototype, and this has been a nightmare.

https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11230

https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11239#discussioncomment-4217061

**Comment by rauwebieten** [comment] 2023-02-03 13:46
Having the same problem. (URP project on unity 2021.3.17f1 + mixed reality toolkit 2.8.3 + oculus integration)

Fix by Cameron-Micka works fine.

**Comment by timothyt** [comment] 2023-05-18 17:21
This is still an issue on MRTK3, Unity 2021.3.24

**Comment by quater782** [comment] 2024-03-21 14:57
I am migrating my application targeted at HL2 to Quest3.  (Unity2021.3.9f1c1, MRTK2.8.3)
fix BY Cameron-Micka works for me. but i ma trapped in other problems like passthrough and hand interations...

**Comment by JuliusJacobitz** [comment] 2024-05-22 13:33
> I am migrating my application targeted at HL2 to Quest3. (Unity2021.3.9f1c1, MRTK2.8.3) fix BY Cameron-Micka works for me. but i ma trapped in other problems like passthrough and hand interations...

Hi @quater782,
I am currently facing exactly the same task. Might you send me an email, I also have some problems with this task and maybe your experience could help me out.
Thank you!

**Comment by quater782** [comment] 2024-06-03 10:34
> > I am migrating my application targeted at HL2 to Quest3. (Unity2021.3.9f1c1, MRTK2.8.3) fix BY Cameron-Micka works for me. but i ma trapped in other problems like passthrough and hand interations...
> 
> Hi @quater782, I am currently facing exactly the same task. Might you send me an email, I also have some problems with this task and maybe your experience could help me out. Thank you!

omg! i am sorry i missed your msg and sorry again for my late reply!!. I hope your problems are already solved 😭😭😭
