### ISSUE TITLE
Building for WSA x64 fails due to a missing WSA x64 PlaneFinding.dll

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#769] opened 2017-07-11 20:37 UTC
Probably related to #746, at least for x64.

**Comment by StephenHodgson** [comment] 2017-09-04 20:18
Duplicate of https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/629

**Closed by StephenHodgson** 2017-09-04 20:18 UTC
Labels: Bug, Duplicate

**Comment by StephenHodgson** [comment] 2017-09-05 17:39
Closed By https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/dc4375db8643632565fa21c4d21893d7f098a98d
