### ISSUE TITLE
Unity editor pauses for a significant amount of time when ending Play mode in a scene when using MRTK 2.0

### ISSUE THREAD

**Issue by shaddadjr** [microsoft/MixedRealityToolkit-Unity#4261] opened 2019-05-10 15:25 UTC
## Describe the bug

The Unity Editor freezes for a significant amount of time when ending Play mode in scene

This has been corroborated by several developers in the HoloDevelopers slack channel:
https://holodevelopers.slack.com/archives/C2H4HT858/p1557497162412800

## To reproduce

1. Import MRTK2.0
2. Configure a scene to use MRTK 2.0
3. Play the scene
4. Exit play mode and observe editor freeze for several seconds (some time as long as 30 seconds)

## Expected behavior

The editor should not freeze when exiting play mode.

## Your Setup (please complete the following information)

- Unity Version [2018.3.11f1]
- MRTK Version [v2.0 RC1 and RC1 refresh]

## Target Platform (please complete the following information)

Unity Editor

**Comment by StephenHodgson** [comment] 2019-05-11 00:11
See https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3026

**Comment by julenka** [comment] 2019-05-11 06:13
Note: you can work around this by creating a custom MRTK profile, then creating a custom input profile, and removing the following two Data Providers from the list:

![image](https://user-images.githubusercontent.com/168492/57565822-35102b80-7379-11e9-8500-360881043c2c.png)

**Comment by julenka** [comment] 2019-05-11 06:15
Closing as duplicate of #3026. Please use the workaround mentioned above. One way we could fix this would be to remove speech input from the default providers, but that would have the disadvantage of removing speech support from MRTK.

**Comment by julenka** [comment] 2019-05-11 09:29
Re opening based on suggestion from eprovencher that we should avoid running the speech code in edit mode, seems like a path to a solution

**Comment by ForrestTrepte** [comment] 2019-05-12 04:24
I am seeing lengthy delays in both startup and shutdown as described in #3026, but I couldn't quite tell what the conclusion was to that issue. Disabling speech in the editor sounds like a good interim solution, but would it also be possible to fix the underlying solution? (If it's a Unity issue, make sure they know that it's still a problem?)

**Comment by StephenHodgson** [comment] 2019-05-12 05:14
Just FYI, I was able to fix this in my fork by not destroying the `DictationRecognizer` & `KeywordRecognizer`s when entering and leaving playmode.

**Comment by wiwei** [comment] 2019-05-15 00:31
Marked as Urgency-Soon, because it's a huge pain to deal with daily development.

**Comment by wiwei** [comment] 2019-05-17 19:25
Should be good now, please reopen if folks still hit this with the latest mrtk_dev

**Closed by wiwei** 2019-05-17 19:25 UTC
Labels: 4 - In Review, Bug, Speech, Urgency-Soon

**Comment by chbecker-ms** [comment] 2019-05-28 19:30
> Just FYI, I was able to fix this in my fork by not destroying the DictationRecognizer & KeywordRecognizers when entering and leaving playmode.

Thank you for sharing this insight Stephen!

**Comment by kevinfoley** [comment] 2022-05-18 19:44
@julenka You wrote that we should remove two data providers from the list, but not which two data providers. The screenshot is not helpful in determining which providers to remove. 

This appears to still be an issue in Unity 2020.3.34f1 / MRTK 2.7.3.0

**Comment by Holo-Krzysztof** [comment] 2022-05-19 07:40
> @julenka You wrote that we should remove two data providers from the list, but not which two data providers. The screenshot is not helpful in determining which providers to remove.
> 
> This appears to still be an issue in Unity 2020.3.34f1 / MRTK 2.7.3.0

It should be speech and dictation, at least that works for me.
