### ISSUE TITLE
Make the MRTK Standard shader compatible with _CameraDepthTexture by adding an optional ShadowCaster pass.

### ISSUE THREAD

**Issue by jayd16** [microsoft/MixedRealityToolkit-Unity#9689] opened 2021-04-20 16:00 UTC
## Describe the problem

I would like to use Unity's _CameraDepthTexture for a post effect type shader.  Depending on platform, Unity generates this texture with a depth pre-pass using the ShadowCaster pass.  The MRTK Standard shader does not have this pass.
https://docs.unity3d.com/Manual/SL-CameraDepthTexture.html

## Describe the solution you'd like

I would like to see an (ideally opt-in) ShadowCaster pass added to the MRTK standard shader.  This would draw to the _CameraDepthTexture in Unity's render setup and create a proper depth texture.

## Describe alternatives you've considered

I could perhaps use a depth render texture on the main camera and a shader replacement technique to build my own depth buffer but that seems a lot more cumbersome.

## Additional context
I believe this solution would work for both built in and URP render modes.
I would also be fine with being able to read the z-buffer directly but I don't think that's made available.

**Comment by Cameron-Micka** [comment] 2021-04-20 18:17
Thank you @jayd16 for opening this request! That is correct the MRTK/Standard shader doesn't have a shadow pass since we often avoid dynamic shadows in mixed reality due to performance constraints. We also avoid features that toggle a depth prepass (such as shadows, soft particles, or other technique that require depth) to keep draw calls at a minimum. 

But, I could see this being useful for other platforms. Let me add @polar-kev who can help with scheduling this for the future.

**Comment by Zee2** [comment] 2022-10-05 05:57
Closing as duplicate of MRGT issue.

**Closed by Zee2** 2022-10-05 05:57 UTC
Labels: Shaders / Materials, Feature Request
